import type { Metadata } from "next";
import Image from "next/image";
import Link from "next/link";

import FloatingContactButtons from "@/app/components/FloatingContactButtons";
import GoldenParticles from "@/app/components/GoldenParticles";
import MagneticButtons from "@/app/components/MagneticButtons";
import Navbar from "@/app/components/Navbar";
import PremiumCursor from "@/app/components/PremiumCursor";
import RevealOnScroll from "@/app/components/RevealOnScroll";
import StaggerItem from "@/app/components/StaggerItem";
import FooterSection from "@/sections/FooterSection";

const canonicalUrl = "https://shiveshinternational.com/export/finland";
const heroImage = "/images/export/finland/finland-export-hero.png";

export const metadata: Metadata = {
  title: "Henna, Indigo, Herbs & Spices Exporter to Finland",
  description:
    "Indian exporter of natural henna powder, indigo powder, botanical hair colors, Ayurvedic herbs and Indian spices for Finnish importers, distributors, wholesalers and private-label buyers.",
  keywords: [
    "Natural products exporter to Finland", "Indian natural products supplier Finland", "Exporter from India to Finland", "Indian supplier for Finnish importers", "Natural product manufacturer India for Finland", "Bulk natural products supplier Finland", "Private label products manufacturer for Finland", "Wholesale botanical products Finland", "Indian exporter for Finnish distributors", "Natural cosmetic ingredients supplier Finland", "Herbal products exporter to Finland", "Plant-based products supplier Finland", "Botanical ingredients exporter Finland", "Indian manufacturer for Finnish wholesalers", "B2B natural products supplier Finland",
    "Henna powder exporter to Finland", "Natural henna powder supplier Finland", "Henna powder manufacturer India for Finland", "Bulk henna powder supplier Finland", "Organic henna powder exporter Finland", "Private label henna powder Finland", "Wholesale henna powder Finland", "Cosmetic-grade henna powder supplier Finland", "Pure henna powder exporter to Finland", "Lawsonia inermis powder supplier Finland", "Indian henna exporter for Finnish importers", "Henna powder for cosmetic brands Finland", "Henna powder for salon suppliers Finland", "Henna powder wholesale supplier Finland", "Private label henna manufacturer India for Finland", "Natural henna supplier Helsinki", "Henna powder supplier Espoo", "Henna exporter for Finnish beauty brands",
    "Indigo powder exporter to Finland", "Natural indigo powder supplier Finland", "Indigo powder manufacturer India for Finland", "Bulk indigo powder supplier Finland", "Organic indigo powder exporter Finland", "Private label indigo powder Finland", "Wholesale indigo powder Finland", "Indigofera tinctoria powder supplier Finland", "Natural indigo for botanical hair color Finland", "Indigo powder for Finnish cosmetic brands", "Indian indigo exporter Finland", "Indigo hair dye ingredient supplier Finland", "Indigo powder for salons Finland", "Bulk indigo supplier for Finnish importers",
    "Natural henna hair color manufacturer for Finland", "Botanical hair color supplier Finland", "Plant-based hair color exporter Finland", "Natural hair dye manufacturer India for Finland", "Private label natural hair color Finland", "Henna hair color wholesale Finland", "Botanical hair dye supplier Finland", "Herbal hair color manufacturer for Finnish brands", "Powder hair color exporter Finland", "Natural hair color supplier for Finnish salons", "Henna-based hair color supplier Finland", "Private label botanical hair color manufacturer India", "Natural hair color for Finnish distributors", "Botanical hair color bulk supplier Finland", "Natural hair dye products for Finnish beauty brands", "Salon hair color supplier Finland",
    "Ayurvedic herbs exporter to Finland", "Indian herbs supplier Finland", "Herbal powder exporter Finland", "Ayurvedic powder supplier Finland", "Bulk Indian herbs supplier Finland", "Private label herbal products Finland", "Wholesale Ayurvedic herbs Finland", "Indian botanical ingredients exporter Finland", "Herbal ingredients for cosmetic brands Finland", "Natural herbal powder manufacturer India for Finland", "Ayurvedic herbs for Finnish importers", "Indian herbs for wellness brands Finland", "Bulk herbal powders exporter Finland", "Cosmetic herbal ingredients supplier Finland", "Amla powder supplier Finland", "Shikakai powder exporter Finland", "Herbal hair-care ingredients Finland",
    "Indian spices exporter to Finland", "Indian spices supplier Finland", "Bulk spices supplier Finland", "Wholesale Indian spices Finland", "Whole spices exporter to Finland", "Ground spices exporter Finland", "Private label Indian spices Finland", "Indian spice manufacturer for Finnish buyers", "Spice exporter from India to Finland", "Indian spices for Finnish importers", "Bulk spice powder supplier Finland", "Indian food ingredient supplier Finland", "Private label spice packaging Finland", "Indian spice wholesale supplier Finland", "Indian spices for Finnish food businesses", "Indian spices distributor supply Finland",
    "Private label manufacturer India for Finland", "Custom packaging supplier for Finnish buyers", "Private label henna packaging Finland", "Private label indigo packaging Finland", "Private label herbal powder Finland", "Private label spice supplier Finland", "Custom branded pouches for Finnish importers", "Retail packaging natural products Finland", "Bulk packaging exporter India to Finland", "Contract packaging for Finnish brands", "Multilingual label coordination Finland", "Finnish and Swedish label coordination", "White label natural products Finland", "OEM natural products supplier Finland", "Custom brand botanical products Finland", "Private label natural hair color Finland",
    "Henna supplier for Finnish importers", "Natural product supplier for Finnish distributors", "Botanical products for Finnish wholesalers", "Private label supplier for Finnish brands", "Henna supplier for salon distributors Finland", "Herbal ingredients for Finnish cosmetic manufacturers", "Indian products for Finnish retail businesses", "Bulk supplier for Finnish natural product brands", "Natural ingredients for Finnish beauty brands", "Indian exporter for Finnish wholesale buyers", "Natural product supplier Helsinki", "Botanical product supplier Espoo", "Indian herbal supplier Turku", "Natural hair-care ingredients Tampere", "Private label products for Finnish e-commerce brands",
    "Reetha powder supplier Finland", "Neem powder Finland", "Bhringraj powder Finland", "Brahmi powder Finland", "Hibiscus powder supplier Finland", "Ashwagandha powder supplier Finland", "Turmeric powder exporter Finland", "Cumin supplier Finland", "Coriander supplier Finland", "Black pepper exporter Finland", "Plant-based hair color supplier Finland",
    "100 g henna pouch Finland", "200 g henna pouch Finland", "500 g herbal powder Finland", "1 kg botanical powder Finland", "20 kg bulk henna Finland", "25 kg bulk henna Finland", "Vacuum packed botanical powders Finland", "Bilingual label coordination Finland", "Finnish buyer packaging support", "Barcode packaging support Finland", "Sustainable packaging planning Finland", "200 kg MOQ natural products Finland",
    "India to Finland export coordination", "Natural products shipping India to Finland", "Commercial invoice support Finland", "Packing list support Finland", "Certificate of origin coordination Finland", "COA document support Finland", "Product specification documents Finland", "Sea freight coordination Finland", "Air freight coordination Finland", "Helsinki port natural products", "Turku port natural products", "HaminaKotka port freight", "Helsinki air cargo natural products", "Vantaa logistics natural products", "Finland import documentation support", "EU buyer documentation natural products", "Indian exporter for Finnish buyers",
  ],
  alternates: { canonical: canonicalUrl },
  openGraph: {
    title: "Henna, Indigo, Herbs & Spices Exporter to Finland",
    description: "Bulk, wholesale and private-label supply of Indian henna, indigo, botanical hair colors, Ayurvedic herbs and spices for professional buyers in Finland.",
    url: canonicalUrl,
    type: "website",
    locale: "en_FI",
    siteName: "Shivesh International",
    images: [{ url: "/images/export/finland/finland-export-hero.png", alt: "Finnish buyers reviewing Indian natural products" }],
  },
  twitter: {
    card: "summary_large_image",
    title: "Henna, Indigo, Herbs & Spices Exporter to Finland",
    description: "Indian natural-product supply for Finnish importers, distributors, salons and private-label brands.",
    images: ["/images/export/finland/finland-export-hero.png"],
  },
  robots: { index: true, follow: true, googleBot: { index: true, follow: true } },
};

const products = [
  { title: "Natural Henna Powder", text: "Fine-quality natural henna powder for Finnish cosmetic brands, salons, wholesalers, natural retailers and customized private-label programmes.", href: "/products/natural-henna-powder" },
  { title: "Natural Indigo Powder", text: "Natural indigo powder for botanical hair-color systems, professional salon supply, bulk sourcing and buyer-brand packaging.", href: "/products/natural-indigo-powder" },
  { title: "Natural Henna Hair Colors", text: "A broad botanical shade collection for Finnish importers, beauty brands, natural hair-care companies and salon distributors.", href: "/products/natural-henna-hair-colors" },
  { title: "Henna-Based Hair Colors", text: "Export-ready powdered hair colors for Finnish buyers requiring wholesale, OEM, professional or customized private-label formats.", href: "/products/henna-based-hair-colors" },
  { title: "Ayurvedic Indian Herbs", text: "Indian herbal powders and botanicals for Finnish cosmetic, personal-care, wellness, hair-care and wholesale applications.", href: "/products/ayurvedic-indian-herbs" },
  { title: "Indian Spices", text: "Whole and powdered Indian spices for Finnish importers, food businesses, specialty retailers, distributors and private-label brands.", href: "/products/indian-spices" },
];

const buyerProfiles = [
  ["Importers and Distributors", "Coordinate specifications, commercial quantities and available documentation for distribution networks serving Helsinki, Espoo and wider Finland."],
  ["Nordic Beauty and Cosmetic Brands", "Review plant-based powders for naturally positioned cosmetic and hair-care concepts, with intended-use and specification assessment."],
  ["Natural and Organic Retailers", "Build selected henna, indigo, herb and spice ranges for Finnish natural shops, organic retailers and specialist channels."],
  ["Professional Salon Suppliers", "Discuss botanical hair colors and herbal hair-care ingredients for professional salon distribution in Finland."],
  ["Herbal and Wellness Businesses", "Assess Ayurvedic powders and selected botanicals for Finnish wellness, specialty retail and own-brand programmes."],
  ["Private-Label and OEM Buyers", "Coordinate feasible pouches, cartons, artwork, barcodes and Finnish, Swedish or bilingual label layouts for buyer-brand projects."],
  ["Food and Spice Importers", "Plan whole-spice, ground-spice and Indian food-ingredient supply for Finnish food businesses and specialist distributors."],
  ["Wholesalers and E-commerce Brands", "Build commercially focused natural-product assortments for wholesale, online and specialty retail channels across Finland."],
];

const documentationItems = [
  ["Commercial Invoice", "Commercial invoice information can be prepared around the confirmed buyer, products, quantities, values and shipment terms."],
  ["Packing List", "Pack counts, net and gross weights, carton information and agreed shipment references can be coordinated for confirmed orders."],
  ["Certificate of Origin", "Certificate-of-origin coordination can be discussed where applicable to the confirmed product and shipment arrangement."],
  ["Specifications and COA", "Product specifications, COA where available, batch references and available quality information depend on the selected product."],
  ["Packaging Information", "Pouch, carton, bulk-bag, label and barcode information can be aligned with the buyer-approved packaging programme."],
  ["Shipping Documents", "Shipment documentation can be coordinated with buyer-appointed freight forwarders and the agreed dispatch plan."],
  ["Destination Review Information", "Available product and packaging information can support the Finnish buyer’s customs and destination-market review."],
  ["Buyer Responsibility", "The importer must verify classification, labels, claims, registrations, customs, taxes and applicable Finnish and EU requirements."],
];

const processSteps = [
  ["Share Product Requirement", "Provide the product name, intended business use, destination, approximate quantity and preferred packaging."],
  ["Confirm Specification and Quantity", "Review the requested grade, available specification and the 200 kg-per-product commercial minimum."],
  ["Review Packaging and Artwork", "Align feasible retail or bulk formats, Finnish, Swedish or bilingual artwork, labels, barcodes and buyer-brand requirements."],
  ["Confirm Documents and Freight Plan", "Discuss available product documents, preferred Finland entry point and the buyer-appointed freight-forwarder arrangement."],
  ["Production and Dispatch Coordination", "Proceed according to confirmed commercial terms, production feasibility and the agreed dispatch plan."],
];

const marketLocations = [
  ["Helsinki", "Importers, natural-cosmetic businesses and private-label buyers in the Helsinki market can discuss multi-category sourcing and buyer-brand formats."],
  ["Espoo", "Espoo-area distributors and wellness businesses can review botanical powders, salon products and herbal retail ranges."],
  ["Vantaa", "Food-ingredient buyers, wholesalers and logistics-oriented businesses around Vantaa can coordinate spice and botanical supply enquiries."],
  ["Tampere", "Tampere speciality retailers, salon suppliers and premium wellness brands can assess selected retail and professional formats."],
  ["Turku", "Natural-product and tourism-linked retail businesses in Turku can discuss focused botanical, herbal and spice collections."],
  ["Oulu", "Oulu-area wellness companies, speciality shops and regional distributors can review commercially feasible product programmes."],
  ["Jyväskylä", "Retail sourcing companies and distributors across Jyväskylä can coordinate bulk supply and private-label presentation requirements."],
  ["Lahti", "Lahti buyers can discuss botanical ingredients, professional hair-care supply, spices and wholesale packaging options."],
];

const nordicPriorities = [
  ["Traceable Product Information", "Clear specifications, batch references and available quality information help Finnish buyers evaluate products for their intended commercial channel."],
  ["Practical Nordic Packaging", "Compact retail formats, durable export packing and clearly organized artwork support professional presentation and efficient handling."],
  ["Finnish and Swedish Label Coordination", "Buyer-approved Finnish, Swedish or bilingual label layouts can be coordinated for feasible private-label programmes."],
  ["Sustainability-Conscious Planning", "Packaging choices, consolidated sourcing and realistic freight planning can be reviewed with buyers seeking resource-conscious commercial solutions."],
];

const faqs = [
  { question: "Do you export natural henna powder from India to Finland?", answer: "Yes. Shivesh International coordinates natural henna powder supply from India for qualified Finnish importers, distributors, wholesalers, salon suppliers and private-label buyers, subject to specification and commercial confirmation." },
  { question: "What is the minimum order quantity for Finnish buyers?", answer: "The minimum order quantity is 200 kg per product. Final quantities depend on the selected product, packaging format and private-label requirements." },
  { question: "Can Finnish buyers order private-label henna and herbal products?", answer: "Selected henna and herbal products can be discussed for private-label supply, including buyer branding, feasible printed pouches or cartons, barcode details and buyer-approved artwork." },
  { question: "Which retail and bulk packaging formats are available?", answer: "Selected products can be discussed in 100 g, 200 g, 500 g and 1 kg pouches. Bulk options include 20 kg and 25 kg double-layer vacuum bags, subject to product and order confirmation." },
  { question: "Can you coordinate Finnish and Swedish packaging artwork?", answer: "Finnish, Swedish or bilingual label artwork coordination can be discussed alongside buyer-supplied artwork and label-layout support. The Finnish buyer remains responsible for final label text, claims and approval." },
  { question: "Which documents can be provided with Finland-bound shipments?", answer: "Depending on the product and availability, coordination can include commercial invoices, packing lists, certificates of origin, specifications, COA, available quality information and shipping documents." },
  { question: "How can products be shipped from India to Finland?", answer: "Buyer-selected arrangements may use sea freight through Helsinki, Turku, HaminaKotka or another agreed port, or air cargo through Helsinki Airport. Routes, schedules and transit times are not guaranteed." },
  { question: "Are Finnish and EU import compliance requirements handled automatically?", answer: "No. The Finnish importer or buyer must confirm classification, labelling, claims, registrations, customs, taxes and applicable Finnish and European Union requirements for the selected product." },
];

const structuredData = {
  "@context": "https://schema.org",
  "@graph": [
    { "@type": "WebPage", "@id": `${canonicalUrl}#webpage`, url: canonicalUrl, name: "Henna, Indigo, Herbs & Spices Exporter to Finland", description: "Finland-focused export supply of natural henna, indigo, botanical hair colors, Ayurvedic herbs and Indian spices from India.", isPartOf: { "@id": "https://shiveshinternational.com/#website" }, about: { "@id": "https://shiveshinternational.com/#organization" }, breadcrumb: { "@id": `${canonicalUrl}#breadcrumb` }, inLanguage: "en" },
    { "@type": "BreadcrumbList", "@id": `${canonicalUrl}#breadcrumb`, itemListElement: [
      { "@type": "ListItem", position: 1, name: "Home", item: "https://shiveshinternational.com/" },
      { "@type": "ListItem", position: 2, name: "Export", item: "https://shiveshinternational.com/export" },
      { "@type": "ListItem", position: 3, name: "Europe", item: "https://shiveshinternational.com/export/europe" },
      { "@type": "ListItem", position: 4, name: "Finland", item: canonicalUrl },
    ] },
  ],
};

const faqStructuredData = { "@context": "https://schema.org", "@type": "FAQPage", "@id": `${canonicalUrl}#faq`, mainEntity: faqs.map((faq) => ({ "@type": "Question", name: faq.question, acceptedAnswer: { "@type": "Answer", text: faq.answer } })) };

export default function FinlandExportPage() {
  return (
    <main className="min-h-screen overflow-x-hidden bg-[#F5F0E6] text-[#173B2A]">
      <script type="application/ld+json" dangerouslySetInnerHTML={{ __html: JSON.stringify(structuredData).replace(/</g, "\\u003c") }} />
      <script type="application/ld+json" dangerouslySetInnerHTML={{ __html: JSON.stringify(faqStructuredData).replace(/</g, "\\u003c") }} />
      <Navbar />

      <section className="relative isolate overflow-hidden">
        <Image src={heroImage} alt="Finnish buyers reviewing Indian henna, indigo, herbs and spices for professional export supply" fill priority sizes="100vw" className="object-cover object-center" />
        <div className="absolute inset-0 bg-gradient-to-r from-[#061711]/72 via-[#102F23]/40 to-[#071B14]/10" />
        <div className="absolute inset-0 bg-gradient-to-t from-black/10 via-transparent to-black/[0.04]" />
        <GoldenParticles />
        <div className="relative z-10 flex items-center px-6 pb-20 pt-32 sm:px-8 sm:pb-24 sm:pt-36 lg:px-12 lg:pb-28 lg:pt-40">
          <div className="w-full max-w-[820px] lg:max-w-[860px] xl:max-w-[900px]">
            <StaggerItem delay={0}><div className="flex items-center gap-4"><span className="h-px w-14 bg-[#C9A962]" /><p className="text-[10px] font-bold uppercase tracking-[0.38em] text-[#E4C878] sm:text-xs">Exporting from India to Finland</p></div></StaggerItem>
            <StaggerItem delay={100}><h1 className="mt-5 font-[family-name:var(--font-playfair)] text-4xl font-medium leading-[1] tracking-[-0.04em] text-[#F5F0E6] sm:text-5xl lg:text-6xl xl:text-[66px]">Natural Products Exporter to Finland<span className="mt-2 block bg-gradient-to-r from-[#F5F0E6] via-[#E4C878] to-[#C9A962] bg-clip-text text-transparent">Henna, Indigo, Herbs &amp; Spices</span></h1></StaggerItem>
            <StaggerItem delay={200}><p className="mt-5 max-w-[730px] text-[16px] font-light leading-7 text-[#F5F0E6]/82 sm:text-[17px] sm:leading-8">Shivesh International supports Finnish importers, distributors, wholesalers, cosmetic companies, salon suppliers, herbal-product businesses, food-sector buyers and private-label brands with export-ready natural henna, indigo, botanical hair colors, Ayurvedic herbs and Indian spices from India.</p></StaggerItem>
            <StaggerItem delay={300}><div className="mt-7 flex flex-wrap gap-4"><Link href="/contact" className="inline-flex items-center gap-4 border border-[#C9A962] bg-[#C9A962] px-7 py-4 text-[10px] font-bold uppercase tracking-[0.2em] text-[#102F23] transition-all hover:-translate-y-1 hover:bg-[#E4C878] focus-visible:outline focus-visible:outline-2 focus-visible:outline-offset-4 focus-visible:outline-[#E4C878]">Send Finland Inquiry <span>→</span></Link><a href="#products" className="inline-flex items-center gap-4 border border-[#F5F0E6]/30 bg-[#102F23]/40 px-7 py-4 text-[10px] font-bold uppercase tracking-[0.2em] text-[#F5F0E6] backdrop-blur-lg transition-all hover:border-[#C9A962] hover:text-[#E4C878] focus-visible:outline focus-visible:outline-2 focus-visible:outline-offset-4 focus-visible:outline-[#E4C878]">Explore Products <span>↓</span></a></div></StaggerItem>
            <StaggerItem delay={400}><div className="mt-10 grid max-w-[740px] grid-cols-2 gap-3 lg:grid-cols-4">{[["200 kg", "MOQ Per Product"], ["Bulk", "Wholesale Supply"], ["OEM", "Private Label"], ["Finland", "Buyer Enquiries"]].map(([value, label]) => <div key={label} className="border border-white/15 bg-black/20 px-4 py-4 backdrop-blur-md"><p className="font-[family-name:var(--font-playfair)] text-xl font-semibold text-[#E4C878]">{value}</p><p className="mt-2 text-[9px] font-bold uppercase tracking-[0.22em] text-[#F5F0E6]/55">{label}</p></div>)}</div></StaggerItem>
          </div>
        </div>
      </section>

      <section className="px-6 py-24 sm:px-8 lg:px-12 lg:py-32"><RevealOnScroll><div className="mx-auto max-w-[1120px]"><p className="text-[10px] font-bold uppercase tracking-[0.4em] text-[#9F7F36]">India–Finland Natural Product Sourcing</p><h2 className="mt-6 font-[family-name:var(--font-playfair)] text-[clamp(2.5rem,4.6vw,4.6rem)] font-semibold leading-[1.04]">One Indian Export Partner <span className="block text-[#A97B22]">for Finnish Natural-Product Buyers</span></h2><p className="mt-7 text-[16px] font-light leading-8 text-[#4C5F54]">Finnish importers, distributors and wholesalers can coordinate multiple product categories with one Indian export team. Shivesh International supports cosmetic and personal-care companies, natural hair-care brands, salon suppliers, herbal and wellness businesses, food ingredient buyers, spice companies, private-label operators and e-commerce brands seeking structured sourcing from India.</p><p className="mt-5 text-[15px] font-light leading-8 text-[#4C5F54]">Commercial enquiries may be associated with buyer and distribution activity in Helsinki, Espoo, Tampere, Vantaa and Turku. Product availability, specifications, packaging, documentation and shipment preparation are reviewed according to the buyer’s selected category and agreed order requirements. Market references identify potential buyer locations and do not imply that Shivesh International maintains a local office or warehouse in Finland.</p></div></RevealOnScroll></section>

      <section id="products" className="scroll-mt-24 bg-[#EDE5D7] px-6 py-24 sm:px-8 lg:px-12 lg:py-32"><RevealOnScroll><div className="mx-auto max-w-[1500px]"><div className="mx-auto max-w-[920px] text-center"><p className="text-[10px] font-bold uppercase tracking-[0.4em] text-[#9F7F36]">Six Commercial Categories</p><h2 className="mt-6 font-[family-name:var(--font-playfair)] text-[clamp(2.5rem,4.8vw,4.8rem)] font-semibold leading-[1.04]">Natural Products <span className="block text-[#A97B22]">for Finnish Importers and Brands</span></h2><p className="mx-auto mt-7 max-w-[820px] text-[16px] font-light leading-8 text-[#4C5F54]">A focused portfolio for Finnish cosmetic brands, professional hair-care channels, herbal businesses, wholesalers, food companies and private-label buyers.</p></div><div className="mt-14 grid auto-rows-fr gap-5 sm:grid-cols-2 lg:grid-cols-3">{products.map((product, index) => <StaggerItem key={product.title} delay={(index % 3) * 90}><article className="group flex h-full min-h-[300px] flex-col border border-[#173B2A]/12 bg-[#FBF8F1] p-7 shadow-[0_18px_45px_rgba(20,50,38,0.07)] transition-all hover:-translate-y-2 hover:border-[#C9A962]/70 sm:p-8"><span className="font-[family-name:var(--font-playfair)] text-4xl font-semibold text-[#C9A962]/60">{String(index + 1).padStart(2, "0")}</span><h3 className="mt-6 font-[family-name:var(--font-playfair)] text-[27px] font-semibold leading-tight">{product.title}</h3><p className="mt-5 flex-1 text-[14px] font-light leading-7 text-[#4C5F54]">{product.text}</p><Link href={product.href} className="mt-7 inline-flex items-center gap-3 text-[10px] font-bold uppercase tracking-[0.2em] text-[#A97B22] focus-visible:outline focus-visible:outline-2 focus-visible:outline-offset-4 focus-visible:outline-[#A97B22]">Explore {product.title} <span className="transition-transform group-hover:translate-x-2">→</span></Link></article></StaggerItem>)}</div></div></RevealOnScroll></section>

      <section className="bg-[#0B3325] px-6 py-24 text-[#F5F0E6] sm:px-8 lg:px-12 lg:py-32"><RevealOnScroll><div className="mx-auto max-w-[1500px]"><div className="mx-auto max-w-[920px] text-center"><p className="text-[10px] font-bold uppercase tracking-[0.4em] text-[#E4C878]">Finnish Commercial Channels</p><h2 className="mt-6 font-[family-name:var(--font-playfair)] text-[clamp(2.5rem,4.7vw,4.7rem)] font-semibold leading-[1.04]">Who We Support in the Finnish Market</h2></div><div className="mt-14 grid auto-rows-fr gap-5 sm:grid-cols-2 lg:grid-cols-4">{buyerProfiles.map(([title, text]) => <article key={title} className="h-full border border-[#C9A962]/25 bg-[#071B14]/55 p-7"><h3 className="font-[family-name:var(--font-playfair)] text-2xl font-semibold text-[#E4C878]">{title}</h3><p className="mt-4 text-[14px] font-light leading-7 text-[#F5F0E6]/65">{text}</p></article>)}</div></div></RevealOnScroll></section>

      <section className="px-6 py-24 sm:px-8 lg:px-12 lg:py-32"><RevealOnScroll><div className="mx-auto max-w-[1500px]"><div className="grid gap-14 lg:grid-cols-[0.7fr_1.3fr] lg:gap-20"><div><p className="text-[10px] font-bold uppercase tracking-[0.4em] text-[#9F7F36]">Buyer Review Information</p><h2 className="mt-6 font-[family-name:var(--font-playfair)] text-[clamp(2.5rem,4.5vw,4.5rem)] font-semibold leading-[1.04]">Export Documentation <span className="block text-[#A97B22]">for Finnish Buyers</span></h2><p className="mt-7 text-[15px] font-light leading-8 text-[#4C5F54]">Documents depend on the selected product and availability. Available commercial, product, packaging and shipment information can be coordinated for buyer and destination review without implying automatic Finnish or European Union compliance.</p></div><div className="grid auto-rows-fr gap-5 sm:grid-cols-2">{documentationItems.map(([title, text]) => <article key={title} className="h-full border border-[#173B2A]/12 bg-[#FBF8F1] p-7"><span className="block h-px w-12 bg-[#C9A962]" /><h3 className="mt-5 font-[family-name:var(--font-playfair)] text-2xl font-semibold">{title}</h3><p className="mt-4 text-[14px] font-light leading-7 text-[#4C5F54]">{text}</p></article>)}</div></div></div></RevealOnScroll></section>

      <section className="px-6 py-24 sm:px-8 lg:px-12 lg:py-32"><RevealOnScroll><div className="mx-auto max-w-[1500px]"><div className="mx-auto max-w-[900px] text-center"><p className="text-[10px] font-bold uppercase tracking-[0.4em] text-[#9F7F36]">Nordic Market Priorities</p><h2 className="mt-6 font-[family-name:var(--font-playfair)] text-[clamp(2.5rem,4.6vw,4.6rem)] font-semibold leading-[1.04]">Practical Supply Planning <span className="block text-[#A97B22]">for Finnish Buyers</span></h2><p className="mx-auto mt-7 max-w-[780px] text-[15px] font-light leading-8 text-[#4C5F54]">Finland-focused programmes can be reviewed around clear product information, practical packaging, appropriate language coordination and commercially realistic sustainability priorities.</p></div><div className="mt-14 grid auto-rows-fr gap-5 sm:grid-cols-2 lg:grid-cols-4">{nordicPriorities.map(([title, text]) => <article key={title} className="h-full border border-[#173B2A]/12 bg-[#FBF8F1] p-7"><span className="block h-px w-12 bg-[#C9A962]" /><h3 className="mt-5 font-[family-name:var(--font-playfair)] text-2xl font-semibold">{title}</h3><p className="mt-4 text-[14px] font-light leading-7 text-[#4C5F54]">{text}</p></article>)}</div></div></RevealOnScroll></section>

      <section className="bg-[#EDE5D7] px-6 py-24 sm:px-8 lg:px-12 lg:py-32"><RevealOnScroll><div className="mx-auto grid max-w-[1500px] gap-14 lg:grid-cols-[1.05fr_0.95fr] lg:gap-20"><div><p className="text-[10px] font-bold uppercase tracking-[0.4em] text-[#9F7F36]">Buyer-Brand Formats</p><h2 className="mt-6 font-[family-name:var(--font-playfair)] text-[clamp(2.5rem,4.6vw,4.6rem)] font-semibold leading-[1.04]">Packaging &amp; Private-Label Solutions <span className="block text-[#A97B22]">for Finnish Buyers</span></h2><p className="mt-7 text-[15px] font-light leading-8 text-[#4C5F54]">Selected programmes can include custom brand names, printed pouches, printed boxes, buyer-supplied artwork coordination, barcodes, label-layout support, Finnish, Swedish or bilingual label artwork coordination and sustainability-conscious packaging review. Retail, salon, professional and bulk formats, including OEM or private-label supply, remain subject to agreed requirements and technical feasibility.</p><p className="mt-5 text-[14px] font-light leading-7 text-[#4C5F54]">Retail options may include 100 g, 200 g, 500 g and 1 kg pouches. Bulk formats may include 20 kg and 25 kg double-layer vacuum bags. Final product labels, language requirements, claims, product classification and destination-market compliance remain subject to buyer review and the applicable product category.</p></div><div><figure className="relative aspect-[3/2] overflow-hidden rounded-sm border border-[#C9A962]/35 shadow-[0_28px_70px_rgba(20,50,38,0.18)]"><Image src="/images/export/finland/finland-buyer-partnership.png" alt="Finnish packaging specialists reviewing private-label formats for Indian natural products" fill sizes="(min-width: 1024px) 45vw, 100vw" className="object-cover object-center" /></figure><div className="mt-5 grid gap-5 sm:grid-cols-2"><article className="border border-[#C9A962]/35 bg-[#FBF8F1] p-7"><h3 className="font-[family-name:var(--font-playfair)] text-2xl font-semibold">Retail Packaging</h3><p className="mt-4 text-sm leading-7 text-[#4C5F54]">100 g · 200 g · 500 g · 1 kg pouches</p></article><article className="border border-[#C9A962]/35 bg-[#FBF8F1] p-7"><h3 className="font-[family-name:var(--font-playfair)] text-2xl font-semibold">Bulk Packaging</h3><p className="mt-4 text-sm leading-7 text-[#4C5F54]">20 kg and 25 kg double-layer vacuum bags</p></article><article className="border border-[#C9A962] bg-[#173B2A] p-7 text-[#F5F0E6] sm:col-span-2"><p className="text-[10px] font-bold uppercase tracking-[0.3em] text-[#E4C878]">Minimum Order Quantity</p><p className="mt-4 font-[family-name:var(--font-playfair)] text-4xl font-semibold">200 kg per product</p></article></div></div></div></RevealOnScroll></section>

      <section className="bg-[#09271D] px-6 py-24 text-[#F5F0E6] sm:px-8 lg:px-12 lg:py-32"><RevealOnScroll><div className="mx-auto max-w-[1500px]"><div className="grid items-center gap-14 lg:grid-cols-[1.05fr_0.95fr] lg:gap-20"><div><p className="text-[10px] font-bold uppercase tracking-[0.4em] text-[#E4C878]">Shipment and Document Support</p><h2 className="mt-6 font-[family-name:var(--font-playfair)] text-[clamp(2.5rem,4.8vw,4.8rem)] font-semibold leading-[1.04]">India-to-Finland Export Coordination</h2><p className="mt-7 text-[16px] font-light leading-8 text-[#F5F0E6]/68">Coordination can cover commercial invoices, packing lists, certificates of origin, product specifications, COA and available quality documents, shipping documentation, buyer-appointed freight forwarders, export cartons, pallets and shipment information sharing.</p><p className="mt-5 text-[15px] font-light leading-8 text-[#F5F0E6]/62">Buyer-selected arrangements may use sea freight through Helsinki, Turku, HaminaKotka or another agreed Finnish port, with onward road or rail delivery where required. Air-cargo coordination may be discussed through Helsinki Airport or another buyer-selected arrangement. No gateway, route, transit time or customs clearance is guaranteed. Documentation and product information can be coordinated according to the product category, destination, buyer instructions and agreed order requirements.</p></div><figure className="relative aspect-[3/2] overflow-hidden rounded-sm border border-[#C9A962]/35 shadow-[0_28px_70px_rgba(0,0,0,0.25)]"><Image src="/images/export/finland/india-to-finland-export-coordination.png" alt="India-to-Finland export coordination for natural products through Finnish sea and rail logistics" fill sizes="(min-width: 1024px) 45vw, 100vw" className="object-cover object-center" /></figure></div><aside className="mt-12 border border-[#C9A962]/35 bg-[#071B14]/60 p-7 text-[14px] font-light leading-7 text-[#F5F0E6]/65">The Finnish importer or buyer remains responsible for confirming product classification, labelling, registration, customs procedures, taxes and applicable Finnish and European Union destination-market requirements. No automatic compliance, registration or customs-clearance claim is made.</aside></div></RevealOnScroll></section>

      <section className="bg-[#EDE5D7] px-6 py-24 sm:px-8 lg:px-12 lg:py-32"><RevealOnScroll><div className="mx-auto max-w-[1500px]"><div className="mx-auto max-w-[920px] text-center"><p className="text-[10px] font-bold uppercase tracking-[0.4em] text-[#9F7F36]">Five Commercial Steps</p><h2 className="mt-6 font-[family-name:var(--font-playfair)] text-[clamp(2.5rem,4.7vw,4.7rem)] font-semibold leading-[1.04]">From Finland Buyer Requirement to Export Coordination</h2></div><div className="mt-14 grid auto-rows-fr gap-5 sm:grid-cols-2 lg:grid-cols-3">{processSteps.map(([title, text]) => <article key={title} className="h-full border border-[#173B2A]/12 bg-[#FBF8F1] p-7 sm:p-8"><span className="block h-px w-12 bg-[#C9A962]" /><h3 className="mt-6 font-[family-name:var(--font-playfair)] text-2xl font-semibold">{title}</h3><p className="mt-4 text-[14px] font-light leading-7 text-[#4C5F54]">{text}</p></article>)}</div></div></RevealOnScroll></section>

      <section className="px-6 py-24 sm:px-8 lg:px-12 lg:py-32"><RevealOnScroll><div className="mx-auto max-w-[1120px]"><p className="text-[10px] font-bold uppercase tracking-[0.4em] text-[#9F7F36]">Finland Buyer Locations</p><h2 className="mt-6 font-[family-name:var(--font-playfair)] text-[clamp(2.5rem,4.6vw,4.6rem)] font-semibold leading-[1.04]">Natural-Product Supply for Buyers Across Finland</h2><p className="mt-7 text-[15px] leading-7 text-[#4C5F54]">These market references identify potential enquiry and distribution locations; they do not represent local Shivesh International offices, warehouses or guaranteed active supply relationships.</p><div className="mt-10 grid auto-rows-fr gap-5 sm:grid-cols-2 lg:grid-cols-4">{marketLocations.map(([location, text]) => <article key={location} className="h-full border border-[#C9A962]/35 bg-[#FBF8F1] p-6"><h3 className="font-[family-name:var(--font-playfair)] text-2xl font-semibold text-[#A97B22]">{location}</h3><p className="mt-4 text-[14px] font-light leading-7 text-[#4C5F54]">{text}</p></article>)}</div></div></RevealOnScroll></section>

      <section className="bg-[#EDE5D7] px-6 py-24 sm:px-8 lg:px-12 lg:py-32"><RevealOnScroll><div className="mx-auto max-w-[1120px]"><div className="text-center"><p className="text-[10px] font-bold uppercase tracking-[0.4em] text-[#9F7F36]">Finnish Buyer Questions</p><h2 className="mt-6 font-[family-name:var(--font-playfair)] text-[clamp(2.4rem,4.4vw,4.4rem)] font-semibold">Finland Export Supply FAQ</h2></div><div className="mt-12 divide-y divide-[#173B2A]/15 border-y border-[#173B2A]/15">{faqs.map((faq) => <article key={faq.question} className="grid gap-4 py-7 md:grid-cols-[0.8fr_1.2fr] md:gap-10"><h3 className="font-[family-name:var(--font-playfair)] text-xl font-semibold">{faq.question}</h3><p className="text-[14px] font-light leading-7 text-[#4C5F54]">{faq.answer}</p></article>)}</div></div></RevealOnScroll></section>

      <section className="relative overflow-hidden bg-[#071B14] px-6 py-24 text-center text-[#F5F0E6] sm:px-8 lg:px-12 lg:py-28"><GoldenParticles /><RevealOnScroll><div className="relative mx-auto max-w-[1000px]"><p className="text-[10px] font-bold uppercase tracking-[0.4em] text-[#E4C878]">Finland Buyer Enquiries</p><h2 className="mt-6 font-[family-name:var(--font-playfair)] text-[clamp(2.5rem,4.8vw,4.8rem)] font-semibold leading-[1.04]">Discuss Your Finland Product Requirement</h2><p className="mx-auto mt-7 max-w-[760px] text-[16px] font-light leading-8 text-[#F5F0E6]/65">Finnish importers, distributors, wholesalers and private-label buyers can share the product name, required quantity, packaging format, destination and intended business application with our export team.</p><div className="mt-9 flex flex-wrap justify-center gap-4"><Link href="/contact" className="inline-flex items-center gap-4 border border-[#C9A962] bg-[#C9A962] px-8 py-4 text-[10px] font-bold uppercase tracking-[0.22em] text-[#102F23] transition-all hover:-translate-y-1 hover:bg-[#E4C878]">Send Your Finland Requirement <span>→</span></Link><Link href="/export/europe" className="inline-flex items-center gap-4 border border-[#F5F0E6]/30 px-8 py-4 text-[10px] font-bold uppercase tracking-[0.22em] text-[#F5F0E6] transition-all hover:border-[#C9A962] hover:text-[#E4C878]">Explore European Markets <span>→</span></Link></div><div className="mt-9 flex flex-wrap justify-center gap-x-6 gap-y-3 text-[10px] font-bold uppercase tracking-[0.16em] text-[#F5F0E6]/45"><Link href="/export">Global Export Information</Link><Link href="/export/france">France Export Market</Link><Link href="/export/germany">Germany Export Market</Link><Link href="/export/italy">Italy Export Market</Link><Link href="/export/spain">Spain Export Market</Link><Link href="/export/austria">Austria Export Market</Link><Link href="/resources">Buyer Resources</Link><Link href="/certifications">Certifications</Link><Link href="/infrastructure">Infrastructure</Link><Link href="/about">About Shivesh International</Link><Link href="/export/finland">Finland Export Page</Link></div></div></RevealOnScroll></section>

      <FooterSection /><FloatingContactButtons /><MagneticButtons /><PremiumCursor />
    </main>
  );
}
