import type { Metadata } from "next";
import { existsSync } from "node:fs";
import Image from "next/image";
import Link from "next/link";

import FloatingContactButtons from "@/app/components/FloatingContactButtons";
import GoldenParticles from "@/app/components/GoldenParticles";
import MagneticButtons from "@/app/components/MagneticButtons";
import Navbar from "@/app/components/Navbar";
import PremiumCursor from "@/app/components/PremiumCursor";
import RevealOnScroll from "@/app/components/RevealOnScroll";
import StaggerItem from "@/app/components/StaggerItem";
import FooterSection from "@/sections/FooterSection";
import { spainLanguageAlternates } from "@/app/lib/i18n";

const canonicalUrl = "https://shiveshinternational.com/export/spain";
const heroImage = "/images/export/spain/spain-export-hero.png";

export const metadata: Metadata = {
  title: "Henna, Indigo, Herbs & Spices Exporter to Spain",
  description:
    "Shivesh International exports natural henna powder, indigo powder, botanical hair colors, Ayurvedic herbs and Indian spices to Spanish importers, distributors and private-label buyers. MOQ 200 kg per product.",
  keywords: [
    "Natural products exporter to Spain", "Indian natural products supplier Spain", "Exporter from India to Spain", "Indian supplier for Spanish importers", "Natural product manufacturer India for Spain", "Bulk natural products supplier Spain", "Private label products manufacturer for Spain", "Wholesale botanical products Spain", "Indian exporter for Spanish distributors", "Natural cosmetic ingredients supplier Spain", "Herbal products exporter to Spain", "Plant-based products supplier Spain", "Botanical ingredients exporter Spain", "Indian manufacturer for Spanish wholesalers", "B2B natural products supplier Spain",
    "Henna powder exporter to Spain", "Natural henna powder supplier Spain", "Henna powder manufacturer India for Spain", "Bulk henna powder supplier Spain", "Organic henna powder exporter Spain", "Private label henna powder Spain", "Wholesale henna powder Spain", "Cosmetic-grade henna powder supplier Spain", "Pure henna powder exporter to Spain", "Lawsonia inermis powder supplier Spain", "Indian henna exporter for Spanish importers", "Henna powder for cosmetic brands Spain", "Henna powder for salon suppliers Spain", "Henna powder wholesale supplier Spain", "Private label henna manufacturer India for Spain", "Natural henna supplier Madrid", "Henna powder supplier Barcelona", "Henna exporter for Spanish beauty brands",
    "Indigo powder exporter to Spain", "Natural indigo powder supplier Spain", "Indigo powder manufacturer India for Spain", "Bulk indigo powder supplier Spain", "Organic indigo powder exporter Spain", "Private label indigo powder Spain", "Wholesale indigo powder Spain", "Indigofera tinctoria powder supplier Spain", "Natural indigo for botanical hair color Spain", "Indigo powder for Spanish cosmetic brands", "Indian indigo exporter Spain", "Indigo hair dye ingredient supplier Spain", "Indigo powder for salons Spain", "Bulk indigo supplier for Spanish importers",
    "Natural henna hair color manufacturer for Spain", "Botanical hair color supplier Spain", "Plant-based hair color exporter Spain", "Natural hair dye manufacturer India for Spain", "Private label natural hair color Spain", "Henna hair color wholesale Spain", "Botanical hair dye supplier Spain", "Herbal hair color manufacturer for Spanish brands", "Powder hair color exporter Spain", "Natural hair color supplier for Spanish salons", "Henna-based hair color supplier Spain", "Private label botanical hair color manufacturer India", "Natural hair color for Spanish distributors", "Botanical hair color bulk supplier Spain", "Natural hair dye products for Spanish beauty brands", "Salon hair color supplier Spain",
    "Ayurvedic herbs exporter to Spain", "Indian herbs supplier Spain", "Herbal powder exporter Spain", "Ayurvedic powder supplier Spain", "Bulk Indian herbs supplier Spain", "Private label herbal products Spain", "Wholesale Ayurvedic herbs Spain", "Indian botanical ingredients exporter Spain", "Herbal ingredients for cosmetic brands Spain", "Natural herbal powder manufacturer India for Spain", "Ayurvedic herbs for Spanish importers", "Indian herbs for wellness brands Spain", "Bulk herbal powders exporter Spain", "Cosmetic herbal ingredients supplier Spain", "Amla powder supplier Spain", "Shikakai powder exporter Spain", "Herbal hair-care ingredients Spain",
    "Indian spices exporter to Spain", "Indian spices supplier Spain", "Bulk spices supplier Spain", "Wholesale Indian spices Spain", "Whole spices exporter to Spain", "Ground spices exporter Spain", "Private label Indian spices Spain", "Indian spice manufacturer for Spanish buyers", "Spice exporter from India to Spain", "Indian spices for Spanish importers", "Bulk spice powder supplier Spain", "Indian food ingredient supplier Spain", "Private label spice packaging Spain", "Indian spice wholesale supplier Spain", "Indian spices for Spanish food businesses", "Indian spices distributor supply Spain",
    "Private label manufacturer India for Spain", "Custom packaging supplier for Spanish buyers", "Private label henna packaging Spain", "Private label indigo packaging Spain", "Private label herbal powder Spain", "Private label spice supplier Spain", "Custom branded pouches for Spanish importers", "Retail packaging natural products Spain", "Bulk packaging exporter India to Spain", "Contract packaging for Spanish brands", "Multilingual label coordination Spain", "Spanish label packaging coordination", "White label natural products Spain", "OEM natural products supplier Spain", "Custom brand botanical products Spain", "Private label natural hair color Spain",
    "Henna supplier for Spanish importers", "Natural product supplier for Spanish distributors", "Botanical products for Spanish wholesalers", "Private label supplier for Spanish brands", "Henna supplier for salon distributors Spain", "Herbal ingredients for Spanish cosmetic manufacturers", "Indian products for Spanish retail businesses", "Bulk supplier for Spanish natural product brands", "Natural ingredients for Spanish beauty brands", "Indian exporter for Spanish wholesale buyers", "Natural product supplier Madrid", "Botanical product supplier Barcelona", "Indian herbal supplier Bilbao", "Natural hair-care ingredients Seville", "Private label products for Spanish e-commerce brands",
  ].filter((_, index) => index % 2 === 0).concat([
    "natural products retailer supplier Spain", "natural hair color salon supply Spain", "botanical hair color supplier for Spanish cosmetic brands", "natural product commercial buyer Spain", "Indian herbs wholesale supplier Spain", "Indian spices B2B supplier Spain", "buyer-brand botanical packaging Spain", "Shivesh International exporter Spain",
  ]),
  alternates: { canonical: canonicalUrl, languages: spainLanguageAlternates },
  openGraph: {
    title: "Henna, Indigo, Herbs & Spices Exporter to Spain",
    description: "Bulk, wholesale and private-label supply of Indian henna, indigo, botanical hair colors, Ayurvedic herbs and spices for professional buyers in Spain.",
    url: canonicalUrl,
    type: "website",
    locale: "en_ES",
    siteName: "Shivesh International",
  },
  twitter: {
    card: "summary_large_image",
    title: "Henna, Indigo, Herbs & Spices Exporter to Spain",
    description: "Indian natural-product supply for Spanish importers, distributors, salons and private-label brands.",
  },
  robots: { index: true, follow: true },
};

const products = [
  { title: "Natural Henna Powder", text: "Fine-quality natural henna powder for Spanish cosmetic brands, salons, wholesalers, herbal-product businesses and customized private-label retail supply.", href: "/products/natural-henna-powder" },
  { title: "Natural Indigo Powder", text: "Natural indigo powder for botanical hair-color systems, cosmetic formulations, salon supply, bulk sourcing and private-label packaging.", href: "/products/natural-indigo-powder" },
  { title: "Natural Henna Hair Colors", text: "A broad botanical shade collection for Spanish importers, beauty brands, natural hair-care companies and salon distribution businesses.", href: "/products/natural-henna-hair-colors" },
  { title: "Henna-Based Hair Colors", text: "Export-ready powdered hair colors for Spanish buyers requiring wholesale, OEM, professional or customized private-label formats.", href: "/products/henna-based-hair-colors" },
  { title: "Ayurvedic Indian Herbs", text: "Indian herbal powders and botanicals for Spanish cosmetic, personal-care, wellness, hair-care and wholesale product applications.", href: "/products/ayurvedic-indian-herbs" },
  { title: "Indian Spices", text: "Whole and powdered Indian spices for Spanish importers, distributors, food businesses, specialty retailers and private-label brands.", href: "/products/indian-spices" },
];

const buyerProfiles = [
  ["Importers", "Coordinate Spain-focused product specifications, quantities, packaging and available export documentation with one India-based supply contact."],
  ["Distributors", "Build natural-product assortments for regional distribution across Spanish professional, beauty, herbal and food channels."],
  ["Cosmetic Brands", "Source henna, indigo and Indian botanical ingredients for buyer-developed cosmetic and personal-care ranges."],
  ["Natural Hair-Care Brands", "Review botanical hair-color powders and herbal hair-care ingredients for Spanish brand programmes."],
  ["Salon & Professional Suppliers", "Discuss henna, indigo and powdered hair colors for salon and professional hair-care distribution across Spanish beauty channels."],
  ["Herbal & Wellness Companies", "Source Ayurvedic powders, amla, shikakai and selected botanicals for Spanish wellness and own-brand ranges."],
  ["Food & Spice Buyers", "Plan whole-spice, ground-spice and Indian food-ingredient supply for wholesale or retail channels."],
  ["Private-Label & E-Commerce Brands", "Coordinate selected products, buyer branding and commercially feasible packs for Spanish digital retail."],
];

const applications = [
  ["Cosmetic & Personal Care", "Natural henna and herbal ingredients can support buyer-developed cosmetic and personal-care formulations, subject to specification and intended-use review."],
  ["Botanical Hair-Color Systems", "Henna, indigo and shade blends support two-step and prepared botanical hair-color concepts for professional buyers."],
  ["Salon Distribution", "Bulk and selected retail formats can be discussed for professional hair-care distributors and salon suppliers."],
  ["Herbal Hair Care & Wellness", "Amla, shikakai and other Ayurvedic powders can support herbal hair-care, wellness and personal-care ranges."],
  ["Retail Natural Products", "Buyer-ready natural-product ranges can combine selected pack sizes with coordinated labels, boxes and pouches."],
  ["Private Label & OEM", "Spanish brands can discuss custom presentation and OEM or private-label supply after technical and commercial review."],
  ["Bulk Ingredient Sourcing", "Manufacturers, importers and wholesalers can source botanical powders in commercial bulk packaging for further use or resale."],
  ["Spice & Food Distribution", "Whole and ground Indian spices can be coordinated for Spanish food businesses, ingredient buyers and private-label programmes."],
  ["E-Commerce Product Development", "Spanish online brands can review focused product ranges, retail pack sizes and private-label presentation for digital sales channels."],
  ["Botanical Wellness Ranges", "Herbal and wellness companies can discuss selected Indian botanicals for buyer-developed natural-product collections."],
];

const trustItems = [
  ["India-Based Export Supplier", "Direct commercial coordination with an India-based natural-products export team."],
  ["MOQ from 200 kg per Product", "The commercial minimum begins at 200 kg for each selected product."],
  ["Retail, Bulk & Private Label", "Selected retail, professional, wholesale and buyer-brand formats can be reviewed."],
  ["Multiple Natural Product Categories", "Source henna, indigo, hair colors, Ayurvedic herbs and Indian spices."],
  ["Packaging Customization Support", "Coordinate feasible pouches, boxes, labels, artwork and barcode requirements."],
  ["Export Documentation Coordination", "Align available commercial and quality information with the agreed order."],
];

const faqs = [
  { question: "What products does Shivesh International export to Spain?", answer: "We supply natural henna powder, indigo powder, botanical and henna-based hair colors, Ayurvedic Indian herbs, and selected whole or ground Indian spices for qualified Spanish business buyers." },
  { question: "What is the minimum order quantity for Spanish buyers?", answer: "The minimum order quantity is 200 kg per product. Final quantities depend on the selected product, packaging format and private-label requirements." },
  { question: "Is private-label packaging available for Spain?", answer: "Private-label support can include buyer branding, printed pouches, boxes, custom labels, barcode coordination and Spanish-language artwork coordination, subject to feasibility and buyer review." },
  { question: "Can Spanish importers order henna and indigo powder in bulk?", answer: "Yes. Spanish importers and distributors can discuss commercial henna and indigo supply in available bulk formats, including 20 kg and 25 kg double-layer vacuum bags." },
  { question: "Which retail packaging sizes are available?", answer: "Selected products can be discussed in 100 g, 200 g, 500 g and 1 kg pouches. Material, print and artwork requirements are confirmed for each order." },
  { question: "Does Shivesh International support export documentation for Spain?", answer: "We coordinate applicable commercial invoices, packing lists, certificates of origin, shipping documentation, product specifications, COA and available quality documents for confirmed orders." },
  { question: "Can Spanish buyers source multiple product categories?", answer: "Multi-category enquiries are welcome. Product combinations, minimum quantities, packaging, documentation and shipment feasibility are reviewed before commercial confirmation." },
  { question: "How can a Spanish buyer request a quotation?", answer: "Use the contact page and share the product, quantity, pack format, destination in Spain and private-label needs. Our export team will review the enquiry and respond with practical next steps." },
];

const structuredData = {
  "@context": "https://schema.org",
  "@graph": [
    { "@type": "WebPage", "@id": `${canonicalUrl}#webpage`, url: canonicalUrl, name: "Henna, Indigo, Herbs & Spices Exporter to Spain", description: "Spain-focused export supply of natural henna, indigo, botanical hair colors, Ayurvedic herbs and Indian spices from India.", isPartOf: { "@id": "https://shiveshinternational.com/#website" }, about: { "@id": "https://shiveshinternational.com/#organization" }, breadcrumb: { "@id": `${canonicalUrl}#breadcrumb` }, inLanguage: "en" },
    { "@type": "BreadcrumbList", "@id": `${canonicalUrl}#breadcrumb`, itemListElement: [
      { "@type": "ListItem", position: 1, name: "Home", item: "https://shiveshinternational.com/" },
      { "@type": "ListItem", position: 2, name: "Export", item: "https://shiveshinternational.com/export" },
      { "@type": "ListItem", position: 3, name: "Europe", item: "https://shiveshinternational.com/export/europe" },
      { "@type": "ListItem", position: 4, name: "Spain", item: canonicalUrl },
    ] },
  ],
};

const faqStructuredData = { "@context": "https://schema.org", "@type": "FAQPage", "@id": `${canonicalUrl}#faq`, mainEntity: faqs.map((faq) => ({ "@type": "Question", name: faq.question, acceptedAnswer: { "@type": "Answer", text: faq.answer } })) };

function OptionalImage({ src, alt, priority = false, sizes = "(min-width: 1024px) 55vw, 100vw", className = "object-cover object-center" }: { src: string; alt: string; priority?: boolean; sizes?: string; className?: string }) {
  if (!existsSync(`${process.cwd()}/public${src}`)) return null;
  return <Image src={src} alt={alt} fill priority={priority} sizes={sizes} className={className} />;
}

export default function SpainExportPage() {
  return (
    <main className="min-h-screen overflow-x-hidden bg-[#F5F0E6] text-[#173B2A]">
      <script type="application/ld+json" dangerouslySetInnerHTML={{ __html: JSON.stringify(structuredData).replace(/</g, "\\u003c") }} />
      <script type="application/ld+json" dangerouslySetInnerHTML={{ __html: JSON.stringify(faqStructuredData).replace(/</g, "\\u003c") }} />
      <Navbar />

      <section className="relative isolate overflow-hidden bg-[radial-gradient(circle_at_75%_42%,#496d58_0%,#173b2a_35%,#071b14_78%)]">
        <OptionalImage src={heroImage} alt="Spanish buyers reviewing Indian henna, indigo, herbs and spices supply for export from India" priority sizes="100vw" className="object-cover object-[50%_52%] sm:object-[50%_52%] lg:object-[50%_52%]" />
        <div className="absolute inset-0 bg-gradient-to-r from-[#061711]/72 via-[#102F23]/40 to-[#071B14]/10" />
        <div className="absolute inset-0 bg-gradient-to-t from-black/10 via-transparent to-black/[0.04]" />
        <GoldenParticles />
        <div className="relative z-10 flex items-center px-6 pb-20 pt-32 sm:px-8 sm:pb-24 sm:pt-36 lg:px-12 lg:pb-28 lg:pt-40">
          <div className="w-full max-w-[820px] lg:max-w-[860px] xl:max-w-[900px]">
            <StaggerItem delay={0}><div className="flex items-center gap-4"><span className="h-px w-14 bg-[#C9A962]" /><p className="text-[10px] font-bold uppercase tracking-[0.38em] text-[#E4C878] sm:text-xs">Exporting from India to Spain</p></div></StaggerItem>
            <StaggerItem delay={100}><h1 className="mt-5 font-[family-name:var(--font-playfair)] text-4xl font-medium leading-[1] tracking-[-0.04em] text-[#F5F0E6] sm:text-5xl lg:text-6xl xl:text-[66px]">Natural Products Exporter to Spain<span className="mt-2 block bg-gradient-to-r from-[#F5F0E6] via-[#E4C878] to-[#C9A962] bg-clip-text text-transparent">Henna, Indigo, Herbs &amp; Spices</span></h1></StaggerItem>
            <StaggerItem delay={200}><p className="mt-5 max-w-[730px] text-[16px] font-light leading-7 text-[#F5F0E6]/82 sm:text-[17px] sm:leading-8">Shivesh International supports Spanish importers, distributors, wholesalers, cosmetic companies, salon suppliers, herbal-product businesses, food-sector buyers and private-label brands with export-ready natural henna, indigo, botanical hair colors, Ayurvedic herbs and Indian spices from India.</p></StaggerItem>
            <StaggerItem delay={300}><div className="mt-7 flex flex-wrap gap-4"><Link href="/contact" className="inline-flex items-center gap-4 border border-[#C9A962] bg-[#C9A962] px-7 py-4 text-[10px] font-bold uppercase tracking-[0.2em] text-[#102F23] transition-all hover:-translate-y-1 hover:bg-[#E4C878] focus-visible:outline focus-visible:outline-2 focus-visible:outline-offset-4 focus-visible:outline-[#E4C878]">Send Spain Inquiry <span>→</span></Link><a href="#spain-products" className="inline-flex items-center gap-4 border border-[#F5F0E6]/30 bg-[#102F23]/40 px-7 py-4 text-[10px] font-bold uppercase tracking-[0.2em] text-[#F5F0E6] backdrop-blur-lg transition-all hover:border-[#C9A962] hover:text-[#E4C878] focus-visible:outline focus-visible:outline-2 focus-visible:outline-offset-4 focus-visible:outline-[#E4C878]">Explore Products <span>↓</span></a></div></StaggerItem>
            <StaggerItem delay={400}><div className="mt-10 grid max-w-[740px] grid-cols-2 gap-3 lg:grid-cols-4">{[["200 kg", "MOQ Per Product"], ["Bulk", "Wholesale Supply"], ["OEM", "Private Label"], ["Spain", "Buyer Enquiries"]].map(([value, label]) => <div key={label} className="border border-white/15 bg-black/20 px-4 py-4 backdrop-blur-md"><p className="font-[family-name:var(--font-playfair)] text-xl font-semibold text-[#E4C878]">{value}</p><p className="mt-2 text-[9px] font-bold uppercase tracking-[0.22em] text-[#F5F0E6]/55">{label}</p></div>)}</div></StaggerItem>
          </div>
        </div>
      </section>

      <section className="px-6 py-24 sm:px-8 lg:px-12 lg:py-32"><RevealOnScroll><div className="mx-auto max-w-[1120px]"><p className="text-[10px] font-bold uppercase tracking-[0.4em] text-[#9F7F36]">India–Spain Natural Product Sourcing</p><h2 className="mt-6 font-[family-name:var(--font-playfair)] text-[clamp(2.5rem,4.6vw,4.6rem)] font-semibold leading-[1.04]">Your Indian Export Partner <span className="block text-[#A97B22]">for the Spanish Market</span></h2><p className="mt-7 text-[16px] font-light leading-8 text-[#4C5F54]">Spanish importers, distributors and wholesalers can coordinate multiple product categories with one Indian export team. Shivesh International supports cosmetic and personal-care companies, natural hair-care brands, salon suppliers, herbal and wellness businesses, food ingredient buyers, spice companies, private-label operators and e-commerce brands seeking structured sourcing from India.</p><p className="mt-5 text-[15px] font-light leading-8 text-[#4C5F54]">Commercial enquiries may be associated with buyer and distribution activity in Madrid, Barcelona, Seville, Valencia and Bilbao. Product availability, specifications, packaging, documentation and shipment preparation are reviewed according to the buyer’s selected category and agreed order requirements. Market references identify potential buyer locations and do not imply that Shivesh International maintains a local office or warehouse in Spain.</p></div></RevealOnScroll></section>

      <section id="spain-products" className="scroll-mt-24 bg-[#EDE5D7] px-6 py-24 sm:px-8 lg:px-12 lg:py-32"><RevealOnScroll><div className="mx-auto max-w-[1500px]"><div className="mx-auto max-w-[920px] text-center"><p className="text-[10px] font-bold uppercase tracking-[0.4em] text-[#9F7F36]">Six Commercial Categories</p><h2 className="mt-6 font-[family-name:var(--font-playfair)] text-[clamp(2.5rem,4.8vw,4.8rem)] font-semibold leading-[1.04]">Natural Products <span className="block text-[#A97B22]">for Spanish Importers and Brands</span></h2><p className="mx-auto mt-7 max-w-[820px] text-[16px] font-light leading-8 text-[#4C5F54]">A focused portfolio for Spanish cosmetic brands, professional hair-care channels, herbal businesses, wholesalers, food companies and private-label buyers.</p></div><div className="mt-14 grid auto-rows-fr gap-5 sm:grid-cols-2 lg:grid-cols-3">{products.map((product, index) => <StaggerItem key={product.title} delay={(index % 3) * 90}><article className="group flex h-full min-h-[300px] flex-col border border-[#173B2A]/12 bg-[#FBF8F1] p-7 shadow-[0_18px_45px_rgba(20,50,38,0.07)] transition-all hover:-translate-y-2 hover:border-[#C9A962]/70 sm:p-8"><span className="font-[family-name:var(--font-playfair)] text-4xl font-semibold text-[#C9A962]/60">{String(index + 1).padStart(2, "0")}</span><h3 className="mt-6 font-[family-name:var(--font-playfair)] text-[27px] font-semibold leading-tight">{product.title}</h3><p className="mt-5 flex-1 text-[14px] font-light leading-7 text-[#4C5F54]">{product.text}</p><Link href={product.href} className="mt-7 inline-flex items-center gap-3 text-[10px] font-bold uppercase tracking-[0.2em] text-[#A97B22] focus-visible:outline focus-visible:outline-2 focus-visible:outline-offset-4 focus-visible:outline-[#A97B22]">Explore {product.title} <span className="transition-transform group-hover:translate-x-2">→</span></Link></article></StaggerItem>)}</div></div></RevealOnScroll></section>

      <section className="bg-[#0B3325] px-6 py-24 text-[#F5F0E6] sm:px-8 lg:px-12 lg:py-32"><RevealOnScroll><div className="mx-auto max-w-[1500px]"><div className="mx-auto max-w-[920px] text-center"><p className="text-[10px] font-bold uppercase tracking-[0.4em] text-[#E4C878]">Spanish Commercial Channels</p><h2 className="mt-6 font-[family-name:var(--font-playfair)] text-[clamp(2.5rem,4.7vw,4.7rem)] font-semibold leading-[1.04]">Supply Solutions for Spanish B2B Buyers</h2></div><div className="mt-14 grid auto-rows-fr gap-5 sm:grid-cols-2 lg:grid-cols-4">{buyerProfiles.map(([title, text]) => <article key={title} className="h-full border border-[#C9A962]/25 bg-[#071B14]/55 p-7"><h3 className="font-[family-name:var(--font-playfair)] text-2xl font-semibold text-[#E4C878]">{title}</h3><p className="mt-4 text-[14px] font-light leading-7 text-[#F5F0E6]/65">{text}</p></article>)}</div></div></RevealOnScroll></section>

      <section className="px-6 py-24 sm:px-8 lg:px-12 lg:py-32"><RevealOnScroll><div className="mx-auto max-w-[1500px]"><div className="grid gap-14 lg:grid-cols-[0.7fr_1.3fr] lg:gap-20"><div><p className="text-[10px] font-bold uppercase tracking-[0.4em] text-[#9F7F36]">Commercial Use Cases</p><h2 className="mt-6 font-[family-name:var(--font-playfair)] text-[clamp(2.5rem,4.5vw,4.5rem)] font-semibold leading-[1.04]">Product Applications <span className="block text-[#A97B22]">for the Spanish Market</span></h2><p className="mt-7 text-[15px] font-light leading-8 text-[#4C5F54]">Every enquiry is reviewed around intended use, buyer specification, commercial quantity, packaging format and destination requirements.</p></div><div className="grid auto-rows-fr gap-5 sm:grid-cols-2">{applications.map(([title, text]) => <article key={title} className="h-full border border-[#173B2A]/12 bg-[#FBF8F1] p-7"><span className="block h-px w-12 bg-[#C9A962]" /><h3 className="mt-5 font-[family-name:var(--font-playfair)] text-2xl font-semibold">{title}</h3><p className="mt-4 text-[14px] font-light leading-7 text-[#4C5F54]">{text}</p></article>)}</div></div></div></RevealOnScroll></section>

      <section className="bg-[#EDE5D7] px-6 py-24 sm:px-8 lg:px-12 lg:py-32"><RevealOnScroll><div className="mx-auto grid max-w-[1500px] gap-14 lg:grid-cols-[1.05fr_0.95fr] lg:gap-20"><div><p className="text-[10px] font-bold uppercase tracking-[0.4em] text-[#9F7F36]">Buyer-Brand Formats</p><h2 className="mt-6 font-[family-name:var(--font-playfair)] text-[clamp(2.5rem,4.6vw,4.6rem)] font-semibold leading-[1.04]">Packaging &amp; Private-Label Solutions <span className="block text-[#A97B22]">for Spanish Buyers</span></h2><p className="mt-7 text-[15px] font-light leading-8 text-[#4C5F54]">Selected programmes can include custom brand names, printed pouches, printed boxes, buyer-supplied artwork coordination, barcodes, label-layout support, multilingual packaging and Spanish-language label artwork coordination. Retail, salon, professional and bulk formats, including OEM or private-label supply, remain subject to agreed requirements and technical feasibility.</p><p className="mt-5 text-[14px] font-light leading-7 text-[#4C5F54]">Retail options may include 100 g, 200 g, 500 g and 1 kg pouches. Bulk formats may include 20 kg and 25 kg double-layer vacuum bags. Final product labels, language requirements, claims, product classification and destination-market compliance remain subject to buyer review and the applicable product category.</p></div><div><figure className="relative aspect-[3/2] overflow-hidden rounded-sm border border-[#C9A962]/35 bg-[linear-gradient(135deg,#0b3325,#496d58)] shadow-[0_28px_70px_rgba(20,50,38,0.18)]"><OptionalImage src="/images/export/spain/spain-buyer-partnership.png" alt="Automated private-label packaging line in India preparing natural products for Spanish buyers" className="object-cover object-center" /></figure><div className="mt-5 grid gap-5 sm:grid-cols-2"><article className="border border-[#C9A962]/35 bg-[#FBF8F1] p-7"><h3 className="font-[family-name:var(--font-playfair)] text-2xl font-semibold">Retail Packaging</h3><p className="mt-4 text-sm leading-7 text-[#4C5F54]">100 g · 200 g · 500 g · 1 kg pouches</p></article><article className="border border-[#C9A962]/35 bg-[#FBF8F1] p-7"><h3 className="font-[family-name:var(--font-playfair)] text-2xl font-semibold">Bulk Packaging</h3><p className="mt-4 text-sm leading-7 text-[#4C5F54]">20 kg and 25 kg double-layer vacuum bags</p></article><article className="border border-[#C9A962] bg-[#173B2A] p-7 text-[#F5F0E6] sm:col-span-2"><p className="text-[10px] font-bold uppercase tracking-[0.3em] text-[#E4C878]">Minimum Order Quantity</p><p className="mt-4 font-[family-name:var(--font-playfair)] text-4xl font-semibold">200 kg per product</p></article></div></div></div></RevealOnScroll></section>

      <section className="bg-[#09271D] px-6 py-24 text-[#F5F0E6] sm:px-8 lg:px-12 lg:py-32"><RevealOnScroll><div className="mx-auto max-w-[1500px]"><div className="grid items-center gap-14 lg:grid-cols-[0.9fr_1.1fr] lg:gap-20"><div><p className="text-[10px] font-bold uppercase tracking-[0.4em] text-[#E4C878]">Shipment and Document Support</p><h2 className="mt-6 font-[family-name:var(--font-playfair)] text-[clamp(2.5rem,4.8vw,4.8rem)] font-semibold leading-[1.04]">India-to-Spain Export Coordination</h2><p className="mt-7 text-[16px] font-light leading-8 text-[#F5F0E6]/68">Coordination can cover commercial invoices, packing lists, certificates of origin, product specifications, COA and available quality documents, shipping documentation, buyer-appointed freight forwarders, export cartons, pallets and shipment information sharing.</p><p className="mt-5 text-[15px] font-light leading-8 text-[#F5F0E6]/62">Sea- or air-freight planning may be discussed for buyer-selected logistics arrangements associated with the Port of Valencia, Port of Barcelona, Port of Algeciras, Port of Bilbao, Madrid-area air cargo or Barcelona-area air cargo. This does not promise route availability, delivery timing or customs clearance. Documentation and product information can be coordinated according to the product category, destination, buyer instructions and agreed order requirements.</p></div><figure className="relative aspect-[3/2] overflow-hidden rounded-sm border border-[#C9A962]/35 bg-[linear-gradient(135deg,#071b14,#496d58)] shadow-[0_28px_70px_rgba(0,0,0,0.25)]"><OptionalImage src="/images/export/spain/india-to-spain-export-coordination.png" alt="India-to-Spain export logistics command centre coordinating documents, tracking and sea shipments" className="object-cover object-center" /></figure></div><aside className="mt-12 border border-[#C9A962]/35 bg-[#071B14]/60 p-7 text-[14px] font-light leading-7 text-[#F5F0E6]/65">The Spanish importer or buyer remains responsible for confirming product classification, labelling, registration, customs procedures and applicable destination-market requirements.</aside></div></RevealOnScroll></section>

      <section className="bg-[#EDE5D7] px-6 py-24 sm:px-8 lg:px-12 lg:py-32"><RevealOnScroll><div className="mx-auto max-w-[1500px]"><div className="mx-auto max-w-[920px] text-center"><p className="text-[10px] font-bold uppercase tracking-[0.4em] text-[#9F7F36]">Commercial Supply Strengths</p><h2 className="mt-6 font-[family-name:var(--font-playfair)] text-[clamp(2.5rem,4.7vw,4.7rem)] font-semibold leading-[1.04]">Why Spanish Buyers Work with Shivesh International</h2></div><div className="mt-14 grid auto-rows-fr gap-5 sm:grid-cols-2 lg:grid-cols-3">{trustItems.map(([title, text]) => <article key={title} className="h-full border border-[#173B2A]/12 bg-[#FBF8F1] p-7 sm:p-8"><span className="block h-px w-12 bg-[#C9A962]" /><h3 className="mt-6 font-[family-name:var(--font-playfair)] text-2xl font-semibold">{title}</h3><p className="mt-4 text-[14px] font-light leading-7 text-[#4C5F54]">{text}</p></article>)}</div></div></RevealOnScroll></section>

      <section className="px-6 py-24 sm:px-8 lg:px-12 lg:py-32"><RevealOnScroll><div className="mx-auto max-w-[1120px]"><p className="text-[10px] font-bold uppercase tracking-[0.4em] text-[#9F7F36]">Spanish Market Locations</p><h2 className="mt-6 font-[family-name:var(--font-playfair)] text-[clamp(2.5rem,4.6vw,4.6rem)] font-semibold leading-[1.04]">Supporting Natural Product Enquiries Across Spain</h2><p className="mt-7 text-[16px] font-light leading-8 text-[#4C5F54]">We welcome professional enquiries associated with Madrid’s import and brand community, Barcelona’s beauty and distribution businesses, Valencia-area food and logistics buyers, Seville and Málaga wellness channels, Bilbao trade businesses, Alicante retail operators and Zaragoza-area wholesale enquiries. Buyers can discuss product category, intended use, quantity, branding, packaging and destination before commercial review.</p><p className="mt-5 text-[14px] leading-7 text-[#4C5F54]">Location references indicate potential enquiry and distribution markets; they do not represent local offices, warehouses or guaranteed active supply relationships.</p><div className="mt-8 flex flex-wrap gap-3">{["Madrid", "Barcelona", "Valencia", "Seville", "Bilbao", "Málaga", "Alicante", "Zaragoza"].map((city) => <span key={city} className="border border-[#C9A962]/40 bg-[#FBF8F1] px-5 py-3 text-[10px] font-bold uppercase tracking-[0.2em] text-[#A97B22]">{city}</span>)}</div></div></RevealOnScroll></section>

      <section className="bg-[#EDE5D7] px-6 py-24 sm:px-8 lg:px-12 lg:py-32"><RevealOnScroll><div className="mx-auto max-w-[1120px]"><div className="text-center"><p className="text-[10px] font-bold uppercase tracking-[0.4em] text-[#9F7F36]">Spanish Buyer Questions</p><h2 className="mt-6 font-[family-name:var(--font-playfair)] text-[clamp(2.4rem,4.4vw,4.4rem)] font-semibold">Spain Export Supply FAQ</h2></div><div className="mt-12 divide-y divide-[#173B2A]/15 border-y border-[#173B2A]/15">{faqs.map((faq) => <article key={faq.question} className="grid gap-4 py-7 md:grid-cols-[0.8fr_1.2fr] md:gap-10"><h3 className="font-[family-name:var(--font-playfair)] text-xl font-semibold">{faq.question}</h3><p className="text-[14px] font-light leading-7 text-[#4C5F54]">{faq.answer}</p></article>)}</div></div></RevealOnScroll></section>

      <section className="relative overflow-hidden bg-[#071B14] px-6 py-24 text-center text-[#F5F0E6] sm:px-8 lg:px-12 lg:py-28"><GoldenParticles /><RevealOnScroll><div className="relative mx-auto max-w-[1000px]"><p className="text-[10px] font-bold uppercase tracking-[0.4em] text-[#E4C878]">Spain Buyer Enquiries</p><h2 className="mt-6 font-[family-name:var(--font-playfair)] text-[clamp(2.5rem,4.8vw,4.8rem)] font-semibold leading-[1.04]">Looking for a Reliable Natural Product Supplier from India?</h2><p className="mx-auto mt-7 max-w-[760px] text-[16px] font-light leading-8 text-[#F5F0E6]/65">Share your required product, quantity, packaging format, destination in Spain and private-label requirements with the Shivesh International export team.</p><div className="mt-9 flex flex-wrap justify-center gap-4"><Link href="/contact" className="inline-flex items-center gap-4 border border-[#C9A962] bg-[#C9A962] px-8 py-4 text-[10px] font-bold uppercase tracking-[0.22em] text-[#102F23] transition-all hover:-translate-y-1 hover:bg-[#E4C878]">Send Your Spain Requirement <span>→</span></Link><Link href="/export/europe" className="inline-flex items-center gap-4 border border-[#F5F0E6]/30 px-8 py-4 text-[10px] font-bold uppercase tracking-[0.22em] text-[#F5F0E6] transition-all hover:border-[#C9A962] hover:text-[#E4C878]">Explore Europe Hub <span>→</span></Link></div><div className="mt-9 flex flex-wrap justify-center gap-x-6 gap-y-3 text-[10px] font-bold uppercase tracking-[0.16em] text-[#F5F0E6]/45"><Link href="/export">Global Export Information</Link><Link href="/export/france">France Export Market</Link><Link href="/export/germany">Germany Export Market</Link><Link href="/export/italy">Italy Export Market</Link><Link href="/resources">Buyer Resources</Link><Link href="/certifications">Certifications</Link><Link href="/infrastructure">Infrastructure</Link><Link href="/about">About Shivesh International</Link><Link href="/export/spain">Spain Export Page</Link></div></div></RevealOnScroll></section>

      <FooterSection /><FloatingContactButtons /><MagneticButtons /><PremiumCursor />
    </main>
  );
}
