/* eslint-disable react/no-unescaped-entities */
import type { Metadata } from "next";
import { existsSync } from "node:fs";
import Image from "next/image";
import Link from "next/link";
import FloatingContactButtons from "@/app/components/FloatingContactButtons";
import GoldenParticles from "@/app/components/GoldenParticles";
import MagneticButtons from "@/app/components/MagneticButtons";
import Navbar from "@/app/components/Navbar";
import PremiumCursor from "@/app/components/PremiumCursor";
import RevealOnScroll from "@/app/components/RevealOnScroll";
import StaggerItem from "@/app/components/StaggerItem";
import FooterSection from "@/sections/FooterSection";

const canonicalUrl = "https://shiveshinternational.com/export/vietnam";
const heroImage = "/images/export/vietnam/vietnam-natural-products-export-hero.png";
const metadataKeywords = [
  "natural products exporter to Vietnam", "natural products supplier Vietnam", "natural products manufacturer India for Vietnam", "bulk natural products supplier Vietnam", "wholesale natural products Vietnam", "private label natural products Vietnam", "OEM natural products Vietnam", "Indian botanical products supplier Vietnam", "herbal products exporter to Vietnam",
  "henna powder exporter to Vietnam", "natural henna powder supplier Vietnam", "henna manufacturer India for Vietnam", "bulk henna powder supplier Vietnam", "wholesale henna powder Vietnam", "organic henna powder supplier Vietnam", "private label henna Vietnam", "OEM henna products Vietnam", "henna powder importer Vietnam", "henna powder distributor Vietnam", "Sojat henna powder supplier Vietnam",
  "indigo powder exporter to Vietnam", "natural indigo powder supplier Vietnam", "indigo powder manufacturer India for Vietnam", "bulk indigo powder supplier Vietnam", "wholesale indigo powder Vietnam", "private label indigo powder Vietnam", "indigo powder importer Vietnam", "indigo powder distributor Vietnam", "botanical hair color ingredient supplier Vietnam",
  "natural henna hair colors exporter Vietnam", "botanical hair color supplier Vietnam", "natural hair color manufacturer India for Vietnam", "henna hair color supplier Vietnam", "private label henna hair colors Vietnam", "OEM botanical hair colors Vietnam", "salon hair color supplier Vietnam", "natural hair dye exporter Vietnam", "herbal hair color supplier Vietnam",
  "Ayurvedic herbs exporter to Vietnam", "Indian herbs supplier Vietnam", "herbal powder exporter Vietnam", "botanical ingredients supplier Vietnam", "private label Ayurvedic herbs Vietnam", "bulk herbal powders Vietnam", "Ayurvedic ingredients importer Vietnam", "spa herbal ingredient supplier Vietnam",
  "Indian spices exporter to Vietnam", "Indian spices supplier Vietnam", "bulk Indian spices Vietnam", "wholesale spices supplier Vietnam", "private label Indian spices Vietnam", "spice importer Vietnam", "spice distributor Vietnam", "Indian food ingredients supplier Vietnam",
  "Vietnam importer natural products India", "Vietnam distributor natural products India", "Vietnam cosmetic ingredient buyer India", "Vietnam natural hair care brand supplier", "Vietnam private label supplier India", "Vietnam herbal wholesaler India", "Vietnam salon supplier natural hair color", "Vietnam retail natural products supplier", "Vietnam e-commerce natural products supplier", "Vietnam spa product supplier India", "Vietnam wellness product supplier India", "India exporter to Vietnam", "Indian exporter natural products Vietnam", "B2B natural products supplier Vietnam", "bulk botanical products Vietnam", "wholesale herbal products Vietnam", "private label botanical products Vietnam", "export documentation support Vietnam", "natural products shipping from India to Vietnam", "India to Vietnam export coordination", "Shivesh International Vietnam exporter",
];
export const metadata: Metadata = {
  title: { absolute: "Natural Products Exporter to Vietnam | Henna, Indigo, Herbs & Spices" },
  description: "Natural henna, indigo, botanical hair colors, Ayurvedic herbs and Indian spices for Vietnam importers, distributors, wholesalers and private-label buyers. MOQ 200 kg per item.",
  keywords: metadataKeywords,
  alternates: { canonical: canonicalUrl },
  openGraph: { title: "Henna & Indigo Exporter to Vietnam | Shivesh International", description: "India-origin henna, indigo, herbs and spices for Vietnamese importers, distributors and buyer-brand programmes.", url: canonicalUrl, type: "website", locale: "en_VN", siteName: "Shivesh International", images: [{ url: heroImage, alt: "Indian natural-product export supply for professional buyers in Vietnam" }] },
  twitter: { card: "summary_large_image", title: "Natural Products Exporter to Vietnam", description: "Bulk and private-label botanical product supply from India for professional buyers in Vietnam.", images: [heroImage] },
  robots: { index: true, follow: true, googleBot: { index: true, follow: true } },
};
const products = [
  ["Natural Henna Powder", "Commercial henna supply for Vietnamese cosmetic businesses, natural hair-care brands, salon channels and repacking programmes.", "/products/natural-henna-powder"],
  ["Natural Indigo Powder", "Plant-based indigo for professional buyers developing two-step botanical hair-color ranges and wholesale assortments.", "/products/natural-indigo-powder"],
  ["Natural Henna Hair Colors", "Retail and professional powder-color options for Vietnam beauty distributors, online sellers and buyer-brand portfolios.", "/products/natural-henna-hair-colors"],
  ["Henna-Based Hair Colors", "Commercial shade selections for salon suppliers, cosmetics channels and technically feasible private-label projects.", "/products/henna-based-hair-colors"],
  ["Ayurvedic Indian Herbs", "Indian herbal powders for appropriate cosmetic, spa, wellness and wholesale uses without therapeutic promises.", "/products/ayurvedic-indian-herbs"],
  ["Indian Spices", "Whole, ground and blended spice options for Vietnamese importers, food businesses and distribution partners.", "/products/indian-spices"],
];
const buyers = [
  ["Importers & Distributors", "Review specifications, commercial volumes, document needs and onward distribution plans for the Vietnamese market."],
  ["Natural Cosmetic Companies", "Source selected botanical powders for suitable formulations, processing requirements and finished-product concepts."],
  ["Hair-Care Brands", "Build professional or retail botanical color ranges around confirmed product and packaging requirements."],
  ["Salon & Beauty Suppliers", "Consider salon-facing formats, wholesale packs and repeat procurement for beauty-sector channels."],
  ["Private-Label Companies", "Coordinate feasible branded pouches, artwork details, pack formats and product portfolio planning."],
  ["Herbal & Wellness Wholesalers", "Assess Indian botanical powders for appropriate wellness retail, specialist trade and wholesale distribution."],
  ["Spa & Wellness Product Buyers", "Discuss suitable herbs and botanical ingredients for spa, hospitality and specialist product programmes."],
  ["Food & Spice Buyers", "Plan Indian spice specifications, pack formats and quantities for food-service or retail distribution."],
];
const documents = [
  ["Commercial Invoice", "Prepared using confirmed products, quantities, values and agreed commercial terms."], ["Packing List", "Can record package counts, weights, cartons or pallets and shipment references."], ["Certificate of Origin", "May be coordinated where applicable and subject to issuing availability."], ["Transport Documents", "A Bill of Lading or Air Waybill follows the confirmed shipping arrangement."], ["Product & Quality Records", "Specifications, COA or MSDS/SDS may be shared where applicable and available."], ["Mutually Agreed Records", "Other export-side documents may be reviewed according to feasibility and availability."],
];
const steps = [
  ["Product Selection", "Define the product, intended use, Vietnamese destination and expected volume."], ["Specification Review", "Align requested parameters with available specifications and product information."], ["Commercial Confirmation", "Confirm quantity, the 200 kg per-item MOQ, quotation and terms."], ["Packaging & Production", "Approve feasible bulk or buyer-brand packing before production."], ["Documentation", "Prepare applicable and available commercial, quality and shipment records."], ["Shipment Coordination", "Coordinate dispatch and document sharing with the buyer or nominated forwarder."],
];
const strengths = [
  ["Export-Focused Experience", "Practical product and sourcing knowledge supports professional buyer discussions."], ["Manufacturing Support", "Production capabilities and a raw-material network support selected programmes."], ["Specification Planning", "Orders proceed around mutually reviewed product requirements."], ["Bulk & Buyer-Brand Options", "Wholesale and private-label formats can be assessed for suitable volumes."], ["Flexible Pack Formats", "Retail-ready and bulk configurations serve different commercial channels."], ["Document Coordination", "Available records can be organized transaction-wise."], ["Forwarder Alignment", "Dispatch can be coordinated with the buyer's selected logistics provider."], ["Responsive Communication", "Enquiries are evaluated around use, specifications, packaging and scale."],
];
const locations = [
  ["Ho Chi Minh City", "Importers, beauty companies, retailers and e-commerce businesses can evaluate multi-product sourcing and private-label opportunities."],
  ["Hanoi", "National distributors, cosmetic buyers and food companies can review specifications, packaging and commercial supply planning."],
  ["Da Nang", "Central Vietnam salon suppliers, hospitality buyers and wellness retailers can assess suitable botanical and branded formats."],
  ["Hai Phong", "Port-connected importers and distributors can discuss bulk procurement, documentation and nominated freight coordination."],
  ["Can Tho", "Mekong Delta wholesalers, retailers and food buyers can explore herbs, spices and natural-product distribution requirements."],
  ["Binh Duong", "Manufacturing and private-label businesses can evaluate ingredients, commercial packs and repeat-order programmes."],
  ["Dong Nai", "Industrial-area cosmetic, food and distribution buyers can plan volume supply and product-specific documentation."],
  ["Bac Ninh", "Northern commercial buyers can consider botanical ingredients, salon products and wholesale assortments."],
];
const faqs = [
  { question: "What products can Vietnam buyers source?", answer: "Vietnam buyers can enquire about natural henna powder, indigo powder, natural henna hair colors, henna-based hair colors, Ayurvedic Indian herbs and Indian spices for suitable professional uses." },
  { question: "What is the MOQ for Vietnam orders?", answer: "The minimum order quantity is 200 kg per selected product or item. Multi-product requirements are reviewed separately for feasibility." },
  { question: "Is private-label supply available for Vietnam buyers?", answer: "Buyer-brand packaging can be discussed for suitable products and volumes, subject to artwork, materials, printing details and technical feasibility." },
  { question: "Which retail pack sizes may be considered?", answer: "Depending on the product and confirmed packaging, retail formats may include 100 g, 200 g, 500 g and 1 kg." },
  { question: "Can Vietnam buyers order bulk packaging?", answer: "Bulk options may include 20 kg and 25 kg packs, including double-layer vacuum packaging where appropriate." },
  { question: "Do you work with Vietnamese importers and distributors?", answer: "Professional buyers may submit their product, intended-use, specification, quantity, packaging and destination requirements for review." },
  { question: "What export documents can be coordinated?", answer: "Depending on availability, records may include an invoice, packing list, certificate of origin, transport document, specification, COA or MSDS/SDS." },
  { question: "Can cargo be coordinated for Ho Chi Minh City, Cat Lai or Hai Phong?", answer: "Those or other feasible buyer-nominated cargo destinations may be considered. Routes, schedules, clearance, transit time and delivery are not guaranteed." },
  { question: "Who is responsible for Vietnam import approvals and labeling?", answer: "The Vietnam importer or buyer must confirm classification, import eligibility, registrations, permits, labeling, language, claims, customs and destination requirements." },
  { question: "How does a Vietnam buyer request a quotation?", answer: "Send company details, product, specification, intended use, quantity, pack preference and destination through the contact page." },
];
const structuredData = { "@context": "https://schema.org", "@graph": [
  { "@type": "WebPage", "@id": `${canonicalUrl}#webpage`, url: canonicalUrl, name: "Natural Products Exporter to Vietnam", description: "Vietnam-focused B2B export supply of natural henna, indigo, botanical hair colors, Ayurvedic herbs and Indian spices from India.", isPartOf: { "@id": "https://shiveshinternational.com/#website" }, about: { "@id": "https://shiveshinternational.com/#organization" }, breadcrumb: { "@id": `${canonicalUrl}#breadcrumb` }, primaryImageOfPage: { "@type": "ImageObject", url: heroImage }, inLanguage: "en" },
  { "@type": "BreadcrumbList", "@id": `${canonicalUrl}#breadcrumb`, itemListElement: [{ "@type": "ListItem", position: 1, name: "Home", item: "https://shiveshinternational.com/" }, { "@type": "ListItem", position: 2, name: "Export", item: "https://shiveshinternational.com/export" }, { "@type": "ListItem", position: 3, name: "Asia-Pacific", item: "https://shiveshinternational.com/export/asia-pacific" }, { "@type": "ListItem", position: 4, name: "Vietnam", item: canonicalUrl }] },
] };
const faqStructuredData = { "@context": "https://schema.org", "@type": "FAQPage", "@id": `${canonicalUrl}#faq`, mainEntity: faqs.map((faq) => ({ "@type": "Question", name: faq.question, acceptedAnswer: { "@type": "Answer", text: faq.answer } })) };
function OptionalImage({ src, alt, priority = false, sizes = "(min-width: 1024px) 55vw, 100vw", className = "object-contain object-center" }: { src: string; alt: string; priority?: boolean; sizes?: string; className?: string }) { if (!existsSync(`${process.cwd()}/public${src}`)) return null; return <Image src={src} alt={alt} fill priority={priority} sizes={sizes} className={className}/>; }
const Cards = ({ items, columns = "lg:grid-cols-4" }: { items: string[][]; columns?: string }) => <div className={`mt-14 grid auto-rows-fr gap-5 sm:grid-cols-2 ${columns}`}>{items.map(([title,text])=><article key={title} className="h-full border border-[#173B2A]/12 bg-[#FBF8F1] p-7 sm:p-8"><span className="block h-px w-12 bg-[#C9A962]"/><h3 className="mt-5 font-[family-name:var(--font-playfair)] text-2xl font-semibold">{title}</h3><p className="mt-4 text-sm font-light leading-7 text-[#4C5F54]">{text}</p></article>)}</div>;

export default function VietnamExportPage(){return <main className="min-h-screen overflow-x-hidden bg-[#F5F0E6] text-[#173B2A]">
  <script type="application/ld+json" dangerouslySetInnerHTML={{__html:JSON.stringify(structuredData).replace(/</g,"\\u003c")}}/><script type="application/ld+json" dangerouslySetInnerHTML={{__html:JSON.stringify(faqStructuredData).replace(/</g,"\\u003c")}}/><Navbar/>
  <section className="relative isolate overflow-hidden bg-[#071B14]"><OptionalImage src={heroImage} alt="Indian henna, indigo, herbs and spices prepared for professional supply to Vietnam" priority sizes="100vw" className="object-cover object-[72%_center] sm:object-[70%_center] lg:object-[65%_center] xl:object-center"/><div className="absolute inset-0 bg-gradient-to-r from-[#061711]/30 via-[#102F23]/12 to-transparent"/><div className="absolute inset-0 bg-gradient-to-t from-black/[0.05] via-transparent to-transparent"/><GoldenParticles/><div className="relative z-10 flex items-center px-6 pb-20 pt-32 sm:px-8 sm:pb-24 sm:pt-36 lg:px-12 lg:pb-28 lg:pt-40"><div className="w-full max-w-[950px]"><StaggerItem delay={0}><p className="text-[10px] font-bold uppercase tracking-[0.38em] text-[#E4C878] sm:text-xs">India to Vietnam B2B Supply</p></StaggerItem><StaggerItem delay={100}><h1 className="mt-5 font-[family-name:var(--font-playfair)] text-4xl font-medium leading-[1.02] tracking-[-0.04em] text-[#F5F0E6] sm:text-5xl lg:text-6xl xl:text-[66px]">Natural Henna, Indigo, Herbs &amp; Spices <span className="block bg-gradient-to-r from-[#F5F0E6] via-[#E4C878] to-[#C9A962] bg-clip-text text-transparent">Exporter to Vietnam</span></h1></StaggerItem><StaggerItem delay={200}><p className="mt-5 max-w-[790px] text-[16px] font-light leading-8 text-white/82">Shivesh International coordinates natural henna powder, indigo powder, botanical hair colors, Ayurvedic herbs and Indian spices for Vietnam importers, distributors, private-label brands and wholesale buyers.</p></StaggerItem><StaggerItem delay={300}><div className="mt-7 flex flex-wrap gap-4"><Link href="/contact" className="border border-[#C9A962] bg-[#C9A962] px-7 py-4 text-[10px] font-bold uppercase tracking-[0.2em] text-[#102F23]">Send Vietnam Inquiry →</Link><a href="#products" className="border border-white/30 bg-[#102F23]/40 px-7 py-4 text-[10px] font-bold uppercase tracking-[0.2em] text-white">Explore Export Products ↓</a></div></StaggerItem><StaggerItem delay={400}><div className="mt-10 grid max-w-[760px] grid-cols-2 gap-3 lg:grid-cols-4">{[["200 kg","MOQ per item"],["Bulk","B2B supply"],["Private Label","Buyer-brand packs"],["Export","Coordination"]].map(([v,l])=><div key={l} className="border border-white/15 bg-black/20 p-4"><p className="font-[family-name:var(--font-playfair)] text-xl font-semibold text-[#E4C878]">{v}</p><p className="mt-2 text-[9px] uppercase tracking-[0.22em] text-white/55">{l}</p></div>)}</div></StaggerItem></div></div></section>
  <section className="px-6 py-24 sm:px-8 lg:px-12 lg:py-32"><RevealOnScroll><div className="mx-auto max-w-[1200px]"><p className="text-[10px] font-bold uppercase tracking-[0.4em] text-[#9F7F36]">Vietnam Market Supply</p><h2 className="mt-6 font-[family-name:var(--font-playfair)] text-[clamp(2.3rem,4.6vw,4.6rem)] font-semibold">Indian Botanical Supply <span className="block text-[#A97B22]">for Vietnam's Professional Buyers</span></h2><p className="mt-7 text-[16px] font-light leading-8 text-[#4C5F54]">Businesses can discuss botanical hair-color powders, cosmetic ingredients, herbal products, buyer-brand programmes, wholesale raw materials, Indian herbs and spice formats according to their commercial channel.</p><p className="mt-5 text-[15px] font-light leading-8 text-[#4C5F54]">Enquiries connected with Ho Chi Minh City, Hanoi, Da Nang, Hai Phong, Can Tho, Binh Duong, Dong Nai, Bac Ninh or another nominated destination can be reviewed. Geographic references describe market context only and do not imply local premises, stock, personnel, buyer networks, registrations or approvals.</p></div></RevealOnScroll></section>
  <section id="products" className="bg-[#EDE5D7] px-6 py-24 sm:px-8 lg:px-12 lg:py-32"><RevealOnScroll><div className="mx-auto max-w-[1500px]"><div className="text-center"><p className="text-[10px] uppercase tracking-[0.4em] text-[#9F7F36]">Six Export Product Categories</p><h2 className="mt-6 font-[family-name:var(--font-playfair)] text-[clamp(2.3rem,4.8vw,4.8rem)] font-semibold">Products for Professional <span className="block text-[#A97B22]">Vietnam Market Enquiries</span></h2></div><div className="mt-14 grid auto-rows-fr gap-5 sm:grid-cols-2 lg:grid-cols-3">{products.map(([title,text,href],i)=><article key={title} className="flex h-full min-h-[290px] flex-col border border-[#173B2A]/12 bg-[#FBF8F1] p-7"><span className="text-4xl text-[#C9A962]">{String(i+1).padStart(2,"0")}</span><h3 className="mt-5 font-[family-name:var(--font-playfair)] text-2xl font-semibold">{title}</h3><p className="mt-4 flex-1 text-sm leading-7 text-[#4C5F54]">{text}</p><Link href={href} className="mt-6 text-[10px] font-bold uppercase tracking-[0.2em] text-[#A97B22]">Explore {title} →</Link></article>)}</div></div></RevealOnScroll></section>
  <section className="px-6 py-24 sm:px-8 lg:px-12 lg:py-32"><RevealOnScroll><div className="mx-auto max-w-[1500px]"><div className="text-center"><p className="text-[10px] uppercase tracking-[0.4em] text-[#9F7F36]">Vietnam Buyer Profiles</p><h2 className="mt-6 font-[family-name:var(--font-playfair)] text-[clamp(2.3rem,4.7vw,4.7rem)] font-semibold">Professional Channels We Can Support</h2><p className="mx-auto mt-7 max-w-[900px] text-[15px] leading-8 text-[#4C5F54]">Each enquiry is reviewed against intended use, specification, order volume, packing requirements and the buyer's applicable destination obligations.</p></div><Cards items={buyers}/></div></RevealOnScroll></section>
  <section className="bg-[#EDE5D7] px-6 py-24 sm:px-8 lg:px-12 lg:py-32"><RevealOnScroll><div className="mx-auto max-w-[1500px]"><div className="grid gap-14 lg:grid-cols-[1.05fr_0.95fr] lg:gap-20"><div><p className="text-[10px] uppercase tracking-[0.4em] text-[#9F7F36]">Packaging &amp; Private Label</p><h2 className="mt-6 font-[family-name:var(--font-playfair)] text-[clamp(2.3rem,4.6vw,4.6rem)] font-semibold">Commercial Packs and <span className="block text-[#A97B22]">Vietnam Buyer-Brand Options</span></h2><p className="mt-7 text-[15px] leading-8 text-[#4C5F54]">Silver or gold metallized pouches, buyer-brand packs, artwork and label coordination, retail-ready formats and bulk packs for repacking or manufacturing may be evaluated.</p><p className="mt-5 text-[14px] leading-7 text-[#4C5F54]">Availability depends on the product, material, artwork, pack size, quantity and technical feasibility. The MOQ applies to each item, and not every configuration suits every product.</p></div><div><figure className="relative aspect-[3/2] overflow-hidden border border-[#C9A962]/35 bg-[#FBF8F1] shadow-[0_28px_70px_rgba(20,50,38,0.18)]"><OptionalImage src="/images/export/vietnam/vietnam-private-label-henna-indigo-buyers.png" alt="Vietnam private-label buyers reviewing packaging for Indian natural products" className="object-cover object-center"/></figure><div className="mt-5 grid gap-5 sm:grid-cols-2"><article className="border border-[#C9A962]/35 bg-[#FBF8F1] p-7"><h3 className="text-2xl font-semibold">Retail Packaging</h3><p className="mt-5 text-sm leading-7 text-[#4C5F54]">100 g · 200 g · 500 g · 1 kg formats</p></article><article className="border border-[#C9A962]/35 bg-[#FBF8F1] p-7"><h3 className="text-2xl font-semibold">Bulk Packaging</h3><p className="mt-5 text-sm leading-7 text-[#4C5F54]">20 kg and 25 kg, with double-layer vacuum packaging where applicable</p></article><article className="border border-[#C9A962] bg-[#173B2A] p-7 text-white sm:col-span-2"><p className="text-[10px] uppercase tracking-[0.3em] text-[#E4C878]">Minimum Order Quantity</p><p className="mt-4 text-4xl font-semibold">200 kg per item</p></article></div></div></div></div></RevealOnScroll></section>
  <section className="relative bg-[#09271D] px-6 py-24 text-white sm:px-8 lg:px-12 lg:py-32"><RevealOnScroll><div className="mx-auto max-w-[1500px]"><div className="grid items-center gap-14 lg:grid-cols-[0.9fr_1.1fr] lg:gap-20"><div><p className="text-[10px] uppercase tracking-[0.4em] text-[#E4C878]">Shipment and Document Support</p><h2 className="mt-6 font-[family-name:var(--font-playfair)] text-[clamp(2.3rem,4.7vw,4.7rem)] font-semibold">Structured Export Coordination for Vietnam</h2><p className="mt-7 text-[16px] leading-8 text-white/68">Coordination may cover product selection, specification alignment, quotation and terms, packaging confirmation, production, quality checks, export documentation, shipment planning, dispatch and record sharing with the buyer or nominated forwarder.</p><p className="mt-5 text-[15px] leading-8 text-white/62">Ho Chi Minh City, Cat Lai, Hai Phong or another feasible buyer-selected cargo destination may be considered. Freight rates, vessel schedules, transit times, import approval, registration, customs clearance, inspection, delivery and regulatory acceptance are not guaranteed.</p></div><figure className="relative aspect-[3/2] overflow-hidden border border-[#C9A962]/35 bg-[#071B14]"><OptionalImage src="/images/export/vietnam/india-to-vietnam-export-coordination.png" alt="India-to-Vietnam natural-product shipment and document coordination" className="object-cover object-center"/><div className="absolute inset-0 bg-gradient-to-t from-[#061711]/65 via-transparent to-transparent"/><figcaption className="absolute bottom-5 left-5 border border-white/15 bg-[#071B14]/80 px-4 py-3 text-[9px] uppercase tracking-[0.22em] text-[#E4C878]">India-to-Vietnam Export Coordination</figcaption></figure></div><aside className="mt-12 border border-[#C9A962]/35 bg-[#071B14]/60 p-7 text-sm leading-7 text-white/65">The Vietnam importer or buyer remains responsible for product classification, intended-use requirements, ingredient restrictions, import eligibility, registrations, filings, permits, labeling, language requirements, claims, testing, inspection, customs clearance and local regulatory compliance. Shivesh International may coordinate export-side documentation for the agreed transaction but does not guarantee Vietnamese import approval, clearance or regulatory acceptance. This information is not legal or regulatory advice.</aside></div></RevealOnScroll></section>
  <section className="px-6 py-24 sm:px-8 lg:px-12 lg:py-32"><RevealOnScroll><div className="mx-auto max-w-[1500px]"><div className="text-center"><p className="text-[10px] uppercase tracking-[0.4em] text-[#9F7F36]">Available Commercial and Shipment Records</p><h2 className="mt-6 font-[family-name:var(--font-playfair)] text-[clamp(2.1rem,4.7vw,4.7rem)] font-semibold">Vietnam Export Documentation Support</h2><p className="mx-auto mt-7 max-w-[950px] text-[15px] leading-8 text-[#4C5F54]">Document availability depends on the product, order, shipment terms and buyer instructions. Organic, phytosanitary, health, free-sale, laboratory, legalization, registration or inspection records are not automatically promised.</p></div><Cards items={documents} columns="lg:grid-cols-3"/></div></RevealOnScroll></section>
  <section className="bg-[#EDE5D7] px-6 py-24 sm:px-8 lg:px-12 lg:py-32"><RevealOnScroll><div className="mx-auto max-w-[1500px]"><div className="text-center"><p className="text-[10px] uppercase tracking-[0.4em] text-[#9F7F36]">Six-Step Commercial Process</p><h2 className="mt-6 font-[family-name:var(--font-playfair)] text-[clamp(2.3rem,4.7vw,4.7rem)] font-semibold">Vietnam Supply Workflow</h2></div><Cards items={steps} columns="lg:grid-cols-3"/></div></RevealOnScroll></section>
  <section className="px-6 py-24 sm:px-8 lg:px-12 lg:py-32"><RevealOnScroll><div className="mx-auto max-w-[1500px]"><div className="text-center"><p className="text-[10px] uppercase tracking-[0.4em] text-[#9F7F36]">Professional India-Origin Supply</p><h2 className="mt-6 font-[family-name:var(--font-playfair)] text-[clamp(2.3rem,4.7vw,4.7rem)] font-semibold">Why Vietnam Buyers Consider <span className="block text-[#A97B22]">Shivesh International</span></h2></div><Cards items={strengths}/></div></RevealOnScroll></section>
  <section className="px-6 py-24 sm:px-8 lg:px-12 lg:py-32"><RevealOnScroll><div className="mx-auto max-w-[1280px]"><p className="text-[10px] font-bold uppercase tracking-[0.4em] text-[#9F7F36]">Major Vietnamese Commercial Locations</p><h2 className="mt-6 font-[family-name:var(--font-playfair)] text-[clamp(2.5rem,4.6vw,4.6rem)] font-semibold">Buyer and Distribution Context <span className="block text-[#A97B22]">Across Vietnam</span></h2><p className="mt-7 max-w-[940px] text-[15px] leading-8 text-[#4C5F54]">These cities identify potential commercial and distribution contexts only. They do not represent Shivesh International premises, warehouses, current buyers, stock, inventory, guaranteed relationships, exclusive territories, branches or agents in Vietnam.</p><Cards items={locations}/></div></RevealOnScroll></section>
  <section className="bg-[#EDE5D7] px-6 py-24 sm:px-8 lg:px-12 lg:py-32"><RevealOnScroll><div className="mx-auto max-w-[1120px]"><div className="text-center"><p className="text-[10px] uppercase tracking-[0.4em] text-[#9F7F36]">Vietnam Buyer Questions</p><h2 className="mt-6 font-[family-name:var(--font-playfair)] text-[clamp(2.3rem,4.4vw,4.4rem)] font-semibold">Vietnam Export Supply FAQ</h2></div><div className="mt-12 divide-y divide-[#173B2A]/15 border-y border-[#173B2A]/15">{faqs.map(f=><article key={f.question} className="grid gap-4 py-7 md:grid-cols-[0.8fr_1.2fr]"><h3 className="text-xl font-semibold">{f.question}</h3><p className="text-sm leading-7 text-[#4C5F54]">{f.answer}</p></article>)}</div></div></RevealOnScroll></section>
  <section className="relative overflow-hidden bg-[#071B14] px-6 py-24 text-center text-white sm:px-8 lg:px-12 lg:py-28"><GoldenParticles/><RevealOnScroll><div className="relative mx-auto max-w-[1000px]"><p className="text-[10px] uppercase tracking-[0.4em] text-[#E4C878]">Vietnam Export Enquiry</p><h2 className="mt-6 font-[family-name:var(--font-playfair)] text-[clamp(2.3rem,4.8vw,4.8rem)] font-semibold">Plan Your India-to-Vietnam Product Supply</h2><p className="mx-auto mt-7 max-w-[820px] text-[16px] leading-8 text-white/65">Share the product, specification, intended use, packaging, quantity and destination. The team will assess the enquiry and respond with relevant commercial information.</p><Link href="/contact" className="mt-9 inline-flex border border-[#C9A962] bg-[#C9A962] px-8 py-4 text-[10px] font-bold uppercase tracking-[0.2em] text-[#102F23]">Request Vietnam Export Quotation →</Link></div></RevealOnScroll></section>
  <FooterSection/><FloatingContactButtons/><MagneticButtons/><PremiumCursor/>
</main>}
