import type { Metadata } from "next";
import Image from "next/image";
import Link from "next/link";

import FloatingContactButtons from "@/app/components/FloatingContactButtons";
import GoldenParticles from "@/app/components/GoldenParticles";
import MagneticButtons from "@/app/components/MagneticButtons";
import Navbar from "@/app/components/Navbar";
import PremiumCursor from "@/app/components/PremiumCursor";
import RevealOnScroll from "@/app/components/RevealOnScroll";
import StaggerItem from "@/app/components/StaggerItem";
import { franceLanguageAlternates } from "@/app/lib/i18n";
import FooterSection from "@/sections/FooterSection";

const pageUrl = "https://shiveshinternational.com/it/export/francia";
const heroImage = `${pageUrl.split("/it/export/francia")[0]}/images/export/france/france-botanical-beauty-atelier-hero-premium-v1.png`;

export const metadata: Metadata = {
  title: "Esportatore di prodotti naturali in Francia",
  description: "Henné, indigo, colorazioni vegetali, erbe ayurvediche e spezie per importatori, grossisti, acquirenti OEM e marchi privati in Francia. MOQ di 200 kg per articolo.",
  keywords: [
    "esportatore di prodotti naturali in Francia", "produttore di henné per la Francia", "fornitore di henné naturale", "henné all’ingrosso Francia", "esportatore di indigo naturale", "fornitore di indigo naturale", "fornitore di colorazioni vegetali", "fornitore di colorazioni botaniche per capelli", "fornitore per saloni professionali", "fornitore di cosmetici naturali", "importatori in Francia", "distributori in Francia", "grossisti in Francia", "retailer specializzati", "marchio privato", "Private Label", "OEM", "fornitura sfusa", "fornitore di erbe ayurvediche", "esportatore di erbe ayurvediche", "fornitore di spezie indiane", "esportatore di spezie indiane", "approvvigionamento B2B Francia", "produttore di prodotti naturali per la Francia", "fornitore indiano per marchi cosmetici francesi", "confezionamento di prodotti naturali Francia", "etichettatura Private Label Francia", "esportazione India Francia", "colorazione naturale all’henné Francia", "Shivesh International Francia",
  ],
  alternates: { canonical: pageUrl, languages: franceLanguageAlternates },
  openGraph: {
    title: "Fornitura di prodotti naturali per la Francia",
    description: "Fornitura sfusa, all’ingrosso, OEM e Private Label di henné, indigo, colorazioni botaniche per capelli, erbe ayurvediche e spezie indiane per acquirenti professionali in Francia.",
    url: pageUrl,
    type: "website",
    locale: "it_IT",
    siteName: "Shivesh International",
    images: [{ url: "/images/export/france/france-botanical-beauty-atelier-hero-premium-v1.png", width: 1536, height: 1024, alt: "Acquirenti francesi di cosmetici naturali e un esportatore indiano sviluppano prodotti botanici in un atelier di Parigi" }],
  },
  twitter: {
    card: "summary_large_image",
    title: "Fornitura di prodotti naturali per la Francia",
    description: "Fornitore indiano di henné, indigo, colorazioni vegetali, erbe e spezie per importatori e marchi privati in Francia.",
    images: ["/images/export/france/france-botanical-beauty-atelier-hero-premium-v1.png"],
  },
  robots: { index: true, follow: true, googleBot: { index: true, follow: true, "max-image-preview": "large", "max-snippet": -1, "max-video-preview": -1 } },
};

const products = [
  { number: "01", title: "Henné naturale in polvere", description: "Henné finemente lavorato per importatori francesi, marchi di cosmetica naturale e canali professionali, con qualità, specifiche e confezionamento concordati per ogni ordine.", href: "/products/natural-henna-powder" },
  { number: "02", title: "Indigo naturale in polvere", description: "Indigo botanico per programmi commerciali di colorazione dei capelli, disponibile in formati sfusi, professionali e con il marchio dell’acquirente previa verifica.", href: "/products/natural-indigo-powder" },
  { number: "03", title: "Colorazioni naturali per capelli all’henné", description: "Una gamma selezionata di colorazioni vegetali per distributori francesi, fornitori di saloni e marchi di cura naturale dei capelli che sviluppano linee professionali o retail.", href: "/products/natural-henna-hair-colors" },
  { number: "04", title: "Colorazioni per capelli a base di henné", description: "Prodotti coloranti a base di henné per gamme Private Label, soggetti a formula, uso previsto, confezionamento e fattibilità commerciale.", href: "/products/henna-based-hair-colors" },
  { number: "05", title: "Erbe ayurvediche indiane", description: "Erbe ayurvediche e polveri botaniche selezionate per programmi di approvvigionamento dedicati al benessere, alla cura personale e al commercio specializzato in Francia.", href: "/products/ayurvedic-indian-herbs" },
  { number: "06", title: "Spezie indiane", description: "Spezie indiane intere e macinate selezionate per importatori, grossisti, catene retail e aziende alimentari francesi pertinenti.", href: "/products/indian-spices" },
];

const buyerTypes = ["Importatori", "Distributori", "Grossisti", "Marchi di cosmetica naturale", "Marchi di cura botanica dei capelli", "Fornitori per saloni professionali", "Aziende ayurvediche", "Catene retail", "Aziende del benessere", "Acquirenti OEM", "Acquirenti all’ingrosso", "Acquirenti Private Label"];
const supplyServices = [
  { title: "Fornitura sfusa e all’ingrosso", text: "Le quantità commerciali per importatori, distributori e grossisti in Francia possono essere pianificate in formati sfusi, professionali o retail selezionati. Il MOQ è di 200 kg per articolo." },
  { title: "OEM e Private Label", text: "I marchi di cosmetica naturale, cura botanica dei capelli e benessere possono valutare programmi OEM o Private Label per prodotti selezionati, subordinatamente alla fattibilità del prodotto e della produzione." },
  { title: "Confezionamento personalizzato", text: "Possiamo coordinare buste, scatole, barattoli e presentazioni con il marchio dell’acquirente per ordini fattibili. Le grafiche fornite dall’acquirente sono soggette a verifica dei materiali, tecnica e di stampa." },
  { title: "Specifiche e documentazione", text: "Le specifiche disponibili e la documentazione commerciale pertinente vengono esaminate in base all’articolo selezionato, all’uso previsto e all’operazione confermata." },
];
const process = [
  { step: "01", title: "Verifica del prodotto e della quantità", text: "La richiesta per la Francia inizia dal prodotto, dal canale previsto, dalla qualità, dalla quantità e dall’ordine minimo di 200 kg per articolo." },
  { step: "02", title: "Specifiche e campioni", text: "Con l’acquirente vengono esaminate le specifiche disponibili, l’uso previsto, le opzioni di confezionamento e i campioni commercialmente fattibili." },
  { step: "03", title: "Offerta e condizioni commerciali", text: "L’offerta riporta l’ambito confermato, i prezzi, le condizioni di pagamento, il confezionamento e i termini commerciali di spedizione applicabili." },
  { step: "04", title: "Coordinamento del confezionamento e della grafica", text: "La presentazione retail, professionale, sfusa o Private Label viene esaminata insieme alla grafica dell’acquirente in base alla fattibilità tecnica, dei materiali e di stampa." },
  { step: "05", title: "Produzione e controllo qualità", text: "I prodotti confermati vengono lavorati, confezionati e controllati in conformità alle specifiche e ai requisiti concordati per l’ordine." },
  { step: "06", title: "Documentazione export e spedizione", text: "I documenti commerciali, le informazioni sull’imballaggio e la pianificazione della spedizione dall’India vengono coordinati in conformità alle condizioni commerciali confermate." },
];
const faqs = [
  { question: "Quali categorie di prodotti possono acquistare gli acquirenti francesi?", answer: "La gamma comprende henné naturale in polvere, indigo naturale in polvere, colorazioni naturali per capelli all’henné, colorazioni a base di henné, erbe ayurvediche indiane e spezie indiane selezionate. Disponibilità e idoneità vengono verificate per ogni richiesta." },
  { question: "Qual è il MOQ per gli ordini di esportazione in Francia?", answer: "L’ordine minimo è di 200 kg per articolo. Le quantità finali e le configurazioni di confezionamento dipendono dal prodotto, dal formato e dall’ambito commerciale confermati." },
  { question: "Quali tipi di acquirenti francesi possono inviare richieste?", answer: "Gestiamo richieste pertinenti di importatori, distributori, grossisti, marchi di cosmetica naturale e cura botanica dei capelli, fornitori di saloni, aziende ayurvediche e del benessere, catene retail, acquirenti OEM e marchi privati." },
  { question: "Offrite forniture sfuse e all’ingrosso per la Francia?", answer: "Sì. I prodotti idonei possono essere preparati per la fornitura sfusa e all’ingrosso in imballaggi industriali concordati, formati professionali o presentazioni retail selezionate." },
  { question: "I marchi francesi possono richiedere confezionamento OEM o Private Label?", answer: "Il supporto OEM e Private Label può essere valutato per prodotti selezionati. I formati di confezionamento, la presentazione del marchio dell’acquirente e le quantità vengono confermati solo dopo una verifica tecnica e commerciale." },
  { question: "È possibile utilizzare grafiche dell’acquirente e buste metallizzate?", answer: "Le grafiche dell’acquirente possono essere valutate per buste metallizzate dorate o argentate, formati kraft, scatole, barattoli e altri imballaggi fattibili. I requisiti relativi a materiale, fustella, stampa, lingua e quantità sono soggetti ad approvazione." },
  { question: "Sono disponibili specifiche, documenti e campioni?", answer: "Le specifiche disponibili e i documenti commerciali pertinenti vengono esaminati per il prodotto e l’operazione scelti. È possibile organizzare campioni quando commercialmente fattibile; disponibilità e idoneità non sono automatiche." },
  { question: "Chi conferma i requisiti di importazione francesi e dell’UE?", answer: "L’importatore o acquirente francese è responsabile della conferma della classificazione, dell’uso previsto, dei requisiti applicabili in Francia e nell’Unione europea, dell’importazione, dello sdoganamento, della registrazione o notifica ove richiesta, dell’etichettatura, della lingua, della dichiarazione degli ingredienti, delle indicazioni e degli obblighi di commercializzazione." },
];

const structuredData = { "@context": "https://schema.org", "@graph": [
  { "@type": "WebPage", "@id": `${pageUrl}#webpage`, url: pageUrl, name: "Fornitura di prodotti naturali per la Francia", description: "Informazioni in italiano per il mercato francese sulla fornitura sfusa, all’ingrosso, OEM e Private Label di henné, indigo, colorazioni vegetali, erbe ayurvediche e spezie indiane.", isPartOf: { "@id": "https://shiveshinternational.com/#website" }, about: { "@id": "https://shiveshinternational.com/#organization" }, breadcrumb: { "@id": `${pageUrl}#breadcrumb` }, primaryImageOfPage: { "@type": "ImageObject", url: heroImage, width: 1536, height: 1024 }, inLanguage: "it" },
  { "@type": "Service", "@id": `${pageUrl}#service`, name: "Fornitura di prodotti naturali dall’India alla Francia", serviceType: "Fornitura export sfusa, all’ingrosso, OEM e Private Label", description: "Fornitura commerciale dall’India per importatori, distributori, grossisti, fornitori di saloni e marchi che servono il mercato francese.", url: pageUrl, provider: { "@id": "https://shiveshinternational.com/#organization" }, areaServed: { "@type": "Country", name: "Francia", sameAs: "https://www.wikidata.org/wiki/Q142" }, audience: { "@type": "BusinessAudience", audienceType: buyerTypes.join(", ") }, category: products.map((product) => product.title), termsOfService: "L’ordine minimo è di 200 kg per articolo. Il prodotto, il confezionamento, la documentazione e le condizioni commerciali vengono confermati per ogni esigenza dell’acquirente." },
  { "@type": "BreadcrumbList", "@id": `${pageUrl}#breadcrumb`, itemListElement: [{ "@type": "ListItem", position: 1, name: "Home", item: "https://shiveshinternational.com/" }, { "@type": "ListItem", position: 2, name: "Export", item: "https://shiveshinternational.com/export" }, { "@type": "ListItem", position: 3, name: "Esportazione in Francia", item: pageUrl }] },
  { "@type": "ItemList", "@id": `${pageUrl}#products`, name: "Prodotti naturali per acquirenti in Francia", numberOfItems: products.length, itemListElement: products.map((product, index) => ({ "@type": "ListItem", position: index + 1, name: product.title, url: `https://shiveshinternational.com${product.href}` })) },
] };
const faqStructuredData = { "@context": "https://schema.org", "@type": "FAQPage", "@id": `${pageUrl}#faq`, mainEntity: faqs.map((faq) => ({ "@type": "Question", name: faq.question, acceptedAnswer: { "@type": "Answer", text: faq.answer } })) };

export default function FranceExportPageItalian() {
  return <main className="min-h-screen overflow-x-hidden bg-[#F5F0E6] text-[#173B2A]">
    <script type="application/ld+json" dangerouslySetInnerHTML={{ __html: JSON.stringify(structuredData).replace(/</g, "\\u003c") }} />
    <script type="application/ld+json" dangerouslySetInnerHTML={{ __html: JSON.stringify(faqStructuredData).replace(/</g, "\\u003c") }} />
    <Navbar />

    <section className="relative isolate overflow-hidden bg-[#071B14]">
      <Image src="/images/export/france/france-botanical-beauty-atelier-hero-premium-v1.png" alt="Acquirenti francesi di cosmetici naturali e un esportatore indiano sviluppano prodotti botanici in un atelier di Parigi" fill priority sizes="100vw" className="object-cover object-[90%_center]" />
      <div className="absolute inset-0 bg-gradient-to-r from-[#061711]/38 via-[#102F23]/18 to-transparent" /><div className="absolute inset-0 bg-gradient-to-t from-black/18 via-transparent to-black/[0.06]" /><GoldenParticles />
      <div className="relative z-10 flex items-center px-6 pb-20 pt-32 sm:px-8 sm:pb-24 sm:pt-36 lg:px-12 lg:pb-28 lg:pt-40"><div className="w-full max-w-[790px]">
        <StaggerItem delay={0}><div className="flex items-center gap-4"><span className="h-px w-14 bg-[#C9A962]" /><span className="text-[10px] font-bold uppercase tracking-[0.38em] text-[#E4C878] sm:text-xs">Dall’India alla Francia</span></div></StaggerItem>
        <StaggerItem delay={100}><h1 className="mt-6 font-[family-name:var(--font-playfair)] text-[clamp(2.65rem,5.2vw,5.4rem)] font-medium leading-[1.02] tracking-[-0.04em] text-[#F5F0E6]">Fornitura botanica dall’India<span className="mt-2 block bg-gradient-to-r from-[#F5F0E6] via-[#E4C878] to-[#C9A962] bg-clip-text text-transparent">per gli acquirenti in Francia</span></h1></StaggerItem>
        <StaggerItem delay={200}><p className="mt-7 max-w-[700px] text-[16px] font-light leading-8 text-[#F5F0E6]/80 sm:text-[18px]">Shivesh International collabora con acquirenti professionali in tutta la Francia —da Parigi e Lione a Marsiglia, Bordeaux e Lille— per l’approvvigionamento sfuso, all’ingrosso, OEM e Private Label di henné, indigo, colorazioni botaniche per capelli, erbe ayurvediche e spezie indiane selezionate.</p></StaggerItem>
        <StaggerItem delay={300}><div className="mt-9 flex flex-wrap gap-4"><a href="#gama-productos-francia" className="inline-flex items-center gap-4 border border-[#C9A962] bg-[#C9A962] px-7 py-4 text-[10px] font-bold uppercase tracking-[0.2em] text-[#102F23] transition-all duration-500 hover:-translate-y-1 hover:bg-[#E4C878]">Scopri la gamma <span>↓</span></a><Link href="/contact" className="inline-flex items-center border border-[#F5F0E6]/30 bg-[#102F23]/40 px-7 py-4 text-[10px] font-bold uppercase tracking-[0.2em] text-[#F5F0E6] backdrop-blur-lg transition-all duration-500 hover:border-[#C9A962] hover:text-[#E4C878]">Richiedi un preventivo per la Francia</Link></div></StaggerItem>
        <StaggerItem delay={400}><div className="mt-10 grid max-w-[740px] gap-3 sm:grid-cols-2 lg:grid-cols-4">{[["200 kg", "MOQ per articolo"], ["Sfuso", "Fornitura all’ingrosso"], ["OEM", "Private Label"], ["Francia", "Richieste B2B"]].map(([value, label]) => <div key={label} className="border border-white/15 bg-black/20 px-4 py-4 backdrop-blur-md"><p className="font-[family-name:var(--font-playfair)] text-xl font-semibold text-[#E4C878]">{value}</p><p className="mt-2 text-[9px] font-bold uppercase tracking-[0.22em] text-[#F5F0E6]/55">{label}</p></div>)}</div></StaggerItem>
      </div></div>
    </section>

    <section id="gama-productos-francia" className="relative overflow-hidden px-6 py-24 sm:px-8 lg:px-12 lg:py-32"><RevealOnScroll><div className="mx-auto max-w-[1500px]">
      <div className="mx-auto max-w-[920px] text-center"><p className="text-[10px] font-bold uppercase tracking-[0.4em] text-[#9F7F36]">Sei categorie commerciali</p><h2 className="mt-6 font-[family-name:var(--font-playfair)] text-[clamp(2.4rem,4.6vw,4.8rem)] font-semibold leading-[1.04] tracking-[-0.035em]">Prodotti naturali dall’India<span className="mt-1 block text-[#A97B22]">per il mercato francese</span></h2><p className="mx-auto mt-7 max-w-[820px] text-[16px] font-light leading-8 text-[#4C5F54] sm:text-[17px]">Un portafoglio di sei categorie per acquirenti professionali che sviluppano gamme di cosmetica naturale, cura botanica dei capelli, saloni, benessere, alimentazione e Private Label per la Francia.</p></div>
      <div className="mt-14 grid gap-5 sm:grid-cols-2 lg:grid-cols-3">{products.map((product, index) => <StaggerItem key={product.title} delay={(index % 3) * 90}><article className="group flex h-full min-h-[300px] flex-col border border-[#173B2A]/12 bg-[#FBF8F1] p-7 shadow-[0_18px_45px_rgba(20,50,38,0.07)] transition-all duration-500 hover:-translate-y-2 hover:border-[#C9A962]/70 sm:p-8"><span className="font-[family-name:var(--font-playfair)] text-4xl font-semibold text-[#C9A962]/60">{product.number}</span><h3 className="mt-6 font-[family-name:var(--font-playfair)] text-[27px] font-semibold leading-tight">{product.title}</h3><p className="mt-5 flex-1 text-[14px] font-light leading-7 text-[#4C5F54]">{product.description}</p><Link href={product.href} className="mt-7 inline-flex items-center gap-3 text-[10px] font-bold uppercase tracking-[0.2em] text-[#A97B22]">Vedi prodotto <span className="transition-transform group-hover:translate-x-2">→</span></Link></article></StaggerItem>)}</div>
    </div></RevealOnScroll></section>

    <section className="relative overflow-hidden bg-[#0B3325] px-6 py-24 text-[#F5F0E6] sm:px-8 lg:px-12 lg:py-32"><RevealOnScroll><div className="mx-auto grid max-w-[1500px] items-center gap-14 lg:grid-cols-[0.9fr_1.1fr] lg:gap-20"><div><p className="text-[10px] font-bold uppercase tracking-[0.4em] text-[#E4C878]">Pensato per gli acquisti professionali</p><h2 className="mt-6 font-[family-name:var(--font-playfair)] text-[clamp(2.35rem,4.4vw,4.6rem)] font-semibold leading-[1.04]">Fornitura strutturata per<span className="block text-[#E4C878]">i canali commerciali in Francia</span></h2><p className="mt-7 text-[16px] font-light leading-8 text-[#F5F0E6]/68">Supportiamo importatori, distributori, grossisti, fornitori di saloni, catene retail e marchi attraverso una verifica commerciale dell’uso previsto, delle specifiche, della quantità, del confezionamento e della fattibilità della fornitura.</p><div className="mt-8 flex flex-wrap gap-2">{buyerTypes.map((buyer) => <span key={buyer} className="border border-[#C9A962]/30 bg-white/[0.04] px-4 py-3 text-[9px] font-bold uppercase tracking-[0.18em] text-[#F5F0E6]/75">{buyer}</span>)}</div></div><div className="grid gap-5 sm:grid-cols-2">{supplyServices.map((service) => <article key={service.title} className="border border-[#C9A962]/25 bg-[#071B14]/55 p-7 sm:p-8"><span className="block h-px w-12 bg-[#C9A962]" /><h3 className="mt-6 font-[family-name:var(--font-playfair)] text-2xl font-semibold text-[#E4C878]">{service.title}</h3><p className="mt-4 text-[14px] font-light leading-7 text-[#F5F0E6]/65">{service.text}</p></article>)}</div></div></RevealOnScroll></section>

    <section className="px-6 py-24 sm:px-8 lg:px-12 lg:py-32"><RevealOnScroll><div className="mx-auto max-w-[1120px]"><div className="text-center"><p className="text-[10px] font-bold uppercase tracking-[0.4em] text-[#9F7F36]">Domande degli acquirenti francesi</p><h2 className="mt-6 font-[family-name:var(--font-playfair)] text-[clamp(2.3rem,4.2vw,4.4rem)] font-semibold">Domande frequenti sull’esportazione in Francia</h2></div><div className="mt-12 divide-y divide-[#173B2A]/15 border-y border-[#173B2A]/15">{faqs.map((faq) => <article key={faq.question} className="grid gap-4 py-7 md:grid-cols-[0.8fr_1.2fr] md:gap-10"><h3 className="font-[family-name:var(--font-playfair)] text-xl font-semibold">{faq.question}</h3><p className="text-[14px] font-light leading-7 text-[#4C5F54]">{faq.answer}</p></article>)}</div></div></RevealOnScroll></section>

    <section className="px-6 py-24 sm:px-8 lg:px-12 lg:py-32"><RevealOnScroll><div className="mx-auto grid max-w-[1500px] items-center gap-14 lg:grid-cols-2 lg:gap-20"><div className="relative aspect-[4/3] overflow-hidden border border-[#C9A962]/35 bg-[#102F23] shadow-[0_28px_70px_rgba(20,50,38,0.18)]"><Image src="/images/export/france/france-private-label-colour-pouch-gallery-premium-v1.png" alt="Acquirenti francesi e un esportatore indiano esaminano colori delle buste e finiture per confezioni Private Label" fill sizes="(min-width: 1024px) 50vw, 100vw" className="object-cover object-center" /><div className="absolute inset-0 bg-gradient-to-t from-[#071B14]/60 to-transparent" /></div><div><p className="text-[10px] font-bold uppercase tracking-[0.4em] text-[#9F7F36]">Sviluppo del marchio dell’acquirente</p><h2 className="mt-6 font-[family-name:var(--font-playfair)] text-[clamp(2.35rem,4.35vw,4.6rem)] font-semibold leading-[1.04]">Programmi di confezionamento per<span className="block text-[#A97B22]">i canali retail e professionali in Francia</span></h2><p className="mt-7 text-[16px] font-light leading-8 text-[#4C5F54]">Gli acquirenti francesi possono valutare confezioni retail, formati professionali, fornitura sfusa, buste metallizzate dorate o argentate ove opportuno, formati kraft o altre opzioni commercialmente fattibili, scatole, barattoli e una presentazione coordinata con il proprio marchio.</p><p className="mt-5 text-[14px] leading-7 text-[#4C5F54]">Le grafiche fornite dall’acquirente sono soggette a fattibilità tecnica, dei materiali e di stampa. L’importatore è responsabile dell’etichettatura, della lingua, della dichiarazione degli ingredienti, delle indicazioni e dei requisiti di commercializzazione applicabili in Francia e nell’UE.</p><Link href="/contact" className="mt-8 inline-flex items-center gap-4 border border-[#C9A962] bg-[#C9A962] px-7 py-4 text-[10px] font-bold uppercase tracking-[0.2em] text-[#102F23] transition-all hover:-translate-y-1 hover:bg-[#D8BB68]">Richiedi informazioni sulla Private Label <span>→</span></Link></div></div></RevealOnScroll></section>

    <section className="relative overflow-hidden bg-[#09271D] px-6 py-24 text-[#F5F0E6] sm:px-8 lg:px-12 lg:py-32"><div aria-hidden="true" className="pointer-events-none absolute -left-40 top-12 h-[460px] w-[460px] rounded-full bg-[#C9A962]/10 blur-[150px]" /><div aria-hidden="true" className="pointer-events-none absolute -right-48 bottom-10 h-[520px] w-[520px] rounded-full bg-[#C9A962]/[0.07] blur-[170px]" /><RevealOnScroll><div className="relative mx-auto max-w-[1500px]"><div className="grid items-center gap-12 lg:grid-cols-[0.9fr_1.1fr] lg:gap-16 xl:gap-20"><div><div className="flex items-center gap-4"><span className="h-px w-12 bg-[#C9A962]" /><p className="text-[10px] font-bold uppercase tracking-[0.4em] text-[#E4C878]">Dall’India alla Francia</p></div><h2 className="mt-6 font-[family-name:var(--font-playfair)] text-[clamp(2.3rem,4.4vw,4.8rem)] font-semibold leading-[1.04]">Coordinamento strutturato dell’esportazione per gli acquirenti in Francia</h2><p className="mt-7 max-w-[720px] text-[16px] font-light leading-8 text-[#F5F0E6]/68 sm:text-[17px]">Ogni richiesta viene coordinata in base al prodotto, alla quantità, alle specifiche, al confezionamento, alla documentazione disponibile e alla pianificazione della spedizione dall’India, in conformità alle condizioni commerciali confermate.</p></div><figure className="relative aspect-[4/3] overflow-hidden border border-[#C9A962]/35 bg-[#071B14] shadow-[0_28px_75px_rgba(0,0,0,0.28)]"><Image src="/images/export/france/france-maritime-route-coordination-atelier-premium-v1.png" alt="Coordinamento della rotta marittima, della documentazione e della spedizione dall’India alla Francia a Marsiglia" fill sizes="(min-width: 1024px) 55vw, 100vw" className="object-cover object-center" /><div className="pointer-events-none absolute inset-0 bg-gradient-to-t from-[#061711]/70 via-transparent to-transparent" /><figcaption className="absolute bottom-5 left-5 border border-white/15 bg-[#071B14]/80 px-4 py-3 text-[9px] font-bold uppercase tracking-[0.24em] text-[#E4C878] backdrop-blur-md sm:bottom-6 sm:left-6">Coordinamento export India–Francia</figcaption></figure></div>
      <div className="mt-16 grid auto-rows-fr gap-6 md:grid-cols-2 md:gap-8 lg:gap-10">{process.map((item) => <article key={item.step} className="group relative h-full border border-[#C9A962]/22 bg-[#071B14]/65 p-7 shadow-[0_22px_55px_rgba(0,0,0,0.16)] backdrop-blur-sm transition-all duration-500 hover:border-[#C9A962]/55 sm:p-8"><div className="flex items-start gap-5"><span className="flex h-14 w-14 shrink-0 items-center justify-center rounded-full border border-[#C9A962]/45 bg-[#C9A962]/10 font-[family-name:var(--font-playfair)] text-xl font-semibold text-[#E4C878]">{item.step}</span><div><h3 className="font-[family-name:var(--font-playfair)] text-[23px] font-semibold leading-tight text-[#F5F0E6] sm:text-[26px]">{item.title}</h3><p className="mt-4 text-[14px] font-light leading-7 text-[#F5F0E6]/62">{item.text}</p></div></div><span className="mt-7 block h-px w-full origin-left scale-x-0 bg-gradient-to-r from-[#C9A962] to-transparent transition-transform duration-500 group-hover:scale-x-100" /></article>)}</div>
      <aside className="mx-auto mt-20 max-w-[1120px] border border-[#C9A962]/45 bg-[#F5F0E6] p-7 text-[#173B2A] shadow-[0_24px_70px_rgba(0,0,0,0.2)] sm:p-9 lg:p-10"><div className="flex flex-col gap-6 sm:flex-row sm:items-start"><span className="inline-flex h-12 w-12 shrink-0 items-center justify-center rounded-full bg-[#173B2A] text-lg text-[#E4C878]">i</span><div><h3 className="font-[family-name:var(--font-playfair)] text-2xl font-semibold text-[#A97B22]">Responsabilità dell’importatore in Francia e nell’UE</h3><p className="mt-4 text-[14px] font-light leading-7 text-[#4C5F54] sm:text-[15px]">Shivesh International coordina la documentazione commerciale e di esportazione dell’ordine confermato. L’importatore o acquirente francese è responsabile della classificazione del prodotto, dei requisiti di importazione, dello sdoganamento, dell’etichettatura, delle indicazioni, della registrazione e dei requisiti applicabili in Francia e nell’UE.</p></div></div></aside>
      <div className="mt-10 text-center"><Link href="/contact" className="inline-flex items-center gap-4 border border-[#C9A962] bg-[#C9A962] px-8 py-4 text-[10px] font-bold uppercase tracking-[0.22em] text-[#102F23] transition-all duration-500 hover:-translate-y-1 hover:bg-[#E4C878]">Richiedi un preventivo export per la Francia <span>→</span></Link><p className="mx-auto mt-5 max-w-[720px] text-[9px] font-semibold uppercase tracking-[0.24em] text-[#F5F0E6]/38">Prodotto · Quantità · Specifiche · Confezionamento · Documentazione</p></div>
    </div></RevealOnScroll></section>

    <section className="relative overflow-hidden bg-[#071B14] px-6 py-24 text-center text-[#F5F0E6] sm:px-8 lg:px-12"><GoldenParticles /><RevealOnScroll><div className="relative mx-auto max-w-[1000px]"><p className="text-[10px] font-bold uppercase tracking-[0.4em] text-[#E4C878]">Avviate un progetto di fornitura per la Francia</p><h2 className="mt-6 font-[family-name:var(--font-playfair)] text-[clamp(2.3rem,4.4vw,4.8rem)] font-semibold leading-[1.04]">Pianificate la fornitura di prodotti naturali per la Francia</h2><p className="mx-auto mt-7 max-w-[760px] text-[16px] font-light leading-8 text-[#F5F0E6]/65">Indicate il prodotto, la quantità, il formato della confezione, le esigenze di branding, la destinazione e le informazioni richieste. Il nostro team esaminerà la richiesta e risponderà con i successivi passaggi commercialmente fattibili.</p><Link href="/contact" className="mt-9 inline-flex items-center gap-4 border border-[#C9A962] bg-[#C9A962] px-8 py-4 text-[10px] font-bold uppercase tracking-[0.22em] text-[#102F23] transition-all hover:-translate-y-1 hover:bg-[#E4C878]">Richiedi un preventivo export per la Francia <span>→</span></Link></div></RevealOnScroll></section>
    <FooterSection locale="it" /><FloatingContactButtons /><MagneticButtons /><PremiumCursor />
  </main>;
}
