import { existsSync } from "node:fs";
import type { Metadata } from "next";
import Image from "next/image";
import Link from "next/link";
import Navbar from "@/app/components/Navbar";
import FloatingContactButtons from "@/app/components/FloatingContactButtons";
import GoldenParticles from "@/app/components/GoldenParticles";
import MagneticButtons from "@/app/components/MagneticButtons";
import PremiumCursor from "@/app/components/PremiumCursor";
import { spainLanguageAlternates } from "@/app/lib/i18n";
import FooterSection from "@/sections/FooterSection";

const url="https://shiveshinternational.com/es/export/espana";
const hero="/images/export/spain/spain-export-hero.png";
export const metadata:Metadata={title:"Exportador de productos naturales a España | Henna e índigo",description:"Henna, índigo, coloración vegetal, plantas ayurvédicas y especias de la India para compradores B2B en España. Granel, OEM y marca propia desde 200 kg.",keywords:["exportador de productos naturales a España","fabricante de henna para España","exportador de henna natural","proveedor de henna natural","henna al por mayor España","proveedor de índigo natural","exportador de índigo natural","proveedor de coloración vegetal","coloración capilar botánica","proveedor de coloración natural","proveedor para salones de peluquería","proveedor profesional de peluquería","proveedor de cosmética natural","marcas de cosmética natural","marcas capilares","importadores","distribuidores","mayoristas","minoristas","proveedores","fabricante","exportador","Private Label","marca propia","OEM","fabricación por contrato","envasado a granel","suministro a granel","proveedor de plantas ayurvédicas","exportador de plantas ayurvédicas","proveedor de especias indias","exportador de especias indias","aprovisionamiento B2B España","henna natural a granel","índigo natural a granel","coloración natural para marcas","productos botánicos para salones","proveedor Madrid","proveedor Barcelona","aprovisionamiento Valencia","compradores Sevilla","distribuidores Málaga","mayoristas Bilbao","cosmética natural marca propia","etiquetado en español","envasado para marcas","productos naturales de la India","ingredientes botánicos","plantas ayurvédicas al por mayor","especias indias al por mayor","exportación India España","proveedor B2B de henna","fabricante Private Label India","proveedor OEM","coloraciones con henna","plantas ayurvédicas de la India","especias de la India","comercio minorista","comercio electrónico","documentación de exportación","COA productos botánicos","INCI ingredientes botánicos","embalaje multilingüe","marca de distribuidor","importación de henna","importación de índigo","marcas capilares España","bienestar natural","exportación marítima","exportación aérea","proveedor Valencia","proveedor Sevilla","proveedor Málaga","proveedor Bilbao"],alternates:{canonical:url,languages:spainLanguageAlternates},openGraph:{title:"Productos naturales de la India para compradores en España",description:"Suministro B2B de henna, índigo, coloración vegetal, plantas ayurvédicas y especias.",url,type:"website",locale:"es_ES",siteName:"Shivesh International",images:[{url:hero,width:1944,height:809,alt:"Compradores españoles evaluando productos naturales de la India"}]},robots:{index:true,follow:true}};
const products=[["Henna natural","Henna para importadores, marcas, minoristas y peluquería profesional.","/products/natural-henna-powder"],["Índigo natural","Índigo botánico para coloración capilar y formatos a granel.","/products/natural-indigo-powder"],["Coloraciones capilares naturales con henna","Colección vegetal para distribuidores, marcas y salones.","/products/natural-henna-hair-colors"],["Coloraciones capilares a base de henna","Productos de marca privada sujetos a viabilidad.","/products/henna-based-hair-colors"],["Plantas ayurvédicas de la India","Plantas y polvos para bienestar y cuidado personal.","/products/ayurvedic-indian-herbs"],["Especias de la India","Especias enteras y molidas para compradores alimentarios.","/products/indian-spices"]] as const;
const buyers=[["Importadores y distribuidores","Especificaciones, cantidades y documentos para redes españolas."],["Mayoristas y minoristas","Surtidos para comercio especializado y electrónico."],["Marcas de cosmética natural","Ingredientes botánicos para conceptos cosméticos."],["Marcas capilares","Gamas botánicas para canales profesionales."],["Proveedores de salones","Formatos para peluquerías y distribuidores."],["Empresas de plantas y bienestar","Ingredientes ayurvédicos para programas especializados."],["Compradores de marca propia y OEM","Envases, artes finales y marca del comprador."],["Importadores de alimentos y especias","Especias para empresas y distribuidores."]] as const;
const applications=[["Coloración capilar botánica","Henna e índigo para gamas vegetales."],["Cuidado capilar profesional","Polvos para salones y marcas."],["Cosmética natural","Ingredientes sujetos a evaluación."],["Bienestar ayurvédico","Plantas para comercios especializados."],["Ingredientes alimentarios","Especias para importadores."],["Comercio minorista","Formatos para tiendas."],["Marca propia","Presentaciones para el comprador."],["Suministro a granel","Formatos para mayoristas."],["Fabricación por contrato","Programas OEM acordados."],["Aprovisionamiento multicategoría","Seis familias con un equipo."]] as const;
const trust=[["Experiencia exportadora","Coordinación comercial desde la India."],["Seis familias","Cartera para compradores profesionales."],["MOQ claro","200 kg por producto."],["Marca propia","Envasado sujeto a viabilidad."],["Documentación","Información según producto y pedido."],["Responsabilidad","Sin promesas de aprobación automática."]] as const;
const faqs=[{question:"¿Qué productos exportan a España?",answer:"Henna, índigo, coloraciones con henna, plantas ayurvédicas y especias indias."},{question:"¿Cuál es el pedido mínimo?",answer:"El MOQ estándar es de 200 kg por producto, sujeto a confirmación comercial."},{question:"¿Ofrecen marca propia y OEM?",answer:"Sí, según producto, cantidad, impresión y viabilidad técnica."},{question:"¿Qué envases están disponibles?",answer:"Pueden estudiarse 100 g, 200 g, 500 g, 1 kg y granel de 20 kg o 25 kg."},{question:"¿Preparan etiquetas en español?",answer:"Podemos coordinarlas; el comprador valida requisitos legales y declaraciones."},{question:"¿Qué documentos están disponibles?",answer:"Según producto: factura, lista de embalaje, origen, especificaciones y COA."},{question:"¿Coordinan transporte a España?",answer:"Sí, con el transitario elegido, sin garantizar rutas, plazos ni despacho."},{question:"¿Tienen oficina en España?",answer:"No. Las ciudades citadas son mercados potenciales, no presencia local."}];
const schema={"@context":"https://schema.org","@graph":[{"@type":"WebPage","@id":`${url}#webpage`,url,name:"Exportador de productos naturales a España",description:metadata.description,inLanguage:"es",about:{"@id":"https://shiveshinternational.com/#organization"}},{"@type":"BreadcrumbList",itemListElement:[{"@type":"ListItem",position:1,name:"Inicio",item:"https://shiveshinternational.com/"},{"@type":"ListItem",position:2,name:"Exportación",item:"https://shiveshinternational.com/export"},{"@type":"ListItem",position:3,name:"España",item:url}]}]};
const faqSchema={"@context":"https://schema.org","@type":"FAQPage",mainEntity:faqs.map(f=>({"@type":"Question",name:f.question,acceptedAnswer:{"@type":"Answer",text:f.answer}}))};
function Pic({src,alt,priority=false}:{src:string;alt:string;priority?:boolean}){if(!existsSync(`${process.cwd()}/public${src}`))return null;return <Image src={src} alt={alt} fill priority={priority} sizes="100vw" className="object-cover object-center"/>}
function Grid({items,cols="lg:grid-cols-4"}:{items:readonly(readonly[string,string])[];cols?:string}){return <div className={`mt-14 grid gap-5 sm:grid-cols-2 ${cols}`}>{items.map(([t,d])=><article key={t} className="h-full bg-[#FBF8F1] p-7 text-[#173B2A]"><span className="block h-px w-12 bg-[#C9A962]"/><h3 className="mt-5 text-2xl font-semibold">{t}</h3><p className="mt-4 leading-7 text-[#4C5F54]">{d}</p></article>)}</div>}
const H=({children}:{children:React.ReactNode})=><h2 className="mt-6 text-[clamp(2.2rem,4.7vw,4.7rem)] font-semibold leading-[1.05]">{children}</h2>;
export default function Page(){return <main className="min-h-screen overflow-x-hidden bg-[#F5F0E6] text-[#173B2A]"><script type="application/ld+json" dangerouslySetInnerHTML={{__html:JSON.stringify(schema)}}/><script type="application/ld+json" dangerouslySetInnerHTML={{__html:JSON.stringify(faqSchema)}}/><Navbar/>
<section className="relative isolate overflow-hidden bg-[#071b14]"><Pic src={hero} alt="Compradores españoles revisando productos naturales de la India" priority/><div className="absolute inset-0 bg-gradient-to-r from-[#061711]/75 via-[#102F23]/45 to-transparent"/><GoldenParticles/><div className="relative z-10 px-6 pb-20 pt-32 lg:px-12 lg:pb-28 lg:pt-40"><div className="max-w-[900px]"><p className="text-[10px] font-bold uppercase tracking-[.38em] text-[#E4C878]">Exportación de la India a España</p><h1 className="mt-5 text-[clamp(2.25rem,6vw,4.125rem)] font-medium leading-none text-white">Exportador de productos naturales a España<span className="mt-2 block text-[#E4C878]">Henna, índigo, plantas y especias</span></h1><p className="mt-5 max-w-[730px] leading-8 text-white/80">Suministro para importadores, distribuidores, mayoristas, marcas, salones y compradores de marca propia en España.</p><div className="mt-7 flex flex-wrap gap-4"><Link href="/contact" className="bg-[#C9A962] px-7 py-4 text-[10px] font-bold uppercase text-[#102F23]">Enviar consulta →</Link><a href="#productos" className="border border-white/30 px-7 py-4 text-[10px] font-bold uppercase text-white">Ver productos ↓</a></div><div className="mt-10 grid max-w-[740px] grid-cols-2 gap-3 lg:grid-cols-4">{[["200 kg","MOQ por producto"],["Granel","Mayorista"],["OEM","Marca propia"],["España","Compradores B2B"]].map(([v,l])=><div key={l} className="border border-white/15 bg-black/20 p-4"><p className="text-xl text-[#E4C878]">{v}</p><p className="mt-2 text-[9px] uppercase text-white/60">{l}</p></div>)}</div></div></div></section>
<section className="px-6 py-24 lg:py-32"><div className="mx-auto max-w-[1120px]"><p className="text-[10px] uppercase tracking-[.4em] text-[#9F7F36]">Aprovisionamiento India–España</p><H>Su socio exportador <span className="block text-[#A97B22]">para el mercado español</span></H><p className="mt-7 leading-8 text-[#4C5F54]">Los compradores coordinan varias categorías con un equipo exportador. Revisamos disponibilidad, especificaciones, envases, documentos y preparación del envío. Madrid, Barcelona, Valencia, Sevilla, Málaga y Bilbao son referencias comerciales, no oficinas ni almacenes.</p></div></section>
<section id="productos" className="bg-[#EDE5D7] px-6 py-24 lg:py-32"><div className="mx-auto max-w-[1500px] text-center"><H>Productos naturales <span className="block text-[#A97B22]">para importadores y marcas</span></H><div className="mt-14 grid gap-5 sm:grid-cols-2 lg:grid-cols-3">{products.map(([t,d,h],i)=><article key={t} className="flex min-h-[290px] flex-col bg-white p-7 text-left"><span className="text-4xl text-[#C9A962]">0{i+1}</span><h3 className="mt-5 text-2xl font-semibold">{t}</h3><p className="mt-4 flex-1 leading-7 text-[#4C5F54]">{d}</p><Link href={h} className="mt-6 text-[10px] font-bold uppercase text-[#A97B22]">Explorar →</Link></article>)}</div></div></section>
<section className="bg-[#0B3325] px-6 py-24 text-white"><div className="mx-auto max-w-[1500px]"><H>Soluciones para compradores B2B españoles</H><Grid items={buyers}/></div></section><section className="px-6 py-24"><div className="mx-auto max-w-[1500px]"><H>Aplicaciones para el mercado español</H><Grid items={applications} cols="lg:grid-cols-2"/></div></section>
<section className="bg-[#EDE5D7] px-6 py-24"><div className="mx-auto grid max-w-[1500px] gap-14 lg:grid-cols-2"><div><H>Envasado y Private Label <span className="block text-[#A97B22]">para compradores españoles</span></H><p className="mt-7 leading-8 text-[#4C5F54]">Bolsas y cajas impresas, artes finales, códigos de barras, etiquetas y envases multilingües están sujetos a viabilidad. El comprador valida etiquetado, declaraciones, clasificación y requisitos de España y la UE.</p></div><div><figure className="relative aspect-[3/2]"><Pic src="/images/export/spain/spain-buyer-partnership.png" alt="Envasado de marca propia para compradores españoles"/></figure><div className="mt-5 bg-[#173B2A] p-7 text-white"><p className="text-[#E4C878]">Cantidad mínima de pedido</p><p className="mt-3 text-4xl">200 kg por producto</p></div></div></div></section>
<section className="bg-[#09271D] px-6 py-24 text-white"><div className="mx-auto grid max-w-[1500px] gap-14 lg:grid-cols-2"><div><H>Coordinación de exportación India–España</H><p className="mt-7 leading-8 text-white/70">Factura comercial, lista de embalaje, origen, especificaciones, COA y documentación disponible. Puede estudiarse transporte marítimo o aéreo, sin garantizar rutas, plazos, despacho ni aprobación.</p><p className="mt-5 leading-8 text-white/65">El comprador es responsable de clasificación, etiquetado, registro, aduanas y requisitos del mercado.</p></div><figure className="relative aspect-[3/2]"><Pic src="/images/export/spain/india-to-spain-export-coordination.png" alt="Coordinación documental y logística hacia España"/></figure></div></section>
<section className="bg-[#EDE5D7] px-6 py-24"><div className="mx-auto max-w-[1500px]"><H>Fortalezas del suministro comercial</H><Grid items={trust} cols="lg:grid-cols-3"/></div></section><section className="px-6 py-24"><div className="mx-auto max-w-[1120px]"><H>Mercados comerciales en España</H><p className="mt-7 leading-8 text-[#4C5F54]">Consultas profesionales de Madrid, Barcelona, Valencia, Sevilla, Málaga y Bilbao. Las referencias no representan presencia local.</p><div className="mt-8 flex flex-wrap gap-3">{["Madrid","Barcelona","Valencia","Sevilla","Málaga","Bilbao"].map(c=><span key={c} className="border border-[#C9A962] px-5 py-3">{c}</span>)}</div></div></section>
<section className="bg-[#EDE5D7] px-6 py-24"><div className="mx-auto max-w-[1120px]"><H>Preguntas frecuentes sobre España</H><div className="mt-12 divide-y">{faqs.map(f=><article key={f.question} className="grid gap-4 py-7 md:grid-cols-2"><h3 className="text-xl font-semibold">{f.question}</h3><p className="leading-7 text-[#4C5F54]">{f.answer}</p></article>)}</div></div></section>
<section className="relative bg-[#071B14] px-6 py-24 text-center text-white"><GoldenParticles/><div className="relative mx-auto max-w-[950px]"><H>¿Busca un proveedor fiable de productos naturales?</H><p className="mx-auto mt-7 max-w-[720px] text-white/70">Comparta producto, cantidad, envase, destino y requisitos de marca propia con nuestro equipo exportador.</p><Link href="/contact" className="mt-9 inline-flex bg-[#C9A962] px-8 py-4 text-[10px] font-bold uppercase text-[#102F23]">Enviar requisitos →</Link></div></section><FooterSection locale="es"/><FloatingContactButtons/><MagneticButtons/><PremiumCursor/></main>}
