import type { Metadata } from "next";
import Image from "next/image";
import Link from "next/link";

import FloatingContactButtons from "@/app/components/FloatingContactButtons";
import GoldenParticles from "@/app/components/GoldenParticles";
import MagneticButtons from "@/app/components/MagneticButtons";
import Navbar from "@/app/components/Navbar";
import PremiumCursor from "@/app/components/PremiumCursor";
import RevealOnScroll from "@/app/components/RevealOnScroll";
import StaggerItem from "@/app/components/StaggerItem";
import { belgiumLanguageAlternates } from "@/app/lib/i18n";
import FooterSection from "@/sections/FooterSection";

const pageUrl = "https://shiveshinternational.com/fr/export/belgique";
const heroImage = "https://shiveshinternational.com/images/export/belgium/belgium-export-hero-natural-henna-hair-colors.png";

export const metadata: Metadata = {
  title: "Exportateur de produits naturels vers la Belgique | Private Label",
  description: "Henné, indigo, colorations végétales, plantes ayurvédiques et épices d’Inde pour acheteurs belges. Vrac, gros, OEM et Private Label dès 200 kg par article.",
  keywords: [
    "exportateur de produits naturels vers la Belgique", "fournisseur de produits naturels Belgique", "fabricant de produits naturels Inde Belgique", "produits botaniques indiens Belgique", "fournisseur botanique Belgique", "produits naturels en vrac Belgique", "grossiste produits naturels Belgique", "distributeur produits naturels Belgique", "approvisionnement produits naturels Belgique",
    "fabricant de henné pour la Belgique", "exportateur de henné naturel", "fournisseur de henné naturel", "grossiste henné Belgique", "importateur henné Belgique", "henné naturel en vrac Belgique", "henné marque propre Belgique", "fournisseur henné salons Belgique", "henné pour marques cosmétiques", "henné indien B2B Belgique",
    "fournisseur indigo naturel Belgique", "exportateur indigo naturel", "grossiste indigo Belgique", "indigo naturel en vrac Belgique", "indigo marque propre Belgique", "indigo pour marques cosmétiques Belgique", "importateur poudre indigo Belgique",
    "fournisseur coloration végétale", "colorations capillaires botaniques", "coloration naturelle pour salons", "fournisseur professionnel coiffure", "fournisseur salons de coiffure", "coloration au henné Belgique", "coloration végétale en gros Belgique", "marque propre coloration capillaire", "fabricant coloration naturelle Inde Belgique", "fournisseur marques capillaires Belgique",
    "fournisseur de plantes ayurvédiques", "exportateur de plantes ayurvédiques", "grossiste plantes ayurvédiques Belgique", "poudres végétales en vrac Belgique", "fournisseur poudres d’herbes Belgique", "plantes ayurvédiques marque propre", "fournisseur entreprises bien-être Belgique",
    "fournisseur d’épices indiennes", "exportateur d’épices indiennes", "grossiste épices indiennes Belgique", "épices indiennes en vrac Belgique", "importateur épices Belgique", "épices marque propre Belgique", "épices pour professionnels alimentaires belges",
    "Private Label Belgique", "marque propre produits naturels", "fabrication à façon produits naturels", "OEM produits naturels Belgique", "conditionnement en vrac Belgique", "emballage marque acheteur Belgique", "conditionnement produits naturels Belgique",
    "importateurs Belgique produits naturels", "distributeurs Belgique produits naturels", "grossistes Belgique produits naturels", "détaillants Belgique produits naturels", "marques cosmétiques Belgique", "marques capillaires Belgique", "acheteurs produits naturels Belgique", "entreprises herboristerie Belgique", "sociétés de sourcing Belgique",
    "approvisionnement B2B Belgique", "export Inde Belgique", "commerce botanique Inde Belgique", "coordination export Inde Belgique", "fournisseur indien Bruxelles", "fournisseur indien Anvers", "produits botaniques Gand", "produits naturels Liège", "produits naturels Charleroi", "produits naturels Namur",
  ],
  alternates: { canonical: pageUrl, languages: belgiumLanguageAlternates },
  openGraph: { title: "Approvisionnement en produits naturels de l’Inde vers la Belgique", description: "Henné, indigo, colorations végétales, plantes ayurvédiques et épices en vrac, en gros, en OEM et en Private Label pour acheteurs professionnels belges.", url: pageUrl, type: "website", locale: "fr_BE", siteName: "Shivesh International", images: [{ url: "/images/export/belgium/belgium-export-hero-natural-henna-hair-colors.png", width: 1944, height: 809, alt: "Professionnelles belges de la coiffure étudiant des colorations naturelles au henné fournies depuis l’Inde" }] },
  twitter: { card: "summary_large_image", title: "Produits naturels de l’Inde vers la Belgique", description: "Approvisionnement en henné, indigo, colorations végétales, plantes et épices pour acheteurs professionnels belges.", images: ["/images/export/belgium/belgium-export-hero-natural-henna-hair-colors.png"] },
  robots: { index: true, follow: true },
};

const products = [
  { title: "Henné naturel", text: "Poudre de henné finement travaillée pour importateurs belges, marques de cosmétique naturelle, détaillants et circuits professionnels de coiffure.", href: "/products/natural-henna-powder" },
  { title: "Indigo naturel", text: "Poudre d’indigo botanique pour les gammes de coloration capillaire, proposée en formats vrac, professionnels ou à la marque de l’acheteur après étude.", href: "/products/natural-indigo-powder" },
  { title: "Colorations capillaires naturelles au henné", text: "Une gamme végétale destinée aux distributeurs, marques capillaires et fournisseurs de salons actifs sur le marché belge multilingue.", href: "/products/natural-henna-hair-colors" },
  { title: "Colorations capillaires à base de henné", text: "Des produits pour marques propres étudiés selon la formulation, l’usage prévu, le conditionnement et la faisabilité commerciale.", href: "/products/henna-based-hair-colors" },
  { title: "Plantes ayurvédiques indiennes", text: "Une sélection de plantes et poudres végétales pour les programmes belges de bien-être, de soins personnels et de distribution spécialisée.", href: "/products/ayurvedic-indian-herbs" },
  { title: "Épices indiennes", text: "Des épices entières et moulues sélectionnées pour importateurs, grossistes, détaillants et acheteurs alimentaires professionnels en Belgique.", href: "/products/indian-spices" },
];

const buyers = [
  { title: "Importateurs et distributeurs", text: "Coordination des spécifications, quantités commerciales et documents disponibles pour les réseaux belges d’importation et de distribution desservant Bruxelles, Anvers, Gand et d’autres marchés." },
  { title: "Marques de distribution naturelle et biologique", text: "Étude du henné, de l’indigo, des plantes, des soins capillaires botaniques et des épices pour les gammes naturelles, biologiques et spécialisées en Belgique." },
  { title: "Entreprises cosmétiques et de soins personnels", text: "Échanges de sourcing pour poudres botaniques, colorations végétales et concepts cosmétiques développés par l’acheteur, sous réserve de l’examen du produit et des spécifications." },
  { title: "Fournisseurs de salons professionnels", text: "Étude du henné naturel, de l’indigo et des colorations botaniques pour les circuits belges de fourniture aux salons et de distribution professionnelle." },
  { title: "Entreprises de plantes et de bien-être", text: "Examen de poudres ayurvédiques, d’ingrédients végétaux et de certaines plantes pour les entreprises belges du bien-être et des produits spécialisés." },
  { title: "Acheteurs Private Label et OEM", text: "Coordination de sachets, cartons, créations graphiques, étiquettes et présentations à la marque de l’acheteur pour les commandes commercialement réalisables." },
  { title: "Importateurs alimentaires et d’épices", text: "Échanges concernant certaines épices indiennes entières, moulues ou mélangées pour entreprises alimentaires, importateurs et distributeurs spécialisés belges." },
  { title: "Grossistes et détaillants spécialisés", text: "Construction d’assortiments ciblés pour le commerce de gros, l’e-commerce, la distribution spécialisée et les circuits professionnels belges." },
];

const steps = [
  ["01", "Sélection du produit", "Confirmer la famille de produits, le circuit visé, la qualité, la quantité et la destination en Belgique."],
  ["02", "Spécifications et échantillons", "Examiner les spécifications disponibles et discuter d’échantillons lorsque cela est commercialement réalisable."],
  ["03", "Devis et conditions", "Confirmer le périmètre, le prix, les conditions de paiement, le format d’emballage et les modalités d’expédition applicables."],
  ["04", "Emballage et Private Label", "Étudier les formats de détail ou en vrac, les fichiers de l’acheteur, les étiquettes et la faisabilité d’impression."],
  ["05", "Production et contrôles qualité", "Transformer, conditionner et contrôler les marchandises confirmées selon les exigences convenues de la commande."],
  ["06", "Documents et expédition", "Coordonner les documents d’exportation disponibles, la planification, l’expédition et le partage documentaire avec l’acheteur ou son transitaire désigné."],
];

const documents = [
  { title: "Facture commerciale", text: "Les informations de facture commerciale peuvent être préparées selon l’acheteur confirmé, les produits, quantités, valeurs et conditions d’expédition." },
  { title: "Liste de colisage", text: "Le nombre de colis, les poids nets et bruts, les informations carton et les références d’expédition convenues peuvent être coordonnés pour les commandes confirmées." },
  { title: "Certificat d’origine", text: "La coordination d’un certificat d’origine peut être étudiée lorsqu’elle s’applique au produit et à l’organisation d’expédition confirmés." },
  { title: "Spécifications et COA", text: "Les spécifications produit, le COA lorsqu’il est disponible, les références de lot et les informations qualité disponibles dépendent du produit sélectionné." },
  { title: "Informations d’emballage", text: "Les informations relatives aux sachets, cartons, emballages en vrac, étiquettes et codes-barres peuvent être alignées sur le programme approuvé par l’acheteur." },
  { title: "Documents d’expédition", text: "Les documents d’expédition peuvent être coordonnés avec le transitaire désigné par l’acheteur et le plan d’envoi convenu." },
  { title: "Informations produit et lot", text: "Lorsqu’elles sont disponibles, les informations produit, lot, techniques et références qualité peuvent être examinées selon l’article confirmé." },
  { title: "Responsabilité de l’importateur", text: "L’importateur ou l’acheteur belge reste responsable des exigences applicables d’importation, d’enregistrement, d’étiquetage, d’allégations, de douane et d’accès au marché." },
];

const locations = [
  { title: "Bruxelles", text: "Importateurs, entreprises cosmétiques, marques e-commerce et distributeurs nationaux peuvent discuter de sourcing multigamme et de programmes à leur marque." },
  { title: "Anvers", text: "Importateurs liés au port, grossistes et acheteurs orientés logistique peuvent examiner l’approvisionnement en vrac, l’emballage export et les besoins de distribution ultérieure." },
  { title: "Gand", text: "Détaillants naturels, entreprises du bien-être, fournisseurs de salons et acheteurs alimentaires peuvent étudier des gammes botaniques, capillaires et d’épices ciblées." },
  { title: "Liège", text: "Distributeurs belges francophones et détaillants spécialisés peuvent discuter de produits naturels pour les circuits professionnels, de détail et e-commerce." },
  { title: "Charleroi", text: "Grossistes régionaux, entreprises de soins personnels et fournisseurs professionnels peuvent examiner produits, formats et structures de commande commercialement adaptés." },
  { title: "Namur", text: "Détaillants spécialisés, entreprises de plantes et marques de bien-être peuvent évaluer certaines plantes, poudres botaniques et présentations à leur marque." },
  { title: "Louvain", text: "Entreprises innovantes, sociétés cosmétiques et acheteurs spécialisés peuvent discuter de spécifications produit et de concepts Private Label étudiés." },
  { title: "Bruges", text: "Les entreprises de détail, liées à l’hospitalité et de distribution régionale peuvent examiner des programmes pertinents de produits naturels et d’épices indiennes." },
];

const faqs = [
  { question: "Quels produits les acheteurs belges peuvent-ils commander ?", answer: "La gamme comprend le henné naturel, l’indigo naturel, les colorations capillaires naturelles au henné, les colorations à base de henné, les plantes ayurvédiques indiennes et certaines épices indiennes. La disponibilité et l’adéquation sont étudiées pour chaque demande." },
  { question: "Quelle est la quantité minimale pour la Belgique ?", answer: "Le MOQ est de 200 kg par article. Les quantités finales et les configurations d’emballage dépendent du produit, du format et du périmètre commercial confirmés." },
  { question: "Proposez-vous un approvisionnement en vrac et en gros ?", answer: "Oui. Les produits réalisables peuvent être préparés en emballages vrac convenus de 20 kg ou 25 kg, en formats professionnels ou dans certaines présentations de détail, selon le produit et la quantité." },
  { question: "Les marques belges peuvent-elles demander du Private Label ou de l’OEM ?", answer: "Certains programmes OEM et Private Label peuvent être étudiés pour les commandes commercialement réalisables. Le produit, l’emballage, les fichiers, l’impression et la production sont confirmés avant le lancement de la commande." },
  { question: "Quels formats de détail peuvent être envisagés ?", answer: "Selon le produit et la quantité, les options peuvent inclure 100 g, 200 g, 500 g et 1 kg, des sachets métallisés argent ou or, des formats kraft, des cartons et une présentation à la marque de l’acheteur." },
  { question: "Des échantillons peuvent-ils être discutés avant une commande commerciale ?", answer: "Des échantillons peuvent être discutés lorsque cela est réalisable, après compréhension du produit, des spécifications, de l’usage prévu et de la quantité commerciale demandés." },
  { question: "Quels documents d’exportation sont disponibles pour la Belgique ?", answer: "Les documents commerciaux, produit et d’expédition disponibles peuvent être examinés selon le produit sélectionné, les exigences de commande et la transaction convenue. Aucun document ni aucune approbation n’est implicite sans confirmation." },
  { question: "Qui est responsable des exigences belges et européennes d’importation ?", answer: "L’importateur ou l’acheteur belge reste responsable de la classification, des autorisations d’importation, du dédouanement, de l’étiquetage, des allégations, de l’enregistrement et de toutes les exigences belges et européennes applicables. Nous coordonnons les informations d’exportation selon les conditions confirmées sans garantir le dédouanement ni le délai de livraison." },
];

const structuredData = { "@context": "https://schema.org", "@graph": [
  { "@type": "WebPage", "@id": `${pageUrl}#webpage`, url: pageUrl, name: "Exportateur de produits naturels de l’Inde vers la Belgique", description: "Approvisionnement en gros, en vrac, en OEM et en Private Label de produits botaniques indiens pour acheteurs professionnels belges.", isPartOf: { "@id": "https://shiveshinternational.com/#website" }, about: { "@id": "https://shiveshinternational.com/#organization" }, breadcrumb: { "@id": `${pageUrl}#breadcrumb` }, primaryImageOfPage: { "@type": "ImageObject", url: heroImage }, inLanguage: "fr" },
  { "@type": "BreadcrumbList", "@id": `${pageUrl}#breadcrumb`, itemListElement: [{ "@type": "ListItem", position: 1, name: "Accueil", item: "https://shiveshinternational.com/" }, { "@type": "ListItem", position: 2, name: "Export", item: "https://shiveshinternational.com/export" }, { "@type": "ListItem", position: 3, name: "Export vers la Belgique", item: pageUrl }] },
] };
const faqStructuredData = { "@context": "https://schema.org", "@type": "FAQPage", "@id": `${pageUrl}#faq`, mainEntity: faqs.map((faq) => ({ "@type": "Question", name: faq.question, acceptedAnswer: { "@type": "Answer", text: faq.answer } })) };

export default function BelgiqueExportPage() {
  return <main className="min-h-screen overflow-x-hidden bg-[#F5F0E6] text-[#173B2A]">
    <script type="application/ld+json" dangerouslySetInnerHTML={{ __html: JSON.stringify(structuredData).replace(/</g, "\\u003c") }} />
    <script type="application/ld+json" dangerouslySetInnerHTML={{ __html: JSON.stringify(faqStructuredData).replace(/</g, "\\u003c") }} />
    <Navbar />
    <section className="relative isolate overflow-hidden bg-[#071B14]"><Image src="/images/export/belgium/belgium-export-hero-natural-henna-hair-colors.png" alt="Professionnelles belges de la coiffure étudiant des colorations naturelles au henné fournies depuis l’Inde" fill priority sizes="100vw" className="object-cover object-[68%_center] sm:object-[64%_center] lg:object-center" /><div className="absolute inset-0 bg-gradient-to-r from-[#061711]/80 via-[#102F23]/38 to-transparent" /><GoldenParticles /><div className="relative z-10 flex min-h-[760px] items-center px-6 pb-24 pt-28 sm:px-8 lg:px-12"><div className="w-full max-w-[820px]"><p className="text-[10px] font-bold uppercase tracking-[0.34em] text-[#E4C878] sm:text-xs">Approvisionnement B2B Inde → Belgique</p><h1 className="mt-6 font-[family-name:var(--font-playfair)] text-[clamp(2.35rem,5vw,5rem)] font-medium leading-[1.03] tracking-[-0.04em] text-[#F5F0E6]">Exportateur de produits naturels<span className="mt-2 block text-[#E4C878]">de l’Inde vers la Belgique</span></h1><p className="mt-7 max-w-[720px] text-[16px] font-light leading-8 text-white/78 sm:text-[18px]">Approvisionnement commercial en henné naturel, indigo, colorations capillaires botaniques, plantes ayurvédiques et épices indiennes pour importateurs, grossistes, salons et marques belges, en vrac, en gros, en OEM et en Private Label.</p><div className="mt-9 flex flex-wrap gap-4"><a href="#produits" className="border border-[#C9A962] bg-[#C9A962] px-7 py-4 text-[10px] font-bold uppercase tracking-[0.2em] text-[#102F23]">Découvrir les produits ↓</a><Link href="/contact" className="border border-white/30 bg-black/20 px-7 py-4 text-[10px] font-bold uppercase tracking-[0.2em] text-white">Demander un devis Belgique</Link></div><div className="mt-10 grid max-w-[760px] gap-3 sm:grid-cols-2 lg:grid-cols-4">{[["200 kg", "MOQ par article"], ["Six", "Familles de produits"], ["OEM", "Private Label"], ["Belgique", "Acheteurs professionnels"]].map(([value,label]) => <div key={label} className="border border-white/15 bg-black/25 px-4 py-4"><p className="font-[family-name:var(--font-playfair)] text-xl text-[#E4C878]">{value}</p><p className="mt-2 text-[9px] font-bold uppercase tracking-[0.16em] text-white/55">{label}</p></div>)}</div></div></div></section>

    <section id="produits" className="px-6 py-24 sm:px-8 lg:px-12 lg:py-32"><RevealOnScroll><div className="mx-auto max-w-[1500px]"><div className="mx-auto max-w-[900px] text-center"><p className="text-[10px] font-bold uppercase tracking-[0.38em] text-[#9F7F36]">Six familles commerciales</p><h2 className="mt-6 font-[family-name:var(--font-playfair)] text-[clamp(2.25rem,4.7vw,4.7rem)] font-semibold leading-[1.05]">Produits naturels indiens<span className="block text-[#A97B22]">pour les gammes des acheteurs belges</span></h2><p className="mx-auto mt-7 max-w-[820px] leading-8 text-[#4C5F54]">Une gamme ciblée pour les circuits belges de la beauté naturelle, de la coiffure professionnelle, des plantes, du bien-être, du commerce spécialisé et, selon le produit, de l’alimentation.</p></div><div className="mt-14 grid gap-5 sm:grid-cols-2 lg:grid-cols-3">{products.map((product,index) => <StaggerItem key={product.title} delay={(index % 3) * 90}><article className="flex h-full min-h-[290px] flex-col border border-[#173B2A]/12 bg-[#FBF8F1] p-7 sm:p-8"><span className="text-sm font-bold text-[#C9A962]">0{index + 1}</span><h3 className="mt-5 font-[family-name:var(--font-playfair)] text-[27px] font-semibold">{product.title}</h3><p className="mt-5 flex-1 text-[14px] leading-7 text-[#4C5F54]">{product.text}</p><Link href={product.href} className="mt-7 text-[10px] font-bold uppercase tracking-[0.2em] text-[#A97B22]">Voir le produit →</Link></article></StaggerItem>)}</div></div></RevealOnScroll></section>

    <section className="px-6 py-24 sm:px-8 lg:px-12 lg:py-32"><RevealOnScroll><div className="mx-auto max-w-[1500px]"><div className="text-center"><p className="text-[10px] font-bold uppercase tracking-[0.4em] text-[#9F7F36]">Profils d’acheteurs belges</p><h2 className="mt-6 font-[family-name:var(--font-playfair)] text-[clamp(2.35rem,4.6vw,4.6rem)] font-semibold leading-[1.05]">Planification de l’approvisionnement<span className="block text-[#A97B22]">pour l’importation, le détail et la distribution</span></h2><p className="mx-auto mt-7 max-w-[860px] leading-8 text-[#4C5F54]">Les acheteurs belges peuvent étudier un approvisionnement ciblé selon le produit, le circuit, la quantité et l’usage commercial prévu. Les villes citées décrivent uniquement des contextes de marché et n’impliquent ni locaux, ni stock, ni représentation sur place.</p></div><div className="mt-14 grid auto-rows-fr gap-5 md:grid-cols-2 lg:grid-cols-4">{buyers.map((buyer) => <article key={buyer.title} className="h-full min-h-[280px] border border-[#173B2A]/12 bg-[#FBF8F1] p-7 sm:p-8"><span className="block h-px w-12 bg-[#C9A962]" /><h3 className="mt-6 font-[family-name:var(--font-playfair)] text-[24px] font-semibold leading-tight">{buyer.title}</h3><p className="mt-5 text-[14px] font-light leading-7 text-[#4C5F54]">{buyer.text}</p></article>)}</div></div></RevealOnScroll></section>

    <section className="px-6 py-24 sm:px-8 lg:px-12 lg:py-32"><RevealOnScroll><div className="mx-auto grid max-w-[1500px] items-center gap-14 lg:grid-cols-2 lg:gap-20"><figure className="relative aspect-[4/3] overflow-hidden border border-[#C9A962]/35 bg-[#102F23]"><Image src="/images/export/belgium/belgium-packaging-private-label.png" alt="Développement d’emballages Private Label en Belgique pour le henné, l’indigo, les plantes et les colorations naturelles" fill sizes="(min-width:1024px) 50vw, 100vw" className="object-cover object-center" /></figure><div><p className="text-[10px] font-bold uppercase tracking-[0.38em] text-[#9F7F36]">Emballage et développement de la marque acheteur</p><h2 className="mt-6 font-[family-name:var(--font-playfair)] text-[clamp(2.15rem,3.9vw,3.9rem)] font-semibold leading-[1.07]">Des formats pour les circuits belges<span className="block text-[#A97B22]">de détail, professionnels et en vrac</span></h2><p className="mt-7 leading-8 text-[#4C5F54]">Selon le produit et la quantité, les formats de détail peuvent inclure 100 g, 200 g, 500 g et 1 kg. Les options en vrac peuvent comprendre 20 kg et 25 kg, avec double emballage sous vide lorsque cela convient.</p><p className="mt-5 leading-8 text-[#4C5F54]">Sachets métallisés argent ou or, formats kraft, cartons, fichiers de la marque acheteur, coordination des étiquettes et présentation Private Label peuvent être étudiés sous réserve de la faisabilité des matériaux, de l’impression, de la production et des conditions commerciales. L’acheteur belge reste responsable des exigences applicables d’étiquetage et de mise sur le marché.</p><Link href="/contact" className="mt-8 inline-flex border border-[#C9A962] bg-[#C9A962] px-7 py-4 text-[10px] font-bold uppercase tracking-[0.2em] text-[#102F23]">Discuter d’un projet Private Label →</Link></div></div></RevealOnScroll></section>

    <section className="bg-[#09271D] px-6 py-24 text-[#F5F0E6] sm:px-8 lg:px-12 lg:py-32"><RevealOnScroll><div className="mx-auto max-w-[1500px]"><div className="grid items-center gap-12 lg:grid-cols-[0.9fr_1.1fr]"><div><p className="text-[10px] font-bold uppercase tracking-[0.38em] text-[#E4C878]">Coordination Inde → Belgique</p><h2 className="mt-6 font-[family-name:var(--font-playfair)] text-[clamp(2.25rem,4.35vw,4.35rem)] font-semibold leading-[1.05]">Un parcours structuré<span className="block text-[#E4C878]">de la demande à l’expédition</span></h2><p className="mt-7 leading-8 text-white/65">La planification peut être coordonnée pour des destinations acheteur comme Anvers, Bruxelles et Gand, sous réserve des conditions confirmées, de la disponibilité des transporteurs et des instructions de l’acheteur ou de son transitaire désigné.</p></div><figure className="relative aspect-[4/3] overflow-hidden border border-[#C9A962]/30"><Image src="/images/export/belgium/belgium-export-freight-coordination.png" alt="Coordination des exportations de produits naturels en vrac de l’Inde vers la Belgique" fill sizes="(min-width:1024px) 55vw, 100vw" className="object-cover object-center" /></figure></div><aside className="mt-12 border border-[#C9A962]/40 bg-[#F5F0E6] p-7 text-[#173B2A] sm:p-9"><h3 className="font-[family-name:var(--font-playfair)] text-2xl font-semibold text-[#A97B22]">Documents et responsabilité de l’importateur</h3><p className="mt-4 text-[14px] leading-7 text-[#4C5F54]">Les documents disponibles peuvent être examinés selon les exigences du produit et de la commande. Les tarifs de transport, horaires, délais, dédouanement, inspections, enregistrements, acceptation réglementaire et dates de livraison ne sont pas garantis. L’importateur belge reste responsable de toutes les obligations applicables d’importation et de mise sur le marché.</p></aside></div></RevealOnScroll></section>

    <section className="px-6 py-24 sm:px-8 lg:px-12 lg:py-32"><RevealOnScroll><div className="mx-auto max-w-[1500px]"><div className="mx-auto max-w-[920px] text-center"><p className="text-[10px] font-bold uppercase tracking-[0.38em] text-[#9F7F36]">Informations à examiner par l’acheteur</p><h2 className="mt-6 font-[family-name:var(--font-playfair)] text-[clamp(2.2rem,4.5vw,4.5rem)] font-semibold leading-[1.06]">Documents d’exportation<span className="block text-[#A97B22]">pour les acheteurs belges</span></h2><p className="mx-auto mt-7 max-w-[850px] leading-8 text-[#4C5F54]">Les documents dépendent du produit sélectionné, de la structure de la commande et de leur disponibilité. Les informations commerciales, produit, emballage et expédition disponibles peuvent être coordonnées pour examen par l’acheteur et la destination, sans impliquer une conformité réglementaire belge ou européenne automatique.</p></div><div className="mt-14 grid gap-5 md:grid-cols-2 lg:grid-cols-4">{documents.map((document,index) => <StaggerItem key={document.title} delay={(index % 4) * 80}><article className="h-full min-h-[260px] border border-[#173B2A]/12 bg-[#FBF8F1] p-7 sm:p-8"><div className="flex items-center justify-between"><span className="h-px w-12 bg-[#C9A962]" /><span className="font-[family-name:var(--font-playfair)] text-xl text-[#C9A962]/70">{String(index + 1).padStart(2,"0")}</span></div><h3 className="mt-7 font-[family-name:var(--font-playfair)] text-[24px] font-semibold leading-tight">{document.title}</h3><p className="mt-5 text-[14px] font-light leading-7 text-[#4C5F54]">{document.text}</p></article></StaggerItem>)}</div></div></RevealOnScroll></section>

    <section className="bg-[#EDE5D7] px-6 py-24 sm:px-8 lg:px-12 lg:py-32"><RevealOnScroll><div className="mx-auto max-w-[1500px]"><div className="text-center"><p className="text-[10px] font-bold uppercase tracking-[0.4em] text-[#9F7F36]">Six étapes commerciales</p><h2 className="mt-6 font-[family-name:var(--font-playfair)] text-[clamp(2.3rem,4.6vw,4.6rem)] font-semibold leading-[1.05]">Du besoin de l’acheteur belge<span className="block text-[#A97B22]">à la coordination export</span></h2></div><div className="mt-14 grid auto-rows-fr gap-5 md:grid-cols-2 lg:grid-cols-3">{steps.map(([number,title,text]) => <article key={number} className="h-full min-h-[220px] border border-[#173B2A]/12 bg-[#FBF8F1] p-7 sm:p-8"><div className="flex items-center justify-between"><span className="h-px w-12 bg-[#C9A962]" /><span className="font-[family-name:var(--font-playfair)] text-xl text-[#C9A962]/70">{number}</span></div><h3 className="mt-6 font-[family-name:var(--font-playfair)] text-[24px] font-semibold leading-tight">{title}</h3><p className="mt-5 text-[14px] font-light leading-7 text-[#4C5F54]">{text}</p></article>)}</div></div></RevealOnScroll></section>

    <section className="px-6 py-24 sm:px-8 lg:px-12 lg:py-32"><RevealOnScroll><div className="mx-auto max-w-[1280px]"><p className="text-[10px] font-bold uppercase tracking-[0.4em] text-[#9F7F36]">Principaux marchés commerciaux belges</p><h2 className="mt-6 font-[family-name:var(--font-playfair)] text-[clamp(2.3rem,4.5vw,4.5rem)] font-semibold leading-[1.05]">Contexte des acheteurs et de la distribution<span className="block text-[#A97B22]">à travers la Belgique</span></h2><p className="mt-7 max-w-[900px] text-[15px] leading-8 text-[#4C5F54]">Ces villes identifient des contextes commerciaux et de distribution potentiels. Elles ne représentent ni locaux, ni stock, ni employés, ni agents, ni relations garanties.</p><div className="mt-12 grid auto-rows-fr gap-5 md:grid-cols-2 lg:grid-cols-4">{locations.map((location) => <article key={location.title} className="h-full min-h-[245px] border border-[#173B2A]/12 bg-[#FBF8F1] p-7 sm:p-8"><span className="block h-px w-12 bg-[#C9A962]" /><h3 className="mt-6 font-[family-name:var(--font-playfair)] text-[26px] font-semibold">{location.title}</h3><p className="mt-5 text-[14px] font-light leading-7 text-[#4C5F54]">{location.text}</p></article>)}</div></div></RevealOnScroll></section>

    <section className="px-6 py-24 sm:px-8 lg:px-12 lg:py-32"><RevealOnScroll><div className="mx-auto max-w-[1120px]"><div className="text-center"><p className="text-[10px] font-bold uppercase tracking-[0.38em] text-[#9F7F36]">Questions des acheteurs belges</p><h2 className="mt-6 font-[family-name:var(--font-playfair)] text-[clamp(2.1rem,4.2vw,4.2rem)] font-semibold">Questions fréquentes</h2></div><div className="mt-12 divide-y divide-[#173B2A]/15 border-y border-[#173B2A]/15">{faqs.map((faq) => <article key={faq.question} className="grid gap-4 py-7 md:grid-cols-[0.8fr_1.2fr] md:gap-10"><h3 className="font-[family-name:var(--font-playfair)] text-xl font-semibold">{faq.question}</h3><p className="text-[14px] leading-7 text-[#4C5F54]">{faq.answer}</p></article>)}</div></div></RevealOnScroll></section>

    <section className="relative overflow-hidden bg-[#071B14] px-6 py-24 text-center text-[#F5F0E6] sm:px-8 lg:px-12"><GoldenParticles /><RevealOnScroll><div className="relative mx-auto max-w-[980px]"><p className="text-[10px] font-bold uppercase tracking-[0.38em] text-[#E4C878]">Démarrer une discussion d’approvisionnement pour la Belgique</p><h2 className="mt-6 font-[family-name:var(--font-playfair)] text-[clamp(2.15rem,4.4vw,4.4rem)] font-semibold leading-[1.06]">Planifiez votre approvisionnement en produits naturels depuis l’Inde</h2><p className="mx-auto mt-7 max-w-[760px] leading-8 text-white/65">Indiquez le produit, la quantité, les spécifications, l’emballage, les exigences de votre marque et la destination belge pour une étude commerciale ciblée.</p><Link href="/contact" className="mt-9 inline-flex border border-[#C9A962] bg-[#C9A962] px-8 py-4 text-[10px] font-bold uppercase tracking-[0.22em] text-[#102F23]">Demander un devis Belgique →</Link></div></RevealOnScroll></section>
    <FooterSection locale="fr" /><FloatingContactButtons /><MagneticButtons /><PremiumCursor />
  </main>;
}
