import type { Metadata } from "next";
import { existsSync } from "node:fs";
import Image from "next/image";
import Link from "next/link";

import FloatingContactButtons from "@/app/components/FloatingContactButtons";
import GoldenParticles from "@/app/components/GoldenParticles";
import MagneticButtons from "@/app/components/MagneticButtons";
import Navbar from "@/app/components/Navbar";
import PremiumCursor from "@/app/components/PremiumCursor";
import RevealOnScroll from "@/app/components/RevealOnScroll";
import StaggerItem from "@/app/components/StaggerItem";
import { austriaLanguageAlternates } from "@/app/lib/i18n";
import FooterSection from "@/sections/FooterSection";

const canonicalUrl = "https://shiveshinternational.com/export/austria";
const heroImage = "/images/export/austria/austria-export-hero.png";

export const metadata: Metadata = {
  title: "Henna, Indigo, Herbs & Spices Exporter to Austria",
  description:
    "Indian exporter of natural henna powder, indigo powder, botanical hair colors, Ayurvedic herbs and Indian spices for Austrian importers, distributors, wholesalers and private-label buyers.",
  keywords: [
    "Natural products exporter to Austria", "Indian natural products supplier Austria", "Exporter from India to Austria", "Indian supplier for Austrian importers", "Natural product manufacturer India for Austria", "Bulk natural products supplier Austria", "Private label products manufacturer for Austria", "Wholesale botanical products Austria", "Indian exporter for Austrian distributors", "Natural cosmetic ingredients supplier Austria", "Herbal products exporter to Austria", "Plant-based products supplier Austria", "Botanical ingredients exporter Austria", "Indian manufacturer for Austrian wholesalers", "B2B natural products supplier Austria",
    "Henna powder exporter to Austria", "Natural henna powder supplier Austria", "Henna powder manufacturer India for Austria", "Bulk henna powder supplier Austria", "Organic henna powder exporter Austria", "Private label henna powder Austria", "Wholesale henna powder Austria", "Cosmetic-grade henna powder supplier Austria", "Pure henna powder exporter to Austria", "Lawsonia inermis powder supplier Austria", "Indian henna exporter for Austrian importers", "Henna powder for cosmetic brands Austria", "Henna powder for salon suppliers Austria", "Henna powder wholesale supplier Austria", "Private label henna manufacturer India for Austria", "Natural henna supplier Vienna", "Henna powder supplier Graz", "Henna exporter for Austrian beauty brands",
    "Indigo powder exporter to Austria", "Natural indigo powder supplier Austria", "Indigo powder manufacturer India for Austria", "Bulk indigo powder supplier Austria", "Organic indigo powder exporter Austria", "Private label indigo powder Austria", "Wholesale indigo powder Austria", "Indigofera tinctoria powder supplier Austria", "Natural indigo for botanical hair color Austria", "Indigo powder for Austrian cosmetic brands", "Indian indigo exporter Austria", "Indigo hair dye ingredient supplier Austria", "Indigo powder for salons Austria", "Bulk indigo supplier for Austrian importers",
    "Natural henna hair color manufacturer for Austria", "Botanical hair color supplier Austria", "Plant-based hair color exporter Austria", "Natural hair dye manufacturer India for Austria", "Private label natural hair color Austria", "Henna hair color wholesale Austria", "Botanical hair dye supplier Austria", "Herbal hair color manufacturer for Austrian brands", "Powder hair color exporter Austria", "Natural hair color supplier for Austrian salons", "Henna-based hair color supplier Austria", "Private label botanical hair color manufacturer India", "Natural hair color for Austrian distributors", "Botanical hair color bulk supplier Austria", "Natural hair dye products for Austrian beauty brands", "Salon hair color supplier Austria",
    "Ayurvedic herbs exporter to Austria", "Indian herbs supplier Austria", "Herbal powder exporter Austria", "Ayurvedic powder supplier Austria", "Bulk Indian herbs supplier Austria", "Private label herbal products Austria", "Wholesale Ayurvedic herbs Austria", "Indian botanical ingredients exporter Austria", "Herbal ingredients for cosmetic brands Austria", "Natural herbal powder manufacturer India for Austria", "Ayurvedic herbs for Austrian importers", "Indian herbs for wellness brands Austria", "Bulk herbal powders exporter Austria", "Cosmetic herbal ingredients supplier Austria", "Amla powder supplier Austria", "Shikakai powder exporter Austria", "Herbal hair-care ingredients Austria",
    "Indian spices exporter to Austria", "Indian spices supplier Austria", "Bulk spices supplier Austria", "Wholesale Indian spices Austria", "Whole spices exporter to Austria", "Ground spices exporter Austria", "Private label Indian spices Austria", "Indian spice manufacturer for Austrian buyers", "Spice exporter from India to Austria", "Indian spices for Austrian importers", "Bulk spice powder supplier Austria", "Indian food ingredient supplier Austria", "Private label spice packaging Austria", "Indian spice wholesale supplier Austria", "Indian spices for Austrian food businesses", "Indian spices distributor supply Austria",
    "Private label manufacturer India for Austria", "Custom packaging supplier for Austrian buyers", "Private label henna packaging Austria", "Private label indigo packaging Austria", "Private label herbal powder Austria", "Private label spice supplier Austria", "Custom branded pouches for Austrian importers", "Retail packaging natural products Austria", "Bulk packaging exporter India to Austria", "Contract packaging for Austrian brands", "Multilingual label coordination Austria", "Austrian label packaging coordination", "White label natural products Austria", "OEM natural products supplier Austria", "Custom brand botanical products Austria", "Private label natural hair color Austria",
    "Henna supplier for Austrian importers", "Natural product supplier for Austrian distributors", "Botanical products for Austrian wholesalers", "Private label supplier for Austrian brands", "Henna supplier for salon distributors Austria", "Herbal ingredients for Austrian cosmetic manufacturers", "Indian products for Austrian retail businesses", "Bulk supplier for Austrian natural product brands", "Natural ingredients for Austrian beauty brands", "Indian exporter for Austrian wholesale buyers", "Natural product supplier Vienna", "Botanical product supplier Graz", "Indian herbal supplier Innsbruck", "Natural hair-care ingredients Salzburg", "Private label products for Austrian e-commerce brands",
    "Reetha powder supplier Austria", "Neem powder Austria", "Bhringraj powder Austria", "Brahmi powder Austria", "Hibiscus powder supplier Austria", "Ashwagandha powder supplier Austria", "Turmeric powder exporter Austria", "Cumin supplier Austria", "Coriander supplier Austria", "Black pepper exporter Austria", "Plant-based hair color supplier Austria",
    "100 g henna pouch Austria", "200 g henna pouch Austria", "500 g herbal powder Austria", "1 kg botanical powder Austria", "20 kg bulk henna Austria", "25 kg bulk henna Austria", "Vacuum packed botanical powders Austria", "German language label coordination Austria", "Austrian buyer packaging support", "Barcode packaging support Austria", "200 kg MOQ natural products Austria",
    "India to Austria export coordination", "Natural products shipping India to Austria", "Commercial invoice support Austria", "Packing list support Austria", "Certificate of origin coordination Austria", "COA document support Austria", "Product specification documents Austria", "Sea freight coordination Austria", "Air freight coordination Austria", "Road freight coordination Austria", "Multimodal shipment India Austria", "Vienna air cargo natural products", "Linz logistics natural products", "Graz freight natural products", "Austria import documentation support", "EU buyer documentation natural products", "Indian exporter for Austrian buyers",
  ].filter((_, index) => index % 2 === 0),
  alternates: {
    canonical: canonicalUrl,
    languages: austriaLanguageAlternates,
  },
  openGraph: {
    title: "Henna, Indigo, Herbs & Spices Exporter to Austria",
    description: "Bulk, wholesale and private-label supply of Indian henna, indigo, botanical hair colors, Ayurvedic herbs and spices for professional buyers in Austria.",
    url: canonicalUrl,
    type: "website",
    locale: "en_AT",
    siteName: "Shivesh International",
    images: [{ url: "/images/export/austria/austria-export-hero.png", alt: "Austrian buyers reviewing Indian natural products" }],
  },
  twitter: {
    card: "summary_large_image",
    title: "Henna, Indigo, Herbs & Spices Exporter to Austria",
    description: "Indian natural-product supply for Austrian importers, distributors, salons and private-label brands.",
    images: ["/images/export/austria/austria-export-hero.png"],
  },
  robots: { index: true, follow: true, googleBot: { index: true, follow: true } },
};

const products = [
  { title: "Natural Henna Powder", text: "Fine-quality natural henna powder for Austrian cosmetic brands, salons, wholesalers, herbal-product businesses and customized private-label retail supply.", href: "/products/natural-henna-powder" },
  { title: "Natural Indigo Powder", text: "Natural indigo powder for botanical hair-color systems, cosmetic formulations, salon supply, bulk sourcing and private-label packaging.", href: "/products/natural-indigo-powder" },
  { title: "Natural Henna Hair Colors", text: "A broad botanical shade collection for Austrian importers, beauty brands, natural hair-care companies and salon distribution businesses.", href: "/products/natural-henna-hair-colors" },
  { title: "Henna-Based Hair Colors", text: "Export-ready powdered hair colors for Austrian buyers requiring wholesale, OEM, professional or customized private-label formats.", href: "/products/henna-based-hair-colors" },
  { title: "Ayurvedic Indian Herbs", text: "Indian herbal powders and botanicals for Austrian cosmetic, personal-care, wellness, hair-care and wholesale product applications.", href: "/products/ayurvedic-indian-herbs" },
  { title: "Indian Spices", text: "Whole and powdered Indian spices for Austrian importers, distributors, food businesses, specialty retailers and private-label brands.", href: "/products/indian-spices" },
];

const buyerProfiles = [
  ["Importers and Distributors", "Coordinate specifications, commercial quantities and available documentation for Austrian distribution networks serving Vienna, Graz and other regional markets."],
  ["Organic and Natural Retail Brands", "Review henna, indigo, herbs and spices for Austrian organic shops, natural retailers and buyer-brand ranges, subject to product-specific evidence and buyer assessment."],
  ["Cosmetic and Personal-Care Companies", "Source botanical powders for buyer-developed cosmetic and personal-care concepts with intended-use and specification review."],
  ["Professional Salon Suppliers", "Discuss botanical hair-color powders and herbal hair-care ingredients for salon and professional distribution in Austria."],
  ["Herbal and Wellness Businesses", "Assess Ayurvedic powders and selected botanicals for Austrian wellness, speciality retail and own-brand programmes."],
  ["Private-Label and OEM Buyers", "Coordinate feasible pouches, cartons, artwork, barcodes and German-language label layouts for buyer-brand projects."],
  ["Food and Spice Importers", "Plan whole-spice, ground-spice and Indian food-ingredient supply for Austrian food businesses and specialist distributors."],
  ["Wholesalers and Speciality Retailers", "Build focused natural-product assortments for wholesale, e-commerce and speciality retail channels across Austria."],
];

const documentationItems = [
  ["Commercial Invoice", "Commercial invoice information can be prepared around the confirmed buyer, products, quantities, values and shipment terms."],
  ["Packing List", "Pack counts, net and gross weights, carton information and agreed shipment references can be coordinated for confirmed orders."],
  ["Certificate of Origin", "Certificate-of-origin coordination can be discussed where applicable to the confirmed product and shipment arrangement."],
  ["Specifications and COA", "Product specifications, COA where available, batch references and available quality information depend on the selected product."],
  ["Packaging Information", "Pouch, carton, bulk-bag, label and barcode information can be aligned with the buyer-approved packaging programme."],
  ["Shipping Documents", "Shipment documentation can be coordinated with buyer-appointed freight forwarders and the agreed dispatch plan."],
  ["Destination Review Information", "Available product and packaging information can support the Austrian buyer’s customs and destination-market review."],
  ["Buyer Responsibility", "The importer must verify classification, labels, claims, registrations, customs, taxes and applicable Austrian and EU requirements."],
];

const processSteps = [
  ["Share Product Requirement", "Provide the product name, intended business use, destination, approximate quantity and preferred packaging."],
  ["Confirm Specification and Quantity", "Review the requested grade, available specification and the 200 kg-per-product commercial minimum."],
  ["Review Packaging and Private Label", "Align feasible retail or bulk formats, artwork, labels, barcodes and buyer-brand requirements."],
  ["Confirm Documents and Shipment Plan", "Discuss available product documents and the buyer-appointed freight-forwarder arrangement."],
  ["Production and Dispatch Coordination", "Proceed according to confirmed commercial terms, production feasibility and the agreed dispatch plan."],
];

const marketLocations = [
  ["Vienna", "Importers, natural-cosmetic businesses and private-label buyers in the Vienna market can discuss multi-category sourcing and buyer-brand formats."],
  ["Graz", "Graz-area distributors and wellness businesses can review botanical powders, salon products and herbal retail ranges."],
  ["Linz", "Food-ingredient buyers, wholesalers and logistics-oriented businesses around Linz can coordinate spice and botanical supply enquiries."],
  ["Salzburg", "Salzburg speciality retailers, salon suppliers and premium wellness brands can assess selected retail and professional formats."],
  ["Innsbruck", "Natural-product and tourism-linked retail businesses in Innsbruck can discuss focused botanical, herbal and spice collections."],
  ["Klagenfurt", "Klagenfurt-area wellness companies, speciality shops and regional distributors can review commercially feasible product programmes."],
  ["Lower Austria", "Retail sourcing companies and distributors across Lower Austria can coordinate bulk supply and private-label presentation requirements."],
  ["Upper Austria", "Upper Austria buyers can discuss botanical ingredients, professional hair-care supply, spices and wholesale packaging options."],
];

const faqs = [
  { question: "Do you export natural henna powder from India to Austria?", answer: "Yes. Shivesh International coordinates natural henna powder supply from India for qualified Austrian importers, distributors, wholesalers, salon suppliers and private-label buyers, subject to specification and commercial confirmation." },
  { question: "What is the minimum order quantity for Austrian buyers?", answer: "The minimum order quantity is 200 kg per product. Final quantities depend on the selected product, packaging format and private-label requirements." },
  { question: "Can Austrian buyers order private-label henna and herbal products?", answer: "Selected henna and herbal products can be discussed for private-label supply, including buyer branding, feasible printed pouches or cartons, barcode details and buyer-approved artwork." },
  { question: "Which retail and bulk packaging formats are available?", answer: "Selected products can be discussed in 100 g, 200 g, 500 g and 1 kg pouches. Bulk options include 20 kg and 25 kg double-layer vacuum bags, subject to product and order confirmation." },
  { question: "Can you coordinate German-language packaging artwork?", answer: "German-language label artwork coordination can be discussed alongside multilingual packaging, buyer-supplied artwork and label-layout support. The Austrian buyer remains responsible for final label text, claims and approval." },
  { question: "Which documents can be provided with Austria-bound shipments?", answer: "Depending on the product and availability, coordination can include commercial invoices, packing lists, certificates of origin, specifications, COA, available quality information and shipping documents." },
  { question: "How can products be shipped from India to landlocked Austria?", answer: "Buyer-selected arrangements may use sea freight through a European gateway followed by road or rail transport, or air cargo through Vienna or another agreed airport. Routes and transit times are not guaranteed." },
  { question: "Are Austrian and EU import compliance requirements handled automatically?", answer: "No. The Austrian importer or buyer must confirm classification, labelling, claims, registrations, customs, taxes and applicable Austrian and European Union requirements for the selected product." },
];

const structuredData = {
  "@context": "https://schema.org",
  "@graph": [
    { "@type": "WebPage", "@id": `${canonicalUrl}#webpage`, url: canonicalUrl, name: "Henna, Indigo, Herbs & Spices Exporter to Austria", description: "Austria-focused export supply of natural henna, indigo, botanical hair colors, Ayurvedic herbs and Indian spices from India.", isPartOf: { "@id": "https://shiveshinternational.com/#website" }, about: { "@id": "https://shiveshinternational.com/#organization" }, breadcrumb: { "@id": `${canonicalUrl}#breadcrumb` }, inLanguage: "en" },
    { "@type": "BreadcrumbList", "@id": `${canonicalUrl}#breadcrumb`, itemListElement: [
      { "@type": "ListItem", position: 1, name: "Home", item: "https://shiveshinternational.com/" },
      { "@type": "ListItem", position: 2, name: "Export", item: "https://shiveshinternational.com/export" },
      { "@type": "ListItem", position: 3, name: "Europe", item: "https://shiveshinternational.com/export/europe" },
      { "@type": "ListItem", position: 4, name: "Austria", item: canonicalUrl },
    ] },
  ],
};

const faqStructuredData = { "@context": "https://schema.org", "@type": "FAQPage", "@id": `${canonicalUrl}#faq`, mainEntity: faqs.map((faq) => ({ "@type": "Question", name: faq.question, acceptedAnswer: { "@type": "Answer", text: faq.answer } })) };

function OptionalImage({ src, alt, priority = false, sizes = "(min-width: 1024px) 55vw, 100vw", className = "object-cover object-center" }: { src: string; alt: string; priority?: boolean; sizes?: string; className?: string }) {
  if (!existsSync(`${process.cwd()}/public${src}`)) return null;
  return <Image src={src} alt={alt} fill priority={priority} sizes={sizes} className={className} />;
}

export default function AustriaExportPage() {
  return (
    <main className="min-h-screen overflow-x-hidden bg-[#F5F0E6] text-[#173B2A]">
      <script type="application/ld+json" dangerouslySetInnerHTML={{ __html: JSON.stringify(structuredData).replace(/</g, "\\u003c") }} />
      <script type="application/ld+json" dangerouslySetInnerHTML={{ __html: JSON.stringify(faqStructuredData).replace(/</g, "\\u003c") }} />
      <Navbar />

      <section className="relative isolate overflow-hidden bg-[radial-gradient(circle_at_75%_42%,#496d58_0%,#173b2a_35%,#071b14_78%)]">
        <OptionalImage src={heroImage} alt="Austrian buyers reviewing Indian henna, indigo, herbs and spices for export supply" priority sizes="100vw" className="object-cover object-[58%_50%] sm:object-[55%_50%] lg:object-[50%_50%]" />
        <div className="absolute inset-0 bg-gradient-to-r from-[#061711]/72 via-[#102F23]/40 to-[#071B14]/10" />
        <div className="absolute inset-0 bg-gradient-to-t from-black/10 via-transparent to-black/[0.04]" />
        <GoldenParticles />
        <div className="relative z-10 flex items-center px-6 pb-20 pt-32 sm:px-8 sm:pb-24 sm:pt-36 lg:px-12 lg:pb-28 lg:pt-40">
          <div className="w-full max-w-[820px] lg:max-w-[860px] xl:max-w-[900px]">
            <StaggerItem delay={0}><div className="flex items-center gap-4"><span className="h-px w-14 bg-[#C9A962]" /><p className="text-[10px] font-bold uppercase tracking-[0.38em] text-[#E4C878] sm:text-xs">Exporting from India to Austria</p></div></StaggerItem>
            <StaggerItem delay={100}><h1 className="mt-5 font-[family-name:var(--font-playfair)] text-4xl font-medium leading-[1] tracking-[-0.04em] text-[#F5F0E6] sm:text-5xl lg:text-6xl xl:text-[66px]">Natural Products Exporter to Austria<span className="mt-2 block bg-gradient-to-r from-[#F5F0E6] via-[#E4C878] to-[#C9A962] bg-clip-text text-transparent">Henna, Indigo, Herbs &amp; Spices</span></h1></StaggerItem>
            <StaggerItem delay={200}><p className="mt-5 max-w-[730px] text-[16px] font-light leading-7 text-[#F5F0E6]/82 sm:text-[17px] sm:leading-8">Shivesh International supports Austrian importers, distributors, wholesalers, cosmetic companies, salon suppliers, herbal-product businesses, food-sector buyers and private-label brands with export-ready natural henna, indigo, botanical hair colors, Ayurvedic herbs and Indian spices from India.</p></StaggerItem>
            <StaggerItem delay={300}><div className="mt-7 flex flex-wrap gap-4"><Link href="/contact" className="inline-flex items-center gap-4 border border-[#C9A962] bg-[#C9A962] px-7 py-4 text-[10px] font-bold uppercase tracking-[0.2em] text-[#102F23] transition-all hover:-translate-y-1 hover:bg-[#E4C878] focus-visible:outline focus-visible:outline-2 focus-visible:outline-offset-4 focus-visible:outline-[#E4C878]">Send Austria Inquiry <span>→</span></Link><a href="#products" className="inline-flex items-center gap-4 border border-[#F5F0E6]/30 bg-[#102F23]/40 px-7 py-4 text-[10px] font-bold uppercase tracking-[0.2em] text-[#F5F0E6] backdrop-blur-lg transition-all hover:border-[#C9A962] hover:text-[#E4C878] focus-visible:outline focus-visible:outline-2 focus-visible:outline-offset-4 focus-visible:outline-[#E4C878]">Explore Products <span>↓</span></a></div></StaggerItem>
            <StaggerItem delay={400}><div className="mt-10 grid max-w-[740px] grid-cols-2 gap-3 lg:grid-cols-4">{[["200 kg", "MOQ Per Product"], ["Bulk", "Wholesale Supply"], ["OEM", "Private Label"], ["Austria", "Buyer Enquiries"]].map(([value, label]) => <div key={label} className="border border-white/15 bg-black/20 px-4 py-4 backdrop-blur-md"><p className="font-[family-name:var(--font-playfair)] text-xl font-semibold text-[#E4C878]">{value}</p><p className="mt-2 text-[9px] font-bold uppercase tracking-[0.22em] text-[#F5F0E6]/55">{label}</p></div>)}</div></StaggerItem>
          </div>
        </div>
      </section>

      <section className="px-6 py-24 sm:px-8 lg:px-12 lg:py-32"><RevealOnScroll><div className="mx-auto max-w-[1120px]"><p className="text-[10px] font-bold uppercase tracking-[0.4em] text-[#9F7F36]">India–Austria Natural Product Sourcing</p><h2 className="mt-6 font-[family-name:var(--font-playfair)] text-[clamp(2.5rem,4.6vw,4.6rem)] font-semibold leading-[1.04]">One Indian Export Partner <span className="block text-[#A97B22]">for Austrian Natural-Product Buyers</span></h2><p className="mt-7 text-[16px] font-light leading-8 text-[#4C5F54]">Austrian importers, distributors and wholesalers can coordinate multiple product categories with one Indian export team. Shivesh International supports cosmetic and personal-care companies, natural hair-care brands, salon suppliers, herbal and wellness businesses, food ingredient buyers, spice companies, private-label operators and e-commerce brands seeking structured sourcing from India.</p><p className="mt-5 text-[15px] font-light leading-8 text-[#4C5F54]">Commercial enquiries may be associated with buyer and distribution activity in Vienna, Graz, Salzburg, Linz and Innsbruck. Product availability, specifications, packaging, documentation and shipment preparation are reviewed according to the buyer’s selected category and agreed order requirements. Market references identify potential buyer locations and do not imply that Shivesh International maintains a local office or warehouse in Austria.</p></div></RevealOnScroll></section>

      <section id="products" className="scroll-mt-24 bg-[#EDE5D7] px-6 py-24 sm:px-8 lg:px-12 lg:py-32"><RevealOnScroll><div className="mx-auto max-w-[1500px]"><div className="mx-auto max-w-[920px] text-center"><p className="text-[10px] font-bold uppercase tracking-[0.4em] text-[#9F7F36]">Six Commercial Categories</p><h2 className="mt-6 font-[family-name:var(--font-playfair)] text-[clamp(2.5rem,4.8vw,4.8rem)] font-semibold leading-[1.04]">Natural Products <span className="block text-[#A97B22]">for Austrian Importers and Brands</span></h2><p className="mx-auto mt-7 max-w-[820px] text-[16px] font-light leading-8 text-[#4C5F54]">A focused portfolio for Austrian cosmetic brands, professional hair-care channels, herbal businesses, wholesalers, food companies and private-label buyers.</p></div><div className="mt-14 grid auto-rows-fr gap-5 sm:grid-cols-2 lg:grid-cols-3">{products.map((product, index) => <StaggerItem key={product.title} delay={(index % 3) * 90}><article className="group flex h-full min-h-[300px] flex-col border border-[#173B2A]/12 bg-[#FBF8F1] p-7 shadow-[0_18px_45px_rgba(20,50,38,0.07)] transition-all hover:-translate-y-2 hover:border-[#C9A962]/70 sm:p-8"><span className="font-[family-name:var(--font-playfair)] text-4xl font-semibold text-[#C9A962]/60">{String(index + 1).padStart(2, "0")}</span><h3 className="mt-6 font-[family-name:var(--font-playfair)] text-[27px] font-semibold leading-tight">{product.title}</h3><p className="mt-5 flex-1 text-[14px] font-light leading-7 text-[#4C5F54]">{product.text}</p><Link href={product.href} className="mt-7 inline-flex items-center gap-3 text-[10px] font-bold uppercase tracking-[0.2em] text-[#A97B22] focus-visible:outline focus-visible:outline-2 focus-visible:outline-offset-4 focus-visible:outline-[#A97B22]">Explore {product.title} <span className="transition-transform group-hover:translate-x-2">→</span></Link></article></StaggerItem>)}</div></div></RevealOnScroll></section>

      <section className="bg-[#0B3325] px-6 py-24 text-[#F5F0E6] sm:px-8 lg:px-12 lg:py-32"><RevealOnScroll><div className="mx-auto max-w-[1500px]"><div className="mx-auto max-w-[920px] text-center"><p className="text-[10px] font-bold uppercase tracking-[0.4em] text-[#E4C878]">Austrian Commercial Channels</p><h2 className="mt-6 font-[family-name:var(--font-playfair)] text-[clamp(2.5rem,4.7vw,4.7rem)] font-semibold leading-[1.04]">Who We Support in the Austrian Market</h2></div><div className="mt-14 grid auto-rows-fr gap-5 sm:grid-cols-2 lg:grid-cols-4">{buyerProfiles.map(([title, text]) => <article key={title} className="h-full border border-[#C9A962]/25 bg-[#071B14]/55 p-7"><h3 className="font-[family-name:var(--font-playfair)] text-2xl font-semibold text-[#E4C878]">{title}</h3><p className="mt-4 text-[14px] font-light leading-7 text-[#F5F0E6]/65">{text}</p></article>)}</div></div></RevealOnScroll></section>

      <section className="px-6 py-24 sm:px-8 lg:px-12 lg:py-32"><RevealOnScroll><div className="mx-auto max-w-[1500px]"><div className="grid gap-14 lg:grid-cols-[0.7fr_1.3fr] lg:gap-20"><div><p className="text-[10px] font-bold uppercase tracking-[0.4em] text-[#9F7F36]">Buyer Review Information</p><h2 className="mt-6 font-[family-name:var(--font-playfair)] text-[clamp(2.5rem,4.5vw,4.5rem)] font-semibold leading-[1.04]">Export Documentation <span className="block text-[#A97B22]">for Austrian Buyers</span></h2><p className="mt-7 text-[15px] font-light leading-8 text-[#4C5F54]">Documents depend on the selected product and availability. Available commercial, product, packaging and shipment information can be coordinated for buyer and destination review without implying automatic Austrian or European Union compliance.</p></div><div className="grid auto-rows-fr gap-5 sm:grid-cols-2">{documentationItems.map(([title, text]) => <article key={title} className="h-full border border-[#173B2A]/12 bg-[#FBF8F1] p-7"><span className="block h-px w-12 bg-[#C9A962]" /><h3 className="mt-5 font-[family-name:var(--font-playfair)] text-2xl font-semibold">{title}</h3><p className="mt-4 text-[14px] font-light leading-7 text-[#4C5F54]">{text}</p></article>)}</div></div></div></RevealOnScroll></section>

      <section className="bg-[#EDE5D7] px-6 py-24 sm:px-8 lg:px-12 lg:py-32"><RevealOnScroll><div className="mx-auto grid max-w-[1500px] gap-14 lg:grid-cols-[1.05fr_0.95fr] lg:gap-20"><div><p className="text-[10px] font-bold uppercase tracking-[0.4em] text-[#9F7F36]">Buyer-Brand Formats</p><h2 className="mt-6 font-[family-name:var(--font-playfair)] text-[clamp(2.5rem,4.6vw,4.6rem)] font-semibold leading-[1.04]">Packaging &amp; Private-Label Solutions <span className="block text-[#A97B22]">for Austrian Buyers</span></h2><p className="mt-7 text-[15px] font-light leading-8 text-[#4C5F54]">Selected programmes can include custom brand names, printed pouches, printed boxes, buyer-supplied artwork coordination, barcodes, label-layout support, multilingual packaging and German-language label artwork coordination. Retail, salon, professional and bulk formats, including OEM or private-label supply, remain subject to agreed requirements and technical feasibility.</p><p className="mt-5 text-[14px] font-light leading-7 text-[#4C5F54]">Retail options may include 100 g, 200 g, 500 g and 1 kg pouches. Bulk formats may include 20 kg and 25 kg double-layer vacuum bags. Final product labels, language requirements, claims, product classification and destination-market compliance remain subject to buyer review and the applicable product category.</p></div><div><figure className="relative aspect-[3/2] overflow-hidden rounded-sm border border-[#C9A962]/35 bg-[linear-gradient(135deg,#0b3325,#496d58)] shadow-[0_28px_70px_rgba(20,50,38,0.18)]"><OptionalImage src="/images/export/austria/austria-buyer-partnership.png" alt="Private-label packaging and natural-product formats prepared for Austrian buyers" className="object-cover object-center" /></figure><div className="mt-5 grid gap-5 sm:grid-cols-2"><article className="border border-[#C9A962]/35 bg-[#FBF8F1] p-7"><h3 className="font-[family-name:var(--font-playfair)] text-2xl font-semibold">Retail Packaging</h3><p className="mt-4 text-sm leading-7 text-[#4C5F54]">100 g · 200 g · 500 g · 1 kg pouches</p></article><article className="border border-[#C9A962]/35 bg-[#FBF8F1] p-7"><h3 className="font-[family-name:var(--font-playfair)] text-2xl font-semibold">Bulk Packaging</h3><p className="mt-4 text-sm leading-7 text-[#4C5F54]">20 kg and 25 kg double-layer vacuum bags</p></article><article className="border border-[#C9A962] bg-[#173B2A] p-7 text-[#F5F0E6] sm:col-span-2"><p className="text-[10px] font-bold uppercase tracking-[0.3em] text-[#E4C878]">Minimum Order Quantity</p><p className="mt-4 font-[family-name:var(--font-playfair)] text-4xl font-semibold">200 kg per product</p></article></div></div></div></RevealOnScroll></section>

      <section className="bg-[#09271D] px-6 py-24 text-[#F5F0E6] sm:px-8 lg:px-12 lg:py-32"><RevealOnScroll><div className="mx-auto max-w-[1500px]"><div className="grid items-center gap-14 lg:grid-cols-[1.05fr_0.95fr] lg:gap-20"><div><p className="text-[10px] font-bold uppercase tracking-[0.4em] text-[#E4C878]">Shipment and Document Support</p><h2 className="mt-6 font-[family-name:var(--font-playfair)] text-[clamp(2.5rem,4.8vw,4.8rem)] font-semibold leading-[1.04]">India-to-Austria Export Coordination</h2><p className="mt-7 text-[16px] font-light leading-8 text-[#F5F0E6]/68">Coordination can cover commercial invoices, packing lists, certificates of origin, product specifications, COA and available quality documents, shipping documentation, buyer-appointed freight forwarders, export cartons, pallets and shipment information sharing.</p><p className="mt-5 text-[15px] font-light leading-8 text-[#F5F0E6]/62">Because Austria is landlocked, buyer-selected arrangements may use sea freight through European gateways such as Hamburg, Bremerhaven, Rotterdam, Koper or Trieste, followed by road or rail transport to Austria. Air-cargo coordination may be discussed for Vienna or another buyer-selected arrangement. No gateway, route, transit time or customs clearance is guaranteed. Documentation and product information can be coordinated according to the product category, destination, buyer instructions and agreed order requirements.</p></div><figure className="relative aspect-[3/2] overflow-hidden rounded-sm border border-[#C9A962]/35 bg-[linear-gradient(135deg,#071b14,#496d58)] shadow-[0_28px_70px_rgba(0,0,0,0.25)]"><OptionalImage src="/images/export/austria/india-to-austria-export-coordination.png" alt="India-to-Austria export coordination for natural products, documentation and freight" className="object-cover object-center" /></figure></div><aside className="mt-12 border border-[#C9A962]/35 bg-[#071B14]/60 p-7 text-[14px] font-light leading-7 text-[#F5F0E6]/65">The Austrian importer or buyer remains responsible for confirming product classification, labelling, registration, customs procedures, taxes and applicable Austrian and European Union destination-market requirements. No automatic compliance, registration or customs-clearance claim is made.</aside></div></RevealOnScroll></section>

      <section className="bg-[#EDE5D7] px-6 py-24 sm:px-8 lg:px-12 lg:py-32"><RevealOnScroll><div className="mx-auto max-w-[1500px]"><div className="mx-auto max-w-[920px] text-center"><p className="text-[10px] font-bold uppercase tracking-[0.4em] text-[#9F7F36]">Five Commercial Steps</p><h2 className="mt-6 font-[family-name:var(--font-playfair)] text-[clamp(2.5rem,4.7vw,4.7rem)] font-semibold leading-[1.04]">Austria Export Supply Process</h2></div><div className="mt-14 grid auto-rows-fr gap-5 sm:grid-cols-2 lg:grid-cols-3">{processSteps.map(([title, text]) => <article key={title} className="h-full border border-[#173B2A]/12 bg-[#FBF8F1] p-7 sm:p-8"><span className="block h-px w-12 bg-[#C9A962]" /><h3 className="mt-6 font-[family-name:var(--font-playfair)] text-2xl font-semibold">{title}</h3><p className="mt-4 text-[14px] font-light leading-7 text-[#4C5F54]">{text}</p></article>)}</div></div></RevealOnScroll></section>

      <section className="px-6 py-24 sm:px-8 lg:px-12 lg:py-32"><RevealOnScroll><div className="mx-auto max-w-[1120px]"><p className="text-[10px] font-bold uppercase tracking-[0.4em] text-[#9F7F36]">Austria Buyer Locations</p><h2 className="mt-6 font-[family-name:var(--font-playfair)] text-[clamp(2.5rem,4.6vw,4.6rem)] font-semibold leading-[1.04]">Natural-Product Supply for Buyers Across Austria</h2><p className="mt-7 text-[15px] leading-7 text-[#4C5F54]">These market references identify potential enquiry and distribution locations; they do not represent local Shivesh International offices, warehouses or guaranteed active supply relationships.</p><div className="mt-10 grid auto-rows-fr gap-5 sm:grid-cols-2 lg:grid-cols-4">{marketLocations.map(([location, text]) => <article key={location} className="h-full border border-[#C9A962]/35 bg-[#FBF8F1] p-6"><h3 className="font-[family-name:var(--font-playfair)] text-2xl font-semibold text-[#A97B22]">{location}</h3><p className="mt-4 text-[14px] font-light leading-7 text-[#4C5F54]">{text}</p></article>)}</div></div></RevealOnScroll></section>

      <section className="bg-[#EDE5D7] px-6 py-24 sm:px-8 lg:px-12 lg:py-32"><RevealOnScroll><div className="mx-auto max-w-[1120px]"><div className="text-center"><p className="text-[10px] font-bold uppercase tracking-[0.4em] text-[#9F7F36]">Austrian Buyer Questions</p><h2 className="mt-6 font-[family-name:var(--font-playfair)] text-[clamp(2.4rem,4.4vw,4.4rem)] font-semibold">Austria Export Supply FAQ</h2></div><div className="mt-12 divide-y divide-[#173B2A]/15 border-y border-[#173B2A]/15">{faqs.map((faq) => <article key={faq.question} className="grid gap-4 py-7 md:grid-cols-[0.8fr_1.2fr] md:gap-10"><h3 className="font-[family-name:var(--font-playfair)] text-xl font-semibold">{faq.question}</h3><p className="text-[14px] font-light leading-7 text-[#4C5F54]">{faq.answer}</p></article>)}</div></div></RevealOnScroll></section>

      <section className="relative overflow-hidden bg-[#071B14] px-6 py-24 text-center text-[#F5F0E6] sm:px-8 lg:px-12 lg:py-28"><GoldenParticles /><RevealOnScroll><div className="relative mx-auto max-w-[1000px]"><p className="text-[10px] font-bold uppercase tracking-[0.4em] text-[#E4C878]">Austria Buyer Enquiries</p><h2 className="mt-6 font-[family-name:var(--font-playfair)] text-[clamp(2.5rem,4.8vw,4.8rem)] font-semibold leading-[1.04]">Discuss Your Austria Product Requirement</h2><p className="mx-auto mt-7 max-w-[760px] text-[16px] font-light leading-8 text-[#F5F0E6]/65">Austrian importers, distributors, wholesalers and private-label buyers can share the product name, required quantity, packaging format, destination and intended business application with our export team.</p><div className="mt-9 flex flex-wrap justify-center gap-4"><Link href="/contact" className="inline-flex items-center gap-4 border border-[#C9A962] bg-[#C9A962] px-8 py-4 text-[10px] font-bold uppercase tracking-[0.22em] text-[#102F23] transition-all hover:-translate-y-1 hover:bg-[#E4C878]">Send Your Austria Requirement <span>→</span></Link><Link href="/export/europe" className="inline-flex items-center gap-4 border border-[#F5F0E6]/30 px-8 py-4 text-[10px] font-bold uppercase tracking-[0.22em] text-[#F5F0E6] transition-all hover:border-[#C9A962] hover:text-[#E4C878]">Explore European Markets <span>→</span></Link></div><div className="mt-9 flex flex-wrap justify-center gap-x-6 gap-y-3 text-[10px] font-bold uppercase tracking-[0.16em] text-[#F5F0E6]/45"><Link href="/export">Global Export Information</Link><Link href="/export/france">France Export Market</Link><Link href="/export/germany">Germany Export Market</Link><Link href="/export/italy">Italy Export Market</Link><Link href="/export/spain">Spain Export Market</Link><Link href="/resources">Buyer Resources</Link><Link href="/certifications">Certifications</Link><Link href="/infrastructure">Infrastructure</Link><Link href="/about">About Shivesh International</Link><Link href="/export/austria">Austria Export Page</Link></div></div></RevealOnScroll></section>

      <FooterSection /><FloatingContactButtons /><MagneticButtons /><PremiumCursor />
    </main>
  );
}
