import type { Metadata } from "next";
import Image from "next/image";
import Link from "next/link";
import FloatingContactButtons from "@/app/components/FloatingContactButtons";
import GoldenParticles from "@/app/components/GoldenParticles";
import MagneticButtons from "@/app/components/MagneticButtons";
import Navbar from "@/app/components/Navbar";
import PremiumCursor from "@/app/components/PremiumCursor";
import RevealOnScroll from "@/app/components/RevealOnScroll";
import { usaLanguageAlternates } from "@/app/lib/i18n";
import FooterSection from "@/sections/FooterSection";

const canonicalUrl="https://shiveshinternational.com/es/export/usa";
const hero="/images/export/usa/usa-henna-natural-products-export-hero-final-v3.png";
const packagingImage="/images/export/usa/usa-private-label-natural-products-packaging-final-v3.png";
const shippingImage="/images/export/usa/india-to-usa-export-shipping-coordination-final-v3.png";
export const metadata:Metadata={title:{absolute:"Exportador de henna y productos naturales a EE. UU. | Shivesh International"},description:"Henna, índigo, coloración capilar botánica, plantas ayurvédicas y especias de la India para importadores, distribuidores y marcas privadas de Estados Unidos. MOQ de 200 kg por artículo.",keywords:["exportador de henna a Estados Unidos","proveedor de índigo natural EE. UU.","productos naturales al por mayor Estados Unidos","marca privada de henna EE. UU.","fabricante OEM de productos naturales","exportación de India a Estados Unidos"],alternates:{canonical:canonicalUrl,languages:usaLanguageAlternates},openGraph:{title:"Exportador de henna y productos naturales a Estados Unidos",description:"Suministro a granel, mayorista, OEM y de marca privada de henna, índigo, coloración botánica, plantas ayurvédicas y especias de la India.",url:canonicalUrl,type:"website",locale:"es_US",siteName:"Shivesh International",images:[{url:hero,width:1536,height:1024,alt:"Henna y productos naturales de la India para compradores profesionales de Estados Unidos"}]},twitter:{card:"summary_large_image",title:"Exportador de henna y productos naturales a Estados Unidos",description:"Suministro indio a granel, mayorista, OEM y de marca privada para compradores profesionales de Estados Unidos.",images:[hero]},robots:{index:true,follow:true,googleBot:{index:true,follow:true,"max-image-preview":"large","max-snippet":-1,"max-video-preview":-1}}};
const products=[
 ["Henna natural en polvo","Henna natural de origen Sojat para suministro a granel, mayorista y de marca privada.","/products/natural-henna-powder"],
 ["Índigo natural en polvo","Indigofera tinctoria con triple tamizado para coloración capilar botánica, salones y marcas privadas.","/products/natural-indigo-powder"],
 ["Coloraciones capilares naturales con henna","Colección de coloraciones botánicas en polvo para canales profesionales, mayoristas y marcas.","/products/natural-henna-hair-colors"],
 ["Coloraciones capilares a base de henna","Opciones profesionales en polvo para distribuidores, salones y marcas cosméticas.","/products/henna-based-hair-colors"],
 ["Plantas ayurvédicas de la India","Plantas y polvos herbales para empresas de bienestar, cuidado personal, ingredientes y marca privada.","/products/ayurvedic-indian-herbs"],
 ["Especias de la India","Especias enteras y molidas seleccionadas para requisitos mayoristas, minoristas y de marca privada elegibles.","/products/indian-spices"],
] as const;
const advantages=[["Proveedor indio con experiencia","Más de 30 años de experiencia en productos naturales, abastecimiento, procesamiento y requisitos comerciales."],["Procesamiento controlado","Manipulación, molienda, tamizado, mezclado, controles de calidad y envasado según la categoría."],["Suministro a granel y mayorista","Apoyo para importadores, distribuidores, mayoristas, salones y empresas de cosmética y bienestar."],["OEM y marca privada","Coordinación de productos, tamaños, diseños, etiquetas, presentación minorista y cajas de exportación."],["Documentación de exportación","Coordinación profesional de documentos comerciales, datos de producto, embalaje y envío."],["Comunicación centrada en el comprador","Coordinación clara de productos, cantidades, muestras viables, envases y suministro recurrente."]] as const;
const packaging=[["OEM","Apoyo para productos OEM"],["PL","Marca privada"],["PK","Coordinación de envases"],["LB","Diseños de etiqueta del comprador"],["BX","Cajas y bolsas minoristas"],["CT","Cajas para exportación a granel"]] as const;
const steps=[["Revisión de producto y cantidad","Revisamos producto, grado, cantidad, uso previsto y pedido mínimo."],["Cotización y condiciones comerciales","Se coordinan precio, envase, producción, pago y condiciones de envío aplicables."],["Muestra y especificaciones","Las muestras comercialmente viables y las especificaciones disponibles se revisan cuando corresponde."],["Producción y control de calidad","La producción, el procesamiento, los controles y el envasado siguen el pedido confirmado."],["Documentación y embalaje","Se preparan los documentos comerciales aplicables y el embalaje de exportación acordado."],["Coordinación del envío","Transporte, destino, Incoterms y responsabilidades logísticas se confirman con el comprador."]] as const;
const buyers=[["Importadores","Empresas que adquieren productos botánicos, cosméticos, de bienestar y alimentarios de la India."],["Distribuidores","Distribuidores regionales y nacionales de cuidado capilar natural, productos herbales, bienestar o especias."],["Mayoristas","Compradores que requieren cantidades a granel, envases mayoristas o productos para redistribución."],["Marcas cosméticas","Empresas de belleza y cuidado capilar que buscan henna, índigo y coloración botánica en polvo."],["Marcas para salones","Grupos de salones y empresas profesionales interesados en productos seleccionados de coloración botánica."],["Empresas de bienestar","Empresas herbales y de cuidado personal que buscan plantas ayurvédicas e ingredientes botánicos."],["Empresas minoristas","Marcas minoristas y de comercio electrónico que estudian envases de consumo y presentación de marca."],["Compradores de marca privada","Empresas cualificadas que requieren marca, envase y gamas de productos coordinadas."]] as const;
const faqs=[
 {question:"¿Qué productos naturales exportan de la India a Estados Unidos?",answer:"Shivesh International suministra henna natural en polvo, índigo natural en polvo, coloraciones capilares naturales con henna, coloraciones a base de henna, plantas ayurvédicas de la India y especias seleccionadas a compradores comerciales cualificados de Estados Unidos."},
 {question:"¿Cuál es la cantidad mínima de pedido para compradores de Estados Unidos?",answer:"La cantidad mínima es de 200 kg por artículo. La cantidad comercial final también puede depender del producto seleccionado, el formato de envase y los requisitos de marca privada."},
 {question:"¿Ofrecen productos OEM y de marca privada para marcas de Estados Unidos?",answer:"Sí. Los compradores cualificados pueden consultar apoyo OEM y de marca privada para productos seleccionados, incluida la coordinación de marca, etiquetas, bolsas, cajas minoristas, envases profesionales y cajas de exportación."},
 {question:"¿Pueden los compradores pedir envases a granel y mayoristas?",answer:"Sí. Pueden estudiarse opciones de envasado a granel, mayorista, profesional y minorista seleccionado según la categoría, cantidad y viabilidad del envase."},
 {question:"¿Se pueden solicitar muestras antes de un pedido a granel?",answer:"Las muestras pueden revisarse cuando sean comercialmente adecuadas y estén disponibles. La cantidad, disponibilidad, coste de mensajería y cargos aplicables se confirman antes del envío."},
 {question:"¿Coordinan envíos desde la India a Estados Unidos?",answer:"Coordinamos el embalaje de exportación aplicable, la documentación comercial y la preparación del envío. El transporte, destino, Incoterms y responsabilidad logística se confirman con el comprador antes de finalizar el pedido."},
 {question:"¿Todos los productos están aprobados automáticamente para venderse en Estados Unidos?",answer:"No se realiza ninguna afirmación de aprobación universal. Los requisitos varían según producto, uso previsto, envase y destino. El importador o comprador debe confirmar los requisitos aduaneros, federales, estatales, de etiquetado y específicos del producto."},
 {question:"¿Cómo puede un comprador solicitar una cotización de exportación?",answer:"Puede utilizar el formulario de contacto e indicar producto, grado, cantidad, formato de envase, requisitos de marca privada y destino. Nuestro equipo de exportación revisará la consulta antes de facilitar información comercial."},
] as const;
const structuredData={"@context":"https://schema.org","@graph":[{"@type":"WebPage","@id":`${canonicalUrl}#webpage`,url:canonicalUrl,name:"Exportador de henna y productos naturales a Estados Unidos",description:"Suministro desde la India de henna, índigo, coloración botánica, plantas ayurvédicas y especias para Estados Unidos.",isPartOf:{"@id":"https://shiveshinternational.com/#website"},about:{"@id":"https://shiveshinternational.com/#organization"},breadcrumb:{"@id":`${canonicalUrl}#breadcrumb`},primaryImageOfPage:{"@type":"ImageObject",url:`https://shiveshinternational.com${hero}`,width:1536,height:1024},inLanguage:"es-US"},{"@type":"Service","@id":`${canonicalUrl}#service`,name:"Suministro de productos naturales a Estados Unidos",serviceType:"Suministro a granel, mayorista, OEM y de marca privada",description:"Suministro desde la India para compradores profesionales de Estados Unidos.",url:canonicalUrl,provider:{"@id":"https://shiveshinternational.com/#organization"},areaServed:{"@type":"Country",name:"Estados Unidos",sameAs:"https://www.wikidata.org/wiki/Q30"},audience:{"@type":"BusinessAudience",audienceType:"Compradores profesionales de Estados Unidos"},category:products.map(([name])=>name),termsOfService:"Cantidad mínima de pedido: 200 kg por artículo. La disponibilidad, el envase y las condiciones comerciales se confirman según los requisitos del comprador."},{"@type":"BreadcrumbList","@id":`${canonicalUrl}#breadcrumb`,itemListElement:[{"@type":"ListItem",position:1,name:"Inicio",item:"https://shiveshinternational.com/"},{"@type":"ListItem",position:2,name:"Exportación",item:"https://shiveshinternational.com/export"},{"@type":"ListItem",position:3,name:"Exportación a Estados Unidos",item:canonicalUrl}]},{"@type":"ItemList","@id":`${canonicalUrl}#products`,name:"Productos naturales suministrados a Estados Unidos",numberOfItems:products.length,itemListElement:products.map(([name,,path],index)=>({"@type":"ListItem",position:index+1,name,url:`https://shiveshinternational.com${path}`}))}]};
const faqStructuredData={"@context":"https://schema.org","@type":"FAQPage","@id":`${canonicalUrl}#faq`,mainEntity:faqs.map(faq=>({"@type":"Question",name:faq.question,acceptedAnswer:{"@type":"Answer",text:faq.answer}}))};
const Cards=({items,dark=false,columns="lg:grid-cols-3"}:{items:readonly (readonly [string,string])[];dark?:boolean;columns?:string})=><div className={`mt-12 grid auto-rows-fr gap-5 sm:grid-cols-2 ${columns}`}>{items.map(([title,text],i)=><article key={title} className={`h-full min-h-[220px] border p-7 ${dark?"border-[#C9A962]/20 bg-[#0D3828] text-[#F5F0E6]":"border-[#173B2A]/12 bg-[#FBF8F1]"}`}><span className="text-[10px] text-[#C9A962]">{String(i+1).padStart(2,"0")}</span><h3 className="mt-6 text-2xl font-semibold">{title}</h3><p className={`mt-4 text-sm leading-7 ${dark?"text-white/60":"text-[#4C5F54]"}`}>{text}</p></article>)}</div>;
export default function USAExportPageSpanish(){return <main className="min-h-screen overflow-x-hidden bg-[#F5F0E6] text-[#173B2A]">
 <script type="application/ld+json" dangerouslySetInnerHTML={{__html:JSON.stringify(structuredData).replace(/</g,"\\u003c")}}/><script type="application/ld+json" dangerouslySetInnerHTML={{__html:JSON.stringify(faqStructuredData).replace(/</g,"\\u003c")}}/><Navbar/>
 <section className="relative isolate min-h-[720px] overflow-hidden bg-[#071B14] lg:aspect-[160/63] lg:min-h-0"><Image src={hero} alt="Henna, índigo, plantas ayurvédicas y especias de la India para compradores de Estados Unidos" fill priority sizes="100vw" className="object-cover object-center"/><div className="absolute inset-0 bg-gradient-to-r from-[#061711]/80 via-[#102F23]/45 to-[#071B14]/10"/><GoldenParticles/><div className="relative z-10 flex min-h-[78vh] items-center px-6 pb-16 pt-28 sm:px-8 lg:px-12"><div className="max-w-[800px]"><p className="text-xs font-bold uppercase tracking-[0.38em] text-[#E4C878]">De la India a Estados Unidos</p><h1 className="mt-6 text-[clamp(2.8rem,5.4vw,5.4rem)] font-medium leading-[1.02] text-[#F5F0E6]">Henna y productos naturales <span className="block text-[#E4C878]">para Estados Unidos</span></h1><p className="mt-7 max-w-[700px] text-[17px] leading-8 text-white/80">Shivesh International es un fabricante, exportador y proveedor indio de henna natural, índigo, coloración capilar botánica, plantas ayurvédicas y especias de la India para importadores, distribuidores, mayoristas y compradores de marca privada de Estados Unidos.</p><div className="mt-9 flex flex-wrap gap-4"><a href="#productos-usa" className="bg-[#C9A962] px-7 py-4 text-[10px] font-bold uppercase text-[#102F23]">Ver la oferta</a><Link href="/contact" className="border border-white/30 px-7 py-4 text-[10px] font-bold uppercase text-white">Solicitar cotización</Link></div><div className="mt-10 grid grid-cols-2 gap-3 lg:grid-cols-4">{[["200 kg","MOQ por artículo"],["A granel","Venta mayorista"],["OEM","Marca privada"],["EE. UU.","Apoyo al comprador"]].map(([v,l])=><div key={l} className="border border-white/15 bg-black/20 p-4"><p className="text-xl font-semibold text-[#E4C878]">{v}</p><p className="mt-2 text-[9px] uppercase text-white/55">{l}</p></div>)}</div></div></div></section>
 <section id="productos-usa" className="px-6 py-24 lg:px-12 lg:py-32"><RevealOnScroll><div className="mx-auto max-w-[1500px] text-center"><p className="text-[10px] uppercase tracking-[0.4em] text-[#9F7F36]">Productos naturales para Estados Unidos</p><h2 className="mt-6 text-[clamp(2.5rem,4.8vw,4.8rem)] font-semibold">Productos de la India <span className="block text-[#A97B22]">para compradores profesionales</span></h2><div className="mt-14 grid gap-5 text-left sm:grid-cols-2 lg:grid-cols-3">{products.map(([title,text,href],i)=><article key={title} className="flex min-h-[280px] flex-col border border-[#173B2A]/12 bg-[#FBF8F1] p-7"><span className="text-[#A97B22]">{String(i+1).padStart(2,"0")}</span><h3 className="mt-6 text-2xl font-semibold">{title}</h3><p className="mt-4 flex-1 text-sm leading-7 text-[#4C5F54]">{text}</p><Link href={href} className="mt-6 text-[10px] font-bold uppercase text-[#8B6A1E]">Ver detalles →</Link></article>)}</div><aside className="mx-auto mt-10 max-w-[900px] bg-[#12382A] p-6 text-sm leading-7 text-white/70"><strong className="text-[#E4C878]">Cantidad mínima: 200 kg por artículo.</strong> Producto, envase, etiquetado y envío se confirman según los requisitos comerciales.</aside></div></RevealOnScroll></section>
 <section className="bg-[#09271D] px-6 py-24 text-[#F5F0E6] lg:px-12 lg:py-32"><RevealOnScroll><div className="mx-auto max-w-[1500px] text-center"><p className="text-[10px] uppercase tracking-[0.4em] text-[#E4C878]">Ventajas para compradores de Estados Unidos</p><h2 className="mt-6 text-[clamp(2.5rem,4.8vw,4.8rem)] font-semibold">Por qué elegir <span className="block text-[#E4C878]">Shivesh International</span></h2><Cards items={advantages} dark/><Link href="/contact" className="mt-10 inline-flex bg-[#C9A962] px-7 py-4 text-[10px] font-bold uppercase text-[#102F23]">Consultar un requisito →</Link></div></RevealOnScroll></section>
 <section className="bg-[#EDE5D7] px-6 py-24 lg:px-12 lg:py-32"><RevealOnScroll><div className="mx-auto grid max-w-[1500px] gap-14 lg:grid-cols-2 lg:items-center"><figure className="relative aspect-[3/2] overflow-hidden border border-[#C9A962]/35"><Image src={packagingImage} alt="Envases de marca privada para productos naturales destinados a compradores de Estados Unidos" fill sizes="(min-width:1024px) 48vw, 100vw" className="object-cover"/></figure><div><p className="text-[10px] uppercase tracking-[0.4em] text-[#9F7F36]">Soluciones para marcas del comprador</p><h2 className="mt-6 text-[clamp(2.5rem,4.5vw,4.6rem)] font-semibold">OEM, marca privada y envases <span className="block text-[#A97B22]">para Estados Unidos</span></h2><p className="mt-7 text-[16px] leading-8 text-[#4C5F54]">Los compradores cualificados pueden consultar suministro a granel, envases mayoristas y profesionales, fabricación OEM y presentación de marca privada. Las opciones dependen del producto, cantidad, diseño y viabilidad técnica.</p><Cards items={packaging} columns="lg:grid-cols-2"/><aside className="mt-8 bg-[#173B2A] p-6 text-sm leading-7 text-white/70"><strong className="text-[#E4C878]">MOQ: 200 kg por artículo.</strong> Tamaños, bolsas, impresión, etiquetas y cajas se revisan antes de la confirmación.</aside><Link href="/contact" className="mt-8 inline-flex bg-[#C9A962] px-7 py-4 text-[10px] font-bold uppercase text-[#102F23]">Solicitar información →</Link></div></div></RevealOnScroll></section>
 <section className="px-6 py-24 lg:px-12 lg:py-32"><RevealOnScroll><div className="mx-auto grid max-w-[1500px] gap-14 lg:grid-cols-2"><div><p className="text-[10px] uppercase tracking-[0.4em] text-[#9F7F36]">Coordinación de la India a Estados Unidos</p><h2 className="mt-6 text-[clamp(2.5rem,4.5vw,4.6rem)] font-semibold">Proceso estructurado <span className="block text-[#A97B22]">de exportación</span></h2><p className="mt-7 text-[16px] leading-8 text-[#4C5F54]">Cada consulta se revisa según producto, cantidad, envase, destino y documentación antes de confirmar el pedido y planificar el envío.</p><Cards items={steps} columns="lg:grid-cols-2"/></div><div><figure className="relative aspect-[3/2] overflow-hidden border border-[#C9A962]/35"><Image src={shippingImage} alt="Coordinación documental y logística para exportar productos naturales de la India a Estados Unidos" fill sizes="(min-width:1024px) 48vw, 100vw" className="object-cover"/></figure><aside className="mt-8 bg-[#173B2A] p-7 text-sm leading-8 text-white/70"><strong className="text-[#E4C878]">Importación y regulación:</strong> no se afirma aprobación universal. El importador debe confirmar requisitos aduaneros, federales, estatales, de etiquetado y del producto. No se garantiza aprobación, despacho, tránsito ni entrega.</aside></div></div></RevealOnScroll></section>
 <section className="bg-[#09271D] px-6 py-24 text-[#F5F0E6] lg:px-12 lg:py-32"><RevealOnScroll><div className="mx-auto max-w-[1500px] text-center"><p className="text-[10px] uppercase tracking-[0.4em] text-[#E4C878]">Compradores B2B</p><h2 className="mt-6 text-[clamp(2.5rem,4.6vw,4.7rem)] font-semibold">Perfiles de compradores <span className="block text-[#E4C878]">en Estados Unidos</span></h2><Cards items={buyers} dark columns="lg:grid-cols-4"/><div className="mt-12 border border-[#C9A962]/25 p-7"><h3 className="text-3xl font-semibold">Consultas comerciales de todo Estados Unidos</h3><div className="mt-6 flex flex-wrap justify-center gap-3">{["Nueva York","Nueva Jersey","California","Texas","Florida","Illinois","Georgia","Washington","Massachusetts","Pensilvania","Carolina del Norte","Otros mercados"].map(m=><span key={m} className="border border-[#C9A962]/25 px-4 py-3 text-[9px] uppercase text-white/65">{m}</span>)}</div><p className="mt-7 border-t border-white/10 pt-6 text-xs text-white/45">Estas ubicaciones no implican oficina, almacén, inventario local ni distribución exclusiva en Estados Unidos.</p></div></div></RevealOnScroll></section>
 <section className="bg-[#EDE5D7] px-6 py-24 lg:px-12 lg:py-32"><RevealOnScroll><div className="mx-auto max-w-[1100px]"><div className="text-center"><p className="text-[10px] uppercase tracking-[0.4em] text-[#9F7F36]">Preguntas de compradores</p><h2 className="mt-6 text-[clamp(2.4rem,4.4vw,4.4rem)] font-semibold">Preguntas frecuentes sobre exportación</h2></div><div className="mt-12 divide-y divide-[#173B2A]/15 border-y border-[#173B2A]/15">{faqs.map((f,i)=><details key={f.question}><summary className="flex cursor-pointer list-none justify-between gap-6 py-6"><h3 className="text-xl font-semibold"><span className="mr-4 text-[#A97B22]">{String(i+1).padStart(2,"0")}</span>{f.question}</h3><span className="text-2xl text-[#A97B22]">+</span></summary><p className="pb-7 text-[15px] leading-8 text-[#4C5F54]">{f.answer}</p></details>)}</div><div className="mt-10 text-center"><Link href="/contact" className="inline-flex bg-[#C9A962] px-7 py-4 text-[10px] font-bold uppercase text-[#102F23]">Consultar al equipo →</Link></div></div></RevealOnScroll></section>
 <section className="bg-[#071B14] px-6 py-24 text-center text-[#F5F0E6] lg:px-12 lg:py-32"><RevealOnScroll><div className="mx-auto max-w-[1100px]"><p className="text-[10px] uppercase tracking-[0.4em] text-[#E4C878]">Importadores · Distribuidores · Compradores de marca privada</p><h2 className="mt-7 text-[clamp(2.6rem,5vw,5.2rem)] font-semibold">Productos naturales de la India <span className="block text-[#E4C878]">para su empresa en Estados Unidos</span></h2><p className="mx-auto mt-7 max-w-[850px] text-[17px] leading-8 text-white/65">Contáctenos para consultas a granel, mayoristas, OEM y de marca privada sobre henna, índigo, coloración botánica, plantas ayurvédicas y especias.</p><p className="mt-6 text-sm text-white/55">Indique producto, cantidad, envase, marca privada, destino y datos de empresa.</p><div className="mt-9 flex flex-wrap justify-center gap-4"><Link href="/contact" className="bg-[#C9A962] px-8 py-4 text-[10px] font-bold uppercase text-[#102F23]">Solicitar cotización</Link><a href="mailto:export@shiveshinternational.com?subject=Consulta%20de%20exportaci%C3%B3n%20a%20Estados%20Unidos" className="border border-white/30 px-8 py-4 text-[10px] font-bold uppercase">Enviar correo</a><a href="https://wa.me/919999774950?text=Hola%20Shivesh%20International%2C%20tengo%20una%20consulta%20de%20exportaci%C3%B3n%20para%20Estados%20Unidos." target="_blank" rel="noopener noreferrer" className="border border-white/30 px-8 py-4 text-[10px] font-bold uppercase">WhatsApp</a></div><nav aria-label="Páginas relacionadas de exportación y productos" className="mt-12 flex flex-wrap justify-center gap-6 border-t border-white/10 pt-8">{[["Servicios de exportación","/export"],["Henna natural","/products/natural-henna-powder"],["Índigo natural","/products/natural-indigo-powder"],["Coloraciones con henna","/products/natural-henna-hair-colors"],["Plantas ayurvédicas","/products/ayurvedic-indian-herbs"],["Especias de la India","/products/indian-spices"],["Infraestructura","/infrastructure"],["Certificaciones","/certifications"]].map(([l,h])=><Link key={h} href={h} className="text-[10px] uppercase text-white/50">{l}</Link>)}</nav><p className="mx-auto mt-8 max-w-[850px] text-xs leading-6 text-white/35">MOQ: 200 kg por artículo. Disponibilidad, precio, envase, producción, documentación y envío se confirman tras revisar el requisito comercial completo.</p></div></RevealOnScroll></section>
 <FooterSection locale="es"/><FloatingContactButtons/><PremiumCursor/><MagneticButtons/>
 </main>}
