/* eslint-disable react/no-unescaped-entities */
import type { Metadata } from "next";
import { existsSync } from "node:fs";
import Image from "next/image";
import Link from "next/link";
import FloatingContactButtons from "@/app/components/FloatingContactButtons";
import GoldenParticles from "@/app/components/GoldenParticles";
import MagneticButtons from "@/app/components/MagneticButtons";
import Navbar from "@/app/components/Navbar";
import PremiumCursor from "@/app/components/PremiumCursor";
import RevealOnScroll from "@/app/components/RevealOnScroll";
import StaggerItem from "@/app/components/StaggerItem";
import FooterSection from "@/sections/FooterSection";

const canonicalUrl = "https://shiveshinternational.com/export/thailand";
const heroImage = "/images/export/thailand/thailand-natural-products-export-hero.png";
const metadataKeywords = [
  "natural products exporter to Thailand", "natural products supplier Thailand", "natural products manufacturer India for Thailand", "bulk natural products supplier Thailand", "wholesale natural products Thailand", "private label natural products Thailand", "OEM natural products Thailand", "Indian botanical products supplier Thailand", "herbal products exporter to Thailand",
  "henna powder exporter to Thailand", "natural henna powder supplier Thailand", "henna manufacturer India for Thailand", "bulk henna powder supplier Thailand", "wholesale henna powder Thailand", "organic henna powder supplier Thailand", "private label henna Thailand", "OEM henna products Thailand", "henna powder importer Thailand", "henna powder distributor Thailand", "Sojat henna powder supplier Thailand",
  "indigo powder exporter to Thailand", "natural indigo powder supplier Thailand", "indigo powder manufacturer India for Thailand", "bulk indigo powder supplier Thailand", "wholesale indigo powder Thailand", "private label indigo powder Thailand", "indigo powder importer Thailand", "indigo powder distributor Thailand", "botanical hair color ingredient supplier Thailand",
  "natural henna hair colors exporter Thailand", "botanical hair color supplier Thailand", "natural hair color manufacturer India for Thailand", "henna hair color supplier Thailand", "private label henna hair colors Thailand", "OEM botanical hair colors Thailand", "professional salon hair color supplier Thailand", "natural hair dye exporter Thailand",
  "Ayurvedic herbs exporter to Thailand", "Indian herbs supplier Thailand", "herbal powder exporter Thailand", "botanical ingredients supplier Thailand", "private label Ayurvedic herbs Thailand", "bulk herbal powders Thailand", "Ayurvedic ingredients importer Thailand",
  "Indian spices exporter to Thailand", "Indian spices supplier Thailand", "bulk Indian spices Thailand", "wholesale spices supplier Thailand", "private label Indian spices Thailand", "spice importer Thailand", "spice distributor Thailand", "Indian food ingredients supplier Thailand",
  "Thailand importer natural products India", "Thailand distributor natural products India", "Thailand cosmetic ingredient buyer India", "Thailand natural hair care brand supplier", "Thailand private label supplier India", "Thailand herbal wholesaler India", "Thailand salon supplier natural hair color", "Thailand retail natural products supplier", "Thailand e-commerce natural products supplier", "Thailand spa product supplier India", "Thailand wellness product supplier India", "spa herbal ingredient supplier Thailand", "India exporter to Thailand", "Indian exporter natural products Thailand", "B2B natural products supplier Thailand", "bulk botanical products Thailand", "wholesale herbal products Thailand", "private label botanical products Thailand", "export documentation support Thailand", "natural products shipping from India to Thailand", "Shivesh International Thailand exporter",
];

export const metadata: Metadata = {
  title: { absolute: "Natural Products Exporter to Thailand | Henna, Indigo, Herbs & Spices" },
  description: "Natural henna, indigo, botanical hair colors, Ayurvedic herbs and Indian spices for Thailand importers, distributors, wholesalers and private-label buyers. MOQ 200 kg per item.",
  keywords: metadataKeywords,
  alternates: { canonical: canonicalUrl },
  openGraph: { title: "Henna & Indigo Exporter to Thailand | Shivesh International", description: "Bulk and private-label natural henna, indigo, herbs and spices supplied from India for professional buyers in Thailand.", url: canonicalUrl, type: "website", locale: "en_TH", siteName: "Shivesh International", images: [{ url: heroImage, alt: "Natural henna, indigo, herbs and spices export supply for professional buyers in Thailand" }] },
  twitter: { card: "summary_large_image", title: "Henna & Indigo Exporter to Thailand", description: "Indian natural-product supply for Thailand importers, distributors and private-label brands.", images: [heroImage] },
  robots: { index: true, follow: true, googleBot: { index: true, follow: true } },
};

const products = [
  ["Natural Henna Powder", "For Thai natural cosmetic companies, hair-care brands, salon suppliers, wholesalers and private-label programmes.", "/products/natural-henna-powder"],
  ["Natural Indigo Powder", "For botanical dark hair-color systems developed by importers, professional suppliers and hair-care brands.", "/products/natural-indigo-powder"],
  ["Natural Henna Hair Colors", "Powder hair-color options for Thai distributors, salon channels, retail chains and online brands.", "/products/natural-henna-hair-colors"],
  ["Henna-Based Hair Colors", "Commercial shade options for beauty suppliers, wholesale programmes and feasible buyer-brand requirements.", "/products/henna-based-hair-colors"],
  ["Ayurvedic Indian Herbs", "Herbs and botanical powders for suitable cosmetic, herbal, spa, wellness and wholesale applications without medical claims.", "/products/ayurvedic-indian-herbs"],
  ["Indian Spices", "Whole, ground and blended spices for Thai food companies, importers, distributors and commercial buyers.", "/products/indian-spices"],
];
const buyers = [
  ["Importers & Distributors", "Plan selected products, commercial volumes, specifications, documentation needs and onward distribution in Thailand."],
  ["Natural Cosmetic Companies", "Evaluate henna, indigo and botanical powders for intended formulations or finished-product programmes."],
  ["Hair-Care Brands", "Develop botanical color and natural hair-care ranges for professional, retail and e-commerce channels."],
  ["Salon & Beauty Suppliers", "Review professional formats and repeat supply for salon and beauty-product distribution."],
  ["Private-Label Companies", "Discuss feasible buyer-brand packaging, artwork, label layouts and selected product portfolios."],
  ["Herbal & Wellness Wholesalers", "Source Indian herbs and botanical powders for appropriate herbal, wellness and wholesale channels."],
  ["Spa & Wellness Product Buyers", "Assess suitable botanical ingredients and packs for spa, hospitality and specialist wellness businesses."],
  ["Food & Spice Buyers", "Plan whole, ground or blended Indian spice requirements for suitable food and distribution channels."],
];
const documents = [
  ["Commercial Invoice", "Prepared around confirmed products, quantities, values and commercial terms."],
  ["Packing List", "May detail pack counts, net and gross weights, cartons or pallets and shipment references."],
  ["Certificate of Origin", "May be coordinated according to product and shipment requirements, subject to issuing availability."],
  ["Transport Documents", "A Bill of Lading or Air Waybill may be provided according to the confirmed shipment mode."],
  ["Product and Quality Records", "A specification sheet, Certificate of Analysis or MSDS/SDS may be provided where applicable and available."],
  ["Other Agreed Documents", "A Non-GMO declaration or other mutually agreed export documents may be discussed where applicable."],
];
const steps = [
  ["Product Selection", "Identify the category, intended commercial use, Thai destination and approximate quantity."],
  ["Specification Review", "Compare requested parameters with available product specifications and information."],
  ["Commercial Confirmation", "Confirm the 200 kg per-item MOQ, quotation, quantities and transaction terms."],
  ["Packaging & Production", "Approve feasible bulk or private-label packaging before production under the agreed order."],
  ["Documentation", "Coordinate applicable and available commercial, product and shipment records."],
  ["Shipment Coordination", "Plan dispatch and document sharing with the buyer or nominated freight forwarder."],
];
const strengths = [
  ["Established Experience", "Product and sourcing experience supports practical discussions with professional buyers."],
  ["Manufacturing Support", "Certified manufacturing support and a raw-material sourcing network underpin selected programmes."],
  ["Consistent Specifications", "Orders are planned around agreed product specifications and commercial requirements."],
  ["Bulk & Private Label", "Wholesale and buyer-brand supply can be reviewed according to feasibility."],
  ["Packaging Formats", "Retail-ready and bulk options support different commercial channels."],
  ["Documentation Support", "Applicable and available commercial, product and shipment records can be coordinated."],
  ["Shipment Coordination", "Dispatch planning can be aligned with the buyer's nominated freight forwarder."],
  ["Buyer-Focused Communication", "Each enquiry is reviewed around its product, use, specification, packaging and volume."],
];
const locations = [
  ["Bangkok", "Importers, national distributors, cosmetic companies and retail businesses can assess multi-category sourcing and buyer-brand programmes."],
  ["Chonburi", "Eastern-corridor buyers can discuss bulk botanicals, spice supply and shipment planning near major logistics gateways."],
  ["Chiang Mai", "Herbal wholesalers, spa businesses and natural-product retailers can evaluate Indian herbs, botanical powders and retail formats."],
  ["Phuket", "Spa, wellness, hospitality and specialist retail buyers can review suitable botanical, herbal and private-label requirements."],
  ["Samut Prakan", "Import and distribution businesses can plan documentation, commercial quantities and onward supply for greater Bangkok channels."],
  ["Nonthaburi", "Beauty suppliers, salon distributors and e-commerce companies can explore henna, indigo and botanical hair-care programmes."],
  ["Pathum Thani", "Private-label companies and cosmetic buyers can coordinate specifications, packaging artwork and repeat-order planning."],
  ["Khon Kaen", "Northeastern wholesalers, food businesses and retailers can assess Indian spices, herbs and natural-product distribution needs."],
];
const faqs = [
  { question: "What products does Shivesh International export to Thailand?", answer: "Thailand buyers can discuss natural henna powder, indigo powder, natural henna hair colors, henna-based hair colors, Ayurvedic Indian herbs and Indian spices for suitable professional channels." },
  { question: "What is the MOQ for Thailand orders?", answer: "The minimum order quantity is 200 kg per selected product or item. Multi-product planning is reviewed separately according to commercial and production feasibility." },
  { question: "Is private-label supply available for Thailand buyers?", answer: "Private-label packaging may be coordinated for suitable products and quantities, subject to materials, artwork, printing, label details and technical feasibility." },
  { question: "Which retail pack sizes can be discussed?", answer: "Retail formats may include 100 g, 200 g, 500 g and 1 kg, depending on the selected product, packaging material and confirmed order." },
  { question: "Is bulk packaging available for Thailand?", answer: "Bulk formats may include 20 kg and 25 kg packs, with double-layer vacuum packaging where applicable to the product and order." },
  { question: "Can you support Thai importers and distributors?", answer: "Importers and distributors can share their product, intended use, specification, volume, packaging and destination requirements for commercial review." },
  { question: "Which export documents can be coordinated?", answer: "Available records may include a commercial invoice, packing list, certificate of origin, transport document, specification, COA or MSDS/SDS where applicable and available." },
  { question: "Can shipments be coordinated for Bangkok or Laem Chabang?", answer: "Bangkok, Laem Chabang or another feasible buyer-nominated cargo destination may be considered with the nominated forwarder. Routes, schedules, clearance, transit time and delivery are not guaranteed." },
  { question: "Who handles Thailand import approvals and labeling?", answer: "The Thailand importer or buyer is responsible for classification, import eligibility, registrations, permits, labeling, language, claims, customs clearance and applicable destination requirements." },
  { question: "How can a Thailand buyer request a quotation?", answer: "Share company details, selected product, specification, intended use, required quantity, packaging preference and destination through the contact page for commercial review." },
];
const structuredData = { "@context": "https://schema.org", "@graph": [
  { "@type": "WebPage", "@id": `${canonicalUrl}#webpage`, url: canonicalUrl, name: "Henna & Indigo Exporter to Thailand", description: "Thailand-focused export supply of natural henna, indigo, botanical hair colors, Ayurvedic herbs and Indian spices from India.", isPartOf: { "@id": "https://shiveshinternational.com/#website" }, about: { "@id": "https://shiveshinternational.com/#organization" }, breadcrumb: { "@id": `${canonicalUrl}#breadcrumb` }, primaryImageOfPage: { "@type": "ImageObject", url: heroImage }, inLanguage: "en" },
  { "@type": "BreadcrumbList", "@id": `${canonicalUrl}#breadcrumb`, itemListElement: [{ "@type": "ListItem", position: 1, name: "Home", item: "https://shiveshinternational.com/" }, { "@type": "ListItem", position: 2, name: "Export", item: "https://shiveshinternational.com/export" }, { "@type": "ListItem", position: 3, name: "Asia-Pacific", item: "https://shiveshinternational.com/export/asia-pacific" }, { "@type": "ListItem", position: 4, name: "Thailand", item: canonicalUrl }] },
] };
const faqStructuredData = { "@context": "https://schema.org", "@type": "FAQPage", "@id": `${canonicalUrl}#faq`, mainEntity: faqs.map((faq) => ({ "@type": "Question", name: faq.question, acceptedAnswer: { "@type": "Answer", text: faq.answer } })) };

function OptionalImage({ src, alt, priority = false, sizes = "(min-width: 1024px) 55vw, 100vw", className = "object-contain object-center" }: { src: string; alt: string; priority?: boolean; sizes?: string; className?: string }) { if (!existsSync(`${process.cwd()}/public${src}`)) return null; return <Image src={src} alt={alt} fill priority={priority} sizes={sizes} className={className}/>; }
const Cards = ({ items, columns = "lg:grid-cols-4" }: { items: string[][]; columns?: string }) => <div className={`mt-14 grid auto-rows-fr gap-5 sm:grid-cols-2 ${columns}`}>{items.map(([title,text])=><article key={title} className="h-full border border-[#173B2A]/12 bg-[#FBF8F1] p-7 sm:p-8"><span className="block h-px w-12 bg-[#C9A962]"/><h3 className="mt-5 font-[family-name:var(--font-playfair)] text-2xl font-semibold">{title}</h3><p className="mt-4 text-sm font-light leading-7 text-[#4C5F54]">{text}</p></article>)}</div>;

export default function ThailandExportPage(){return <main className="min-h-screen overflow-x-hidden bg-[#F5F0E6] text-[#173B2A]">
  <script type="application/ld+json" dangerouslySetInnerHTML={{__html:JSON.stringify(structuredData).replace(/</g,"\\u003c")}}/><script type="application/ld+json" dangerouslySetInnerHTML={{__html:JSON.stringify(faqStructuredData).replace(/</g,"\\u003c")}}/><Navbar/>
  <section className="relative isolate overflow-hidden bg-[#071B14]"><OptionalImage src={heroImage} alt="Natural henna, indigo, herbs and spices export supply for professional buyers in Thailand" priority sizes="100vw" className="object-cover object-[72%_center] sm:object-[70%_center] lg:object-[65%_center] xl:object-center"/><div className="absolute inset-0 bg-gradient-to-r from-[#061711]/28 via-[#102F23]/10 to-transparent"/><div className="absolute inset-0 bg-gradient-to-t from-black/[0.04] via-transparent to-transparent"/><GoldenParticles/><div className="relative z-10 flex items-center px-6 pb-20 pt-32 sm:px-8 sm:pb-24 sm:pt-36 lg:px-12 lg:pb-28 lg:pt-40"><div className="w-full max-w-[950px]"><StaggerItem delay={0}><p className="text-[10px] font-bold uppercase tracking-[0.38em] text-[#E4C878] sm:text-xs">India to Thailand B2B Supply</p></StaggerItem><StaggerItem delay={100}><h1 className="mt-5 font-[family-name:var(--font-playfair)] text-4xl font-medium leading-[1.02] tracking-[-0.04em] text-[#F5F0E6] sm:text-5xl lg:text-6xl xl:text-[66px]">Natural Henna, Indigo, Herbs &amp; Spices <span className="block bg-gradient-to-r from-[#F5F0E6] via-[#E4C878] to-[#C9A962] bg-clip-text text-transparent">Exporter to Thailand</span></h1></StaggerItem><StaggerItem delay={200}><p className="mt-5 max-w-[790px] text-[16px] font-light leading-8 text-white/82">Shivesh International supplies natural henna powder, indigo powder, botanical hair colors, Ayurvedic herbs and Indian spices to importers, distributors, private-label brands and wholesale buyers across Thailand.</p></StaggerItem><StaggerItem delay={300}><div className="mt-7 flex flex-wrap gap-4"><Link href="/contact" className="border border-[#C9A962] bg-[#C9A962] px-7 py-4 text-[10px] font-bold uppercase tracking-[0.2em] text-[#102F23]">Send Thailand Inquiry →</Link><a href="#products" className="border border-white/30 bg-[#102F23]/40 px-7 py-4 text-[10px] font-bold uppercase tracking-[0.2em] text-white">Explore Export Products ↓</a></div></StaggerItem><StaggerItem delay={400}><div className="mt-10 grid max-w-[760px] grid-cols-2 gap-3 lg:grid-cols-4">{[["200 kg","MOQ per item"],["Bulk","B2B supply"],["Private Label","Buyer-brand packs"],["Export","Coordination"]].map(([v,l])=><div key={l} className="border border-white/15 bg-black/20 p-4"><p className="font-[family-name:var(--font-playfair)] text-xl font-semibold text-[#E4C878]">{v}</p><p className="mt-2 text-[9px] uppercase tracking-[0.22em] text-white/55">{l}</p></div>)}</div></StaggerItem></div></div></section>
  <section className="px-6 py-24 sm:px-8 lg:px-12 lg:py-32"><RevealOnScroll><div className="mx-auto max-w-[1200px]"><p className="text-[10px] font-bold uppercase tracking-[0.4em] text-[#9F7F36]">Thailand Market Supply</p><h2 className="mt-6 font-[family-name:var(--font-playfair)] text-[clamp(2.3rem,4.6vw,4.6rem)] font-semibold">Natural Product Supply <span className="block text-[#A97B22]">for Professional Buyers in Thailand</span></h2><p className="mt-7 text-[16px] font-light leading-8 text-[#4C5F54]">Professional buyers can discuss natural hair-color powders, botanical cosmetic ingredients, herbal powders, private-label natural products, bulk raw materials, Indian herbs and whole or ground Indian spices according to their intended use and sales channel.</p><p className="mt-5 text-[15px] font-light leading-8 text-[#4C5F54]">Professional enquiries associated with Bangkok, Chonburi, Chiang Mai, Phuket, Samut Prakan, Nonthaburi, Pathum Thani, Khon Kaen and other buyer-nominated destinations can plan product, packaging and documentation requirements. These references do not imply local offices, warehouses, employees, stock points, distributors, guaranteed demand, acceptance, registration or approval.</p></div></RevealOnScroll></section>
  <section id="products" className="bg-[#EDE5D7] px-6 py-24 sm:px-8 lg:px-12 lg:py-32"><RevealOnScroll><div className="mx-auto max-w-[1500px]"><div className="text-center"><p className="text-[10px] uppercase tracking-[0.4em] text-[#9F7F36]">Six Commercial Categories</p><h2 className="mt-6 font-[family-name:var(--font-playfair)] text-[clamp(2.3rem,4.8vw,4.8rem)] font-semibold">Products Available <span className="block text-[#A97B22]">for Thailand Buyers</span></h2></div><div className="mt-14 grid auto-rows-fr gap-5 sm:grid-cols-2 lg:grid-cols-3">{products.map(([title,text,href],i)=><article key={title} className="flex h-full min-h-[290px] flex-col border border-[#173B2A]/12 bg-[#FBF8F1] p-7"><span className="text-4xl text-[#C9A962]">{String(i+1).padStart(2,"0")}</span><h3 className="mt-5 font-[family-name:var(--font-playfair)] text-2xl font-semibold">{title}</h3><p className="mt-4 flex-1 text-sm leading-7 text-[#4C5F54]">{text}</p><Link href={href} className="mt-6 text-[10px] font-bold uppercase tracking-[0.2em] text-[#A97B22]">Explore {title} →</Link></article>)}</div></div></RevealOnScroll></section>
  <section className="px-6 py-24 sm:px-8 lg:px-12 lg:py-32"><RevealOnScroll><div className="mx-auto max-w-[1500px]"><div className="text-center"><p className="text-[10px] uppercase tracking-[0.4em] text-[#9F7F36]">Thailand Buyer Profiles</p><h2 className="mt-6 font-[family-name:var(--font-playfair)] text-[clamp(2.3rem,4.7vw,4.7rem)] font-semibold">Who We Supply in Thailand</h2><p className="mx-auto mt-7 max-w-[900px] text-[15px] leading-8 text-[#4C5F54]">Final product, specification, packaging and documentation requirements depend on the intended use, product category, buyer's commercial channel and applicable destination requirements.</p></div><Cards items={buyers}/></div></RevealOnScroll></section>
<section className="bg-[#EDE5D7] px-6 py-24 sm:px-8 lg:px-12 lg:py-32"><RevealOnScroll><div className="mx-auto max-w-[1500px]"><div className="grid gap-14 lg:grid-cols-[1.05fr_0.95fr] lg:gap-20"><div><p className="text-[10px] uppercase tracking-[0.4em] text-[#9F7F36]">Packaging & Private Label</p><h2 className="mt-6 font-[family-name:var(--font-playfair)] text-[clamp(2.3rem,4.6vw,4.6rem)] font-semibold">Bulk, Retail and <span className="block text-[#A97B22]">Private-Label Packaging</span></h2><p className="mt-7 text-[15px] leading-8 text-[#4C5F54]">Silver and gold metallized pouches, buyer-brand packaging, artwork and label coordination, retail-ready formats and bulk packs for repacking or manufacturing can be reviewed.</p><p className="mt-5 text-[14px] leading-7 text-[#4C5F54]">Packaging is confirmed according to the product, material, artwork, quantity and technical feasibility. The MOQ applies per selected product or item; mixed-product planning may be discussed separately, and final packing depends on product, pack size, artwork and order quantity. Not every packaging option is available for every product.</p></div><div><figure className="relative aspect-[3/2] overflow-hidden border border-[#C9A962]/35 bg-[#FBF8F1] shadow-[0_28px_70px_rgba(20,50,38,0.18)]"><OptionalImage src="/images/export/thailand/thailand-private-label-henna-indigo-buyers.png" alt="Thai buyers reviewing private-label packaging for henna, indigo, herbs and spices" className="object-cover object-center"/></figure><div className="mt-5 grid gap-5 sm:grid-cols-2"><article className="border border-[#C9A962]/35 bg-[#FBF8F1] p-7"><h3 className="text-2xl font-semibold">Retail Packaging</h3><p className="mt-5 text-sm leading-7 text-[#4C5F54]">100 g · 200 g · 500 g · 1 kg formats</p></article><article className="border border-[#C9A962]/35 bg-[#FBF8F1] p-7"><h3 className="text-2xl font-semibold">Bulk Packaging</h3><p className="mt-5 text-sm leading-7 text-[#4C5F54]">20 kg and 25 kg, with double-layer vacuum packaging where applicable</p></article><article className="border border-[#C9A962] bg-[#173B2A] p-7 text-white sm:col-span-2"><p className="text-[10px] uppercase tracking-[0.3em] text-[#E4C878]">Minimum Order Quantity</p><p className="mt-4 text-4xl font-semibold">200 kg per item</p></article></div></div></div></div></RevealOnScroll></section>
  <section className="relative bg-[#09271D] px-6 py-24 text-white sm:px-8 lg:px-12 lg:py-32"><RevealOnScroll><div className="mx-auto max-w-[1500px]"><div className="grid items-center gap-14 lg:grid-cols-[0.9fr_1.1fr] lg:gap-20"><div><p className="text-[10px] uppercase tracking-[0.4em] text-[#E4C878]">Shipment and Document Support</p><h2 className="mt-6 font-[family-name:var(--font-playfair)] text-[clamp(2.3rem,4.7vw,4.7rem)] font-semibold">Structured Export Coordination for Thailand</h2><p className="mt-7 text-[16px] leading-8 text-white/68">Structured coordination can cover product selection, specification review, quotation, commercial terms, packaging or private-label confirmation, production, quality checks, export documentation, shipment planning, dispatch and document sharing with the buyer or nominated freight forwarder.</p><p className="mt-5 text-[15px] leading-8 text-white/62">Bangkok, Laem Chabang or another feasible buyer-nominated cargo destination may be considered. Freight rates, schedules, transit times, import approval, registration, clearance, inspection, delivery or regulatory acceptance are not guaranteed.</p></div><figure className="relative aspect-[3/2] overflow-hidden border border-[#C9A962]/35 bg-[#071B14]"><OptionalImage src="/images/export/thailand/india-to-thailand-export-coordination.png" alt="India-to-Thailand export coordination for natural products and private-label shipments" className="object-cover object-center"/><div className="absolute inset-0 bg-gradient-to-t from-[#061711]/65 via-transparent to-transparent"/><figcaption className="absolute bottom-5 left-5 border border-white/15 bg-[#071B14]/80 px-4 py-3 text-[9px] uppercase tracking-[0.22em] text-[#E4C878]">India-to-Thailand Export Coordination</figcaption></figure></div><aside className="mt-12 border border-[#C9A962]/35 bg-[#071B14]/60 p-7 text-sm leading-7 text-white/65">The Thailand importer or buyer is responsible for confirming product classification, intended-use requirements, ingredient restrictions, import eligibility, registrations, filings, permits, labeling, language requirements, claims, testing, inspection, customs clearance and applicable local regulatory compliance before ordering. Requirements may differ between cosmetics, cosmetic ingredients, herbal products, food ingredients and spices. Shivesh International does not guarantee Thailand import approval or customs clearance, and this page does not constitute legal or regulatory advice. Production or dispatch should proceed only after the buyer confirms applicable destination requirements.</aside></div></RevealOnScroll></section>
  <section className="px-6 py-24 sm:px-8 lg:px-12 lg:py-32"><RevealOnScroll><div className="mx-auto max-w-[1500px]"><div className="text-center"><p className="text-[10px] uppercase tracking-[0.4em] text-[#9F7F36]">Available Product and Shipment Records</p><h2 className="mt-6 font-[family-name:var(--font-playfair)] text-[clamp(2.1rem,4.7vw,4.7rem)] font-semibold">Export Documentation Support</h2><p className="mx-auto mt-7 max-w-[950px] text-[15px] leading-8 text-[#4C5F54]">Available documents depend on the product, order, shipment terms, buyer requirements and issuing availability. Organic, phytosanitary, health, free-sale, government-laboratory, legalization, attestation, registration or inspection documents are not automatically promised.</p></div><Cards items={documents} columns="lg:grid-cols-3"/></div></RevealOnScroll></section>
  <section className="bg-[#EDE5D7] px-6 py-24 sm:px-8 lg:px-12 lg:py-32"><RevealOnScroll><div className="mx-auto max-w-[1500px]"><div className="text-center"><p className="text-[10px] uppercase tracking-[0.4em] text-[#9F7F36]">Six Commercial Steps</p><h2 className="mt-6 font-[family-name:var(--font-playfair)] text-[clamp(2.3rem,4.7vw,4.7rem)] font-semibold">Thailand Commercial Workflow</h2></div><Cards items={steps} columns="lg:grid-cols-3"/></div></RevealOnScroll></section>
  <section className="px-6 py-24 sm:px-8 lg:px-12 lg:py-32"><RevealOnScroll><div className="mx-auto max-w-[1500px]"><div className="text-center"><p className="text-[10px] uppercase tracking-[0.4em] text-[#9F7F36]">Professional Export Supply</p><h2 className="mt-6 font-[family-name:var(--font-playfair)] text-[clamp(2.3rem,4.7vw,4.7rem)] font-semibold">Why Thailand Buyers Choose <span className="block text-[#A97B22]">Shivesh International</span></h2></div><Cards items={strengths}/></div></RevealOnScroll></section>
  <section className="px-6 py-24 sm:px-8 lg:px-12 lg:py-32"><RevealOnScroll><div className="mx-auto max-w-[1280px]"><p className="text-[10px] font-bold uppercase tracking-[0.4em] text-[#9F7F36]">Major Thai Commercial Locations</p><h2 className="mt-6 font-[family-name:var(--font-playfair)] text-[clamp(2.5rem,4.6vw,4.6rem)] font-semibold">Buyer and Distribution Context <span className="block text-[#A97B22]">Across Thailand</span></h2><p className="mt-7 max-w-[940px] text-[15px] leading-8 text-[#4C5F54]">These locations describe potential commercial and distribution contexts only. They do not represent Shivesh International premises, warehouses, stock, inventory, current buyer networks, guaranteed relationships, exclusive territories, branches or agents in Thailand.</p><Cards items={locations}/></div></RevealOnScroll></section>
  <section className="bg-[#EDE5D7] px-6 py-24 sm:px-8 lg:px-12 lg:py-32"><RevealOnScroll><div className="mx-auto max-w-[1120px]"><div className="text-center"><p className="text-[10px] uppercase tracking-[0.4em] text-[#9F7F36]">Thailand Buyer Questions</p><h2 className="mt-6 font-[family-name:var(--font-playfair)] text-[clamp(2.3rem,4.4vw,4.4rem)] font-semibold">Thailand Export Supply FAQ</h2></div><div className="mt-12 divide-y divide-[#173B2A]/15 border-y border-[#173B2A]/15">{faqs.map(f=><article key={f.question} className="grid gap-4 py-7 md:grid-cols-[0.8fr_1.2fr]"><h3 className="text-xl font-semibold">{f.question}</h3><p className="text-sm leading-7 text-[#4C5F54]">{f.answer}</p></article>)}</div></div></RevealOnScroll></section>
  <section className="relative overflow-hidden bg-[#071B14] px-6 py-24 text-center text-white sm:px-8 lg:px-12 lg:py-28"><GoldenParticles/><RevealOnScroll><div className="relative mx-auto max-w-[1000px]"><p className="text-[10px] uppercase tracking-[0.4em] text-[#E4C878]">Thailand Export Enquiry</p><h2 className="mt-6 font-[family-name:var(--font-playfair)] text-[clamp(2.3rem,4.8vw,4.8rem)] font-semibold">Source Natural Indian Products for Thailand</h2><p className="mx-auto mt-7 max-w-[820px] text-[16px] leading-8 text-white/65">Tell us your required product, specification, intended use, packaging format and order quantity. Our team will review your Thailand inquiry and provide the relevant commercial and export information.</p><Link href="/contact" className="mt-9 inline-flex border border-[#C9A962] bg-[#C9A962] px-8 py-4 text-[10px] font-bold uppercase tracking-[0.2em] text-[#102F23]">Request Thailand Export Quotation →</Link></div></RevealOnScroll></section>
  <FooterSection/><FloatingContactButtons/><MagneticButtons/><PremiumCursor/>
</main>}
