import type { Metadata } from "next";
import { existsSync } from "node:fs";
import Image from "next/image";
import Link from "next/link";
import FloatingContactButtons from "@/app/components/FloatingContactButtons";
import GoldenParticles from "@/app/components/GoldenParticles";
import MagneticButtons from "@/app/components/MagneticButtons";
import Navbar from "@/app/components/Navbar";
import PremiumCursor from "@/app/components/PremiumCursor";
import RevealOnScroll from "@/app/components/RevealOnScroll";
import StaggerItem from "@/app/components/StaggerItem";
import { italyLanguageAlternates } from "@/app/lib/i18n";
import FooterSection from "@/sections/FooterSection";

const canonicalUrl = "https://shiveshinternational.com/it/export/italia";
export const metadata: Metadata = {
  title: "Esportatore di henné, indigo, erbe e spezie in Italia",
  description: "Shivesh International esporta henné naturale, indigo, colorazioni vegetali, erbe ayurvediche e spezie indiane per importatori, distributori e marchi privati in Italia. MOQ 200 kg per prodotto.",
  keywords: ["esportatore di prodotti naturali in Italia", "produttore di henné per l’Italia", "fornitore di henné naturale", "henné all’ingrosso Italia", "esportatore di henné naturale", "fornitore di indigo naturale", "esportatore di indigo naturale", "fornitore di colorazioni vegetali", "colorazione botanica per capelli", "fornitore per saloni professionali", "fornitore di cosmetici naturali", "importatori in Italia", "distributori in Italia", "grossisti in Italia", "rivenditori specializzati", "fornitore di erbe ayurvediche", "esportatore di erbe ayurvediche", "fornitore di spezie indiane", "esportatore di spezie indiane", "marchio proprio", "Private Label", "OEM", "fornitura all’ingrosso", "approvvigionamento B2B Italia"],
  alternates: { canonical: canonicalUrl, languages: italyLanguageAlternates },
  openGraph: { title: "Esportatore di henné, indigo, erbe e spezie in Italia", description: "Fornitura B2B all’ingrosso e Private Label di prodotti naturali indiani per acquirenti professionali in Italia.", url: canonicalUrl, type: "website", locale: "it_IT", siteName: "Shivesh International" },
  twitter: { card: "summary_large_image", title: "Fornitore di prodotti naturali per l’Italia", description: "Henné, indigo, colorazioni vegetali, erbe ayurvediche e spezie indiane per il mercato italiano." },
  robots: { index: true, follow: true },
};

const products = [
  ["Henné naturale in polvere", "Henné naturale di qualità fine per marchi di cosmetica, fornitori per saloni, aziende erboristiche, grossisti e progetti a marchio proprio.", "/products/natural-henna-powder"],
  ["Indigo naturale in polvere", "Indigo naturale per sistemi di colorazione botanica, formulazioni cosmetiche, canali professionali e confezionamento Private Label.", "/products/natural-indigo-powder"],
  ["Colorazioni naturali all’henné", "Una gamma di tonalità botaniche per importatori, marchi di bellezza, aziende per la cura dei capelli e distribuzione professionale.", "/products/natural-henna-hair-colors"],
  ["Colorazioni per capelli a base di henné", "Colorazioni in polvere pronte per l’esportazione, disponibili per forniture all’ingrosso, OEM e progetti personalizzati Private Label.", "/products/henna-based-hair-colors"],
  ["Erbe ayurvediche indiane", "Polveri erboristiche e botaniche indiane per applicazioni cosmetiche, cura personale, benessere, capelli e vendita all’ingrosso.", "/products/ayurvedic-indian-herbs"],
  ["Spezie indiane", "Spezie indiane intere e macinate per importatori, aziende alimentari, distributori, rivenditori e acquirenti Private Label.", "/products/indian-spices"],
] as const;
const buyers = [
  ["Importatori", "Coordinate specifiche, quantità, confezionamento e documentazione disponibile con un unico referente di fornitura in India."], ["Distributori", "Sviluppate assortimenti per i canali professionali, cosmetici, erboristici e alimentari italiani."], ["Marchi di cosmetica naturale", "Approvvigionate henné, indigo e ingredienti botanici per gamme cosmetiche sviluppate dall’acquirente."], ["Marchi per la cura dei capelli", "Valutate colorazioni botaniche ed erbe per programmi destinati al mercato italiano."], ["Fornitori per saloni", "Esaminate henné, indigo e colorazioni in polvere per saloni professionali in Italia."], ["Aziende erboristiche e del benessere", "Approvvigionate amla, shikakai e altre erbe ayurvediche per gamme benessere e a marchio proprio."], ["Acquirenti alimentari e di spezie", "Pianificate la fornitura di spezie intere, macinate e ingredienti indiani per canali retail o all’ingrosso."], ["Marchi Private Label ed e-commerce", "Coordinate prodotti, identità del marchio e formati commercialmente realizzabili per la vendita digitale."],
];
const applications = [
  ["Cosmetica e cura personale", "Henné ed erbe naturali per formulazioni sviluppate dall’acquirente, previa verifica delle specifiche e dell’uso previsto."], ["Sistemi di colorazione botanica", "Henné, indigo e miscele di tonalità per concetti di colorazione in due fasi o già preparati."], ["Distribuzione per saloni", "Formati all’ingrosso e retail selezionati per distributori professionali e fornitori per saloni."], ["Cura erboristica dei capelli e benessere", "Amla, shikakai e altre polveri ayurvediche per gamme dedicate ai capelli, al benessere e alla cura personale."], ["Prodotti naturali retail", "Gamme con formati selezionati, etichette, astucci e buste coordinati."], ["Private Label e OEM", "Presentazione personalizzata e fornitura OEM o Private Label dopo verifica tecnica e commerciale."], ["Approvvigionamento di ingredienti sfusi", "Polveri botaniche in confezioni commerciali per ulteriore impiego o rivendita."], ["Distribuzione alimentare e di spezie", "Spezie indiane intere e macinate per aziende alimentari, acquirenti di ingredienti e programmi Private Label."],
];
const strengths = [["Esportatore con sede in India", "Coordinamento commerciale diretto con un team indiano specializzato nell’esportazione."], ["MOQ da 200 kg per prodotto", "Il quantitativo minimo commerciale parte da 200 kg per ciascun prodotto selezionato."], ["Retail, ingrosso e Private Label", "È possibile valutare formati retail, professionali, all’ingrosso e a marchio dell’acquirente."], ["Più categorie naturali", "Henné, indigo, colorazioni, erbe ayurvediche e spezie indiane da un unico fornitore."], ["Supporto alla personalizzazione", "Coordinamento di buste, astucci, etichette, grafiche e codici a barre fattibili."], ["Coordinamento documentale", "Allineamento delle informazioni commerciali e qualitative disponibili con l’ordine concordato."]];
const faqs = [
  { question: "Quali prodotti esporta Shivesh International in Italia?", answer: "Forniamo henné naturale, indigo, colorazioni botaniche e a base di henné, erbe ayurvediche indiane e spezie intere o macinate ad acquirenti professionali qualificati." },
  { question: "Qual è il quantitativo minimo per gli acquirenti italiani?", answer: "Il MOQ è di 200 kg per prodotto. Le quantità finali dipendono dal prodotto, dal formato di confezionamento e dai requisiti Private Label." },
  { question: "È disponibile il confezionamento Private Label per l’Italia?", answer: "Il supporto può includere marchio dell’acquirente, buste e astucci stampati, etichette, codici a barre e coordinamento della grafica in italiano, previa verifica di fattibilità." },
  { question: "Gli importatori italiani possono ordinare henné e indigo sfusi?", answer: "Sì. È possibile valutare formati all’ingrosso disponibili, comprese buste sottovuoto a doppio strato da 20 kg e 25 kg." },
  { question: "Quali formati retail sono disponibili?", answer: "Per prodotti selezionati si possono valutare buste da 100 g, 200 g, 500 g e 1 kg. Materiali, stampa e grafica vengono confermati per ogni ordine." },
  { question: "Fornite documentazione per l’esportazione in Italia?", answer: "Per ordini confermati coordiniamo, ove applicabili e disponibili, fattura commerciale, packing list, certificato di origine, documenti di spedizione, specifiche, COA e documenti qualità." },
  { question: "È possibile acquistare più categorie di prodotto?", answer: "Sì. Combinazioni, quantità minime, confezionamento, documentazione e fattibilità della spedizione vengono verificati prima della conferma commerciale." },
  { question: "Come può un acquirente italiano richiedere un preventivo?", answer: "Utilizzate la pagina Contatti indicando prodotto, quantità, formato, destinazione in Italia ed esigenze Private Label. Il team export valuterà la richiesta." },
];
const structuredData = { "@context": "https://schema.org", "@graph": [{ "@type": "WebPage", "@id": `${canonicalUrl}#webpage`, url: canonicalUrl, name: "Esportatore di henné, indigo, erbe e spezie in Italia", description: "Fornitura per l’Italia di henné, indigo, colorazioni botaniche, erbe ayurvediche e spezie indiane.", isPartOf: { "@id": "https://shiveshinternational.com/#website" }, about: { "@id": "https://shiveshinternational.com/#organization" }, breadcrumb: { "@id": `${canonicalUrl}#breadcrumb` }, inLanguage: "it" }, { "@type": "BreadcrumbList", "@id": `${canonicalUrl}#breadcrumb`, itemListElement: [{ "@type": "ListItem", position: 1, name: "Home", item: "https://shiveshinternational.com/" }, { "@type": "ListItem", position: 2, name: "Export", item: "https://shiveshinternational.com/export" }, { "@type": "ListItem", position: 3, name: "Europa", item: "https://shiveshinternational.com/export/europe" }, { "@type": "ListItem", position: 4, name: "Italia", item: canonicalUrl }] }] };
const faqStructuredData = { "@context": "https://schema.org", "@type": "FAQPage", "@id": `${canonicalUrl}#faq`, mainEntity: faqs.map((faq) => ({ "@type": "Question", name: faq.question, acceptedAnswer: { "@type": "Answer", text: faq.answer } })) };
function OptionalImage({ src, alt, priority = false }: { src: string; alt: string; priority?: boolean }) { if (!existsSync(`${process.cwd()}/public${src}`)) return null; return <Image src={src} alt={alt} fill priority={priority} sizes="(min-width: 1024px) 55vw, 100vw" className="object-contain object-center" />; }
const Heading = ({ eyebrow, children }: { eyebrow: string; children: React.ReactNode }) => <><p className="text-[10px] font-bold uppercase tracking-[0.4em] text-[#9F7F36]">{eyebrow}</p><h2 className="mt-6 font-[family-name:var(--font-playfair)] text-[clamp(2.4rem,4.7vw,4.7rem)] font-semibold leading-[1.04]">{children}</h2></>;

export default function ItalyExportPage() { return <main className="min-h-screen overflow-x-hidden bg-[#F5F0E6] text-[#173B2A]">
  <script type="application/ld+json" dangerouslySetInnerHTML={{ __html: JSON.stringify(structuredData).replace(/</g, "\\u003c") }} /><script type="application/ld+json" dangerouslySetInnerHTML={{ __html: JSON.stringify(faqStructuredData).replace(/</g, "\\u003c") }} /><Navbar />
  <section className="relative isolate overflow-hidden bg-[#071b14]"><OptionalImage src="/images/export/italy/italy-export-hero.png" alt="Acquirenti italiani esaminano henné, colorazioni botaniche e formulazioni naturali presso uno stabilimento indiano" priority /><div className="absolute inset-0 bg-gradient-to-r from-[#061711]/80 via-[#102F23]/45 to-transparent" /><GoldenParticles /><div className="relative z-10 px-6 pb-20 pt-32 sm:px-8 sm:pt-36 lg:px-12 lg:pb-28 lg:pt-40"><div className="max-w-[900px]"><p className="text-xs font-bold uppercase tracking-[0.38em] text-[#E4C878]">Esportazione dall’India verso l’Italia</p><h1 className="mt-5 font-[family-name:var(--font-playfair)] text-4xl font-medium leading-none text-[#F5F0E6] sm:text-5xl lg:text-6xl">Esportatore di prodotti naturali in Italia<span className="mt-2 block text-[#E4C878]">Henné, indigo, erbe e spezie</span></h1><p className="mt-5 max-w-[760px] text-[16px] leading-8 text-[#F5F0E6]/82">Shivesh International supporta importatori, distributori, grossisti, marchi di cosmetica, fornitori per saloni, aziende erboristiche e acquirenti Private Label con prodotti naturali pronti per l’esportazione dall’India.</p><div className="mt-7 flex flex-wrap gap-4"><Link href="/contact" className="bg-[#C9A962] px-7 py-4 text-[10px] font-bold uppercase tracking-[0.2em] text-[#102F23]">Invia una richiesta per l’Italia →</Link><a href="#prodotti-italia" className="border border-white/30 px-7 py-4 text-[10px] font-bold uppercase tracking-[0.2em] text-white">Esplora i prodotti ↓</a></div><div className="mt-10 grid max-w-[740px] grid-cols-2 gap-3 lg:grid-cols-4">{[["200 kg", "MOQ per prodotto"], ["Sfuso", "Fornitura all’ingrosso"], ["OEM", "Private Label"], ["Italia", "Richieste B2B"]].map(([v,l]) => <div key={l} className="border border-white/15 bg-black/20 p-4"><p className="text-xl font-semibold text-[#E4C878]">{v}</p><p className="mt-2 text-[9px] font-bold uppercase tracking-[0.2em] text-white/55">{l}</p></div>)}</div></div></div></section>
  <section className="px-6 py-24 lg:px-12 lg:py-32"><RevealOnScroll><div className="mx-auto max-w-[1120px]"><Heading eyebrow="Approvvigionamento India–Italia">Il vostro partner indiano per il mercato italiano</Heading><p className="mt-7 text-[16px] leading-8 text-[#4C5F54]">Importatori, distributori e grossisti possono coordinare più categorie con un unico team export indiano: cosmetica, cura naturale dei capelli, saloni, erboristeria, benessere, ingredienti alimentari, spezie, marchio proprio ed e-commerce.</p><p className="mt-5 text-[15px] leading-8 text-[#4C5F54]">Le richieste possono provenire da Milano, Roma, Bologna, Torino e Napoli. Disponibilità, specifiche, confezionamento, documentazione e spedizione vengono valutati secondo l’ordine concordato. Tali riferimenti non implicano uffici o magazzini Shivesh International in Italia.</p></div></RevealOnScroll></section>
  <section id="prodotti-italia" className="bg-[#EDE5D7] px-6 py-24 lg:px-12 lg:py-32"><div className="mx-auto max-w-[1500px]"><div className="text-center"><Heading eyebrow="Sei categorie commerciali">Prodotti adatti agli acquirenti italiani</Heading></div><div className="mt-14 grid gap-5 sm:grid-cols-2 lg:grid-cols-3">{products.map(([title,text,href],i)=><StaggerItem key={title} delay={(i%3)*90}><article className="flex h-full min-h-[300px] flex-col bg-[#FBF8F1] p-7"><span className="text-4xl text-[#C9A962]">{String(i+1).padStart(2,"0")}</span><h3 className="mt-6 text-2xl font-semibold">{title}</h3><p className="mt-5 flex-1 text-sm leading-7 text-[#4C5F54]">{text}</p><Link href={href} className="mt-7 text-[10px] font-bold uppercase tracking-[0.2em] text-[#A97B22]">Scopri {title} →</Link></article></StaggerItem>)}</div></div></section>
  <section className="bg-[#0B3325] px-6 py-24 text-white lg:px-12 lg:py-32"><div className="mx-auto max-w-[1500px]"><div className="text-center"><Heading eyebrow="Canali commerciali italiani">Fornitura di prodotti naturali per acquirenti B2B</Heading></div><div className="mt-14 grid gap-5 sm:grid-cols-2 lg:grid-cols-4">{buyers.map(([t,x])=><article key={t} className="border border-[#C9A962]/25 bg-[#071B14]/55 p-7"><h3 className="text-2xl font-semibold text-[#E4C878]">{t}</h3><p className="mt-4 text-sm leading-7 text-white/65">{x}</p></article>)}</div></div></section>
  <section className="px-6 py-24 lg:px-12 lg:py-32"><div className="mx-auto grid max-w-[1500px] gap-14 lg:grid-cols-[.7fr_1.3fr]"><div><Heading eyebrow="Impieghi commerciali">Applicazioni per il mercato italiano</Heading><p className="mt-7 leading-8 text-[#4C5F54]">Ogni richiesta viene valutata in base a uso previsto, specifiche, quantità, confezionamento e destinazione.</p></div><div className="grid gap-5 sm:grid-cols-2">{applications.map(([t,x])=><article key={t} className="bg-[#FBF8F1] p-7"><h3 className="text-2xl font-semibold">{t}</h3><p className="mt-4 text-sm leading-7 text-[#4C5F54]">{x}</p></article>)}</div></div></section>
  <section className="bg-[#EDE5D7] px-6 py-24 lg:px-12 lg:py-32"><div className="mx-auto grid max-w-[1500px] gap-14 lg:grid-cols-2"><div><Heading eyebrow="Formati con il marchio dell’acquirente">Confezionamento e soluzioni Private Label</Heading><p className="mt-7 leading-8 text-[#4C5F54]">I programmi selezionati possono comprendere marchio proprio, buste e astucci stampati, grafica fornita dall’acquirente, codici a barre, layout delle etichette e confezioni multilingue. Tutto resta soggetto ai requisiti concordati e alla fattibilità tecnica.</p><p className="mt-5 leading-7 text-[#4C5F54]">Formati retail: 100 g, 200 g, 500 g e 1 kg. Formati sfusi: 20 kg e 25 kg in buste sottovuoto a doppio strato. Etichette, lingua, dichiarazioni, classificazione e conformità restano responsabilità dell’acquirente.</p></div><div><figure className="relative aspect-[3/2] bg-[#173B2A]"><OptionalImage src="/images/export/italy/italy-buyer-partnership.png" alt="Acquirenti italiani e specialisti indiani sviluppano confezioni retail, sfuse e Private Label" /></figure><div className="mt-5 grid gap-5 sm:grid-cols-2"><article className="bg-white p-7"><h3 className="text-2xl font-semibold">Confezioni retail</h3><p className="mt-4">100 g · 200 g · 500 g · 1 kg</p></article><article className="bg-white p-7"><h3 className="text-2xl font-semibold">Confezioni sfuse</h3><p className="mt-4">20 kg e 25 kg, sottovuoto a doppio strato</p></article><article className="bg-[#173B2A] p-7 text-white sm:col-span-2"><p className="text-xs uppercase text-[#E4C878]">Quantitativo minimo d’ordine</p><p className="mt-4 text-4xl font-semibold">200 kg per prodotto</p></article></div></div></div></section>
  <section className="bg-[#09271D] px-6 py-24 text-white lg:px-12 lg:py-32"><div className="mx-auto max-w-[1500px]"><div className="grid items-center gap-14 lg:grid-cols-2"><div><Heading eyebrow="Supporto per spedizione e documenti">Coordinamento export dall’India all’Italia</Heading><p className="mt-7 leading-8 text-white/70">Il coordinamento può includere fattura commerciale, packing list, certificato di origine, specifiche, COA, documenti qualità disponibili, documenti di spedizione, spedizionieri nominati dall’acquirente, cartoni e pallet.</p><p className="mt-5 leading-8 text-white/65">Il trasporto marittimo o aereo può essere pianificato secondo termini commerciali confermati e disponibilità del vettore per Genova, La Spezia, Trieste, Milano o Roma. Non garantiamo rotte, tempi, tariffe, accettazione portuale o sdoganamento.</p></div><figure className="relative aspect-[3/2] bg-[#173B2A]"><OptionalImage src="/images/export/italy/india-to-italy-export-coordination.png" alt="Rappresentanti italiani e personale logistico indiano coordinano documenti e spedizioni" /></figure></div><aside className="mt-12 border border-[#C9A962]/35 p-7 text-sm leading-7 text-white/65">L’importatore o acquirente italiano resta responsabile della classificazione, etichettatura, registrazione, procedure doganali e requisiti applicabili nel mercato di destinazione.</aside></div></section>
  <section className="bg-[#EDE5D7] px-6 py-24 lg:px-12 lg:py-32"><div className="mx-auto max-w-[1500px]"><div className="text-center"><Heading eyebrow="Punti di forza commerciali">Perché gli acquirenti italiani scelgono Shivesh International</Heading></div><div className="mt-14 grid gap-5 sm:grid-cols-2 lg:grid-cols-3">{strengths.map(([t,x])=><article key={t} className="bg-white p-7"><h3 className="text-2xl font-semibold">{t}</h3><p className="mt-4 text-sm leading-7 text-[#4C5F54]">{x}</p></article>)}</div></div></section>
  <section className="px-6 py-24 lg:px-12 lg:py-32"><div className="mx-auto max-w-[1120px]"><Heading eyebrow="Mercati italiani">Richieste professionali da tutta Italia</Heading><p className="mt-7 leading-8 text-[#4C5F54]">Accogliamo richieste da attività di Milano, importatori e rivenditori di Roma, canali di Torino e Bologna, aziende erboristiche di Napoli, marchi di Firenze, operatori logistici di Genova e realtà commerciali di Venezia.</p><p className="mt-5 text-sm leading-7 text-[#4C5F54]">Le località indicano mercati potenziali e non rappresentano uffici, magazzini o rapporti di fornitura garantiti.</p><div className="mt-8 flex flex-wrap gap-3">{["Milano","Roma","Torino","Bologna","Napoli","Firenze","Genova","Venezia"].map(c=><span key={c} className="border border-[#C9A962]/40 px-5 py-3 text-xs font-bold uppercase">{c}</span>)}</div></div></section>
  <section className="bg-[#EDE5D7] px-6 py-24 lg:px-12 lg:py-32"><div className="mx-auto max-w-[1120px]"><div className="text-center"><Heading eyebrow="Domande degli acquirenti italiani">FAQ sulla fornitura export per l’Italia</Heading></div><div className="mt-12 divide-y divide-[#173B2A]/15 border-y border-[#173B2A]/15">{faqs.map(f=><article key={f.question} className="grid gap-4 py-7 md:grid-cols-[.8fr_1.2fr]"><h3 className="text-xl font-semibold">{f.question}</h3><p className="text-sm leading-7 text-[#4C5F54]">{f.answer}</p></article>)}</div></div></section>
  <section className="relative bg-[#071B14] px-6 py-24 text-center text-white"><GoldenParticles /><div className="relative mx-auto max-w-[1000px]"><Heading eyebrow="Richieste dall’Italia">Cercate un fornitore affidabile di prodotti naturali dall’India?</Heading><p className="mx-auto mt-7 max-w-[760px] leading-8 text-white/65">Comunicate prodotto, quantità, formato, destinazione in Italia ed esigenze Private Label al team export Shivesh International.</p><div className="mt-9 flex flex-wrap justify-center gap-4"><Link href="/contact" className="bg-[#C9A962] px-8 py-4 text-xs font-bold uppercase text-[#102F23]">Invia la tua richiesta →</Link><Link href="/export/europe" className="border border-white/30 px-8 py-4 text-xs font-bold uppercase">Esplora l’Europa →</Link></div></div></section>
  <FooterSection locale="it" /><FloatingContactButtons /><MagneticButtons /><PremiumCursor />
</main>; }
