import type { Metadata } from "next";
import { existsSync } from "node:fs";
import Image from "next/image";
import Link from "next/link";
import FloatingContactButtons from "@/app/components/FloatingContactButtons";
import GoldenParticles from "@/app/components/GoldenParticles";
import MagneticButtons from "@/app/components/MagneticButtons";
import Navbar from "@/app/components/Navbar";
import PremiumCursor from "@/app/components/PremiumCursor";
import RevealOnScroll from "@/app/components/RevealOnScroll";
import StaggerItem from "@/app/components/StaggerItem";
import FooterSection from "@/sections/FooterSection";

const canonicalUrl = "https://shiveshinternational.com/export/russia";
const heroImage = "/images/export/russia/russia-natural-products-export-hero.png";
const packagingImage = "/images/export/russia/russia-private-label-henna-indigo-buyers.png";
const coordinationImage = "/images/export/russia/india-to-russia-export-coordination.png";
const metadataKeywords = [
  "natural products exporter Russia", "natural products supplier Russia", "natural products manufacturer India for Russia", "Indian natural products exporter Russia", "bulk natural products Russia", "wholesale natural products Russia", "B2B natural products supplier Russia", "private label natural products Russia", "OEM natural products Russia", "India exporter to Russia",
  "henna exporter Russia", "henna powder exporter Russia", "natural henna powder supplier Russia", "henna manufacturer India for Russia", "bulk henna powder Russia", "wholesale henna powder Russia", "private label henna Russia", "henna importer Russia", "henna distributor Russia",
  "indigo powder exporter Russia", "natural indigo supplier Russia", "indigo powder manufacturer India for Russia", "bulk indigo powder Russia", "wholesale indigo powder Russia", "private label indigo Russia", "indigo importer Russia", "indigo distributor Russia",
  "natural henna hair colors Russia", "henna-based hair colors Russia", "botanical hair color supplier Russia", "natural hair color exporter Russia", "herbal hair color supplier Russia", "private label hair colors Russia", "OEM botanical hair colors Russia", "salon hair color supplier Russia",
  "Ayurvedic herbs exporter Russia", "Indian herbs supplier Russia", "herbal powder exporter Russia", "botanical ingredients supplier Russia", "bulk herbal powders Russia", "private label Ayurvedic herbs Russia", "wellness ingredient supplier Russia",
  "Indian spices exporter Russia", "Indian spices supplier Russia", "bulk Indian spices Russia", "wholesale spices Russia", "private label Indian spices Russia", "spice importer Russia", "spice distributor Russia", "Indian food ingredients Russia",
  "Russia natural product importer", "Russia natural product distributor", "Russia cosmetic ingredient buyer", "Russia natural cosmetic supplier", "Russia salon supplier", "Russia wellness product supplier", "Russia herbal wholesaler", "Russia private label supplier India", "Russia retail natural products supplier", "Russia e-commerce natural products supplier", "Russia food ingredient buyer", "Russia spice importer",
  "India to Russia natural products export", "India to Russia henna export", "India to Russia indigo export", "India to Russia herbs export", "India to Russia spices export", "natural products shipping India Russia", "export documentation support Russia", "bulk botanical products Russia", "Shivesh International Russia exporter",
];
export const metadata: Metadata = {
  title: { absolute: "Natural Products Exporter to Russia | Henna, Indigo, Herbs & Spices" },
  description: "Natural henna, indigo, botanical hair colors, Ayurvedic herbs and Indian spices for Russian importers, distributors, wholesalers and private-label buyers, subject to case-specific trade review. MOQ 200 kg per item.",
  keywords: metadataKeywords,
  alternates: { canonical: canonicalUrl },
  openGraph: { title: "Henna & Indigo Exporter to Russia | Shivesh International", description: "India-origin botanical products for professional Russian buyers, subject to product, compliance, banking, carrier and route feasibility.", url: canonicalUrl, type: "website", locale: "en_US", siteName: "Shivesh International", images: [{ url: heroImage, alt: "Indian natural-product export planning for professional buyers in Russia" }] },
  twitter: { card: "summary_large_image", title: "Natural Products Exporter to Russia", description: "Bulk and private-label botanical-product enquiries from Russian professional buyers, reviewed case by case.", images: [heroImage] },
  robots: { index: true, follow: true, googleBot: { index: true, follow: true } },
};
const products = [
  ["Natural Henna Powder", "Fine botanical powder for Russian hair-care businesses, ingredient buyers, specialist retailers and bulk repackers.", "/products/natural-henna-powder"],
  ["Natural Indigo Powder", "Natural indigo for suitable two-step hair-color ranges, professional beauty distribution and buyer-brand planning.", "/products/natural-indigo-powder"],
  ["Natural Henna Hair Colors", "Botanical powder shades for retail, e-commerce and natural hair-care portfolios, subject to confirmed requirements.", "/products/natural-henna-hair-colors"],
  ["Henna-Based Hair Colors", "Commercial shade concepts for salon suppliers, private-label companies and selected cosmetic ranges.", "/products/henna-based-hair-colors"],
  ["Ayurvedic Indian Herbs", "Selected Indian herbal powders for appropriate wellness, personal-care and specialist wholesale applications.", "/products/ayurvedic-indian-herbs"],
  ["Indian Spices", "Whole, ground and blended formats for Russian food importers, wholesalers and specialty retail businesses.", "/products/indian-spices"],
];
const buyers = [
  ["Importers & Distributors", "Assess specifications, trade eligibility and onward distribution requirements for professional channels."],
  ["Natural Cosmetic Companies", "Evaluate henna, indigo and herbal powders for suitable formulation or finished-product concepts."],
  ["Hair-Care Brands", "Plan botanical color assortments for salon, specialist retail and online customer segments."],
  ["Salon & Beauty Suppliers", "Review professional pack formats and repeat-volume needs for beauty-trade distribution."],
  ["Private-Label Companies", "Discuss buyer-brand artwork, labels, feasible pouch materials and commercially suitable quantities."],
  ["Herbal & Wellness Wholesalers", "Source selected Indian herbs for appropriate wholesale and natural-lifestyle ranges."],
  ["Retail & E-Commerce Businesses", "Consider retail-ready botanical and spice products for specialist physical or online stores."],
  ["Food & Spice Buyers", "Define grades, formats and commercial quantities for food-service, manufacturing or retail channels."],
];
const locations = [
  ["Moscow", "National head offices, import businesses, beauty brands and broad distribution networks may evaluate multi-category programmes."],
  ["Saint Petersburg", "Port-linked commerce, specialist retail and northwestern distribution can inform buyer-nominated supply planning."],
  ["Kazan", "Volga-region wholesalers, beauty businesses and food-sector buyers may assess regional product requirements."],
  ["Yekaterinburg", "Ural-region distribution, professional beauty and natural-product businesses can review suitable commercial formats."],
  ["Novosibirsk", "Siberian wholesale networks, specialist retailers and wellness businesses may consider regional supply programmes."],
  ["Samara", "Volga logistics, food businesses and regional distributors can evaluate bulk and retail-ready requirements."],
  ["Rostov-on-Don", "Southern-region wholesalers, food-sector buyers and beauty businesses may assess selected products and packs."],
  ["Vladivostok", "Far Eastern import and distribution context may be relevant only where buyer-nominated routes and trade conditions are feasible."],
];
const documents = [
  ["Commercial Invoice", "Prepared using confirmed products, quantities, values and legally permissible commercial terms."],
  ["Packing List", "May record package counts, weights, cartons, pallets and agreed shipment references."],
  ["Certificate of Origin", "May be coordinated where applicable and subject to issuing requirements and availability."],
  ["Transport Documents", "A Bill of Lading or Air Waybill depends on a confirmed, lawful and available shipment arrangement."],
  ["Product & Quality Records", "Specifications, COA or MSDS/SDS may be shared where applicable and available."],
  ["Agreed Export Records", "Other export-side documents may be reviewed transaction by transaction under applicable law."],
];
const steps = [
  ["Product Selection", "Define the product, intended use, Russian destination and expected commercial volume."],
  ["Specification Review", "Align requested parameters with available product information and destination requirements."],
  ["Commercial Confirmation", "Review trade feasibility, quantity, the 200 kg per-item MOQ, quotation and terms."],
  ["Packaging & Production", "Confirm feasible buyer-brand or bulk packing before any agreed production schedule."],
  ["Documentation", "Prepare applicable and available export-side records for the reviewed transaction."],
  ["Shipment Coordination", "Coordinate only a lawful, available arrangement with the buyer or nominated freight forwarder."],
];
const faqs = [
  { question: "What products do you export for Russian buyers?", answer: "Russian professional buyers may enquire about natural henna powder, indigo powder, natural henna hair colors, henna-based hair colors, Ayurvedic Indian herbs and Indian spices. Every transaction remains subject to product, party, trade, banking, carrier and route review." },
  { question: "What is your MOQ for Russia enquiries?", answer: "The minimum order quantity is 200 kg per selected product or item. Multi-product requirements and transaction feasibility are reviewed separately." },
  { question: "Do you offer private-label products for Russian buyers?", answer: "Buyer-brand packaging may be discussed for suitable products and quantities, subject to artwork, label, pack-size, technical, commercial and compliance feasibility." },
  { question: "What retail packaging sizes are available?", answer: "Depending on the product and confirmed feasibility, retail formats may include 100 g, 200 g, 500 g and 1 kg." },
  { question: "Do you offer bulk packaging?", answer: "Bulk formats may include 20 kg and 25 kg packs, including double-layer vacuum packaging where appropriate for the product and order." },
  { question: "Can you support Russian importers and distributors?", answer: "Professional buyers can submit company, ownership, product, intended-use, specification, quantity, packaging and destination details for case-specific review. An enquiry does not confirm that a transaction is permitted or feasible." },
  { question: "What export documents can you coordinate?", answer: "Subject to applicability, availability and law, records may include an invoice, packing list, certificate of origin, transport document, specification, COA or MSDS/SDS." },
  { question: "How is shipment planning for Russia handled?", answer: "Saint Petersburg, Vladivostok, Moscow-area cargo coordination or another buyer-nominated destination may be assessed only after case-specific route, carrier, party and legal review. No shipping pathway or availability is guaranteed." },
  { question: "Who is responsible for Russian import, compliance and trade restrictions?", answer: "The Russian importer or buyer must confirm classification, eligibility, declarations, permits, labeling, customs, sanctions, restricted-party, banking, payment, carrier, route and all local requirements with qualified advisers before ordering." },
  { question: "How can a Russian buyer request a quotation?", answer: "Send company and ownership details, product, intended use, specification, quantity, packaging and destination information. A quotation or transaction can proceed only after applicable case-specific reviews." },
];
const structuredData = { "@context": "https://schema.org", "@graph": [
  { "@type": "WebPage", "@id": `${canonicalUrl}#webpage`, url: canonicalUrl, name: "Natural Products Exporter to Russia", description: "Russia-focused B2B enquiry information for natural henna, indigo, botanical hair colors, Ayurvedic herbs and Indian spices from India, subject to case-specific trade review.", isPartOf: { "@id": "https://shiveshinternational.com/#website" }, about: { "@id": "https://shiveshinternational.com/#organization" }, breadcrumb: { "@id": `${canonicalUrl}#breadcrumb` }, primaryImageOfPage: { "@type": "ImageObject", url: heroImage }, inLanguage: "en" },
  { "@type": "BreadcrumbList", "@id": `${canonicalUrl}#breadcrumb`, itemListElement: [{ "@type": "ListItem", position: 1, name: "Home", item: "https://shiveshinternational.com/" }, { "@type": "ListItem", position: 2, name: "Export", item: "https://shiveshinternational.com/export" }, { "@type": "ListItem", position: 3, name: "Europe", item: "https://shiveshinternational.com/export/europe" }, { "@type": "ListItem", position: 4, name: "Russia", item: canonicalUrl }] },
] };
const faqStructuredData = { "@context": "https://schema.org", "@type": "FAQPage", "@id": `${canonicalUrl}#faq`, mainEntity: faqs.map((faq) => ({ "@type": "Question", name: faq.question, acceptedAnswer: { "@type": "Answer", text: faq.answer } })) };
function OptionalImage({ src, alt, priority = false, className = "object-contain object-center" }: { src: string; alt: string; priority?: boolean; className?: string }) { if (!existsSync(`${process.cwd()}/public${src}`)) return null; return <Image src={src} alt={alt} fill priority={priority} sizes="(min-width: 1024px) 50vw, 100vw" className={className} />; }
function Cards({ items, columns = "lg:grid-cols-4" }: { items: string[][]; columns?: string }) { return <div className={`mt-14 grid auto-rows-fr gap-5 sm:grid-cols-2 ${columns}`}>{items.map(([title, text]) => <article key={title} className="h-full border border-[#173B2A]/12 bg-[#FBF8F1] p-7 sm:p-8"><span className="block h-px w-12 bg-[#C9A962]" /><h3 className="mt-5 font-[family-name:var(--font-playfair)] text-2xl font-semibold">{title}</h3><p className="mt-4 text-sm font-light leading-7 text-[#4C5F54]">{text}</p></article>)}</div>; }

export default function RussiaExportPage() { return <main className="min-h-screen overflow-x-hidden bg-[#F5F0E6] text-[#173B2A]">
  <script type="application/ld+json" dangerouslySetInnerHTML={{ __html: JSON.stringify(structuredData).replace(/</g, "\\u003c") }} /><script type="application/ld+json" dangerouslySetInnerHTML={{ __html: JSON.stringify(faqStructuredData).replace(/</g, "\\u003c") }} /><Navbar />
  <section className="relative isolate overflow-hidden bg-[#071B14]"><OptionalImage src={heroImage} alt="Indian henna, indigo, herbs and spices prepared for professional Russia supply enquiries" priority className="object-cover object-center" /><div className="absolute inset-0 bg-gradient-to-r from-[#061711]/85 via-[#102F23]/58 to-[#071B14]/35" /><GoldenParticles /><div className="relative z-10 flex items-center px-6 pb-20 pt-32 sm:px-8 sm:pb-24 sm:pt-36 lg:px-12 lg:pb-28 lg:pt-40"><div className="w-full max-w-[950px]"><StaggerItem delay={0}><p className="text-[10px] font-bold uppercase tracking-[0.38em] text-[#E4C878] sm:text-xs">India to Russia B2B Supply</p></StaggerItem><StaggerItem delay={100}><h1 className="mt-5 font-[family-name:var(--font-playfair)] text-4xl font-medium leading-[1.02] tracking-[-0.04em] text-[#F5F0E6] sm:text-5xl lg:text-6xl xl:text-[66px]">Natural Henna, Indigo, Herbs &amp; Spices <span className="block bg-gradient-to-r from-[#F5F0E6] via-[#E4C878] to-[#C9A962] bg-clip-text text-transparent">Exporter to Russia</span></h1></StaggerItem><StaggerItem delay={200}><p className="mt-5 max-w-[820px] text-[16px] font-light leading-8 text-white/82">Shivesh International reviews enquiries for natural henna powder, natural indigo powder, botanical hair colors, Ayurvedic herbs and Indian spices from Russian importers, distributors, wholesalers, private-label brands, beauty businesses and professional buyers, subject to case-specific feasibility.</p></StaggerItem><StaggerItem delay={300}><div className="mt-7 flex flex-wrap gap-4"><Link href="/contact" className="border border-[#C9A962] bg-[#C9A962] px-7 py-4 text-[10px] font-bold uppercase tracking-[0.2em] text-[#102F23]">Send Russia Inquiry →</Link><a href="#products" className="border border-white/30 bg-[#102F23]/40 px-7 py-4 text-[10px] font-bold uppercase tracking-[0.2em] text-white">Explore Export Products ↓</a></div></StaggerItem><StaggerItem delay={400}><div className="mt-10 grid max-w-[760px] grid-cols-2 gap-3 lg:grid-cols-4">{[["200 kg", "MOQ per item"], ["Bulk", "B2B supply"], ["Private Label", "Buyer-brand packs"], ["Export", "Coordination"]].map(([value, label]) => <div key={label} className="border border-white/15 bg-black/20 p-4"><p className="font-[family-name:var(--font-playfair)] text-xl font-semibold text-[#E4C878]">{value}</p><p className="mt-2 text-[9px] uppercase tracking-[0.22em] text-white/55">{label}</p></div>)}</div></StaggerItem></div></div></section>
  <section className="px-6 py-24 sm:px-8 lg:px-12 lg:py-32"><RevealOnScroll><div className="mx-auto max-w-[1200px]"><p className="text-[10px] font-bold uppercase tracking-[0.4em] text-[#9F7F36]">Russia Market Enquiries</p><h2 className="mt-6 font-[family-name:var(--font-playfair)] text-[clamp(2.3rem,4.6vw,4.6rem)] font-semibold">Indian Botanical Supply <span className="block text-[#A97B22]">for Professional Russian Buyers</span></h2><p className="mt-7 text-[16px] font-light leading-8 text-[#4C5F54]">Product programmes may involve botanical hair color, natural cosmetic ingredients, wellness ranges, buyer-brand packs, bulk inputs and Indian food ingredients. Commercial discussions remain conditional on intended use, specification, quantity, parties, destination, applicable trade rules, banking, carrier and route feasibility.</p></div></RevealOnScroll></section>
  <section id="products" className="bg-[#EDE5D7] px-6 py-24 sm:px-8 lg:px-12 lg:py-32"><RevealOnScroll><div className="mx-auto max-w-[1500px]"><div className="text-center"><p className="text-[10px] uppercase tracking-[0.4em] text-[#9F7F36]">Six Export Product Categories</p><h2 className="mt-6 font-[family-name:var(--font-playfair)] text-[clamp(2.3rem,4.8vw,4.8rem)] font-semibold">Products for Russian <span className="block text-[#A97B22]">Commercial Enquiries</span></h2></div><div className="mt-14 grid auto-rows-fr gap-5 sm:grid-cols-2 lg:grid-cols-3">{products.map(([title, text, href]) => <article key={title} className="flex h-full flex-col border border-[#173B2A]/12 bg-[#FBF8F1] p-8"><span className="block h-px w-12 bg-[#C9A962]" /><h3 className="mt-5 font-[family-name:var(--font-playfair)] text-2xl font-semibold">{title}</h3><p className="mt-4 flex-1 text-sm font-light leading-7 text-[#4C5F54]">{text}</p><Link href={href} className="mt-7 text-[10px] font-bold uppercase tracking-[0.2em] text-[#A97B22]">View Product →</Link></article>)}</div></div></RevealOnScroll></section>
  <section className="px-6 py-24 sm:px-8 lg:px-12 lg:py-32"><RevealOnScroll><div className="mx-auto max-w-[1500px]"><p className="text-center text-[10px] uppercase tracking-[0.4em] text-[#9F7F36]">Professional Buyer Profiles</p><h2 className="mt-6 text-center font-[family-name:var(--font-playfair)] text-[clamp(2.3rem,4.6vw,4.6rem)] font-semibold">Commercial Buyers <span className="block text-[#A97B22]">Who May Enquire</span></h2><Cards items={buyers} /></div></RevealOnScroll></section>
  <section className="bg-[#0B3325] px-6 py-24 text-[#F5F0E6] sm:px-8 lg:px-12 lg:py-32"><RevealOnScroll><div className="mx-auto max-w-[1500px]"><p className="text-center text-[10px] uppercase tracking-[0.4em] text-[#E4C878]">Major Russian Commercial Locations</p><h2 className="mt-6 text-center font-[family-name:var(--font-playfair)] text-[clamp(2.3rem,4.6vw,4.6rem)] font-semibold">Buyer and Distribution Context <span className="block text-[#E4C878]">Across Russia</span></h2><div className="[&_article]:border-white/12 [&_article]:bg-white/[0.04] [&_article_h3]:text-[#F5F0E6] [&_article_p]:text-white/65"><Cards items={locations} /></div><p className="mx-auto mt-10 max-w-[1080px] border border-[#C9A962]/25 bg-black/15 p-6 text-center text-sm font-light leading-7 text-white/65">These locations identify potential commercial and distribution contexts only. They do not represent a Shivesh International office, branch, warehouse, stock, inventory, agent, current buyer, exclusive distributor, guaranteed relationship or exclusive territory.</p></div></RevealOnScroll></section>
  <section className="px-6 py-24 sm:px-8 lg:px-12 lg:py-32"><RevealOnScroll><div className="mx-auto grid max-w-[1400px] items-center gap-14 lg:grid-cols-2"><div><p className="text-[10px] font-bold uppercase tracking-[0.4em] text-[#9F7F36]">Packaging &amp; Private Label</p><h2 className="mt-6 font-[family-name:var(--font-playfair)] text-[clamp(2.3rem,4.5vw,4.5rem)] font-semibold">Commercial Packs for <span className="block text-[#A97B22]">Confirmed Requirements</span></h2><p className="mt-7 text-[16px] font-light leading-8 text-[#4C5F54]">Retail formats may include 100 g, 200 g, 500 g and 1 kg packs. Silver or gold metallized pouches, buyer-brand packaging, artwork coordination, label coordination and retail-ready formats may be reviewed for suitable products and quantities.</p><p className="mt-5 text-[16px] font-light leading-8 text-[#4C5F54]">Bulk supply may include 20 kg and 25 kg packs, with double-layer vacuum packaging where applicable. MOQ is 200 kg per item. Final availability depends on the product, pack-size feasibility, technical feasibility, artwork and order quantity; not every format suits every product, and Russian regulatory acceptance is not promised.</p></div><div className="relative aspect-[4/3] overflow-hidden border border-[#C9A962]/30 bg-[#102F23]"><OptionalImage src={packagingImage} alt="Private-label henna and indigo packaging planning for Russian professional buyers" /></div></div></RevealOnScroll></section>
  <section className="bg-[#EDE5D7] px-6 py-24 sm:px-8 lg:px-12 lg:py-32"><RevealOnScroll><div className="mx-auto grid max-w-[1400px] items-center gap-14 lg:grid-cols-2"><div className="relative aspect-[4/3] overflow-hidden border border-[#C9A962]/30 bg-[#102F23]"><OptionalImage src={coordinationImage} alt="India to Russia export-side document and shipment planning" /></div><div><p className="text-[10px] font-bold uppercase tracking-[0.4em] text-[#9F7F36]">Case-Specific Feasibility</p><h2 className="mt-6 font-[family-name:var(--font-playfair)] text-[clamp(2.3rem,4.5vw,4.5rem)] font-semibold">Structured Export Coordination <span className="block text-[#A97B22]">for Russia</span></h2><p className="mt-7 text-[16px] font-light leading-8 text-[#4C5F54]">Where legally permissible and feasible, coordination may cover product selection, specification confirmation, quotation, commercial terms, packaging or private-label confirmation, production, quality checks, export documentation, shipment planning, dispatch, document sharing and alignment with the buyer or nominated freight forwarder.</p><p className="mt-5 text-[16px] font-light leading-8 text-[#4C5F54]">Saint Petersburg, Vladivostok, Moscow-area cargo coordination or another buyer-nominated destination may be assessed case by case. No route, carrier, port, payment channel, transit pathway, freight rate, vessel or airline schedule, transit time, customs clearance, import approval, registration, inspection, delivery, regulatory acceptance, payment acceptance or banking availability is guaranteed or represented as currently available.</p></div></div></RevealOnScroll></section>
  <section className="px-6 py-24 sm:px-8 lg:px-12 lg:py-32"><RevealOnScroll><div className="mx-auto max-w-[1500px]"><div className="text-center"><p className="text-[10px] uppercase tracking-[0.4em] text-[#9F7F36]">Transaction-Wise Records</p><h2 className="mt-6 font-[family-name:var(--font-playfair)] text-[clamp(2.3rem,4.6vw,4.6rem)] font-semibold">Export-Side Document <span className="block text-[#A97B22]">Coordination</span></h2></div><Cards items={documents} columns="lg:grid-cols-3" /></div></RevealOnScroll></section>
  <section className="bg-[#0B3325] px-6 py-24 text-[#F5F0E6] sm:px-8 lg:px-12 lg:py-28"><RevealOnScroll><div className="mx-auto max-w-[1200px]"><p className="text-[10px] font-bold uppercase tracking-[0.4em] text-[#E4C878]">Importer Responsibility Notice</p><h2 className="mt-6 font-[family-name:var(--font-playfair)] text-[clamp(2.2rem,4.2vw,4.2rem)] font-semibold">Compliance and Trade Review <span className="block text-[#E4C878]">Before Any Transaction</span></h2><p className="mt-7 text-[16px] font-light leading-8 text-white/70">The Russian importer or buyer is responsible for confirming product classification, intended use, ingredient restrictions, import eligibility, registrations, permits, declarations, filings, labeling, language requirements, claims, testing, inspection, customs requirements, local regulations, applicable trade restrictions, sanctions and restricted-party requirements, payment and banking eligibility, and route and carrier availability.</p><p className="mt-5 text-[16px] font-light leading-8 text-white/70">Shivesh International may coordinate export-side documentation only for an agreed transaction and in accordance with applicable law. Nothing on this page states that a Russia transaction is legally permitted without case-specific review, constitutes legal advice, or claims legal, customs, banking or regulatory approval. No third-country routing, transshipment, payment workaround or other means to bypass restrictions is recommended or supported.</p></div></RevealOnScroll></section>
  <section className="px-6 py-24 sm:px-8 lg:px-12 lg:py-32"><RevealOnScroll><div className="mx-auto max-w-[1500px]"><div className="text-center"><p className="text-[10px] uppercase tracking-[0.4em] text-[#9F7F36]">Six-Step Workflow</p><h2 className="mt-6 font-[family-name:var(--font-playfair)] text-[clamp(2.3rem,4.6vw,4.6rem)] font-semibold">From Enquiry to <span className="block text-[#A97B22]">Conditional Coordination</span></h2></div><div className="mt-14 grid auto-rows-fr gap-5 sm:grid-cols-2 lg:grid-cols-3">{steps.map(([title, text], index) => <article key={title} className="border border-[#173B2A]/12 bg-[#FBF8F1] p-8"><p className="text-[10px] font-bold uppercase tracking-[0.25em] text-[#A97B22]">Step {String(index + 1).padStart(2, "0")}</p><h3 className="mt-5 font-[family-name:var(--font-playfair)] text-2xl font-semibold">{title}</h3><p className="mt-4 text-sm font-light leading-7 text-[#4C5F54]">{text}</p></article>)}</div></div></RevealOnScroll></section>
  <section className="bg-[#EDE5D7] px-6 py-24 sm:px-8 lg:px-12 lg:py-32"><RevealOnScroll><div className="mx-auto max-w-[1200px]"><div className="text-center"><p className="text-[10px] uppercase tracking-[0.4em] text-[#9F7F36]">Buyer Questions</p><h2 className="mt-6 font-[family-name:var(--font-playfair)] text-[clamp(2.3rem,4.6vw,4.6rem)] font-semibold">Russia Export <span className="block text-[#A97B22]">Frequently Asked Questions</span></h2></div><div className="mt-14 grid gap-5 lg:grid-cols-2">{faqs.map((faq) => <article key={faq.question} className="border border-[#173B2A]/12 bg-[#FBF8F1] p-7 sm:p-8"><h3 className="font-[family-name:var(--font-playfair)] text-xl font-semibold">{faq.question}</h3><p className="mt-4 text-sm font-light leading-7 text-[#4C5F54]">{faq.answer}</p></article>)}</div></div></RevealOnScroll></section>
  <section className="bg-[#071B14] px-6 py-24 text-center text-[#F5F0E6] sm:px-8 lg:px-12"><RevealOnScroll><div className="mx-auto max-w-[950px]"><p className="text-[10px] font-bold uppercase tracking-[0.4em] text-[#E4C878]">Submit Requirements for Review</p><h2 className="mt-6 font-[family-name:var(--font-playfair)] text-[clamp(2.4rem,5vw,5rem)] font-semibold">Planning a Russia <span className="block text-[#E4C878]">Commercial Enquiry?</span></h2><p className="mx-auto mt-7 max-w-[800px] text-[16px] font-light leading-8 text-white/65">Share company and ownership details, product, intended use, specification, quantity, packaging and destination. Submission does not confirm transaction, banking, carrier, route, import or regulatory feasibility.</p><Link href="/contact" className="mt-9 inline-flex border border-[#C9A962] bg-[#C9A962] px-8 py-4 text-[10px] font-bold uppercase tracking-[0.2em] text-[#102F23]">Send Russia Inquiry →</Link></div></RevealOnScroll></section>
  <FooterSection /><FloatingContactButtons /><MagneticButtons /><PremiumCursor />
</main>; }
