import type { Metadata } from "next";
import Image from "next/image";
import Link from "next/link";

import FloatingContactButtons from "@/app/components/FloatingContactButtons";
import GoldenParticles from "@/app/components/GoldenParticles";
import MagneticButtons from "@/app/components/MagneticButtons";
import Navbar from "@/app/components/Navbar";
import PremiumCursor from "@/app/components/PremiumCursor";
import RevealOnScroll from "@/app/components/RevealOnScroll";
import StaggerItem from "@/app/components/StaggerItem";
import { uaeLanguageAlternates } from "@/app/lib/i18n";
import FooterSection from "@/sections/FooterSection";

const canonicalUrl = "https://shiveshinternational.com/ar/export/uae";
const heroImage = "/images/export/uae/uae-export-partnership-hero-premium-v1.png";

export const metadata: Metadata = {
  title: "مُصدّر المنتجات الطبيعية إلى الإمارات | شيفيش إنترناشيونال",
  description: "مُصدّر هندي للحناء والنيلة وألوان الشعر النباتية والأعشاب الأيورفيدية والتوابل للمشترين بالجملة والعلامات الخاصة في الإمارات. الحد الأدنى 200 كجم للصنف.",
  keywords: ["مُصدّر منتجات طبيعية إلى الإمارات", "مورد حناء طبيعي في الإمارات", "مورد مسحوق النيلة في دبي", "ألوان شعر نباتية بالجملة", "أعشاب أيورفيدية هندية", "توابل هندية بالجملة في الإمارات", "منتجات طبيعية بعلامة خاصة", "تصنيع OEM في الهند للإمارات", "تغليف علامة خاصة في الإمارات", "تصدير منتجات طبيعية من الهند إلى الإمارات"],
  alternates: { canonical: canonicalUrl, languages: uaeLanguageAlternates },
  openGraph: { title: "مُصدّر المنتجات الطبيعية إلى الإمارات العربية المتحدة", description: "توريد هندي بالجملة وبنظام OEM والعلامة الخاصة للحناء والنيلة وألوان الشعر النباتية والأعشاب والتوابل للمشترين المهنيين في الإمارات.", url: canonicalUrl, type: "website", locale: "ar_AE", siteName: "Shivesh International", images: [{ url: heroImage, width: 1536, height: 1024, alt: "شركاء أعمال في الإمارات والهند ينسقون توريد المنتجات الطبيعية" }] },
  twitter: { card: "summary_large_image", title: "مُصدّر المنتجات الطبيعية إلى الإمارات", description: "حناء ونيلة وألوان نباتية وأعشاب وتوابل هندية للمستوردين والعلامات الخاصة في الإمارات.", images: [heroImage] },
  robots: { index: true, follow: true, googleBot: { index: true, follow: true, "max-image-preview": "large", "max-snippet": -1, "max-video-preview": -1 } },
};

const products = [
  { title: "مسحوق الحناء الطبيعي", text: "مسحوق حناء بمستوى تصديري لتلبية متطلبات شركات مستحضرات التجميل والصالونات والعلامات الخاصة في الإمارات، ضمن عبوات سائبة أو مخصصة متفق عليها.", href: "/products/natural-henna-powder" },
  { title: "مسحوق النيلة الطبيعي", text: "مسحوق نيلة طبيعي لمجموعات صبغات الشعر النباتية المهنية، بمواصفات وتعبئة تُحدد وفق الطلب المؤكد للمشتري في الإمارات.", href: "/products/natural-indigo-powder" },
  { title: "ألوان الشعر الطبيعية بالحناء", text: "ألوان شعر نباتية للموزعين وموردي الصالونات والعلامات التي تطور مجموعات مهنية أو للبيع بالتجزئة بمظهر طبيعي.", href: "/products/natural-henna-hair-colors" },
  { title: "ألوان الشعر القائمة على الحناء", text: "خيارات تجارية لألوان الشعر القائمة على الحناء لقنوات الصالونات والتجزئة، رهناً بجدوى المنتج والتعبئة والتصميم.", href: "/products/henna-based-hair-colors" },
  { title: "الأعشاب الأيورفيدية الهندية", text: "أعشاب أيورفيدية ومساحيق نباتية مختارة لبرامج العافية والعناية الشخصية والتوريد بعلامة خاصة في الإمارات.", href: "/products/ayurvedic-indian-herbs" },
  { title: "التوابل الهندية", text: "توابل هندية كاملة ومطحونة للمستوردين وتجار الجملة وشركات الأغذية ومتطلبات التعبئة المعتمدة بعلامة المشتري.", href: "/products/indian-spices" },
];
const buyerTypes = ["المستوردون", "الموزعون", "تجار الجملة", "موردو الصالونات", "علامات مستحضرات التجميل", "علامات العناية بالشعر", "سلاسل التجزئة", "شركات العافية", "مشترون بعلامة خاصة"];
const supplyServices = [
  ["التوريد السائب وبالجملة", "يمكن تجهيز الكميات التجارية في عبوات سائبة أو مهنية أو مختارة للبيع بالتجزئة. الحد الأدنى للطلب هو 200 كجم لكل صنف."],
  ["التصنيع للغير والعلامة الخاصة", "يمكن للمشترين المؤهلين مناقشة منتجات مختارة تحت علامتهم، مع مراجعة جدوى التركيبة أو المجموعة قبل التأكيد التجاري."],
  ["التعبئة المخصصة", "يمكن تنسيق أحجام العبوات والأكياس والكرتون والملصقات والتصاميم المقدمة من المشتري، وفق الملاءمة الفنية والكمية وجدوى الطباعة."],
  ["المواصفات والمستندات", "تُراجع مواصفات المنتجات المتاحة والمستندات التجارية ذات الصلة وفق المنتج والاستخدام المقصود والشحنة ومتطلبات المشتري."],
];
const process = [
  ["01", "مراجعة المنتج والكمية", "نراجع المنتج والدرجة والاستخدام المقصود والكمية التجارية ومتطلبات الحد الأدنى للطلب."],
  ["02", "مناقشة المواصفات والعينات", "تُناقش المواصفات والعينات المتاحة وأشكال التعبئة والمتطلبات الخاصة بالمشتري قبل التأكيد التجاري."],
  ["03", "عرض السعر والشروط التجارية", "تُراجع الأسعار ونطاق الإنتاج وشروط الدفع وتفاصيل التعبئة وشروط الشحن المنطبقة مع المشتري."],
  ["04", "تنسيق التعبئة والتصميم", "تُنسق العبوات السائبة أو التجارية أو المهنية أو الخاصة وفق الجدوى والتصميم المقدم من المشتري."],
  ["05", "الإنتاج ومراجعة الجودة", "تُجهز المنتجات المؤكدة وتُعبأ وتُراجع وفق المواصفات المتفق عليها ومتطلبات الطلب."],
  ["06", "مستندات التصدير وتنسيق الإرسال", "تُجهز المستندات التجارية ومعلومات التعبئة وتنسيق الشحنة وفق الطلب المؤكد وشروط التسليم المتفق عليها."],
];
const faqs = [
  { question: "ما المنتجات الطبيعية التي يمكن توريدها للمشترين في الإمارات؟", answer: "تشمل المجموعة مسحوق الحناء الطبيعي ومسحوق النيلة الطبيعي وألوان الشعر الطبيعية بالحناء وألوان الشعر القائمة على الحناء والأعشاب الأيورفيدية الهندية والتوابل الهندية، رهناً بالجدوى التجارية." },
  { question: "ما الحد الأدنى للطلب للمشترين في الإمارات؟", answer: "الحد الأدنى للطلب هو 200 كجم لكل صنف. وقد تؤثر التعبئة واختيار المنتج ومتطلبات العلامة الخاصة في الكمية التجارية العملية." },
  { question: "هل يمكنكم التوريد للمستوردين وتجار الجملة وموردي الصالونات في الإمارات؟", answer: "نعم. نرحب باستفسارات المستوردين والموزعين وتجار الجملة وموردي الصالونات وعلامات مستحضرات التجميل والعناية بالشعر وشركات العافية وسلاسل التجزئة ومشتري العلامات الخاصة في أنحاء الإمارات." },
  { question: "هل تتوفر خدمات OEM أو التعبئة بعلامة خاصة؟", answer: "يتوفر دعم التصنيع للغير والعلامة الخاصة لمنتجات مختارة. ويمكن مناقشة عبوات التجزئة والعبوات المهنية والسائبة وفق المنتج والكمية والخامة وجدوى الطباعة." },
  { question: "هل يمكن للمشترين في الإمارات تقديم تصاميم العبوات الخاصة بهم؟", answer: "يمكن مراجعة التصاميم المقدمة من المشتري لعبوات مختارة. ويجب تقييم قوالب القص ومحتوى الملصق وحجم العبوة والخامات وكميات الطباعة ومتطلبات كرتون التصدير قبل التأكيد." },
  { question: "هل يمكن مناقشة العينات ومواصفات المنتجات؟", answer: "يمكن مناقشة العينات والمواصفات والدرجات وأشكال التعبئة المتاحة قبل التأكيد التجاري. ويعتمد التوفر على المنتج المختار ومتطلبات المشتري." },
  { question: "ما المستندات التجارية التي يمكن تنسيقها؟", answer: "تُناقش المستندات التجارية ومستندات الشحن ذات الصلة ومواصفات المنتج ومعلومات التعبئة للطلب المؤكد. ويعتمد توفرها وانطباقها على المنتج والمعاملة." },
  { question: "من المسؤول عن التسجيل والجمارك والامتثال في الإمارات؟", answer: "يتحمل المستورد أو المشتري في الإمارات مسؤولية تصنيف المنتج والتسجيل عند انطباقه والتخليص الجمركي والملصقات والادعاءات والامتثال للمتطلبات الإماراتية المنطبقة. ولا نضمن الموافقة أو أهلية الاستيراد." },
];
const structuredData = { "@context": "https://schema.org", "@graph": [
  { "@type": "WebPage", "@id": `${canonicalUrl}#webpage`, url: canonicalUrl, name: "مُصدّر المنتجات الطبيعية إلى الإمارات العربية المتحدة", description: "توريد الحناء والنيلة وألوان الشعر النباتية والأعشاب الأيورفيدية والتوابل الهندية بالجملة والعلامة الخاصة إلى المشترين في الإمارات.", isPartOf: { "@id": "https://shiveshinternational.com/#website" }, about: { "@id": "https://shiveshinternational.com/#organization" }, breadcrumb: { "@id": `${canonicalUrl}#breadcrumb` }, primaryImageOfPage: { "@type": "ImageObject", url: `https://shiveshinternational.com${heroImage}`, width: 1536, height: 1024 }, inLanguage: "ar-AE" },
  { "@type": "Service", "@id": `${canonicalUrl}#service`, name: "توريد المنتجات الطبيعية للتصدير إلى الإمارات", serviceType: "توريد المنتجات الطبيعية بالجملة وبنظام OEM والعلامة الخاصة", url: canonicalUrl, provider: { "@id": "https://shiveshinternational.com/#organization" }, areaServed: { "@type": "Country", name: "الإمارات العربية المتحدة", sameAs: "https://www.wikidata.org/wiki/Q878" } },
  { "@type": "BreadcrumbList", "@id": `${canonicalUrl}#breadcrumb`, itemListElement: [{ "@type": "ListItem", position: 1, name: "الرئيسية", item: "https://shiveshinternational.com/" }, { "@type": "ListItem", position: 2, name: "التصدير", item: "https://shiveshinternational.com/export" }, { "@type": "ListItem", position: 3, name: "التصدير إلى الإمارات", item: canonicalUrl }] },
] };
const faqStructuredData = { "@context": "https://schema.org", "@type": "FAQPage", "@id": `${canonicalUrl}#faq`, mainEntity: faqs.map((faq) => ({ "@type": "Question", name: faq.question, acceptedAnswer: { "@type": "Answer", text: faq.answer } })) };

export default function ArabicUAEExportPage() {
  return <main className="min-h-screen overflow-x-hidden bg-[#F5F0E6] text-right text-[#173B2A]">
    <script type="application/ld+json" dangerouslySetInnerHTML={{ __html: JSON.stringify(structuredData).replace(/</g, "\\u003c") }} /><script type="application/ld+json" dangerouslySetInnerHTML={{ __html: JSON.stringify(faqStructuredData).replace(/</g, "\\u003c") }} /><Navbar />
    <section className="relative isolate overflow-hidden bg-[#071B14]"><Image src={heroImage} alt="شركاء أعمال من الهند والإمارات يطورون توريد المنتجات الطبيعية للتصدير" fill priority sizes="100vw" className="object-cover object-[62%_center] sm:object-[56%_center] lg:object-center" /><div className="absolute inset-0 bg-gradient-to-l from-[#061711]/55 via-[#102F23]/24 to-transparent" /><GoldenParticles /><div className="relative z-10 flex min-h-[760px] items-center px-6 pb-24 pt-28 sm:min-h-[800px] sm:px-8 lg:min-h-[820px] lg:px-12"><div className="mr-auto w-full max-w-[790px]"><StaggerItem delay={0}><p className="text-xs font-bold text-[#E4C878]">من الهند إلى الإمارات العربية المتحدة</p></StaggerItem><StaggerItem delay={100}><h1 className="mt-6 text-[clamp(2.8rem,5.4vw,5.4rem)] font-semibold leading-[1.18] text-[#F5F0E6]">توريد المنتجات الطبيعية <span className="mt-2 block text-[#E4C878]">للأعمال في الإمارات</span></h1></StaggerItem><StaggerItem delay={200}><p className="mt-7 max-w-[700px] text-[17px] font-light leading-9 text-[#F5F0E6]/80">تورد شيفيش إنترناشيونال الحناء والنيلة وألوان الشعر النباتية والأعشاب الأيورفيدية والتوابل الهندية للمستوردين والموزعين وتجار الجملة وموردي الصالونات والعلامات التجارية ومشتري العلامات الخاصة في دبي وسائر الإمارات.</p></StaggerItem><StaggerItem delay={300}><div className="mt-9 flex flex-wrap gap-4"><a href="#uae-product-range" className="inline-flex items-center gap-4 border border-[#C9A962] bg-[#C9A962] px-7 py-4 text-sm font-bold text-[#102F23]">استكشف المجموعة <span>↓</span></a><Link href="/contact" className="inline-flex items-center border border-[#F5F0E6]/30 bg-[#102F23]/40 px-7 py-4 text-sm font-bold text-[#F5F0E6]">اطلب عرض سعر للإمارات</Link></div></StaggerItem><div className="mt-10 grid max-w-[740px] gap-3 sm:grid-cols-2 lg:grid-cols-4">{[["200 كجم","الحد الأدنى للصنف"],["سائب","توريد بالجملة"],["OEM","علامة خاصة"],["الإمارات","استفسارات المشترين"]].map(([value,label])=><div key={label} className="border border-white/15 bg-black/20 px-4 py-4"><p className="text-xl font-semibold text-[#E4C878]" dir="auto">{value}</p><p className="mt-2 text-xs font-bold text-[#F5F0E6]/55">{label}</p></div>)}</div></div></div></section>
    <section id="uae-product-range" className="px-6 py-24 sm:px-8 lg:px-12 lg:py-32"><RevealOnScroll><div className="mx-auto max-w-[1500px]"><div className="mx-auto max-w-[920px] text-center"><p className="text-sm font-bold text-[#9F7F36]">ست فئات تجارية من المنتجات</p><h2 className="mt-6 text-[clamp(2.5rem,4.8vw,4.8rem)] font-semibold leading-[1.18]">منتجات طبيعية هندية <span className="block text-[#A97B22]">لسوق الإمارات</span></h2><p className="mx-auto mt-7 max-w-[820px] text-[17px] font-light leading-9 text-[#4C5F54]">ست فئات للمشترين المهنيين الذين يطورون مجموعات للبيع بالجملة أو للصالونات أو مستحضرات التجميل أو العافية أو الأغذية أو العلامات الخاصة في دبي وأبوظبي والشارقة وسائر الإمارات.</p></div><div className="mt-14 grid auto-rows-fr gap-5 sm:grid-cols-2 lg:grid-cols-3">{products.map((product,index)=><StaggerItem key={product.title} delay={(index%3)*90}><article className="group flex h-full min-h-[300px] flex-col border border-[#173B2A]/12 bg-[#FBF8F1] p-7"><span className="text-4xl font-semibold text-[#C9A962]/60" dir="ltr">{String(index+1).padStart(2,"0")}</span><h3 className="mt-6 text-[27px] font-semibold leading-tight">{product.title}</h3><p className="mt-5 flex-1 text-[15px] font-light leading-8 text-[#4C5F54]">{product.text}</p><Link href={product.href} className="mt-7 inline-flex items-center gap-3 text-sm font-bold text-[#A97B22]">عرض المنتج <span>←</span></Link></article></StaggerItem>)}</div></div></RevealOnScroll></section>
    <section className="bg-[#0B3325] px-6 py-24 text-[#F5F0E6] sm:px-8 lg:px-12 lg:py-32"><RevealOnScroll><div className="mx-auto grid max-w-[1500px] gap-14 lg:grid-cols-[0.9fr_1.1fr] lg:gap-20"><div><p className="text-sm font-bold text-[#E4C878]">مصمم للشراء المهني</p><h2 className="mt-6 text-[clamp(2.5rem,4.6vw,4.6rem)] font-semibold leading-[1.18]">توريد مرن <span className="block text-[#E4C878]">لقنوات الأعمال في الإمارات</span></h2><p className="mt-7 text-[17px] font-light leading-9 text-[#F5F0E6]/68">تُراجع احتياجات المستوردين والموزعين وتجار الجملة وموردي الصالونات والعلامات في الإمارات وفق الاستخدام المقصود والحجم والمواصفات والتعبئة وخطة الشحن.</p><div className="mt-8 flex flex-wrap gap-2">{buyerTypes.map((buyer)=><span key={buyer} className="border border-[#C9A962]/30 bg-white/[0.04] px-4 py-3 text-sm text-[#F5F0E6]/75">{buyer}</span>)}</div></div><div className="grid auto-rows-fr gap-5 sm:grid-cols-2">{supplyServices.map(([title,text])=><article key={title} className="h-full border border-[#C9A962]/25 bg-[#071B14]/55 p-7"><span className="block h-px w-12 bg-[#C9A962]"/><h3 className="mt-6 text-2xl font-semibold text-[#E4C878]">{title}</h3><p className="mt-4 text-[15px] font-light leading-8 text-[#F5F0E6]/65">{text}</p></article>)}</div></div></RevealOnScroll></section>
    <section className="px-6 py-24 sm:px-8 lg:px-12 lg:py-32"><RevealOnScroll><div className="mx-auto grid max-w-[1500px] items-center gap-14 lg:grid-cols-2 lg:gap-20"><figure className="relative aspect-[4/3] overflow-hidden border border-[#C9A962]/35"><Image src="/images/export/uae/uae-private-label-packaging-studio-premium-v1.png" alt="تنسيق تعبئة العلامة الخاصة وتطويرها للمشترين في الإمارات" fill sizes="(min-width:1024px) 50vw, 100vw" className="object-cover object-center"/></figure><div><p className="text-sm font-bold text-[#9F7F36]">تطوير علامة المشتري</p><h2 className="mt-6 text-[clamp(2.5rem,4.6vw,4.6rem)] font-semibold leading-[1.18]">تعبئة تناسب <span className="block text-[#A97B22]">متطلبات سوقكم في الإمارات</span></h2><p className="mt-7 text-[17px] font-light leading-9 text-[#4C5F54]">يمكن للمشترين مناقشة عبوات التجزئة والعبوات المهنية والأشكال السائبة والعرض بعلامة خاصة. ونراجع أحجام العبوات والخامات وكميات الطباعة ومتطلبات كرتون التصدير.</p><p className="mt-5 text-[15px] leading-8 text-[#4C5F54]">تخضع التصاميم وقوالب القص ومحتوى الملصقات المقدمة من المشتري لمراجعة الجدوى. ولا يعني التنسيق اعتماد الملصقات أو الادعاءات أو التسجيل أو الامتثال للسوق الإماراتي.</p><Link href="/contact" className="mt-8 inline-flex items-center gap-4 border border-[#C9A962] bg-[#C9A962] px-7 py-4 text-sm font-bold text-[#102F23]">ناقش العلامة الخاصة <span>←</span></Link></div></div></RevealOnScroll></section>
    <section className="bg-[#09271D] px-6 py-24 text-[#F5F0E6] sm:px-8 lg:px-12 lg:py-32"><RevealOnScroll><div className="mx-auto max-w-[1500px]"><div className="grid items-center gap-12 lg:grid-cols-[0.9fr_1.1fr] lg:gap-20"><div><p className="text-sm font-bold text-[#E4C878]">من الهند إلى الإمارات العربية المتحدة</p><h2 className="mt-6 text-[clamp(2.5rem,4.8vw,4.8rem)] font-semibold leading-[1.18]">تنسيق منظم للتصدير <span className="block text-[#E4C878]">للمشترين في الإمارات</span></h2><p className="mt-7 text-[17px] font-light leading-9 text-[#F5F0E6]/68">يُراجع كل استفسار وفق المنتج والكمية التجارية والمواصفات وشكل التعبئة والوجهة ومتطلبات مستندات المشتري قبل تأكيد الطلب وتخطيط الشحنة.</p></div><figure className="relative aspect-[4/3] overflow-hidden border border-[#C9A962]/35"><Image src="/images/export/uae/uae-export-logistics-command-centre-premium-v1.png" alt="تنسيق مستندات وفحص وشحن الصادرات من الهند إلى الإمارات" fill sizes="(min-width:1024px) 55vw, 100vw" className="object-cover object-center"/><figcaption className="absolute bottom-5 right-5 border border-white/15 bg-[#071B14]/80 px-4 py-3 text-sm text-[#E4C878]">تنسيق التصدير بين الهند والإمارات</figcaption></figure></div><div className="mt-16 grid auto-rows-fr gap-6 md:grid-cols-2">{process.map(([step,title,text])=><article key={step} className="h-full border border-[#C9A962]/22 bg-[#071B14]/65 p-7"><div className="flex items-start gap-5"><span className="flex h-14 w-14 shrink-0 items-center justify-center rounded-full border border-[#C9A962]/45 text-xl text-[#E4C878]" dir="ltr">{step}</span><div><h3 className="text-2xl font-semibold">{title}</h3><p className="mt-4 text-[15px] font-light leading-8 text-[#F5F0E6]/62">{text}</p></div></div></article>)}</div><aside className="mx-auto mt-20 max-w-[1120px] border border-[#C9A962]/45 bg-[#F5F0E6] p-8 text-[#173B2A]"><h3 className="text-2xl font-semibold text-[#A97B22]">مسؤولية المستورد عن الامتثال في الإمارات</h3><p className="mt-4 text-[15px] font-light leading-8 text-[#4C5F54]">تنسق شيفيش إنترناشيونال المستندات التجارية ومستندات التصدير للطلب المؤكد. ويبقى المستورد أو المشتري في الإمارات مسؤولاً عن تصنيف المنتج والتسجيل عند انطباقه والتخليص الجمركي والملصقات والادعاءات والامتثال للمتطلبات الإماراتية المنطبقة.</p></aside></div></RevealOnScroll></section>
    <section className="px-6 py-24 sm:px-8 lg:px-12 lg:py-32"><RevealOnScroll><div className="mx-auto max-w-[1120px]"><div className="text-center"><p className="text-sm font-bold text-[#9F7F36]">أسئلة المشترين في الإمارات</p><h2 className="mt-6 text-[clamp(2.4rem,4.4vw,4.4rem)] font-semibold">الأسئلة الشائعة عن التوريد للتصدير إلى الإمارات</h2></div><div className="mt-12 divide-y divide-[#173B2A]/15 border-y border-[#173B2A]/15">{faqs.map((faq)=><article key={faq.question} className="grid gap-4 py-7 md:grid-cols-[0.8fr_1.2fr] md:gap-10"><h3 className="text-xl font-semibold">{faq.question}</h3><p className="text-[15px] font-light leading-8 text-[#4C5F54]">{faq.answer}</p></article>)}</div></div></RevealOnScroll></section>
    <section className="relative overflow-hidden bg-[#071B14] px-6 py-24 text-center text-[#F5F0E6] sm:px-8 lg:px-12"><GoldenParticles/><RevealOnScroll><div className="relative mx-auto max-w-[1000px]"><p className="text-sm font-bold text-[#E4C878]">ابدأ مناقشة التوريد إلى الإمارات</p><h2 className="mt-6 text-[clamp(2.5rem,4.8vw,4.8rem)] font-semibold leading-[1.18]">خطط لتوريد منتجاتكم الطبيعية إلى الإمارات</h2><p className="mx-auto mt-7 max-w-[760px] text-[17px] font-light leading-9 text-[#F5F0E6]/65">أرسلوا المنتج والكمية وحجم العبوة ومتطلبات العلامة والوجهة والمعلومات المطلوبة. سيراجع فريقنا الاستفسار ويرد بالخطوات التجارية العملية التالية.</p><Link href="/contact" className="mt-9 inline-flex items-center gap-4 border border-[#C9A962] bg-[#C9A962] px-8 py-4 text-sm font-bold text-[#102F23]">اطلب عرض سعر للتصدير إلى الإمارات <span>←</span></Link></div></RevealOnScroll></section>
    <FooterSection locale="ar"/><FloatingContactButtons/><MagneticButtons/><PremiumCursor/>
  </main>;
}
