import type { Metadata } from "next";
import { existsSync } from "node:fs";
import Image from "next/image";
import Link from "next/link";

import FloatingContactButtons from "@/app/components/FloatingContactButtons";
import GoldenParticles from "@/app/components/GoldenParticles";
import MagneticButtons from "@/app/components/MagneticButtons";
import Navbar from "@/app/components/Navbar";
import PremiumCursor from "@/app/components/PremiumCursor";
import RevealOnScroll from "@/app/components/RevealOnScroll";
import StaggerItem from "@/app/components/StaggerItem";
import FooterSection from "@/sections/FooterSection";

const canonicalUrl = "https://shiveshinternational.com/export/asia-pacific";
const heroImage = "/images/export/asia-pacific/asia-pacific-natural-products-export-hub-hero.png";
const keywordSubjects = ["henna", "natural henna", "indigo powder", "botanical hair colour", "private label henna", "Ayurvedic herbs", "Indian spices", "bulk natural products", "natural cosmetic ingredients", "herbal powder", "private label botanical products"];
const keywordIntents = ["exporter to Asia-Pacific", "supplier Asia", "exporter Asia", "supplier Asia-Pacific", "manufacturer India for Asia-Pacific", "bulk supplier Asia-Pacific"];
const metadataKeywords = keywordSubjects.flatMap((subject) => keywordIntents.map((intent) => `${subject} ${intent}`)).concat([
  "OEM natural products Asia-Pacific", "OEM botanical hair colors Asia-Pacific", "buyer-brand packaging Asia-Pacific", "natural products retail supplier Asia-Pacific",
]);

export const metadata: Metadata = {
  title: { absolute: "Asia-Pacific Henna & Natural Products Export | Shivesh International" },
  description: "Explore natural henna, indigo, botanical hair colours, Ayurvedic herbs and Indian spices for Asia-Pacific buyers. Bulk and private-label supply from India.",
  keywords: metadataKeywords,
  alternates: { canonical: canonicalUrl },
  openGraph: { title: "Explore Export Markets Across Asia-Pacific", description: "Natural henna, indigo, botanical hair colours, Ayurvedic herbs and Indian spices for professional Asia-Pacific buyers.", url: canonicalUrl, type: "website", locale: "en_IN", siteName: "Shivesh International" },
  twitter: { card: "summary_large_image", title: "Explore Export Markets Across Asia-Pacific", description: "Bulk and private-label natural-product supply from India for Asia-Pacific buyers." },
  robots: { index: true, follow: true },
};

const markets = [
  { name: "China", flag: "🇨🇳", href: "/export/china", text: "Explore bulk and private-label natural products for importers, distributors, cosmetic ingredient buyers and herbal product companies in China." },
  { name: "Taiwan", flag: "🇹🇼", href: "/export/taiwan", text: "Explore henna, indigo, botanical hair colours, Ayurvedic herbs and Indian spices for professional buyers in Taiwan." },
  { name: "South Korea", flag: "🇰🇷", href: "/export/south-korea", text: "Explore natural cosmetic ingredients, botanical hair-colour products and private-label supply for South Korean buyers." },
  { name: "Thailand", flag: "🇹🇭", href: "/export/thailand", text: "Explore natural hair-care powders, herbal products and Indian spices for importers, wholesalers and private-label brands in Thailand." },
  { name: "Vietnam", flag: "🇻🇳", href: "/export/vietnam", text: "Explore bulk botanical powders, herbs, spices and private-label natural products for buyers across Vietnam." },
  { name: "Singapore", flag: "🇸🇬", href: "/export/singapore", text: "Explore premium natural product supply for importers, distributors, brand owners and regional buyers in Singapore." },
];
const products = [
  ["Natural Henna Powder", "Bulk and retail-ready henna powder for cosmetic, natural hair-care, wholesale and private-label programmes.", "/products/natural-henna-powder"],
  ["Natural Indigo Powder", "Natural indigo for botanical hair-colour systems, two-step applications, bulk sourcing and buyer-brand packs.", "/products/natural-indigo-powder"],
  ["Natural Henna Hair Colors", "Botanical powder hair-colour options for distributors, salons, brands and retail channels.", "/products/natural-henna-hair-colors"],
  ["Henna-Based Hair Colors", "Multiple powdered shade options for wholesale and private-label business requirements.", "/products/henna-based-hair-colors"],
  ["Ayurvedic Indian Herbs", "Herbal powders and Indian botanicals for appropriate cosmetic, personal-care and wholesale applications.", "/products/ayurvedic-indian-herbs"],
  ["Indian Spices", "Whole, ground and blended Indian spices for importers, food distributors and wholesale buyers.", "/products/indian-spices"],
];
const buyerTypes = [
  ["Importers & Distributors", "Coordinate market-focused product selection, commercial volumes and onward distribution planning."],
  ["Private-Label Brands", "Discuss feasible buyer-brand packaging, artwork and retail-ready product programmes."],
  ["Natural Hair-Care Companies", "Source henna, indigo and botanical hair-colour products for professional or retail channels."],
  ["Cosmetic Ingredient Buyers", "Review botanical powders according to intended use, specification and product classification."],
  ["Herbal Product Wholesalers", "Plan Indian herbs and herbal powders for appropriate wholesale and personal-care applications."],
  ["Salon & Professional Suppliers", "Discuss professional formats and repeat supply for salon and beauty distribution."],
  ["Spice & Food Distributors", "Coordinate whole, ground or blended spice requirements for food-sector channels."],
  ["Retail & E-commerce Brands", "Select suitable products and pack formats for stores, marketplaces and direct retail."],
];
const strengths = [
  ["Established Experience", "Sourcing and product experience supports practical professional-buyer discussions."],
  ["Manufacturing Support", "Certified manufacturing support underpins selected commercial product programmes."],
  ["Consistent Specifications", "Orders are planned around agreed specifications, pack formats and quantities."],
  ["Bulk & Private Label", "Wholesale and buyer-brand supply can be reviewed according to feasibility."],
  ["Multiple Packaging Formats", "Retail-ready and bulk options support varied commercial channels."],
  ["Documentation Support", "Applicable and available commercial, product and shipment records can be coordinated."],
  ["Shipment Coordination", "Dispatch planning can be aligned with the buyer's nominated freight forwarder."],
  ["Buyer-Focused Communication", "Each enquiry is reviewed around its market, product, specification and volume."],
];
const faqs = [
  { question: "Which Asia-Pacific markets does Shivesh International serve?", answer: "This regional hub covers enquiries for China, Taiwan, South Korea, Thailand, Vietnam and Singapore. Market-specific supply remains subject to product, commercial and destination requirements." },
  { question: "What natural products are available for Asia-Pacific buyers?", answer: "Professional buyers can discuss natural henna powder, indigo powder, natural henna hair colors, henna-based hair colors, Ayurvedic Indian herbs and Indian spices." },
  { question: "What is the minimum order quantity?", answer: "The minimum order quantity is 200 kg per selected product or item. Mixed product planning may be discussed separately." },
  { question: "Is private-label packaging available?", answer: "Private-label packaging may be coordinated for suitable products and orders, subject to product, material, print, artwork and quantity feasibility." },
  { question: "Which retail and bulk packaging formats are available?", answer: "Retail formats may include 100 g, 200 g, 500 g and 1 kg. Bulk formats may include 20 kg and 25 kg, with double-layer vacuum packaging where applicable." },
  { question: "Can buyers source both henna and indigo?", answer: "Yes. Buyers can discuss natural henna and indigo for botanical hair-colour programmes, subject to separate product specifications and the MOQ per item." },
  { question: "What export documents may be provided?", answer: "Documents may include commercial invoices, packing lists, certificates of origin, transport documents, specifications, COA or other available records where applicable to the product and shipment." },
  { question: "How are shipments coordinated from India?", answer: "After order confirmation, shipment planning and dispatch documents can be coordinated with the buyer's nominated freight forwarder under agreed commercial terms." },
  { question: "Can packaging be customized for different markets?", answer: "Buyer-brand artwork, labels, silver or gold metallized pouches and retail-ready formats can be reviewed, but final availability depends on the product and order requirements." },
  { question: "What must the importer confirm before placing an order?", answer: "The importer or its qualified adviser must confirm local import, product classification, labelling, customs, registration and regulatory requirements for the exact product and market." },
];
const structuredData = { "@context": "https://schema.org", "@graph": [
  { "@type": "WebPage", "@id": `${canonicalUrl}#webpage`, url: canonicalUrl, name: "Explore Export Markets Across Asia-Pacific", description: "Asia-Pacific regional export hub for natural henna, indigo, botanical hair colours, Ayurvedic herbs and Indian spices supplied from India.", isPartOf: { "@id": "https://shiveshinternational.com/#website" }, about: { "@id": "https://shiveshinternational.com/#organization" }, breadcrumb: { "@id": `${canonicalUrl}#breadcrumb` }, inLanguage: "en" },
  { "@type": "BreadcrumbList", "@id": `${canonicalUrl}#breadcrumb`, itemListElement: [{ "@type": "ListItem", position: 1, name: "Home", item: "https://shiveshinternational.com/" }, { "@type": "ListItem", position: 2, name: "Export", item: "https://shiveshinternational.com/export" }, { "@type": "ListItem", position: 3, name: "Asia-Pacific", item: canonicalUrl }] },
] };
const faqStructuredData = { "@context": "https://schema.org", "@type": "FAQPage", "@id": `${canonicalUrl}#faq`, mainEntity: faqs.map((faq) => ({ "@type": "Question", name: faq.question, acceptedAnswer: { "@type": "Answer", text: faq.answer } })) };

function OptionalImage({ src, alt, priority = false, sizes = "(min-width: 1024px) 55vw, 100vw", className = "object-contain object-center" }: { src: string; alt: string; priority?: boolean; sizes?: string; className?: string }) {
  if (!existsSync(`${process.cwd()}/public${src}`)) return null;
  return <Image src={src} alt={alt} fill priority={priority} sizes={sizes} className={className} />;
}

const Cards = ({ items, columns = "lg:grid-cols-4" }: { items: string[][]; columns?: string }) => <div className={`mt-14 grid auto-rows-fr gap-5 sm:grid-cols-2 ${columns}`}>{items.map(([title,text])=><article key={title} className="h-full border border-[#173B2A]/12 bg-[#FBF8F1] p-7 sm:p-8"><span className="block h-px w-12 bg-[#C9A962]"/><h3 className="mt-5 font-[family-name:var(--font-playfair)] text-2xl font-semibold">{title}</h3><p className="mt-4 text-sm font-light leading-7 text-[#4C5F54]">{text}</p></article>)}</div>;

export default function AsiaPacificExportPage() {
  return <main className="min-h-screen overflow-x-hidden bg-[#F5F0E6] text-[#173B2A]">
    <script type="application/ld+json" dangerouslySetInnerHTML={{__html:JSON.stringify(structuredData).replace(/</g,"\\u003c")}}/><script type="application/ld+json" dangerouslySetInnerHTML={{__html:JSON.stringify(faqStructuredData).replace(/</g,"\\u003c")}}/><Navbar/>
    <section className="relative isolate overflow-hidden bg-[#071B14]"><OptionalImage src={heroImage} alt="Asia-Pacific buyers exploring natural products supplied from India" priority sizes="100vw" className="object-cover object-center"/><div className="absolute inset-0 bg-gradient-to-r from-[#061711]/76 via-[#102F23]/48 to-[#071B14]/15"/><GoldenParticles/><div className="relative z-10 flex items-center px-6 pb-20 pt-32 sm:px-8 sm:pb-24 sm:pt-36 lg:px-12 lg:pb-28 lg:pt-40"><div className="w-full max-w-[960px]"><StaggerItem delay={0}><p className="text-[10px] font-bold uppercase tracking-[0.38em] text-[#E4C878] sm:text-xs">Asia-Pacific Export Markets</p></StaggerItem><StaggerItem delay={100}><h1 className="mt-5 font-[family-name:var(--font-playfair)] text-4xl font-medium leading-[1.02] tracking-[-0.04em] text-[#F5F0E6] sm:text-5xl lg:text-6xl xl:text-[66px]">Explore Natural Product Export Markets <span className="block bg-gradient-to-r from-[#F5F0E6] via-[#E4C878] to-[#C9A962] bg-clip-text text-transparent">Across Asia-Pacific</span></h1></StaggerItem><StaggerItem delay={200}><p className="mt-5 max-w-[790px] text-[16px] font-light leading-8 text-[#F5F0E6]/82">Explore market-focused B2B export support for natural henna powder, indigo powder, botanical hair colours, Ayurvedic herbs and Indian spices across key Asia-Pacific destinations, with bulk and private-label options, documentation support and shipment coordination.</p></StaggerItem><StaggerItem delay={300}><div className="mt-7 flex flex-wrap gap-4"><a href="#asia-pacific-markets" className="border border-[#C9A962] bg-[#C9A962] px-7 py-4 text-[10px] font-bold uppercase tracking-[0.2em] text-[#102F23]">Explore Country Markets ↓</a><Link href="/contact" className="border border-white/30 bg-[#102F23]/40 px-7 py-4 text-[10px] font-bold uppercase tracking-[0.2em] text-white">Send Export Inquiry →</Link></div></StaggerItem><StaggerItem delay={400}><div className="mt-10 grid max-w-[760px] grid-cols-2 gap-3 lg:grid-cols-4">{[["200 kg","MOQ per item"],["Bulk","B2B supply"],["Private Label","Buyer-brand packs"],["Export","Coordination"]].map(([v,l])=><div key={l} className="border border-white/15 bg-black/20 p-4"><p className="font-[family-name:var(--font-playfair)] text-xl font-semibold text-[#E4C878]">{v}</p><p className="mt-2 text-[9px] uppercase tracking-[0.22em] text-white/55">{l}</p></div>)}</div></StaggerItem></div></div></section>
    <section className="px-6 py-24 sm:px-8 lg:px-12 lg:py-32"><RevealOnScroll><div className="mx-auto max-w-[1200px]"><p className="text-[10px] font-bold uppercase tracking-[0.4em] text-[#9F7F36]">Regional B2B Supply</p><h2 className="mt-6 font-[family-name:var(--font-playfair)] text-[clamp(2.3rem,4.6vw,4.6rem)] font-semibold">India-to-Asia-Pacific <span className="block text-[#A97B22]">Natural Product Supply</span></h2><p className="mt-7 text-[16px] font-light leading-8 text-[#4C5F54]">Shivesh International supports importers and distributors, private-label brands, natural hair-care companies, cosmetic ingredient buyers, herbal product wholesalers, salon and professional suppliers, spice importers, food distributors and retail or e-commerce brands. Each enquiry is reviewed around the destination, product, specification, packaging and order quantity.</p><p className="mt-5 text-[15px] font-light leading-8 text-[#4C5F54]">Market references do not imply regional offices, warehouses, local stock, guaranteed delivery, customs clearance or regulatory approval. Availability and export arrangements remain subject to written confirmation.</p><Cards items={buyerTypes}/></div></RevealOnScroll></section>
    <section id="asia-pacific-markets" className="scroll-mt-24 bg-[#0B3325] px-6 py-24 text-[#F5F0E6] sm:px-8 lg:px-12 lg:py-32"><RevealOnScroll><div className="mx-auto max-w-[1500px]"><div className="text-center"><p className="text-[10px] font-bold uppercase tracking-[0.4em] text-[#E4C878]">Regional Market Navigation</p><h2 className="mt-6 font-[family-name:var(--font-playfair)] text-[clamp(2.3rem,4.8vw,4.8rem)] font-semibold">Explore Our Asia-Pacific Export Markets</h2></div><div className="mt-14 grid auto-rows-fr gap-5 sm:grid-cols-2 lg:grid-cols-3">{markets.map(m=><article key={m.name} className="group flex h-full min-h-[285px] flex-col border border-[#C9A962]/25 bg-[#071B14]/55 p-7 transition-all duration-500 hover:-translate-y-2 hover:border-[#C9A962]/70"><span aria-hidden="true" className="text-4xl">{m.flag}</span><h3 className="mt-5 font-[family-name:var(--font-playfair)] text-3xl font-semibold text-[#E4C878]">{m.name}</h3><p className="mt-4 flex-1 text-sm font-light leading-7 text-white/65">{m.text}</p><Link href={m.href} className="mt-7 inline-flex items-center gap-3 text-[10px] font-bold uppercase tracking-[0.2em] text-[#E4C878] focus-visible:outline focus-visible:outline-2 focus-visible:outline-offset-4 focus-visible:outline-[#E4C878]">Explore {m.name} Market <span>→</span></Link></article>)}</div></div></RevealOnScroll></section>
    <section id="products" className="bg-[#EDE5D7] px-6 py-24 sm:px-8 lg:px-12 lg:py-32"><RevealOnScroll><div className="mx-auto max-w-[1500px]"><div className="text-center"><p className="text-[10px] font-bold uppercase tracking-[0.4em] text-[#9F7F36]">Six Export Categories</p><h2 className="mt-6 font-[family-name:var(--font-playfair)] text-[clamp(2.3rem,4.8vw,4.8rem)] font-semibold">Products Available <span className="block text-[#A97B22]">for Asia-Pacific Buyers</span></h2><p className="mx-auto mt-7 max-w-[850px] text-[15px] leading-8 text-[#4C5F54]">Bulk supply, retail-ready packs, private-label programmes, packaging coordination and product specification confirmation are reviewed with a minimum order quantity of 200 kg per item.</p></div><div className="mt-14 grid auto-rows-fr gap-5 sm:grid-cols-2 lg:grid-cols-3">{products.map(([title,text,href],i)=><article key={title} className="flex h-full min-h-[290px] flex-col border border-[#173B2A]/12 bg-[#FBF8F1] p-7"><span className="text-4xl text-[#C9A962]">{String(i+1).padStart(2,"0")}</span><h3 className="mt-5 font-[family-name:var(--font-playfair)] text-2xl font-semibold">{title}</h3><p className="mt-4 flex-1 text-sm leading-7 text-[#4C5F54]">{text}</p><Link href={href} className="mt-6 text-[10px] font-bold uppercase tracking-[0.2em] text-[#A97B22]">Explore {title} →</Link></article>)}</div></div></RevealOnScroll></section>
    <section className="px-6 py-24 sm:px-8 lg:px-12 lg:py-32"><RevealOnScroll><div className="mx-auto max-w-[1500px]"><div className="grid gap-14 lg:grid-cols-[1.05fr_0.95fr] lg:gap-20"><div><p className="text-[10px] font-bold uppercase tracking-[0.4em] text-[#9F7F36]">Packaging & Private Label</p><h2 className="mt-6 font-[family-name:var(--font-playfair)] text-[clamp(2.3rem,4.6vw,4.6rem)] font-semibold leading-[1.04]">Flexible Packaging <span className="block text-[#A97B22]">for Regional Buyers</span></h2><p className="mt-7 text-[15px] font-light leading-8 text-[#4C5F54]">Silver and gold metallized pouches, buyer-brand packaging, artwork and label coordination, retail-ready formats and bulk supply for repacking or manufacturing can be reviewed for Asia-Pacific buyers.</p><p className="mt-5 text-[14px] font-light leading-7 text-[#4C5F54]">Final availability depends on the selected product, material, artwork, pack size and order requirements. Not every packaging format is available for every product.</p></div><div><figure className="relative aspect-[3/2] overflow-hidden rounded-sm border border-[#C9A962]/35 bg-[#FBF8F1] shadow-[0_28px_70px_rgba(20,50,38,0.18)]"><OptionalImage src="/images/export/asia-pacific/asia-pacific-packaging-private-label-buyers.png" alt="Packaging and private-label natural product solutions for Asia-Pacific buyers" className="object-contain object-center"/></figure><div className="mt-5 grid gap-5 sm:grid-cols-2"><article className="border border-[#C9A962]/35 bg-[#FBF8F1] p-7"><h3 className="font-[family-name:var(--font-playfair)] text-2xl font-semibold">Retail Packaging</h3><p className="mt-5 text-sm leading-7 text-[#4C5F54]">100 g · 200 g · 500 g · 1 kg formats</p></article><article className="border border-[#C9A962]/35 bg-[#FBF8F1] p-7"><h3 className="font-[family-name:var(--font-playfair)] text-2xl font-semibold">Bulk Packaging</h3><p className="mt-5 text-sm leading-7 text-[#4C5F54]">20 kg and 25 kg, with double-layer vacuum packaging where applicable</p></article><article className="border border-[#C9A962] bg-[#173B2A] p-7 text-[#F5F0E6] sm:col-span-2"><p className="text-[10px] font-bold uppercase tracking-[0.3em] text-[#E4C878]">Minimum Order Quantity</p><p className="mt-4 font-[family-name:var(--font-playfair)] text-4xl font-semibold">200 kg per item</p></article></div></div></div></div></RevealOnScroll></section>
    <section className="relative overflow-hidden bg-[#09271D] px-6 py-24 text-[#F5F0E6] sm:px-8 lg:px-12 lg:py-32"><RevealOnScroll><div className="mx-auto max-w-[1500px]"><div className="grid items-center gap-14 lg:grid-cols-[0.9fr_1.1fr] lg:gap-20"><div><p className="text-[10px] font-bold uppercase tracking-[0.4em] text-[#E4C878]">Shipment and Document Support</p><h2 className="mt-6 font-[family-name:var(--font-playfair)] text-[clamp(2.3rem,4.7vw,4.7rem)] font-semibold leading-[1.04]">India-to-Asia-Pacific Export Coordination</h2><p className="mt-7 text-[16px] font-light leading-8 text-[#F5F0E6]/68">Coordination covers product selection, specification confirmation, quotation and commercial terms, packaging or private-label approval, production and quality checks, documentation preparation, shipment planning, dispatch and document sharing.</p><p className="mt-5 text-[15px] font-light leading-8 text-[#F5F0E6]/62">Commercial invoices, packing lists, certificates of origin, transport documents, product specifications, COA and other available records may be coordinated where applicable. Freight planning is aligned with the buyer&apos;s nominated freight forwarder under confirmed commercial terms.</p></div><figure className="relative aspect-[3/2] overflow-hidden rounded-sm border border-[#C9A962]/35 bg-[#071B14] shadow-[0_28px_70px_rgba(20,50,38,0.18)]"><OptionalImage src="/images/export/asia-pacific/india-to-asia-pacific-export-coordination.png" alt="India-to-Asia-Pacific shipment and export documentation coordination" className="object-contain object-center"/><div className="absolute inset-0 bg-gradient-to-t from-[#061711]/65 via-transparent to-transparent"/><figcaption className="absolute bottom-5 left-5 border border-white/15 bg-[#071B14]/80 px-4 py-3 text-[9px] font-bold uppercase tracking-[0.22em] text-[#E4C878] backdrop-blur-md">India-to-Asia-Pacific Export Coordination</figcaption></figure></div><aside className="mt-12 border border-[#C9A962]/35 bg-[#071B14]/60 p-7 text-sm font-light leading-7 text-[#F5F0E6]/64">Each importer is responsible for confirming local import, product classification, labelling, customs, registration and regulatory requirements. Shivesh International does not guarantee regulatory approval, customs clearance, freight rates, transit times or delivery outcomes.</aside></div></RevealOnScroll></section>
    <section className="bg-[#EDE5D7] px-6 py-24 sm:px-8 lg:px-12 lg:py-32"><RevealOnScroll><div className="mx-auto max-w-[1500px]"><div className="text-center"><p className="text-[10px] uppercase tracking-[0.4em] text-[#9F7F36]">Commercial Supply Strengths</p><h2 className="mt-6 font-[family-name:var(--font-playfair)] text-[clamp(2.3rem,4.7vw,4.7rem)] font-semibold">Why Asia-Pacific Buyers Choose <span className="block text-[#A97B22]">Shivesh International</span></h2></div><Cards items={strengths}/></div></RevealOnScroll></section>
    <section className="px-6 py-24 sm:px-8 lg:px-12 lg:py-32"><RevealOnScroll><div className="mx-auto max-w-[1120px]"><div className="text-center"><p className="text-[10px] uppercase tracking-[0.4em] text-[#9F7F36]">Regional Buyer Questions</p><h2 className="mt-6 font-[family-name:var(--font-playfair)] text-[clamp(2.3rem,4.4vw,4.4rem)] font-semibold">Asia-Pacific Export Supply FAQ</h2></div><div className="mt-12 divide-y divide-[#173B2A]/15 border-y border-[#173B2A]/15">{faqs.map(f=><article key={f.question} className="grid gap-4 py-7 md:grid-cols-[0.8fr_1.2fr]"><h3 className="text-xl font-semibold">{f.question}</h3><p className="text-sm leading-7 text-[#4C5F54]">{f.answer}</p></article>)}</div></div></RevealOnScroll></section>
    <section className="relative overflow-hidden bg-[#071B14] px-6 py-24 text-center text-white sm:px-8 lg:px-12 lg:py-28"><GoldenParticles/><RevealOnScroll><div className="relative mx-auto max-w-[1000px]"><p className="text-[10px] uppercase tracking-[0.4em] text-[#E4C878]">Asia-Pacific Export Enquiry</p><h2 className="mt-6 font-[family-name:var(--font-playfair)] text-[clamp(2.3rem,4.8vw,4.8rem)] font-semibold">Start Your Asia-Pacific Product Inquiry</h2><p className="mx-auto mt-7 max-w-[820px] text-[16px] leading-8 text-white/65">Tell us your destination market, required product, specification, packaging format and order quantity. Our team will review your inquiry and provide the relevant commercial and export information.</p><Link href="/contact" className="mt-9 inline-flex border border-[#C9A962] bg-[#C9A962] px-8 py-4 text-[10px] font-bold uppercase tracking-[0.2em] text-[#102F23]">Send Asia-Pacific Inquiry →</Link></div></RevealOnScroll></section>
    <FooterSection/><FloatingContactButtons/><MagneticButtons/><PremiumCursor/>
  </main>;
}
