import type { Metadata } from "next";
import Image from "next/image";
import Link from "next/link";

import FloatingContactButtons from "@/app/components/FloatingContactButtons";
import GoldenParticles from "@/app/components/GoldenParticles";
import MagneticButtons from "@/app/components/MagneticButtons";
import Navbar from "@/app/components/Navbar";
import PremiumCursor from "@/app/components/PremiumCursor";
import RevealOnScroll from "@/app/components/RevealOnScroll";
import StaggerItem from "@/app/components/StaggerItem";
import { finlandLanguageAlternates } from "@/app/lib/i18n";
import FooterSection from "@/sections/FooterSection";

const canonicalUrl = "https://shiveshinternational.com/it/export/finlandia";
const heroImage = "/images/export/finland/finland-export-hero.png";

export const metadata: Metadata = {
  title: "Esportatore di henné, indigo, erbe e spezie in Finlandia",
  description: "Fornitore indiano di henné, indigo, colorazioni botaniche, erbe ayurvediche e spezie per importatori, distributori, grossisti e marchi Private Label in Finlandia.",
  keywords: [
    "esportatore di prodotti naturali in Finlandia", "produttore di henné per la Finlandia", "fornitore di henné naturale in Finlandia", "henné all’ingrosso Finlandia", "esportatore di henné naturale", "fornitore di indigo naturale", "esportatore di indigo naturale", "indigo all’ingrosso Finlandia", "fornitore di colorazioni vegetali", "colorazioni botaniche per capelli", "fornitore per saloni professionali", "fornitore di cosmetici naturali", "importatori in Finlandia", "distributori in Finlandia", "grossisti in Finlandia", "rivenditori in Finlandia", "fornitore di erbe ayurvediche", "esportatore di erbe ayurvediche", "fornitore di spezie indiane", "esportatore di spezie indiane", "Private Label Finlandia", "OEM Finlandia", "fornitura all’ingrosso Finlandia", "approvvigionamento B2B Finlandia", "prodotti naturali India Finlandia", "henné Private Label Finlandia", "indigo Private Label Finlandia", "colorazioni botaniche Finlandia", "erbe indiane all’ingrosso Finlandia", "spezie indiane all’ingrosso Finlandia", "confezionamento per marchi finlandesi", "etichette in finlandese e svedese", "documentazione export Finlandia", "spedizione India Finlandia", "trasporto marittimo Finlandia", "trasporto aereo Finlandia", "MOQ 200 kg per prodotto", "fornitore Helsinki", "fornitore Espoo", "fornitore Turku",
  ],
  alternates: { canonical: canonicalUrl, languages: finlandLanguageAlternates },
  openGraph: {
    title: "Esportatore di henné, indigo, erbe e spezie in Finlandia",
    description: "Fornitura indiana sfusa, all’ingrosso, OEM e Private Label per acquirenti professionali in Finlandia.",
    url: canonicalUrl,
    type: "website",
    locale: "it_IT",
    siteName: "Shivesh International",
    images: [{ url: heroImage, alt: "Acquirenti finlandesi valutano prodotti naturali indiani" }],
  },
  twitter: {
    card: "summary_large_image",
    title: "Esportatore di prodotti naturali in Finlandia",
    description: "Fornitura indiana di henné, indigo, erbe, spezie e Private Label per acquirenti professionali finlandesi.",
    images: [heroImage],
  },
  robots: { index: true, follow: true, googleBot: { index: true, follow: true } },
};

const products = [
  { title: "Henné naturale in polvere", text: "Henné naturale di qualità per marchi cosmetici, saloni, grossisti, rivenditori di prodotti naturali e programmi Private Label personalizzati in Finlandia.", href: "/products/natural-henna-powder" },
  { title: "Indigo naturale in polvere", text: "Indigo naturale in polvere per sistemi di colorazione botanica, fornitura a saloni professionali, approvvigionamento sfuso e confezionamento a marchio dell’acquirente.", href: "/products/natural-indigo-powder" },
  { title: "Colorazioni naturali per capelli all’henné", text: "Un’ampia collezione di tonalità botaniche per importatori finlandesi, marchi di bellezza, aziende di cura naturale dei capelli e distributori per saloni.", href: "/products/natural-henna-hair-colors" },
  { title: "Colorazioni per capelli a base di henné", text: "Colorazioni in polvere pronte per l’esportazione per acquirenti finlandesi che richiedono formati all’ingrosso, OEM, professionali o Private Label personalizzati.", href: "/products/henna-based-hair-colors" },
  { title: "Erbe ayurvediche indiane", text: "Polveri erboristiche e prodotti botanici indiani per applicazioni cosmetiche, di cura personale, benessere, cura dei capelli e vendita all’ingrosso in Finlandia.", href: "/products/ayurvedic-indian-herbs" },
  { title: "Spezie indiane", text: "Spezie indiane intere e macinate per importatori finlandesi, aziende alimentari, rivenditori specializzati, distributori e marchi Private Label.", href: "/products/indian-spices" },
];

const buyerProfiles = [
  ["Importatori e distributori", "Coordiniamo specifiche, quantità commerciali e documentazione disponibile per reti distributive che servono Helsinki, Espoo e il resto della Finlandia."],
  ["Marchi nordici di bellezza e cosmetica", "Valutiamo polveri vegetali per progetti cosmetici e di cura dei capelli a posizionamento naturale, con verifica dell’uso previsto e delle specifiche."],
  ["Rivenditori naturali e biologici", "Sviluppiamo gamme selezionate di henné, indigo, erbe e spezie per negozi naturali, rivenditori biologici e canali specializzati finlandesi."],
  ["Fornitori per saloni professionali", "Valutiamo colorazioni botaniche e ingredienti erboristici per la cura dei capelli destinati alla distribuzione professionale per saloni in Finlandia."],
  ["Aziende erboristiche e del benessere", "Esaminiamo polveri ayurvediche e prodotti botanici selezionati per programmi finlandesi di benessere, retail specializzato e marchio proprio."],
  ["Acquirenti Private Label e OEM", "Coordiniamo buste, scatole, grafiche, codici a barre e layout di etichette in finlandese, svedese o bilingui tecnicamente fattibili per progetti a marchio dell’acquirente."],
  ["Importatori di alimenti e spezie", "Pianifichiamo la fornitura di spezie intere, spezie macinate e ingredienti alimentari indiani per aziende alimentari e distributori specializzati finlandesi."],
  ["Grossisti e marchi e-commerce", "Sviluppiamo assortimenti commerciali di prodotti naturali per canali all’ingrosso, online e retail specializzato in tutta la Finlandia."],
];

const documentationItems = [
  ["Fattura commerciale", "Le informazioni della fattura commerciale possono essere predisposte in base ad acquirente, prodotti, quantità, valori e condizioni di spedizione confermati."],
  ["Packing List", "Conteggio dei colli, pesi netti e lordi, dati dei cartoni e riferimenti di spedizione concordati possono essere coordinati per gli ordini confermati."],
  ["Certificato di origine", "Il coordinamento del certificato di origine può essere valutato ove applicabile al prodotto confermato e alla modalità di spedizione."],
  ["Specifiche e COA", "Specifiche di prodotto, COA ove disponibile, riferimenti di lotto e informazioni di qualità disponibili dipendono dal prodotto selezionato."],
  ["Informazioni sul confezionamento", "Le informazioni relative a buste, scatole, sacchi sfusi, etichette e codici a barre possono essere allineate al programma di confezionamento approvato dall’acquirente."],
  ["Documenti di spedizione", "La documentazione di spedizione può essere coordinata con gli spedizionieri incaricati dall’acquirente e il piano di invio concordato."],
  ["Informazioni per la verifica a destinazione", "Le informazioni disponibili su prodotto e confezionamento possono supportare la verifica doganale e del mercato di destinazione dell’acquirente finlandese."],
  ["Responsabilità dell’acquirente", "L’importatore deve verificare classificazione, etichette, dichiarazioni, registrazioni, dogana, imposte e requisiti finlandesi e UE applicabili."],
];

const processSteps = [
  ["Condividete i requisiti del prodotto", "Indicate nome del prodotto, uso commerciale previsto, destinazione, quantità approssimativa e confezionamento preferito."],
  ["Confermate specifiche e quantità", "Verificate il grado richiesto, le specifiche disponibili e il minimo commerciale di 200 kg per prodotto."],
  ["Verificate confezionamento e grafiche", "Allineate formati retail o sfusi fattibili, grafiche in finlandese, svedese o bilingui, etichette, codici a barre e requisiti del marchio dell’acquirente."],
  ["Confermate documenti e piano di trasporto", "Valutate i documenti disponibili, il punto di ingresso preferito in Finlandia e l’accordo con lo spedizioniere incaricato dall’acquirente."],
  ["Coordinamento di produzione e spedizione", "Procedete secondo condizioni commerciali confermate, fattibilità produttiva e piano di invio concordato."],
];

const marketLocations = [
  ["Helsinki", "Importatori, aziende di cosmetica naturale e acquirenti Private Label nel mercato di Helsinki possono valutare approvvigionamenti multicategoria e formati a marchio proprio."],
  ["Espoo", "Distributori e aziende del benessere dell’area di Espoo possono valutare polveri botaniche, prodotti per saloni e gamme erboristiche retail."],
  ["Vantaa", "Acquirenti di ingredienti alimentari, grossisti e aziende orientate alla logistica nell’area di Vantaa possono coordinare richieste per spezie e prodotti botanici."],
  ["Tampere", "Rivenditori specializzati, fornitori per saloni e marchi premium del benessere di Tampere possono valutare formati retail e professionali selezionati."],
  ["Turku", "Aziende di prodotti naturali e attività retail legate al turismo a Turku possono valutare collezioni mirate di prodotti botanici, erbe e spezie."],
  ["Oulu", "Aziende del benessere, negozi specializzati e distributori regionali dell’area di Oulu possono valutare programmi di prodotto commercialmente fattibili."],
  ["Jyväskylä", "Aziende di approvvigionamento retail e distributori di Jyväskylä possono coordinare fornitura sfusa e requisiti di presentazione Private Label."],
  ["Lahti", "Gli acquirenti di Lahti possono valutare ingredienti botanici, fornitura professionale per la cura dei capelli, spezie e opzioni di confezionamento all’ingrosso."],
];

const nordicPriorities = [
  ["Informazioni di prodotto tracciabili", "Specifiche chiare, riferimenti di lotto e informazioni di qualità disponibili aiutano gli acquirenti finlandesi a valutare i prodotti per il canale commerciale previsto."],
  ["Confezionamento nordico pratico", "Formati retail compatti, imballaggi export resistenti e grafiche organizzate con chiarezza favoriscono una presentazione professionale e una movimentazione efficiente."],
  ["Coordinamento delle etichette in finlandese e svedese", "Layout approvati dall’acquirente in finlandese, svedese o bilingui possono essere coordinati per programmi Private Label tecnicamente fattibili."],
  ["Pianificazione attenta alla sostenibilità", "Scelte di confezionamento, approvvigionamento consolidato e pianificazione realistica del trasporto possono essere valutati con acquirenti interessati a soluzioni commerciali attente alle risorse."],
];

const faqs = [
  { question: "Esportate henné naturale in polvere dall’India alla Finlandia?", answer: "Sì. Shivesh International coordina la fornitura dall’India di henné naturale in polvere per importatori, distributori, grossisti, fornitori per saloni e acquirenti Private Label finlandesi qualificati, previa conferma delle specifiche e delle condizioni commerciali." },
  { question: "Qual è la quantità minima d’ordine per gli acquirenti finlandesi?", answer: "La quantità minima d’ordine è di 200 kg per prodotto. Le quantità finali dipendono dal prodotto selezionato, dal formato di confezionamento e dai requisiti Private Label." },
  { question: "Gli acquirenti finlandesi possono ordinare henné e prodotti erboristici Private Label?", answer: "Prodotti selezionati a base di henné ed erbe possono essere valutati per la fornitura Private Label, inclusi marchio dell’acquirente, buste o scatole stampate tecnicamente fattibili, dati del codice a barre e grafiche approvate dall’acquirente." },
  { question: "Quali formati retail e sfusi sono disponibili?", answer: "Prodotti selezionati possono essere valutati in buste da 100 g, 200 g, 500 g e 1 kg. Le opzioni sfuse comprendono sacchi sottovuoto a doppio strato da 20 kg e 25 kg, previa conferma del prodotto e dell’ordine." },
  { question: "Potete coordinare grafiche per confezioni in finlandese e svedese?", answer: "Il coordinamento di grafiche per etichette in finlandese, svedese o bilingui può essere valutato insieme alle grafiche fornite dall’acquirente e al supporto per il layout. L’acquirente finlandese resta responsabile del testo finale, delle dichiarazioni e dell’approvazione dell’etichetta." },
  { question: "Quali documenti possono accompagnare le spedizioni destinate alla Finlandia?", answer: "In base al prodotto e alla disponibilità, il coordinamento può comprendere fattura commerciale, Packing List, certificato di origine, specifiche, COA, informazioni di qualità disponibili e documenti di spedizione." },
  { question: "Come possono essere spediti i prodotti dall’India alla Finlandia?", answer: "Le modalità selezionate dall’acquirente possono prevedere trasporto marittimo attraverso Helsinki, Turku, HaminaKotka o un altro porto concordato, oppure trasporto aereo tramite l’aeroporto di Helsinki. Rotte, programmi e tempi di transito non sono garantiti." },
  { question: "I requisiti finlandesi e UE di conformità all’importazione sono gestiti automaticamente?", answer: "No. L’importatore o l’acquirente finlandese deve confermare classificazione, etichettatura, dichiarazioni, registrazioni, dogana, imposte e requisiti finlandesi e dell’Unione europea applicabili al prodotto selezionato." },
];

const structuredData = {
  "@context": "https://schema.org",
  "@graph": [
    { "@type": "WebPage", "@id": `${canonicalUrl}#webpage`, url: canonicalUrl, name: "Esportatore di henné, indigo, erbe e spezie in Finlandia", description: "Fornitura export dall’India di henné naturale, indigo, colorazioni botaniche, erbe ayurvediche e spezie indiane per la Finlandia.", isPartOf: { "@id": "https://shiveshinternational.com/#website" }, about: { "@id": "https://shiveshinternational.com/#organization" }, breadcrumb: { "@id": `${canonicalUrl}#breadcrumb` }, inLanguage: "it" },
    { "@type": "BreadcrumbList", "@id": `${canonicalUrl}#breadcrumb`, itemListElement: [
      { "@type": "ListItem", position: 1, name: "Home", item: "https://shiveshinternational.com/" },
      { "@type": "ListItem", position: 2, name: "Export", item: "https://shiveshinternational.com/export" },
      { "@type": "ListItem", position: 3, name: "Europa", item: "https://shiveshinternational.com/export/europe" },
      { "@type": "ListItem", position: 4, name: "Finlandia", item: canonicalUrl },
    ] },
  ],
};

const faqStructuredData = { "@context": "https://schema.org", "@type": "FAQPage", "@id": `${canonicalUrl}#faq`, mainEntity: faqs.map((faq) => ({ "@type": "Question", name: faq.question, acceptedAnswer: { "@type": "Answer", text: faq.answer } })) };

export default function FinlandExportPage() {
  return (
    <main className="min-h-screen overflow-x-hidden bg-[#F5F0E6] text-[#173B2A]">
      <script type="application/ld+json" dangerouslySetInnerHTML={{ __html: JSON.stringify(structuredData).replace(/</g, "\\u003c") }} />
      <script type="application/ld+json" dangerouslySetInnerHTML={{ __html: JSON.stringify(faqStructuredData).replace(/</g, "\\u003c") }} />
      <Navbar />

      <section className="relative isolate overflow-hidden">
        <Image src={heroImage} alt="Acquirenti finlandesi valutano henné, indigo, erbe e spezie indiane per la fornitura export professionale" fill priority sizes="100vw" className="object-cover object-center" />
        <div className="absolute inset-0 bg-gradient-to-r from-[#061711]/72 via-[#102F23]/40 to-[#071B14]/10" />
        <div className="absolute inset-0 bg-gradient-to-t from-black/10 via-transparent to-black/[0.04]" />
        <GoldenParticles />
        <div className="relative z-10 flex items-center px-6 pb-20 pt-32 sm:px-8 sm:pb-24 sm:pt-36 lg:px-12 lg:pb-28 lg:pt-40">
          <div className="w-full max-w-[820px] lg:max-w-[860px] xl:max-w-[900px]">
            <StaggerItem delay={0}><div className="flex items-center gap-4"><span className="h-px w-14 bg-[#C9A962]" /><p className="text-[10px] font-bold uppercase tracking-[0.38em] text-[#E4C878] sm:text-xs">Esportazione dall’India alla Finlandia</p></div></StaggerItem>
            <StaggerItem delay={100}><h1 className="mt-5 font-[family-name:var(--font-playfair)] text-4xl font-medium leading-[1] tracking-[-0.04em] text-[#F5F0E6] sm:text-5xl lg:text-6xl xl:text-[66px]">Esportatore di prodotti naturali in Finlandia<span className="mt-2 block bg-gradient-to-r from-[#F5F0E6] via-[#E4C878] to-[#C9A962] bg-clip-text text-transparent">Henné, indigo, erbe e spezie</span></h1></StaggerItem>
            <StaggerItem delay={200}><p className="mt-5 max-w-[730px] text-[16px] font-light leading-7 text-[#F5F0E6]/82 sm:text-[17px] sm:leading-8">Shivesh International supporta importatori, distributori, grossisti, aziende cosmetiche, fornitori per saloni, aziende erboristiche, acquirenti del settore alimentare e marchi Private Label finlandesi con henné naturale, indigo, colorazioni botaniche, erbe ayurvediche e spezie indiane pronti per l’esportazione dall’India.</p></StaggerItem>
            <StaggerItem delay={300}><div className="mt-7 flex flex-wrap gap-4"><Link href="/contact" className="inline-flex items-center gap-4 border border-[#C9A962] bg-[#C9A962] px-7 py-4 text-[10px] font-bold uppercase tracking-[0.2em] text-[#102F23] transition-all hover:-translate-y-1 hover:bg-[#E4C878] focus-visible:outline focus-visible:outline-2 focus-visible:outline-offset-4 focus-visible:outline-[#E4C878]">Invia una richiesta per la Finlandia <span>→</span></Link><a href="#prodotti" className="inline-flex items-center gap-4 border border-[#F5F0E6]/30 bg-[#102F23]/40 px-7 py-4 text-[10px] font-bold uppercase tracking-[0.2em] text-[#F5F0E6] backdrop-blur-lg transition-all hover:border-[#C9A962] hover:text-[#E4C878] focus-visible:outline focus-visible:outline-2 focus-visible:outline-offset-4 focus-visible:outline-[#E4C878]">Scopri i prodotti <span>↓</span></a></div></StaggerItem>
            <StaggerItem delay={400}><div className="mt-10 grid max-w-[740px] grid-cols-2 gap-3 lg:grid-cols-4">{[["200 kg", "MOQ per prodotto"], ["Sfuso", "Fornitura all’ingrosso"], ["OEM", "Private Label"], ["Finlandia", "Richieste degli acquirenti"]].map(([value, label]) => <div key={label} className="border border-white/15 bg-black/20 px-4 py-4 backdrop-blur-md"><p className="font-[family-name:var(--font-playfair)] text-xl font-semibold text-[#E4C878]">{value}</p><p className="mt-2 text-[9px] font-bold uppercase tracking-[0.22em] text-[#F5F0E6]/55">{label}</p></div>)}</div></StaggerItem>
          </div>
        </div>
      </section>

      <section className="px-6 py-24 sm:px-8 lg:px-12 lg:py-32"><RevealOnScroll><div className="mx-auto max-w-[1120px]"><p className="text-[10px] font-bold uppercase tracking-[0.4em] text-[#9F7F36]">Approvvigionamento di prodotti naturali India–Finlandia</p><h2 className="mt-6 font-[family-name:var(--font-playfair)] text-[clamp(2.5rem,4.6vw,4.6rem)] font-semibold leading-[1.04]">Un unico partner export indiano <span className="block text-[#A97B22]">per acquirenti finlandesi di prodotti naturali</span></h2><p className="mt-7 text-[16px] font-light leading-8 text-[#4C5F54]">Importatori, distributori e grossisti finlandesi possono coordinare più categorie di prodotto con un unico team export indiano. Shivesh International supporta aziende cosmetiche e di cura personale, marchi di cura naturale dei capelli, fornitori per saloni, aziende erboristiche e del benessere, acquirenti di ingredienti alimentari, aziende di spezie, operatori Private Label e marchi e-commerce che cercano un approvvigionamento strutturato dall’India.</p><p className="mt-5 text-[15px] font-light leading-8 text-[#4C5F54]">Le richieste commerciali possono riguardare attività di acquisto e distribuzione a Helsinki, Espoo, Tampere, Vantaa e Turku. Disponibilità, specifiche, confezionamento, documentazione e preparazione della spedizione vengono verificate in base alla categoria selezionata e ai requisiti concordati per l’ordine. I riferimenti di mercato indicano potenziali località degli acquirenti e non implicano che Shivesh International disponga di uffici o magazzini locali in Finlandia.</p></div></RevealOnScroll></section>

      <section id="prodotti" className="scroll-mt-24 bg-[#EDE5D7] px-6 py-24 sm:px-8 lg:px-12 lg:py-32"><RevealOnScroll><div className="mx-auto max-w-[1500px]"><div className="mx-auto max-w-[920px] text-center"><p className="text-[10px] font-bold uppercase tracking-[0.4em] text-[#9F7F36]">Sei categorie commerciali</p><h2 className="mt-6 font-[family-name:var(--font-playfair)] text-[clamp(2.5rem,4.8vw,4.8rem)] font-semibold leading-[1.04]">Prodotti naturali <span className="block text-[#A97B22]">per importatori e marchi finlandesi</span></h2><p className="mx-auto mt-7 max-w-[820px] text-[16px] font-light leading-8 text-[#4C5F54]">Un portafoglio mirato per marchi cosmetici finlandesi, canali professionali per la cura dei capelli, aziende erboristiche, grossisti, aziende alimentari e acquirenti Private Label.</p></div><div className="mt-14 grid auto-rows-fr gap-5 sm:grid-cols-2 lg:grid-cols-3">{products.map((product, index) => <StaggerItem key={product.title} delay={(index % 3) * 90}><article className="group flex h-full min-h-[300px] flex-col border border-[#173B2A]/12 bg-[#FBF8F1] p-7 shadow-[0_18px_45px_rgba(20,50,38,0.07)] transition-all hover:-translate-y-2 hover:border-[#C9A962]/70 sm:p-8"><span className="font-[family-name:var(--font-playfair)] text-4xl font-semibold text-[#C9A962]/60">{String(index + 1).padStart(2, "0")}</span><h3 className="mt-6 font-[family-name:var(--font-playfair)] text-[27px] font-semibold leading-tight">{product.title}</h3><p className="mt-5 flex-1 text-[14px] font-light leading-7 text-[#4C5F54]">{product.text}</p><Link href={product.href} className="mt-7 inline-flex items-center gap-3 text-[10px] font-bold uppercase tracking-[0.2em] text-[#A97B22] focus-visible:outline focus-visible:outline-2 focus-visible:outline-offset-4 focus-visible:outline-[#A97B22]">Scopri {product.title} <span className="transition-transform group-hover:translate-x-2">→</span></Link></article></StaggerItem>)}</div></div></RevealOnScroll></section>

      <section className="bg-[#0B3325] px-6 py-24 text-[#F5F0E6] sm:px-8 lg:px-12 lg:py-32"><RevealOnScroll><div className="mx-auto max-w-[1500px]"><div className="mx-auto max-w-[920px] text-center"><p className="text-[10px] font-bold uppercase tracking-[0.4em] text-[#E4C878]">Canali commerciali finlandesi</p><h2 className="mt-6 font-[family-name:var(--font-playfair)] text-[clamp(2.5rem,4.7vw,4.7rem)] font-semibold leading-[1.04]">Chi supportiamo nel mercato finlandese</h2></div><div className="mt-14 grid auto-rows-fr gap-5 sm:grid-cols-2 lg:grid-cols-4">{buyerProfiles.map(([title, text]) => <article key={title} className="h-full border border-[#C9A962]/25 bg-[#071B14]/55 p-7"><h3 className="font-[family-name:var(--font-playfair)] text-2xl font-semibold text-[#E4C878]">{title}</h3><p className="mt-4 text-[14px] font-light leading-7 text-[#F5F0E6]/65">{text}</p></article>)}</div></div></RevealOnScroll></section>

      <section className="px-6 py-24 sm:px-8 lg:px-12 lg:py-32"><RevealOnScroll><div className="mx-auto max-w-[1500px]"><div className="grid gap-14 lg:grid-cols-[0.7fr_1.3fr] lg:gap-20"><div><p className="text-[10px] font-bold uppercase tracking-[0.4em] text-[#9F7F36]">Informazioni per la verifica dell’acquirente</p><h2 className="mt-6 font-[family-name:var(--font-playfair)] text-[clamp(2.5rem,4.5vw,4.5rem)] font-semibold leading-[1.04]">Documentazione export <span className="block text-[#A97B22]">per acquirenti finlandesi</span></h2><p className="mt-7 text-[15px] font-light leading-8 text-[#4C5F54]">I documenti dipendono dal prodotto selezionato e dalla disponibilità. Le informazioni commerciali, di prodotto, confezionamento e spedizione disponibili possono essere coordinate per la verifica dell’acquirente e del mercato di destinazione, senza implicare conformità automatica ai requisiti finlandesi o dell’Unione europea.</p></div><div className="grid auto-rows-fr gap-5 sm:grid-cols-2">{documentationItems.map(([title, text]) => <article key={title} className="h-full border border-[#173B2A]/12 bg-[#FBF8F1] p-7"><span className="block h-px w-12 bg-[#C9A962]" /><h3 className="mt-5 font-[family-name:var(--font-playfair)] text-2xl font-semibold">{title}</h3><p className="mt-4 text-[14px] font-light leading-7 text-[#4C5F54]">{text}</p></article>)}</div></div></div></RevealOnScroll></section>

      <section className="px-6 py-24 sm:px-8 lg:px-12 lg:py-32"><RevealOnScroll><div className="mx-auto max-w-[1500px]"><div className="mx-auto max-w-[900px] text-center"><p className="text-[10px] font-bold uppercase tracking-[0.4em] text-[#9F7F36]">Priorità del mercato nordico</p><h2 className="mt-6 font-[family-name:var(--font-playfair)] text-[clamp(2.5rem,4.6vw,4.6rem)] font-semibold leading-[1.04]">Pianificazione pratica della fornitura <span className="block text-[#A97B22]">per acquirenti finlandesi</span></h2><p className="mx-auto mt-7 max-w-[780px] text-[15px] font-light leading-8 text-[#4C5F54]">I programmi destinati alla Finlandia possono essere valutati in base a informazioni di prodotto chiare, confezionamento pratico, adeguato coordinamento linguistico e priorità di sostenibilità commercialmente realistiche.</p></div><div className="mt-14 grid auto-rows-fr gap-5 sm:grid-cols-2 lg:grid-cols-4">{nordicPriorities.map(([title, text]) => <article key={title} className="h-full border border-[#173B2A]/12 bg-[#FBF8F1] p-7"><span className="block h-px w-12 bg-[#C9A962]" /><h3 className="mt-5 font-[family-name:var(--font-playfair)] text-2xl font-semibold">{title}</h3><p className="mt-4 text-[14px] font-light leading-7 text-[#4C5F54]">{text}</p></article>)}</div></div></RevealOnScroll></section>

      <section className="bg-[#EDE5D7] px-6 py-24 sm:px-8 lg:px-12 lg:py-32"><RevealOnScroll><div className="mx-auto grid max-w-[1500px] gap-14 lg:grid-cols-[1.05fr_0.95fr] lg:gap-20"><div><p className="text-[10px] font-bold uppercase tracking-[0.4em] text-[#9F7F36]">Formati a marchio dell’acquirente</p><h2 className="mt-6 font-[family-name:var(--font-playfair)] text-[clamp(2.5rem,4.6vw,4.6rem)] font-semibold leading-[1.04]">Soluzioni di confezionamento e Private Label <span className="block text-[#A97B22]">per acquirenti finlandesi</span></h2><p className="mt-7 text-[15px] font-light leading-8 text-[#4C5F54]">I programmi selezionati possono comprendere nomi di marchio personalizzati, buste e scatole stampate, coordinamento delle grafiche fornite dall’acquirente, codici a barre, supporto al layout delle etichette, coordinamento delle grafiche in finlandese, svedese o bilingui e verifica del confezionamento attenta alla sostenibilità. I formati retail, per saloni, professionali e sfusi, inclusa la fornitura OEM o Private Label, restano soggetti ai requisiti concordati e alla fattibilità tecnica.</p><p className="mt-5 text-[14px] font-light leading-7 text-[#4C5F54]">Le opzioni retail possono comprendere buste da 100 g, 200 g, 500 g e 1 kg. I formati sfusi possono comprendere sacchi sottovuoto a doppio strato da 20 kg e 25 kg. Le etichette finali, i requisiti linguistici, le dichiarazioni, la classificazione del prodotto e la conformità nel mercato di destinazione restano soggetti alla verifica dell’acquirente e alla categoria di prodotto applicabile.</p></div><div><figure className="relative aspect-[3/2] overflow-hidden rounded-sm border border-[#C9A962]/35 shadow-[0_28px_70px_rgba(20,50,38,0.18)]"><Image src="/images/export/finland/finland-buyer-partnership.png" alt="Specialisti finlandesi del confezionamento valutano formati Private Label per prodotti naturali indiani" fill sizes="(min-width: 1024px) 45vw, 100vw" className="object-cover object-center" /></figure><div className="mt-5 grid gap-5 sm:grid-cols-2"><article className="border border-[#C9A962]/35 bg-[#FBF8F1] p-7"><h3 className="font-[family-name:var(--font-playfair)] text-2xl font-semibold">Confezionamento retail</h3><p className="mt-4 text-sm leading-7 text-[#4C5F54]">Buste da 100 g · 200 g · 500 g · 1 kg</p></article><article className="border border-[#C9A962]/35 bg-[#FBF8F1] p-7"><h3 className="font-[family-name:var(--font-playfair)] text-2xl font-semibold">Confezionamento sfuso</h3><p className="mt-4 text-sm leading-7 text-[#4C5F54]">Sacchi sottovuoto a doppio strato da 20 kg e 25 kg</p></article><article className="border border-[#C9A962] bg-[#173B2A] p-7 text-[#F5F0E6] sm:col-span-2"><p className="text-[10px] font-bold uppercase tracking-[0.3em] text-[#E4C878]">Quantità minima d’ordine</p><p className="mt-4 font-[family-name:var(--font-playfair)] text-4xl font-semibold">200 kg per prodotto</p></article></div></div></div></RevealOnScroll></section>

      <section className="bg-[#09271D] px-6 py-24 text-[#F5F0E6] sm:px-8 lg:px-12 lg:py-32"><RevealOnScroll><div className="mx-auto max-w-[1500px]"><div className="grid items-center gap-14 lg:grid-cols-[1.05fr_0.95fr] lg:gap-20"><div><p className="text-[10px] font-bold uppercase tracking-[0.4em] text-[#E4C878]">Supporto per spedizioni e documenti</p><h2 className="mt-6 font-[family-name:var(--font-playfair)] text-[clamp(2.5rem,4.8vw,4.8rem)] font-semibold leading-[1.04]">Coordinamento export India–Finlandia</h2><p className="mt-7 text-[16px] font-light leading-8 text-[#F5F0E6]/68">Il coordinamento può comprendere fatture commerciali, Packing List, certificati di origine, specifiche di prodotto, COA e documenti di qualità disponibili, documentazione di spedizione, spedizionieri incaricati dall’acquirente, cartoni export, pallet e condivisione delle informazioni sulla spedizione.</p><p className="mt-5 text-[15px] font-light leading-8 text-[#F5F0E6]/62">Le modalità selezionate dall’acquirente possono prevedere trasporto marittimo attraverso Helsinki, Turku, HaminaKotka o un altro porto finlandese concordato, con successivo trasporto stradale o ferroviario ove necessario. Il trasporto aereo può essere coordinato tramite l’aeroporto di Helsinki o un’altra modalità scelta dall’acquirente. Non sono garantiti gateway, rotta, tempo di transito o sdoganamento. Documentazione e informazioni sul prodotto possono essere coordinate secondo categoria, destinazione, istruzioni dell’acquirente e requisiti concordati per l’ordine.</p></div><figure className="relative aspect-[3/2] overflow-hidden rounded-sm border border-[#C9A962]/35 shadow-[0_28px_70px_rgba(0,0,0,0.25)]"><Image src="/images/export/finland/india-to-finland-export-coordination.png" alt="Coordinamento export India–Finlandia per prodotti naturali attraverso la logistica marittima e ferroviaria finlandese" fill sizes="(min-width: 1024px) 45vw, 100vw" className="object-cover object-center" /></figure></div><aside className="mt-12 border border-[#C9A962]/35 bg-[#071B14]/60 p-7 text-[14px] font-light leading-7 text-[#F5F0E6]/65">L’importatore o l’acquirente finlandese resta responsabile della conferma di classificazione, etichettatura, registrazione, procedure doganali, imposte e requisiti finlandesi e dell’Unione europea applicabili nel mercato di destinazione. Non si dichiara alcuna conformità, registrazione o sdoganamento automatico.</aside></div></RevealOnScroll></section>

      <section className="bg-[#EDE5D7] px-6 py-24 sm:px-8 lg:px-12 lg:py-32"><RevealOnScroll><div className="mx-auto max-w-[1500px]"><div className="mx-auto max-w-[920px] text-center"><p className="text-[10px] font-bold uppercase tracking-[0.4em] text-[#9F7F36]">Cinque fasi commerciali</p><h2 className="mt-6 font-[family-name:var(--font-playfair)] text-[clamp(2.5rem,4.7vw,4.7rem)] font-semibold leading-[1.04]">Dai requisiti dell’acquirente finlandese al coordinamento export</h2></div><div className="mt-14 grid auto-rows-fr gap-5 sm:grid-cols-2 lg:grid-cols-3">{processSteps.map(([title, text]) => <article key={title} className="h-full border border-[#173B2A]/12 bg-[#FBF8F1] p-7 sm:p-8"><span className="block h-px w-12 bg-[#C9A962]" /><h3 className="mt-6 font-[family-name:var(--font-playfair)] text-2xl font-semibold">{title}</h3><p className="mt-4 text-[14px] font-light leading-7 text-[#4C5F54]">{text}</p></article>)}</div></div></RevealOnScroll></section>

      <section className="px-6 py-24 sm:px-8 lg:px-12 lg:py-32"><RevealOnScroll><div className="mx-auto max-w-[1120px]"><p className="text-[10px] font-bold uppercase tracking-[0.4em] text-[#9F7F36]">Località degli acquirenti in Finlandia</p><h2 className="mt-6 font-[family-name:var(--font-playfair)] text-[clamp(2.5rem,4.6vw,4.6rem)] font-semibold leading-[1.04]">Fornitura di prodotti naturali per acquirenti in tutta la Finlandia</h2><p className="mt-7 text-[15px] leading-7 text-[#4C5F54]">Questi riferimenti di mercato indicano potenziali località di richiesta e distribuzione; non rappresentano uffici o magazzini locali di Shivesh International né rapporti di fornitura attivi garantiti.</p><div className="mt-10 grid auto-rows-fr gap-5 sm:grid-cols-2 lg:grid-cols-4">{marketLocations.map(([location, text]) => <article key={location} className="h-full border border-[#C9A962]/35 bg-[#FBF8F1] p-6"><h3 className="font-[family-name:var(--font-playfair)] text-2xl font-semibold text-[#A97B22]">{location}</h3><p className="mt-4 text-[14px] font-light leading-7 text-[#4C5F54]">{text}</p></article>)}</div></div></RevealOnScroll></section>

      <section className="bg-[#EDE5D7] px-6 py-24 sm:px-8 lg:px-12 lg:py-32"><RevealOnScroll><div className="mx-auto max-w-[1120px]"><div className="text-center"><p className="text-[10px] font-bold uppercase tracking-[0.4em] text-[#9F7F36]">Domande degli acquirenti finlandesi</p><h2 className="mt-6 font-[family-name:var(--font-playfair)] text-[clamp(2.4rem,4.4vw,4.4rem)] font-semibold">Domande frequenti sulla fornitura export in Finlandia</h2></div><div className="mt-12 divide-y divide-[#173B2A]/15 border-y border-[#173B2A]/15">{faqs.map((faq) => <article key={faq.question} className="grid gap-4 py-7 md:grid-cols-[0.8fr_1.2fr] md:gap-10"><h3 className="font-[family-name:var(--font-playfair)] text-xl font-semibold">{faq.question}</h3><p className="text-[14px] font-light leading-7 text-[#4C5F54]">{faq.answer}</p></article>)}</div></div></RevealOnScroll></section>

      <section className="relative overflow-hidden bg-[#071B14] px-6 py-24 text-center text-[#F5F0E6] sm:px-8 lg:px-12 lg:py-28"><GoldenParticles /><RevealOnScroll><div className="relative mx-auto max-w-[1000px]"><p className="text-[10px] font-bold uppercase tracking-[0.4em] text-[#E4C878]">Richieste degli acquirenti finlandesi</p><h2 className="mt-6 font-[family-name:var(--font-playfair)] text-[clamp(2.5rem,4.8vw,4.8rem)] font-semibold leading-[1.04]">Parlateci delle vostre esigenze di prodotto per la Finlandia</h2><p className="mx-auto mt-7 max-w-[760px] text-[16px] font-light leading-8 text-[#F5F0E6]/65">Importatori, distributori, grossisti e acquirenti Private Label finlandesi possono comunicare al nostro team export il nome del prodotto, la quantità richiesta, il formato di confezionamento, la destinazione e l’applicazione commerciale prevista.</p><div className="mt-9 flex flex-wrap justify-center gap-4"><Link href="/contact" className="inline-flex items-center gap-4 border border-[#C9A962] bg-[#C9A962] px-8 py-4 text-[10px] font-bold uppercase tracking-[0.22em] text-[#102F23] transition-all hover:-translate-y-1 hover:bg-[#E4C878]">Invia i requisiti per la Finlandia <span>→</span></Link><Link href="/export/europe" className="inline-flex items-center gap-4 border border-[#F5F0E6]/30 px-8 py-4 text-[10px] font-bold uppercase tracking-[0.22em] text-[#F5F0E6] transition-all hover:border-[#C9A962] hover:text-[#E4C878]">Scopri i mercati europei <span>→</span></Link></div><div className="mt-9 flex flex-wrap justify-center gap-x-6 gap-y-3 text-[10px] font-bold uppercase tracking-[0.16em] text-[#F5F0E6]/45"><Link href="/export">Informazioni export globali</Link><Link href="/export/france">Mercato export Francia</Link><Link href="/export/germany">Mercato export Germania</Link><Link href="/export/italy">Mercato export Italia</Link><Link href="/export/spain">Mercato export Spagna</Link><Link href="/export/austria">Mercato export Austria</Link><Link href="/resources">Risorse per gli acquirenti</Link><Link href="/certifications">Certificazioni</Link><Link href="/infrastructure">Infrastruttura</Link><Link href="/about">Chi è Shivesh International</Link><Link href="/export/finland">Pagina export Finlandia</Link></div></div></RevealOnScroll></section>

      <style>{`@media (max-width: 420px) { main > header nav { gap: 0.5rem; padding-left: 1rem; padding-right: 1rem; } main > header nav > a > div:last-child { display: none; } }`}</style>
      <FooterSection locale="it" /><FloatingContactButtons /><MagneticButtons /><PremiumCursor />
    </main>
  );
}
