import type { Metadata } from "next";
import Image from "next/image";
import Link from "next/link";

import FloatingContactButtons from "@/app/components/FloatingContactButtons";
import GoldenParticles from "@/app/components/GoldenParticles";
import MagneticButtons from "@/app/components/MagneticButtons";
import Navbar from "@/app/components/Navbar";
import PremiumCursor from "@/app/components/PremiumCursor";
import RevealOnScroll from "@/app/components/RevealOnScroll";
import StaggerItem from "@/app/components/StaggerItem";
import { belgiumLanguageAlternates } from "@/app/lib/i18n";
import FooterSection from "@/sections/FooterSection";

const pageUrl = "https://shiveshinternational.com/it/export/belgio";
const heroImage = "https://shiveshinternational.com/images/export/belgium/belgium-export-hero-natural-henna-hair-colors.png";

export const metadata: Metadata = {
  title: "Esportatore di prodotti naturali in Belgio",
  description: "Henné, indigo, colorazioni vegetali, erbe ayurvediche e spezie indiane per il Belgio. Fornitura all’ingrosso, OEM e Private Label; MOQ di 200 kg per articolo.",
  keywords: [
    "esportatore di prodotti naturali in Belgio", "produttore di henné per il Belgio", "fornitore di henné naturale in Belgio", "henné all’ingrosso Belgio", "esportatore di henné naturale", "fornitore di indigo naturale", "esportatore di indigo naturale", "fornitore di colorazioni vegetali", "colorazione botanica per capelli", "fornitore per saloni professionali", "fornitore di cosmetici naturali", "importatori in Belgio", "distributori in Belgio", "grossisti in Belgio", "rivenditori specializzati", "fornitore di erbe ayurvediche", "esportatore di erbe ayurvediche", "fornitore di spezie indiane", "esportatore di spezie indiane", "marchio proprio Belgio", "marca privata Belgio", "Private Label Belgio", "OEM Belgio", "fornitura sfusa Belgio", "approvvigionamento B2B Belgio", "fornitore indiano per acquirenti belgi", "confezionamento di prodotti naturali Belgio", "fornitore per marchi di cura dei capelli Belgio", "esportazione India Belgio", "prodotti botanici per Bruxelles", "fornitura all’ingrosso Anversa", "Shivesh International Belgio",
  ],
  alternates: { canonical: pageUrl, languages: belgiumLanguageAlternates },
  openGraph: { title: "Fornitura di prodotti naturali dall’India al Belgio", description: "Fornitura per il Belgio di henné, indigo, colorazioni botaniche per capelli, erbe ayurvediche e spezie in formati sfusi, all’ingrosso, OEM e Private Label.", url: pageUrl, type: "website", locale: "it_IT", siteName: "Shivesh International", images: [{ url: "/images/export/belgium/belgium-export-hero-natural-henna-hair-colors.png", width: 1944, height: 809, alt: "Professionisti belgi di saloni e colorazione dei capelli esaminano colorazioni naturali all’henné fornite dall’India" }] },
  twitter: { card: "summary_large_image", title: "Fornitura di prodotti naturali per il Belgio", description: "Prodotti botanici indiani per importatori, grossisti, saloni e marchi privati in Belgio.", images: ["/images/export/belgium/belgium-export-hero-natural-henna-hair-colors.png"] },
  robots: { index: true, follow: true },
};

const products = [
  { title: "Henné naturale in polvere", text: "Henné finemente lavorato per importatori belgi, marchi di cosmetica naturale, rivenditori e canali di saloni professionali.", href: "/products/natural-henna-powder" },
  { title: "Indigo naturale in polvere", text: "Indigo botanico per programmi di colorazione dei capelli, valutato in formati sfusi, professionali e con il marchio dell’acquirente.", href: "/products/natural-indigo-powder" },
  { title: "Colorazioni naturali per capelli all’henné", text: "Una gamma di colorazioni vegetali per distributori, marchi per la cura dei capelli e fornitori di saloni che servono il mercato multilingue belga.", href: "/products/natural-henna-hair-colors" },
  { title: "Colorazioni per capelli a base di henné", text: "Prodotti coloranti con il marchio dell’acquirente, valutati in base alla formula, all’uso previsto, al confezionamento e alla fattibilità commerciale.", href: "/products/henna-based-hair-colors" },
  { title: "Erbe ayurvediche indiane", text: "Erbe e polveri botaniche selezionate per programmi belgi di approvvigionamento nel benessere, nel commercio specializzato e nella cura personale.", href: "/products/ayurvedic-indian-herbs" },
  { title: "Spezie indiane", text: "Spezie intere e macinate selezionate per importatori, grossisti, rivenditori e acquirenti del settore alimentare in Belgio.", href: "/products/indian-spices" },
];
const buyers = [
  { title: "Importatori e distributori", text: "Coordiniamo specifiche, quantità commerciali e documentazione disponibile per importatori e distributori che servono Bruxelles, Anversa, Gand e altri mercati belgi." },
  { title: "Marchi retail naturali e biologici", text: "Esaminiamo henné, indigo, erbe, prodotti botanici per capelli e spezie per gamme belghe di prodotti naturali, biologici e del commercio specializzato." },
  { title: "Aziende di cosmetica e cura personale", text: "Supportiamo richieste di approvvigionamento di polveri botaniche, colorazioni vegetali e progetti cosmetici o di cura personale sviluppati dall’acquirente, previa verifica del prodotto e delle relative specifiche." },
  { title: "Fornitori per saloni professionali", text: "Valutiamo henné naturale, indigo e colorazioni botaniche per capelli destinati alla fornitura di saloni e canali di distribuzione professionale in Belgio." },
  { title: "Aziende erboristiche e del benessere", text: "Esaminiamo polveri ayurvediche, ingredienti erboristici ed erbe selezionate per aziende belghe del benessere, dei prodotti erboristici e delle specialità." },
  { title: "Acquirenti OEM e Private Label", text: "Coordiniamo buste, scatole, grafiche, etichette e presentazioni Private Label con il marchio dell’acquirente per ordini commercialmente fattibili." },
  { title: "Importatori di alimenti e spezie", text: "Valutiamo spezie indiane intere, macinate e miscele selezionate per aziende alimentari, importatori e distributori specializzati in Belgio." },
  { title: "Grossisti e rivenditori specializzati", text: "Sviluppiamo assortimenti mirati di prodotti naturali per canali belgi all’ingrosso, e-commerce, retail specializzato e di fornitura professionale." },
];
const steps = [
  ["01", "Selezione dei prodotti", "Confermate la famiglia di prodotti, il canale previsto, la qualità, la quantità e la destinazione in Belgio."],
  ["02", "Specifiche e campioni", "Esaminate le specifiche disponibili e richiedete campioni quando commercialmente fattibile."],
  ["03", "Offerta e condizioni", "Confermate l’ambito, i prezzi, le condizioni di pagamento, il formato di confezionamento e i termini di spedizione applicabili."],
  ["04", "Confezionamento e Private Label", "Esaminate i formati retail o sfusi, la grafica dell’acquirente, le etichette e la fattibilità di stampa."],
  ["05", "Produzione e controlli qualità", "Lavoriamo, confezioniamo e controlliamo i prodotti confermati in base ai requisiti concordati per l’ordine."],
  ["06", "Documenti e spedizione", "Coordiniamo la documentazione export disponibile, la pianificazione della spedizione e lo scambio documentale con l’acquirente o lo spedizioniere da lui incaricato."],
];
const documents = [
  { title: "Fattura commerciale", text: "Le informazioni della fattura commerciale possono essere predisposte in base all’acquirente, ai prodotti, alle quantità, ai valori e alle condizioni di spedizione confermati." },
  { title: "Packing List", text: "Per gli ordini confermati è possibile coordinare numero dei colli, pesi netti e lordi, dati delle scatole e riferimenti di spedizione concordati." },
  { title: "Certificato di origine", text: "Il coordinamento del certificato di origine può essere valutato quando applicabile al prodotto e alla spedizione confermati." },
  { title: "Specifiche e COA", text: "Le specifiche, il COA ove disponibile, i riferimenti di lotto e le informazioni disponibili sulla qualità dipendono dal prodotto selezionato." },
  { title: "Informazioni sul confezionamento", text: "Le informazioni relative a buste, scatole, imballaggi sfusi, etichette e codici a barre possono essere adattate al programma di confezionamento approvato dall’acquirente." },
  { title: "Documenti di trasporto", text: "La documentazione di spedizione può essere coordinata con lo spedizioniere designato dall’acquirente e il piano di spedizione concordato." },
  { title: "Informazioni su prodotto e lotto", text: "Ove disponibili, le informazioni sul prodotto, sul lotto, tecniche e di riferimento qualitativo possono essere esaminate in base all’articolo confermato." },
  { title: "Responsabilità di verifica dell’importatore", text: "L’importatore o acquirente belga è responsabile dei requisiti applicabili relativi a importazione, registrazione, etichettatura, indicazioni, dogana e accesso al mercato." },
];
const locations = [
  { title: "Bruxelles", text: "Importatori, aziende cosmetiche, marchi e-commerce e distributori nazionali possono valutare l’approvvigionamento multicategoria e programmi con il marchio dell’acquirente." },
  { title: "Anversa", text: "Importatori collegati al porto, grossisti e acquirenti orientati alla logistica possono esaminare la fornitura sfusa, l’imballaggio export e le esigenze di distribuzione successiva." },
  { title: "Gand", text: "Rivenditori di prodotti naturali, aziende del benessere, fornitori di saloni e acquirenti alimentari possono valutare gamme mirate di erbe, cura dei capelli e spezie." },
  { title: "Liegi", text: "Distributori belgi francofoni e rivenditori specializzati possono valutare prodotti naturali per canali professionali, retail ed e-commerce." },
  { title: "Charleroi", text: "Grossisti regionali, aziende di cura personale e fornitori professionali possono esaminare prodotti, confezioni e strutture d’ordine commercialmente adeguate." },
  { title: "Namur", text: "Rivenditori specializzati, aziende erboristiche e marchi del benessere possono valutare erbe, polveri botaniche e formati con il marchio dell’acquirente." },
  { title: "Lovanio", text: "Aziende orientate all’innovazione, imprese cosmetiche e acquirenti specializzati possono esaminare specifiche e progetti Private Label attentamente definiti." },
  { title: "Bruges", text: "Aziende retail, imprese legate all’ospitalità e distributori regionali possono esaminare programmi pertinenti di fornitura di prodotti naturali e spezie indiane." },
];
const faqs = [
  { question: "Quali prodotti possono acquistare gli acquirenti belgi?", answer: "La gamma comprende henné naturale in polvere, indigo naturale in polvere, colorazioni naturali per capelli all’henné, colorazioni a base di henné, erbe ayurvediche indiane e spezie indiane selezionate. Idoneità e disponibilità vengono verificate per ogni richiesta." },
  { question: "Qual è l’ordine minimo per il Belgio?", answer: "Il MOQ è di 200 kg per articolo. Le quantità finali e le configurazioni di confezionamento dipendono dal prodotto, dal formato e dall’ambito commerciale confermati." },
  { question: "Offrite forniture sfuse e all’ingrosso?", answer: "Sì. I prodotti idonei possono essere preparati in imballaggi sfusi concordati da 20 kg o 25 kg, formati professionali o presentazioni retail selezionate, in base al prodotto e alla quantità." },
  { question: "I marchi belgi possono richiedere forniture Private Label o OEM?", answer: "È possibile valutare programmi OEM e Private Label selezionati per ordini commercialmente fattibili. I dettagli relativi a prodotto, confezionamento, grafica, stampa e produzione vengono confermati prima di procedere con l’ordine." },
  { question: "Quali formati di confezionamento retail possono essere valutati?", answer: "In base al prodotto e alla quantità, le opzioni possono includere confezioni da 100 g, 200 g, 500 g e 1 kg, buste metallizzate argentate o dorate, formati kraft, scatole e presentazioni con il marchio dell’acquirente." },
  { question: "È possibile valutare campioni prima di un ordine commerciale?", answer: "I campioni possono essere valutati quando fattibili, dopo aver definito prodotto, specifiche, uso previsto e quantità commerciale richiesta." },
  { question: "Quali documenti di esportazione sono disponibili per gli ordini destinati al Belgio?", answer: "La documentazione commerciale, di prodotto e di spedizione disponibile può essere esaminata in base al prodotto selezionato, ai requisiti dell’ordine e all’operazione concordata. Nessun documento o approvazione si considera disponibile senza conferma." },
  { question: "Chi è responsabile dei requisiti di importazione belgi e dell’UE?", answer: "L’importatore o acquirente belga è responsabile della classificazione, dei permessi di importazione, dello sdoganamento, dell’etichettatura, delle indicazioni, della registrazione e di tutti i requisiti applicabili in Belgio e nell’UE. Coordiniamo le informazioni di esportazione e spedizione in conformità alle condizioni commerciali confermate, senza garantire lo sdoganamento o i tempi di consegna." },
];
const structuredData = { "@context": "https://schema.org", "@graph": [
  { "@type": "WebPage", "@id": `${pageUrl}#webpage`, url: pageUrl, name: "Esportatore di prodotti naturali dall’India al Belgio", description: "Fornitura sfusa, all’ingrosso, OEM e Private Label di prodotti botanici indiani per acquirenti professionali in Belgio.", isPartOf: { "@id": "https://shiveshinternational.com/#website" }, about: { "@id": "https://shiveshinternational.com/#organization" }, breadcrumb: { "@id": `${pageUrl}#breadcrumb` }, primaryImageOfPage: { "@type": "ImageObject", url: heroImage }, inLanguage: "it" },
  { "@type": "BreadcrumbList", "@id": `${pageUrl}#breadcrumb`, itemListElement: [{ "@type": "ListItem", position: 1, name: "Home", item: "https://shiveshinternational.com/" }, { "@type": "ListItem", position: 2, name: "Export", item: "https://shiveshinternational.com/export" }, { "@type": "ListItem", position: 3, name: "Esportazione in Belgio", item: pageUrl }] },
] };
const faqStructuredData = { "@context": "https://schema.org", "@type": "FAQPage", "@id": `${pageUrl}#faq`, mainEntity: faqs.map((faq) => ({ "@type": "Question", name: faq.question, acceptedAnswer: { "@type": "Answer", text: faq.answer } })) };

export default function BelgiumExportPageItalian() {
  return <main className="min-h-screen overflow-x-hidden bg-[#F5F0E6] text-[#173B2A]">
    <script type="application/ld+json" dangerouslySetInnerHTML={{ __html: JSON.stringify(structuredData).replace(/</g, "\\u003c") }} />
    <script type="application/ld+json" dangerouslySetInnerHTML={{ __html: JSON.stringify(faqStructuredData).replace(/</g, "\\u003c") }} />
    <Navbar />
    <section className="relative isolate overflow-hidden bg-[#071B14]">
      <Image src="/images/export/belgium/belgium-export-hero-natural-henna-hair-colors.png" alt="Professionisti belgi di saloni e colorazione dei capelli esaminano colorazioni naturali all’henné fornite dall’India" fill priority sizes="100vw" className="object-cover object-[68%_center] sm:object-[64%_center] lg:object-center" />
      <div className="absolute inset-0 bg-gradient-to-r from-[#061711]/80 via-[#102F23]/38 to-transparent" /><GoldenParticles />
      <div className="relative z-10 flex min-h-[760px] items-center px-6 pb-24 pt-28 sm:px-8 lg:px-12"><div className="w-full max-w-[820px]">
        <p className="text-[10px] font-bold uppercase tracking-[0.34em] text-[#E4C878] sm:text-xs">Fornitura B2B dall’India al Belgio</p>
        <h1 className="mt-6 font-[family-name:var(--font-playfair)] text-[clamp(2.4rem,5vw,5.2rem)] font-medium leading-[1.03] tracking-[-0.04em] text-[#F5F0E6]">Esportatore di prodotti naturali<span className="mt-2 block text-[#E4C878]">dall’India al Belgio</span></h1>
        <p className="mt-7 max-w-[720px] text-[16px] font-light leading-8 text-white/78 sm:text-[18px]">Fornitura commerciale di henné naturale, indigo, colorazioni botaniche per capelli, erbe ayurvediche e spezie indiane per importatori, grossisti, saloni e marchi in Belgio, attraverso programmi sfusi, all’ingrosso, OEM e Private Label.</p>
        <div className="mt-9 flex flex-wrap gap-4"><a href="#productos" className="border border-[#C9A962] bg-[#C9A962] px-7 py-4 text-[10px] font-bold uppercase tracking-[0.2em] text-[#102F23]">Scopri i prodotti ↓</a><Link href="/contact" className="border border-white/30 bg-black/20 px-7 py-4 text-[10px] font-bold uppercase tracking-[0.2em] text-white">Richiedi un preventivo per il Belgio</Link></div>
        <div className="mt-10 grid max-w-[760px] gap-3 sm:grid-cols-2 lg:grid-cols-4">{[["200 kg", "MOQ per articolo"], ["Sei", "Famiglie di prodotti"], ["OEM", "Private Label"], ["Belgio", "Acquirenti professionali"]].map(([value,label]) => <div key={label} className="border border-white/15 bg-black/25 px-4 py-4"><p className="font-[family-name:var(--font-playfair)] text-xl text-[#E4C878]">{value}</p><p className="mt-2 text-[9px] font-bold uppercase tracking-[0.16em] text-white/55">{label}</p></div>)}</div>
      </div></div>
    </section>

    <section id="productos" className="px-6 py-24 sm:px-8 lg:px-12 lg:py-32"><RevealOnScroll><div className="mx-auto max-w-[1500px]">
      <div className="mx-auto max-w-[900px] text-center"><p className="text-[10px] font-bold uppercase tracking-[0.38em] text-[#9F7F36]">Sei famiglie commerciali di prodotti</p><h2 className="mt-6 font-[family-name:var(--font-playfair)] text-[clamp(2.25rem,4.6vw,4.8rem)] font-semibold leading-[1.05]">Prodotti naturali dall’India<span className="block text-[#A97B22]">per i portafogli degli acquirenti belgi</span></h2><p className="mx-auto mt-7 max-w-[820px] leading-8 text-[#4C5F54]">Una gamma mirata per i settori della bellezza naturale, della cura professionale dei capelli, dei prodotti erboristici, del benessere, del commercio specializzato e dell’alimentazione pertinente in Belgio.</p></div>
      <div className="mt-14 grid gap-5 sm:grid-cols-2 lg:grid-cols-3">{products.map((product,index) => <StaggerItem key={product.title} delay={(index % 3) * 90}><article className="flex h-full min-h-[290px] flex-col border border-[#173B2A]/12 bg-[#FBF8F1] p-7 sm:p-8"><span className="text-sm font-bold text-[#C9A962]">0{index + 1}</span><h3 className="mt-5 font-[family-name:var(--font-playfair)] text-[27px] font-semibold">{product.title}</h3><p className="mt-5 flex-1 text-[14px] leading-7 text-[#4C5F54]">{product.text}</p><Link href={product.href} className="mt-7 text-[10px] font-bold uppercase tracking-[0.2em] text-[#A97B22]">Vedi prodotto →</Link></article></StaggerItem>)}</div>
    </div></RevealOnScroll></section>

    <section className="px-6 py-24 sm:px-8 lg:px-12 lg:py-32"><RevealOnScroll><div className="mx-auto max-w-[1500px]">
      <div className="text-center"><p className="text-[10px] font-bold uppercase tracking-[0.4em] text-[#9F7F36]">Profili degli acquirenti belgi</p><h2 className="mt-6 font-[family-name:var(--font-playfair)] text-[clamp(2.35rem,4.45vw,4.7rem)] font-semibold leading-[1.05]">Pianificazione della fornitura per<span className="block text-[#A97B22]">canali di importazione, vendita e distribuzione</span></h2><p className="mx-auto mt-7 max-w-[860px] leading-8 text-[#4C5F54]">Gli acquirenti di prodotti naturali in Belgio possono valutare la fornitura in base al prodotto, al canale, alla quantità e all’uso previsto. I riferimenti alle città descrivono esclusivamente contesti commerciali e non implicano strutture, scorte o rappresentanza locale.</p></div>
      <div className="mt-14 grid auto-rows-fr gap-5 md:grid-cols-2 lg:grid-cols-4">{buyers.map((buyer) => <article key={buyer.title} className="h-full min-h-[280px] border border-[#173B2A]/12 bg-[#FBF8F1] p-7 sm:p-8"><span className="block h-px w-12 bg-[#C9A962]" /><h3 className="mt-6 font-[family-name:var(--font-playfair)] text-[24px] font-semibold leading-tight text-[#173B2A]">{buyer.title}</h3><p className="mt-5 text-[14px] font-light leading-7 text-[#4C5F54]">{buyer.text}</p></article>)}</div>
    </div></RevealOnScroll></section>

    <section className="px-6 py-24 sm:px-8 lg:px-12 lg:py-32"><RevealOnScroll><div className="mx-auto grid max-w-[1500px] items-center gap-14 lg:grid-cols-2 lg:gap-20">
      <figure className="relative aspect-[4/3] overflow-hidden border border-[#C9A962]/35 bg-[#102F23]"><Image src="/images/export/belgium/belgium-packaging-private-label.png" alt="Sviluppo di confezioni Private Label per henné, indigo, erbe e colorazioni naturali per capelli destinate al Belgio" fill sizes="(min-width:1024px) 50vw, 100vw" className="object-cover object-center" /></figure>
      <div><p className="text-[10px] font-bold uppercase tracking-[0.38em] text-[#9F7F36]">Confezionamento e sviluppo del marchio dell’acquirente</p><h2 className="mt-6 font-[family-name:var(--font-playfair)] text-[clamp(2.15rem,3.8vw,4rem)] font-semibold leading-[1.07]">Formati per i canali belgi<span className="block text-[#A97B22]">retail, professionali e sfusi</span></h2><p className="mt-7 leading-8 text-[#4C5F54]">In base al prodotto e alla quantità, le confezioni retail possono includere formati da 100 g, 200 g, 500 g e 1 kg; le opzioni sfuse possono includere imballaggi da 20 kg e 25 kg con confezionamento sottovuoto a doppio strato ove applicabile.</p><p className="mt-5 leading-8 text-[#4C5F54]">Le buste metallizzate argentate o dorate, i formati kraft, le scatole, le grafiche del marchio, il coordinamento delle etichette e la presentazione Private Label possono essere valutati in base alla disponibilità dei materiali e alla fattibilità di stampa, produzione e commerciale. L’acquirente belga è responsabile dell’etichettatura e dei requisiti di mercato applicabili.</p><Link href="/contact" className="mt-8 inline-flex border border-[#C9A962] bg-[#C9A962] px-7 py-4 text-[10px] font-bold uppercase tracking-[0.2em] text-[#102F23]">Richiedi informazioni sulla Private Label →</Link></div>
    </div></RevealOnScroll></section>

    <section className="bg-[#09271D] px-6 py-24 text-[#F5F0E6] sm:px-8 lg:px-12 lg:py-32"><RevealOnScroll><div className="mx-auto max-w-[1500px]">
      <div className="grid items-center gap-12 lg:grid-cols-[0.9fr_1.1fr]"><div><p className="text-[10px] font-bold uppercase tracking-[0.38em] text-[#E4C878]">Coordinamento dall’India al Belgio</p><h2 className="mt-6 font-[family-name:var(--font-playfair)] text-[clamp(2.25rem,4.3vw,4.5rem)] font-semibold leading-[1.05]">Un percorso strutturato dalla<span className="block text-[#E4C878]">richiesta fino alla spedizione</span></h2><p className="mt-7 leading-8 text-white/65">La pianificazione della spedizione può essere coordinata per destinazioni dell’acquirente come Anversa, Bruxelles e Gand, in base alle condizioni confermate, alla disponibilità del vettore e alle istruzioni dell’acquirente o dello spedizioniere da lui incaricato.</p></div><figure className="relative aspect-[4/3] overflow-hidden border border-[#C9A962]/30"><Image src="/images/export/belgium/belgium-export-freight-coordination.png" alt="Coordinamento dell’esportazione e del trasporto di prodotti naturali sfusi dall’India al Belgio" fill sizes="(min-width:1024px) 55vw, 100vw" className="object-cover object-center" /></figure></div>
      <aside className="mt-12 border border-[#C9A962]/40 bg-[#F5F0E6] p-7 text-[#173B2A] sm:p-9"><h3 className="font-[family-name:var(--font-playfair)] text-2xl font-semibold text-[#A97B22]">Documentazione e responsabilità dell’importatore</h3><p className="mt-4 text-[14px] leading-7 text-[#4C5F54]">La documentazione disponibile può essere esaminata in base al prodotto e ai requisiti dell’ordine. Non sono garantiti tariffe di trasporto, orari, transito, sdoganamento, ispezione, registrazione, accettazione normativa o date di consegna. L’importatore belga rimane responsabile di tutti gli obblighi applicabili relativi all’importazione e alla commercializzazione.</p></aside>
    </div></RevealOnScroll></section>

    <section className="px-6 py-24 sm:px-8 lg:px-12 lg:py-32"><RevealOnScroll><div className="mx-auto max-w-[1500px]">
      <div className="mx-auto max-w-[920px] text-center"><p className="text-[10px] font-bold uppercase tracking-[0.38em] text-[#9F7F36]">Informazioni per la verifica dell’acquirente</p><h2 className="mt-6 font-[family-name:var(--font-playfair)] text-[clamp(2.2rem,4.4vw,4.6rem)] font-semibold leading-[1.06]">Documentazione di esportazione<span className="block text-[#A97B22]">per gli acquirenti in Belgio</span></h2><p className="mx-auto mt-7 max-w-[850px] leading-8 text-[#4C5F54]">I documenti dipendono dal prodotto selezionato, dalla struttura dell’ordine e dalla loro disponibilità. Le informazioni commerciali, di prodotto, confezionamento e spedizione disponibili possono essere coordinate per la verifica dell’acquirente e della destinazione, senza implicare la conformità automatica alla normativa belga o dell’Unione europea.</p></div>
      <div className="mt-14 grid gap-5 md:grid-cols-2 lg:grid-cols-4">{documents.map((document, index) => <StaggerItem key={document.title} delay={(index % 4) * 80}><article className="h-full min-h-[260px] border border-[#173B2A]/12 bg-[#FBF8F1] p-7 sm:p-8"><div className="flex items-center justify-between"><span className="h-px w-12 bg-[#C9A962]" /><span className="font-[family-name:var(--font-playfair)] text-xl text-[#C9A962]/70">{String(index + 1).padStart(2, "0")}</span></div><h3 className="mt-7 font-[family-name:var(--font-playfair)] text-[24px] font-semibold leading-tight">{document.title}</h3><p className="mt-5 text-[14px] font-light leading-7 text-[#4C5F54]">{document.text}</p></article></StaggerItem>)}</div>
    </div></RevealOnScroll></section>

    <section className="bg-[#EDE5D7] px-6 py-24 sm:px-8 lg:px-12 lg:py-32"><RevealOnScroll><div className="mx-auto max-w-[1500px]">
      <div className="text-center"><p className="text-[10px] font-bold uppercase tracking-[0.4em] text-[#9F7F36]">Sei etapas comerciales</p><h2 className="mt-6 font-[family-name:var(--font-playfair)] text-[clamp(2.3rem,4.45vw,4.7rem)] font-semibold leading-[1.05]">Dall’esigenza dell’acquirente belga<span className="block text-[#A97B22]">al coordinamento dell’esportazione</span></h2></div>
      <div className="mt-14 grid auto-rows-fr gap-5 md:grid-cols-2 lg:grid-cols-3">{steps.map(([number, title, text]) => <article key={number} className="h-full min-h-[220px] border border-[#173B2A]/12 bg-[#FBF8F1] p-7 sm:p-8"><div className="flex items-center justify-between"><span className="h-px w-12 bg-[#C9A962]" /><span className="font-[family-name:var(--font-playfair)] text-xl text-[#C9A962]/70">{number}</span></div><h3 className="mt-6 font-[family-name:var(--font-playfair)] text-[24px] font-semibold leading-tight">{title}</h3><p className="mt-5 text-[14px] font-light leading-7 text-[#4C5F54]">{text}</p></article>)}</div>
    </div></RevealOnScroll></section>

    <section className="px-6 py-24 sm:px-8 lg:px-12 lg:py-32"><RevealOnScroll><div className="mx-auto max-w-[1280px]">
      <p className="text-[10px] font-bold uppercase tracking-[0.4em] text-[#9F7F36]">Principali località commerciali belghe</p><h2 className="mt-6 font-[family-name:var(--font-playfair)] text-[clamp(2.3rem,4.4vw,4.6rem)] font-semibold leading-[1.05]">Contesto degli acquirenti e della distribuzione<span className="block text-[#A97B22]">in tutto il Belgio</span></h2><p className="mt-7 max-w-[900px] text-[15px] leading-8 text-[#4C5F54]">Queste località identificano possibili contesti commerciali e distributivi; non rappresentano strutture, scorte, dipendenti, agenti o rapporti garantiti in Belgio.</p>
      <div className="mt-12 grid auto-rows-fr gap-5 md:grid-cols-2 lg:grid-cols-4">{locations.map((location) => <article key={location.title} className="h-full min-h-[245px] border border-[#173B2A]/12 bg-[#FBF8F1] p-7 sm:p-8"><span className="block h-px w-12 bg-[#C9A962]" /><h3 className="mt-6 font-[family-name:var(--font-playfair)] text-[26px] font-semibold">{location.title}</h3><p className="mt-5 text-[14px] font-light leading-7 text-[#4C5F54]">{location.text}</p></article>)}</div>
    </div></RevealOnScroll></section>

    <section className="px-6 py-24 sm:px-8 lg:px-12 lg:py-32"><RevealOnScroll><div className="mx-auto max-w-[1120px]"><div className="text-center"><p className="text-[10px] font-bold uppercase tracking-[0.38em] text-[#9F7F36]">Richieste di approvvigionamento per il Belgio</p><h2 className="mt-6 font-[family-name:var(--font-playfair)] text-[clamp(2.05rem,4vw,4.2rem)] font-semibold">Domande frequenti</h2></div><div className="mt-12 divide-y divide-[#173B2A]/15 border-y border-[#173B2A]/15">{faqs.map((faq) => <article key={faq.question} className="grid gap-4 py-7 md:grid-cols-[0.8fr_1.2fr] md:gap-10"><h3 className="font-[family-name:var(--font-playfair)] text-xl font-semibold">{faq.question}</h3><p className="text-[14px] leading-7 text-[#4C5F54]">{faq.answer}</p></article>)}</div></div></RevealOnScroll></section>

    <section className="relative overflow-hidden bg-[#071B14] px-6 py-24 text-center text-[#F5F0E6] sm:px-8 lg:px-12"><GoldenParticles /><RevealOnScroll><div className="relative mx-auto max-w-[980px]"><p className="text-[10px] font-bold uppercase tracking-[0.38em] text-[#E4C878]">Avviate un progetto di approvvigionamento per il Belgio</p><h2 className="mt-6 font-[family-name:var(--font-playfair)] text-[clamp(2.1rem,4.25vw,4.5rem)] font-semibold leading-[1.06]">Pianificate la fornitura di prodotti naturali dall’India</h2><p className="mx-auto mt-7 max-w-[760px] leading-8 text-white/65">Indicate il prodotto, la quantità, le specifiche, il confezionamento, le esigenze relative al marchio dell’acquirente e la destinazione in Belgio per una verifica commerciale mirata.</p><Link href="/contact" className="mt-9 inline-flex border border-[#C9A962] bg-[#C9A962] px-8 py-4 text-[10px] font-bold uppercase tracking-[0.22em] text-[#102F23]">Richiedi un preventivo per il Belgio →</Link></div></RevealOnScroll></section>
    <FooterSection locale="it" /><FloatingContactButtons /><MagneticButtons /><PremiumCursor />
  </main>;
}
