import type { MetadataRoute } from "next";

import {
  austriaLanguageAlternates,
  belgiumLanguageAlternates,
  franceLanguageAlternates,
  germanyLanguageAlternates,
  italyLanguageAlternates,
  spainLanguageAlternates,
} from "@/app/lib/i18n";

const baseUrl = "https://shiveshinternational.com";

export default function sitemap(): MetadataRoute.Sitemap {
  return [
    {
      url: baseUrl,
      changeFrequency: "weekly",
      priority: 1,
    },
    {
      url: `${baseUrl}/about`,
      changeFrequency: "monthly",
      priority: 0.8,
    },
    {
      url: `${baseUrl}/certifications`,
      changeFrequency: "monthly",
      priority: 0.8,
    },
    {
      url: `${baseUrl}/infrastructure`,
      changeFrequency: "monthly",
      priority: 0.8,
    },
    {
      url: `${baseUrl}/export`,
      changeFrequency: "monthly",
      priority: 0.9,
    },
    {
      url: `${baseUrl}/export/europe`,
      lastModified: new Date("2026-08-20"),
      changeFrequency: "monthly",
      priority: 0.9,
    },
    {
      url: `${baseUrl}/export/asia-pacific`,
      lastModified: new Date("2026-08-22"),
      changeFrequency: "monthly",
      priority: 0.9,
    },
    {
      url: `${baseUrl}/export/china`,
      lastModified: new Date("2026-08-22"),
      changeFrequency: "monthly",
      priority: 0.9,
    },
    {
      url: `${baseUrl}/export/taiwan`,
      lastModified: new Date("2026-08-22"),
      changeFrequency: "monthly",
      priority: 0.9,
    },
        {
      url: `${baseUrl}/export/south-korea`,
      lastModified: new Date("2026-08-26"),
      changeFrequency: "monthly",
      priority: 0.9,
    },
    {
      url: `${baseUrl}/export/thailand`,
      lastModified: new Date("2026-08-26"),
      changeFrequency: "monthly",
      priority: 0.9,
    },
    {
      url: `${baseUrl}/export/vietnam`,
      lastModified: new Date("2026-08-26"),
      changeFrequency: "monthly",
      priority: 0.9,
    },
    {
      url: `${baseUrl}/export/singapore`,
      lastModified: new Date("2026-08-26"),
      changeFrequency: "monthly",
      priority: 0.9,
    },
    {
      url: `${baseUrl}/export/new-zealand`,
      lastModified: new Date("2026-08-27"),
      changeFrequency: "monthly",
      priority: 0.9,
    },
    {
      url: `${baseUrl}/export/russia`,
      lastModified: new Date("2026-08-27"),
      changeFrequency: "monthly",
      priority: 0.9,
    },
    {
      url: `${baseUrl}/export/italy`,
      lastModified: new Date("2026-08-20"),
      changeFrequency: "monthly",
      priority: 0.9,
      alternates: { languages: italyLanguageAlternates },
    },
    {
      url: `${baseUrl}/it/export/italia`,
      lastModified: new Date("2026-09-03"),
      changeFrequency: "monthly",
      priority: 0.9,
      alternates: { languages: italyLanguageAlternates },
    },
    {
      url: `${baseUrl}/export/spain`,
      lastModified: new Date("2026-08-20"),
      changeFrequency: "monthly",
      priority: 0.9,
      alternates: { languages: spainLanguageAlternates },
    },
    {
      url: `${baseUrl}/es/export/espana`,
      lastModified: new Date("2026-08-28"),
      changeFrequency: "monthly",
      priority: 0.9,
      alternates: { languages: spainLanguageAlternates },
    },
    {
      url: `${baseUrl}/it/export/spagna`,
      lastModified: new Date("2026-09-03"),
      changeFrequency: "monthly",
      priority: 0.9,
      alternates: { languages: spainLanguageAlternates },
    },
    {
      url: `${baseUrl}/export/austria`,
      lastModified: new Date("2026-08-20"),
      changeFrequency: "monthly",
      priority: 0.9,
      alternates: { languages: austriaLanguageAlternates },
    },
    {
      url: `${baseUrl}/de/export/oesterreich`,
      lastModified: new Date("2026-08-27"),
      changeFrequency: "monthly",
      priority: 0.9,
      alternates: { languages: austriaLanguageAlternates },
    },
    {
      url: `${baseUrl}/export/finland`,
      lastModified: new Date("2026-08-20"),
      changeFrequency: "monthly",
      priority: 0.9,
    },
    {
      url: `${baseUrl}/export/netherlands`,
      lastModified: new Date("2026-08-21"),
      changeFrequency: "monthly",
      priority: 0.9,
    },
    {
      url: `${baseUrl}/export/belgium`,
      lastModified: new Date("2026-08-28"),
      changeFrequency: "monthly",
      priority: 0.9,
      alternates: { languages: belgiumLanguageAlternates },
    },
    {
      url: `${baseUrl}/fr/export/belgique`,
      lastModified: new Date("2026-08-28"),
      changeFrequency: "monthly",
      priority: 0.9,
      alternates: { languages: belgiumLanguageAlternates },
    },
    {
      url: `${baseUrl}/es/export/belgica`,
      lastModified: new Date("2026-09-03"),
      changeFrequency: "monthly",
      priority: 0.9,
      alternates: { languages: belgiumLanguageAlternates },
    },
    {
      url: `${baseUrl}/it/export/belgio`,
      lastModified: new Date("2026-09-03"),
      changeFrequency: "monthly",
      priority: 0.9,
      alternates: { languages: belgiumLanguageAlternates },
    },
    {
      url: `${baseUrl}/export/poland`,
      lastModified: new Date("2026-08-21"),
      changeFrequency: "monthly",
      priority: 0.9,
    },
    {
      url: `${baseUrl}/export/norway`,
      lastModified: new Date("2026-08-21"),
      changeFrequency: "monthly",
      priority: 0.9,
    },
    {
      url: `${baseUrl}/export/brazil`,
      lastModified: new Date("2026-08-21"),
      changeFrequency: "monthly",
      priority: 0.9,
    },
    {
      url: `${baseUrl}/export/argentina`,
      lastModified: new Date("2026-08-22"),
      changeFrequency: "monthly",
      priority: 0.9,
    },
    {
      url: `${baseUrl}/resources`,
      changeFrequency: "monthly",
      priority: 0.8,
    },
    {
      url: `${baseUrl}/export/usa`,
      changeFrequency: "monthly",
      priority: 0.9,
    },
    {
      url: `${baseUrl}/export/uk`,
      changeFrequency: "monthly",
      priority: 0.9,
    },
    {
      url: `${baseUrl}/export/uae`,
      changeFrequency: "monthly",
      priority: 0.9,
    },
    {
      url: `${baseUrl}/export/germany`,
      changeFrequency: "monthly",
      priority: 0.9,
      alternates: { languages: germanyLanguageAlternates },
    },
    {
      url: `${baseUrl}/de/export/deutschland`,
      lastModified: new Date("2026-08-27"),
      changeFrequency: "monthly",
      priority: 0.9,
      alternates: { languages: germanyLanguageAlternates },
    },
    {
      url: `${baseUrl}/fr/export/allemagne`,
      lastModified: new Date("2026-08-27"),
      changeFrequency: "monthly",
      priority: 0.9,
      alternates: { languages: germanyLanguageAlternates },
    },
    {
      url: `${baseUrl}/es/export/alemania`,
      lastModified: new Date("2026-08-28"),
      changeFrequency: "monthly",
      priority: 0.9,
      alternates: { languages: germanyLanguageAlternates },
    },
    {
      url: `${baseUrl}/it/export/germania`,
      lastModified: new Date("2026-09-03"),
      changeFrequency: "monthly",
      priority: 0.9,
      alternates: { languages: germanyLanguageAlternates },
    },
    {
      url: `${baseUrl}/export/france`,
      changeFrequency: "monthly",
      priority: 0.9,
      alternates: { languages: franceLanguageAlternates },
    },
    {
      url: `${baseUrl}/fr/export/france`,
      lastModified: new Date("2026-08-27"),
      changeFrequency: "monthly",
      priority: 0.9,
      alternates: { languages: franceLanguageAlternates },
    },
    {
      url: `${baseUrl}/es/export/francia`,
      lastModified: new Date("2026-09-03"),
      changeFrequency: "monthly",
      priority: 0.9,
      alternates: { languages: franceLanguageAlternates },
    },
    {
      url: `${baseUrl}/it/export/francia`,
      lastModified: new Date("2026-09-03"),
      changeFrequency: "monthly",
      priority: 0.9,
      alternates: { languages: franceLanguageAlternates },
    },
    {
      url: `${baseUrl}/export/australia`,
      changeFrequency: "monthly",
      priority: 0.9,
    },
    {
      url: `${baseUrl}/export/japan`,
      changeFrequency: "monthly",
      priority: 0.9,
    },
    {
      url: `${baseUrl}/contact`,
      changeFrequency: "monthly",
      priority: 0.8,
    },
    {
      url: `${baseUrl}/privacy-policy`,
      changeFrequency: "yearly",
      priority: 0.4,
    },
    {
      url: `${baseUrl}/cookie-policy`,
      changeFrequency: "yearly",
      priority: 0.4,
    },
    {
      url: `${baseUrl}/products/natural-henna-powder`,
      changeFrequency: "monthly",
      priority: 0.9,
    },
    {
      url: `${baseUrl}/products/natural-indigo-powder`,
      changeFrequency: "monthly",
      priority: 0.9,
    },
    {
      url: `${baseUrl}/products/natural-henna-hair-colors`,
      changeFrequency: "monthly",
      priority: 0.9,
    },
    {
      url: `${baseUrl}/products/henna-based-hair-colors`,
      changeFrequency: "monthly",
      priority: 0.9,
    },
    {
      url: `${baseUrl}/products/ayurvedic-indian-herbs`,
      changeFrequency: "monthly",
      priority: 0.9,
    },
    {
      url: `${baseUrl}/products/indian-spices`,
      changeFrequency: "monthly",
      priority: 0.9,
    },
  ];
}
