import type { Metadata } from "next";
import Image from "next/image";
import Link from "next/link";

import FloatingContactButtons from "@/app/components/FloatingContactButtons";
import GoldenParticles from "@/app/components/GoldenParticles";
import MagneticButtons from "@/app/components/MagneticButtons";
import Navbar from "@/app/components/Navbar";
import PremiumCursor from "@/app/components/PremiumCursor";
import RevealOnScroll from "@/app/components/RevealOnScroll";
import StaggerItem from "@/app/components/StaggerItem";
import { belgiumLanguageAlternates } from "@/app/lib/i18n";
import FooterSection from "@/sections/FooterSection";

const pageUrl = "https://shiveshinternational.com/es/export/belgica";
const heroImage = "https://shiveshinternational.com/images/export/belgium/belgium-export-hero-natural-henna-hair-colors.png";

export const metadata: Metadata = {
  title: "Exportador de productos naturales a Bélgica",
  description: "Henna, índigo, coloración vegetal, plantas ayurvédicas y especias de la India para Bélgica. Suministro mayorista, OEM y Private Label; MOQ de 200 kg por artículo.",
  keywords: [
    "exportador de productos naturales a Bélgica", "fabricante de henna para Bélgica", "proveedor de henna natural en Bélgica", "henna al por mayor Bélgica", "exportador de henna natural", "proveedor de índigo natural", "exportador de índigo natural", "proveedor de coloración vegetal", "coloración capilar botánica", "proveedor para salones profesionales", "proveedor de cosmética natural", "importadores en Bélgica", "distribuidores en Bélgica", "mayoristas en Bélgica", "minoristas especializados", "proveedor de plantas ayurvédicas", "exportador de plantas ayurvédicas", "proveedor de especias indias", "exportador de especias indias", "marca propia Bélgica", "marca privada Bélgica", "Private Label Bélgica", "OEM Bélgica", "suministro a granel Bélgica", "aprovisionamiento B2B Bélgica", "proveedor indio para compradores belgas", "envasado de productos naturales Bélgica", "proveedor para marcas de cuidado capilar Bélgica", "exportación India Bélgica", "productos botánicos para Bruselas", "suministro mayorista Amberes", "Shivesh International Bélgica",
  ],
  alternates: { canonical: pageUrl, languages: belgiumLanguageAlternates },
  openGraph: { title: "Suministro de productos naturales de la India a Bélgica", description: "Suministro para Bélgica de henna, índigo, coloración capilar botánica, plantas ayurvédicas y especias a granel, al por mayor, OEM y Private Label.", url: pageUrl, type: "website", locale: "es_ES", siteName: "Shivesh International", images: [{ url: "/images/export/belgium/belgium-export-hero-natural-henna-hair-colors.png", width: 1944, height: 809, alt: "Profesionales belgas de salones y coloración capilar revisando coloraciones naturales con henna suministradas desde la India" }] },
  twitter: { card: "summary_large_image", title: "Suministro de productos naturales para Bélgica", description: "Productos botánicos de la India para importadores, mayoristas, salones y marcas privadas en Bélgica.", images: ["/images/export/belgium/belgium-export-hero-natural-henna-hair-colors.png"] },
  robots: { index: true, follow: true },
};

const products = [
  { title: "Henna natural en polvo", text: "Henna finamente procesada para importadores belgas, marcas de cosmética natural, minoristas y canales de salones profesionales.", href: "/products/natural-henna-powder" },
  { title: "Índigo natural en polvo", text: "Índigo botánico para programas de coloración capilar, revisado en formatos a granel, profesionales y con la marca del comprador.", href: "/products/natural-indigo-powder" },
  { title: "Coloraciones capilares naturales con henna", text: "Una gama de coloración vegetal para distribuidores, marcas de cuidado capilar y proveedores de salones que atienden el mercado multilingüe belga.", href: "/products/natural-henna-hair-colors" },
  { title: "Coloraciones capilares a base de henna", text: "Productos de coloración con marca del comprador, considerados según la fórmula, el uso previsto, el envasado y la viabilidad comercial.", href: "/products/henna-based-hair-colors" },
  { title: "Plantas ayurvédicas de la India", text: "Plantas y polvos botánicos seleccionados para programas belgas de aprovisionamiento en bienestar, comercio especializado y cuidado personal.", href: "/products/ayurvedic-indian-herbs" },
  { title: "Especias de la India", text: "Especias enteras y molidas seleccionadas para importadores, mayoristas, minoristas y compradores del sector alimentario en Bélgica.", href: "/products/indian-spices" },
];
const buyers = [
  { title: "Importadores y distribuidores", text: "Coordinamos especificaciones, cantidades comerciales y documentación disponible para importadores y distribuidores que atienden Bruselas, Amberes, Gante y otros mercados belgas." },
  { title: "Marcas minoristas naturales y ecológicas", text: "Revisamos henna, índigo, plantas, productos botánicos para el cabello y especias para gamas belgas de productos naturales, ecológicos y de comercio especializado." },
  { title: "Empresas de cosmética y cuidado personal", text: "Apoyamos consultas de aprovisionamiento de polvos botánicos, coloración vegetal y conceptos cosméticos o de cuidado personal desarrollados por el comprador, sujetos a revisión del producto y sus especificaciones." },
  { title: "Proveedores de salones profesionales", text: "Estudiamos henna natural, índigo y coloración capilar botánica para el suministro a salones y los canales de distribución profesional en Bélgica." },
  { title: "Empresas herbales y de bienestar", text: "Revisamos polvos ayurvédicos, ingredientes herbales y plantas seleccionadas para empresas belgas de bienestar, productos herbales y especialidades." },
  { title: "Compradores OEM y de marca privada", text: "Coordinamos bolsas, cajas, diseños, etiquetas y presentaciones Private Label con la marca del comprador para pedidos comercialmente viables." },
  { title: "Importadores de alimentos y especias", text: "Estudiamos especias indias enteras, molidas y mezcladas seleccionadas para empresas alimentarias, importadores y distribuidores especializados en Bélgica." },
  { title: "Mayoristas y minoristas especializados", text: "Desarrollamos surtidos específicos de productos naturales para canales belgas mayoristas, de comercio electrónico, minoristas especializados y de suministro profesional." },
];
const steps = [
  ["01", "Selección de productos", "Confirme la familia de productos, el canal previsto, el grado, la cantidad y el destino en Bélgica."],
  ["02", "Especificaciones y muestras", "Revise las especificaciones disponibles y consulte las muestras cuando resulte comercialmente viable."],
  ["03", "Oferta y condiciones", "Confirme el alcance, los precios, las condiciones de pago, el formato de envase y los términos de envío aplicables."],
  ["04", "Envasado y marca privada", "Revise los formatos minoristas o a granel, el diseño del comprador, las etiquetas y la viabilidad de impresión."],
  ["05", "Producción y controles de calidad", "Procesamos, envasamos y revisamos los productos confirmados según los requisitos acordados para el pedido."],
  ["06", "Documentos y expedición", "Coordinamos la documentación de exportación disponible, la planificación del envío, la expedición y el intercambio documental con el comprador o su transitario designado."],
];
const documents = [
  { title: "Factura comercial", text: "La información de la factura comercial puede prepararse según el comprador, los productos, las cantidades, los valores y las condiciones de envío confirmados." },
  { title: "Lista de empaque", text: "Para pedidos confirmados pueden coordinarse el número de bultos, los pesos neto y bruto, los datos de las cajas y las referencias de envío acordadas." },
  { title: "Certificado de origen", text: "La coordinación del certificado de origen puede estudiarse cuando sea aplicable al producto y al envío confirmados." },
  { title: "Especificaciones y COA", text: "Las especificaciones, el COA cuando esté disponible, las referencias de lote y la información de calidad disponible dependen del producto seleccionado." },
  { title: "Información de envasado", text: "La información de bolsas, cajas, envases a granel, etiquetas y códigos de barras puede ajustarse al programa de envasado aprobado por el comprador." },
  { title: "Documentos de transporte", text: "La documentación de envío puede coordinarse con el transitario designado por el comprador y el plan de expedición acordado." },
  { title: "Información de producto y lote", text: "Cuando esté disponible, la información del producto, lote, técnica y de referencia de calidad puede revisarse según el artículo confirmado." },
  { title: "Responsabilidad de revisión del importador", text: "El importador o comprador belga es responsable de los requisitos aplicables de importación, registro, etiquetado, alegaciones, aduanas y acceso al mercado." },
];
const locations = [
  { title: "Bruselas", text: "Importadores, empresas cosméticas, marcas de comercio electrónico y distribuidores nacionales pueden estudiar el aprovisionamiento multicategoría y programas con la marca del comprador." },
  { title: "Amberes", text: "Importadores vinculados al puerto, mayoristas y compradores orientados a la logística pueden revisar el suministro a granel, el embalaje de exportación y las necesidades de distribución posterior." },
  { title: "Gante", text: "Minoristas de productos naturales, empresas de bienestar, proveedores de salones y compradores alimentarios pueden evaluar gamas específicas de plantas, cuidado capilar y especias." },
  { title: "Lieja", text: "Distribuidores belgas francófonos y minoristas especializados pueden estudiar productos naturales para canales profesionales, minoristas y de comercio electrónico." },
  { title: "Charleroi", text: "Mayoristas regionales, empresas de cuidado personal y proveedores profesionales pueden revisar productos, envases y estructuras de pedido comercialmente adecuados." },
  { title: "Namur", text: "Minoristas especializados, empresas herbales y marcas de bienestar pueden evaluar plantas, polvos botánicos y formatos con la marca del comprador." },
  { title: "Lovaina", text: "Empresas orientadas a la innovación, negocios cosméticos y compradores especializados pueden estudiar especificaciones y conceptos de marca privada cuidadosamente planteados." },
  { title: "Brujas", text: "Empresas minoristas, negocios vinculados a la hostelería y distribuidores regionales pueden revisar programas pertinentes de suministro de productos naturales y especias indias." },
];
const faqs = [
  { question: "¿Qué productos pueden adquirir los compradores belgas?", answer: "La gama comprende henna natural en polvo, índigo natural en polvo, coloraciones capilares naturales con henna, coloraciones a base de henna, plantas ayurvédicas de la India y especias indias seleccionadas. La idoneidad y la disponibilidad se revisan en cada consulta." },
  { question: "¿Cuál es el pedido mínimo para Bélgica?", answer: "El MOQ es de 200 kg por artículo. Las cantidades finales y las configuraciones de envasado dependen del producto, el formato y el alcance comercial confirmados." },
  { question: "¿Ofrecen suministro a granel y al por mayor?", answer: "Sí. Los productos viables pueden prepararse en envases a granel acordados de 20 kg o 25 kg, formatos profesionales o presentaciones minoristas seleccionadas, según el producto y la cantidad." },
  { question: "¿Pueden las marcas belgas solicitar suministro Private Label u OEM?", answer: "Pueden revisarse programas OEM y Private Label seleccionados para pedidos comercialmente viables. Los detalles del producto, envase, diseño, impresión y producción se confirman antes de tramitar el pedido." },
  { question: "¿Qué formatos de envasado minorista pueden considerarse?", answer: "Según el producto y la cantidad, las opciones pueden incluir envases de 100 g, 200 g, 500 g y 1 kg, bolsas metalizadas plateadas o doradas, formatos kraft, cajas y presentaciones con la marca del comprador." },
  { question: "¿Se pueden estudiar muestras antes de un pedido comercial?", answer: "Las muestras pueden estudiarse cuando sean viables, una vez definidos el producto, las especificaciones, el uso previsto y la cantidad comercial requeridos." },
  { question: "¿Qué documentos de exportación están disponibles para pedidos a Bélgica?", answer: "La documentación comercial, de producto y de envío disponible puede revisarse según el producto seleccionado, los requisitos del pedido y la operación acordada. Ningún documento o aprobación se da por supuesto sin confirmación." },
  { question: "¿Quién es responsable de los requisitos de importación belgas y de la UE?", answer: "El importador o comprador belga es responsable de la clasificación, los permisos de importación, el despacho de aduanas, el etiquetado, las alegaciones, el registro y todos los requisitos aplicables en Bélgica y la UE. Coordinamos la información de exportación y envío conforme a las condiciones comerciales confirmadas, sin garantizar el despacho ni los plazos de entrega." },
];
const structuredData = { "@context": "https://schema.org", "@graph": [
  { "@type": "WebPage", "@id": `${pageUrl}#webpage`, url: pageUrl, name: "Exportador de productos naturales de la India a Bélgica", description: "Suministro a granel, al por mayor, OEM y de marca privada de productos botánicos de la India para compradores profesionales en Bélgica.", isPartOf: { "@id": "https://shiveshinternational.com/#website" }, about: { "@id": "https://shiveshinternational.com/#organization" }, breadcrumb: { "@id": `${pageUrl}#breadcrumb` }, primaryImageOfPage: { "@type": "ImageObject", url: heroImage }, inLanguage: "es" },
  { "@type": "BreadcrumbList", "@id": `${pageUrl}#breadcrumb`, itemListElement: [{ "@type": "ListItem", position: 1, name: "Inicio", item: "https://shiveshinternational.com/" }, { "@type": "ListItem", position: 2, name: "Exportación", item: "https://shiveshinternational.com/export" }, { "@type": "ListItem", position: 3, name: "Exportación a Bélgica", item: pageUrl }] },
] };
const faqStructuredData = { "@context": "https://schema.org", "@type": "FAQPage", "@id": `${pageUrl}#faq`, mainEntity: faqs.map((faq) => ({ "@type": "Question", name: faq.question, acceptedAnswer: { "@type": "Answer", text: faq.answer } })) };

export default function BelgiumExportPageSpanish() {
  return <main className="min-h-screen overflow-x-hidden bg-[#F5F0E6] text-[#173B2A]">
    <script type="application/ld+json" dangerouslySetInnerHTML={{ __html: JSON.stringify(structuredData).replace(/</g, "\\u003c") }} />
    <script type="application/ld+json" dangerouslySetInnerHTML={{ __html: JSON.stringify(faqStructuredData).replace(/</g, "\\u003c") }} />
    <Navbar />
    <section className="relative isolate overflow-hidden bg-[#071B14]">
      <Image src="/images/export/belgium/belgium-export-hero-natural-henna-hair-colors.png" alt="Profesionales belgas de salones y coloración capilar revisando coloraciones naturales con henna suministradas desde la India" fill priority sizes="100vw" className="object-cover object-[68%_center] sm:object-[64%_center] lg:object-center" />
      <div className="absolute inset-0 bg-gradient-to-r from-[#061711]/80 via-[#102F23]/38 to-transparent" /><GoldenParticles />
      <div className="relative z-10 flex min-h-[760px] items-center px-6 pb-24 pt-28 sm:px-8 lg:px-12"><div className="w-full max-w-[820px]">
        <p className="text-[10px] font-bold uppercase tracking-[0.34em] text-[#E4C878] sm:text-xs">Suministro B2B de la India a Bélgica</p>
        <h1 className="mt-6 font-[family-name:var(--font-playfair)] text-[clamp(2.4rem,5vw,5.2rem)] font-medium leading-[1.03] tracking-[-0.04em] text-[#F5F0E6]">Exportador de productos naturales<span className="mt-2 block text-[#E4C878]">de la India a Bélgica</span></h1>
        <p className="mt-7 max-w-[720px] text-[16px] font-light leading-8 text-white/78 sm:text-[18px]">Suministro comercial de henna natural, índigo, coloración capilar botánica, plantas ayurvédicas y especias de la India para importadores, mayoristas, salones y marcas en Bélgica, mediante programas a granel, al por mayor, OEM y Private Label.</p>
        <div className="mt-9 flex flex-wrap gap-4"><a href="#productos" className="border border-[#C9A962] bg-[#C9A962] px-7 py-4 text-[10px] font-bold uppercase tracking-[0.2em] text-[#102F23]">Ver productos ↓</a><Link href="/contact" className="border border-white/30 bg-black/20 px-7 py-4 text-[10px] font-bold uppercase tracking-[0.2em] text-white">Solicitar presupuesto para Bélgica</Link></div>
        <div className="mt-10 grid max-w-[760px] gap-3 sm:grid-cols-2 lg:grid-cols-4">{[["200 kg", "MOQ por artículo"], ["Seis", "Familias de productos"], ["OEM", "Private Label"], ["Bélgica", "Compradores profesionales"]].map(([value,label]) => <div key={label} className="border border-white/15 bg-black/25 px-4 py-4"><p className="font-[family-name:var(--font-playfair)] text-xl text-[#E4C878]">{value}</p><p className="mt-2 text-[9px] font-bold uppercase tracking-[0.16em] text-white/55">{label}</p></div>)}</div>
      </div></div>
    </section>

    <section id="productos" className="px-6 py-24 sm:px-8 lg:px-12 lg:py-32"><RevealOnScroll><div className="mx-auto max-w-[1500px]">
      <div className="mx-auto max-w-[900px] text-center"><p className="text-[10px] font-bold uppercase tracking-[0.38em] text-[#9F7F36]">Seis familias comerciales de productos</p><h2 className="mt-6 font-[family-name:var(--font-playfair)] text-[clamp(2.25rem,4.6vw,4.8rem)] font-semibold leading-[1.05]">Productos naturales de la India<span className="block text-[#A97B22]">para las carteras de compradores belgas</span></h2><p className="mx-auto mt-7 max-w-[820px] leading-8 text-[#4C5F54]">Una gama específica para los sectores de belleza natural, cuidado capilar profesional, productos herbales, bienestar, comercio especializado y alimentación pertinente en Bélgica.</p></div>
      <div className="mt-14 grid gap-5 sm:grid-cols-2 lg:grid-cols-3">{products.map((product,index) => <StaggerItem key={product.title} delay={(index % 3) * 90}><article className="flex h-full min-h-[290px] flex-col border border-[#173B2A]/12 bg-[#FBF8F1] p-7 sm:p-8"><span className="text-sm font-bold text-[#C9A962]">0{index + 1}</span><h3 className="mt-5 font-[family-name:var(--font-playfair)] text-[27px] font-semibold">{product.title}</h3><p className="mt-5 flex-1 text-[14px] leading-7 text-[#4C5F54]">{product.text}</p><Link href={product.href} className="mt-7 text-[10px] font-bold uppercase tracking-[0.2em] text-[#A97B22]">Ver producto →</Link></article></StaggerItem>)}</div>
    </div></RevealOnScroll></section>

    <section className="px-6 py-24 sm:px-8 lg:px-12 lg:py-32"><RevealOnScroll><div className="mx-auto max-w-[1500px]">
      <div className="text-center"><p className="text-[10px] font-bold uppercase tracking-[0.4em] text-[#9F7F36]">Perfiles de compradores belgas</p><h2 className="mt-6 font-[family-name:var(--font-playfair)] text-[clamp(2.35rem,4.45vw,4.7rem)] font-semibold leading-[1.05]">Planificación del suministro para<span className="block text-[#A97B22]">canales de importación, venta y distribución</span></h2><p className="mx-auto mt-7 max-w-[860px] leading-8 text-[#4C5F54]">Los compradores de productos naturales en Bélgica pueden revisar el suministro según el producto, canal, cantidad y uso previsto. Las referencias a ciudades describen únicamente contextos comerciales y no implican instalaciones, existencias ni representación local.</p></div>
      <div className="mt-14 grid auto-rows-fr gap-5 md:grid-cols-2 lg:grid-cols-4">{buyers.map((buyer) => <article key={buyer.title} className="h-full min-h-[280px] border border-[#173B2A]/12 bg-[#FBF8F1] p-7 sm:p-8"><span className="block h-px w-12 bg-[#C9A962]" /><h3 className="mt-6 font-[family-name:var(--font-playfair)] text-[24px] font-semibold leading-tight text-[#173B2A]">{buyer.title}</h3><p className="mt-5 text-[14px] font-light leading-7 text-[#4C5F54]">{buyer.text}</p></article>)}</div>
    </div></RevealOnScroll></section>

    <section className="px-6 py-24 sm:px-8 lg:px-12 lg:py-32"><RevealOnScroll><div className="mx-auto grid max-w-[1500px] items-center gap-14 lg:grid-cols-2 lg:gap-20">
      <figure className="relative aspect-[4/3] overflow-hidden border border-[#C9A962]/35 bg-[#102F23]"><Image src="/images/export/belgium/belgium-packaging-private-label.png" alt="Desarrollo de envases Private Label para henna, índigo, plantas y coloración capilar natural destinada a Bélgica" fill sizes="(min-width:1024px) 50vw, 100vw" className="object-cover object-center" /></figure>
      <div><p className="text-[10px] font-bold uppercase tracking-[0.38em] text-[#9F7F36]">Envasado y desarrollo de la marca del comprador</p><h2 className="mt-6 font-[family-name:var(--font-playfair)] text-[clamp(2.15rem,3.8vw,4rem)] font-semibold leading-[1.07]">Formatos para canales belgas<span className="block text-[#A97B22]">minoristas, profesionales y a granel</span></h2><p className="mt-7 leading-8 text-[#4C5F54]">Según el producto y la cantidad, los envases minoristas pueden incluir formatos de 100 g, 200 g, 500 g y 1 kg; las opciones a granel pueden incluir envases de 20 kg y 25 kg con envasado al vacío de doble capa cuando proceda.</p><p className="mt-5 leading-8 text-[#4C5F54]">Las bolsas metalizadas plateadas o doradas, los formatos kraft, las cajas, los diseños de marca, la coordinación de etiquetas y la presentación Private Label pueden revisarse según la disponibilidad de materiales y la viabilidad de impresión, producción y comercial. El comprador belga es responsable del etiquetado y los requisitos de mercado aplicables.</p><Link href="/contact" className="mt-8 inline-flex border border-[#C9A962] bg-[#C9A962] px-7 py-4 text-[10px] font-bold uppercase tracking-[0.2em] text-[#102F23]">Consultar sobre Private Label →</Link></div>
    </div></RevealOnScroll></section>

    <section className="bg-[#09271D] px-6 py-24 text-[#F5F0E6] sm:px-8 lg:px-12 lg:py-32"><RevealOnScroll><div className="mx-auto max-w-[1500px]">
      <div className="grid items-center gap-12 lg:grid-cols-[0.9fr_1.1fr]"><div><p className="text-[10px] font-bold uppercase tracking-[0.38em] text-[#E4C878]">Coordinación de la India a Bélgica</p><h2 className="mt-6 font-[family-name:var(--font-playfair)] text-[clamp(2.25rem,4.3vw,4.5rem)] font-semibold leading-[1.05]">Una ruta estructurada desde<span className="block text-[#E4C878]">la consulta hasta la expedición</span></h2><p className="mt-7 leading-8 text-white/65">La planificación del envío puede coordinarse para destinos del comprador como Amberes, Bruselas y Gante, sujeta a las condiciones confirmadas, la disponibilidad del transportista y las instrucciones del comprador o de su transitario designado.</p></div><figure className="relative aspect-[4/3] overflow-hidden border border-[#C9A962]/30"><Image src="/images/export/belgium/belgium-export-freight-coordination.png" alt="Coordinación de exportación y transporte de productos naturales a granel desde la India hasta Bélgica" fill sizes="(min-width:1024px) 55vw, 100vw" className="object-cover object-center" /></figure></div>
      <aside className="mt-12 border border-[#C9A962]/40 bg-[#F5F0E6] p-7 text-[#173B2A] sm:p-9"><h3 className="font-[family-name:var(--font-playfair)] text-2xl font-semibold text-[#A97B22]">Documentación y responsabilidad del importador</h3><p className="mt-4 text-[14px] leading-7 text-[#4C5F54]">La documentación disponible puede revisarse según el producto y los requisitos del pedido. No se garantizan las tarifas de transporte, los horarios, el tránsito, el despacho de aduanas, la inspección, el registro, la aceptación normativa ni las fechas de entrega. El importador belga sigue siendo responsable de todas las obligaciones de importación y comercialización aplicables.</p></aside>
    </div></RevealOnScroll></section>

    <section className="px-6 py-24 sm:px-8 lg:px-12 lg:py-32"><RevealOnScroll><div className="mx-auto max-w-[1500px]">
      <div className="mx-auto max-w-[920px] text-center"><p className="text-[10px] font-bold uppercase tracking-[0.38em] text-[#9F7F36]">Información para la revisión del comprador</p><h2 className="mt-6 font-[family-name:var(--font-playfair)] text-[clamp(2.2rem,4.4vw,4.6rem)] font-semibold leading-[1.06]">Documentación de exportación<span className="block text-[#A97B22]">para compradores en Bélgica</span></h2><p className="mx-auto mt-7 max-w-[850px] leading-8 text-[#4C5F54]">Los documentos dependen del producto seleccionado, la estructura del pedido y su disponibilidad. La información comercial, de producto, envasado y envío disponible puede coordinarse para la revisión del comprador y el destino, sin implicar el cumplimiento automático de la normativa belga o de la Unión Europea.</p></div>
      <div className="mt-14 grid gap-5 md:grid-cols-2 lg:grid-cols-4">{documents.map((document, index) => <StaggerItem key={document.title} delay={(index % 4) * 80}><article className="h-full min-h-[260px] border border-[#173B2A]/12 bg-[#FBF8F1] p-7 sm:p-8"><div className="flex items-center justify-between"><span className="h-px w-12 bg-[#C9A962]" /><span className="font-[family-name:var(--font-playfair)] text-xl text-[#C9A962]/70">{String(index + 1).padStart(2, "0")}</span></div><h3 className="mt-7 font-[family-name:var(--font-playfair)] text-[24px] font-semibold leading-tight">{document.title}</h3><p className="mt-5 text-[14px] font-light leading-7 text-[#4C5F54]">{document.text}</p></article></StaggerItem>)}</div>
    </div></RevealOnScroll></section>

    <section className="bg-[#EDE5D7] px-6 py-24 sm:px-8 lg:px-12 lg:py-32"><RevealOnScroll><div className="mx-auto max-w-[1500px]">
      <div className="text-center"><p className="text-[10px] font-bold uppercase tracking-[0.4em] text-[#9F7F36]">Seis etapas comerciales</p><h2 className="mt-6 font-[family-name:var(--font-playfair)] text-[clamp(2.3rem,4.45vw,4.7rem)] font-semibold leading-[1.05]">Desde la necesidad del comprador belga<span className="block text-[#A97B22]">hasta la coordinación de la exportación</span></h2></div>
      <div className="mt-14 grid auto-rows-fr gap-5 md:grid-cols-2 lg:grid-cols-3">{steps.map(([number, title, text]) => <article key={number} className="h-full min-h-[220px] border border-[#173B2A]/12 bg-[#FBF8F1] p-7 sm:p-8"><div className="flex items-center justify-between"><span className="h-px w-12 bg-[#C9A962]" /><span className="font-[family-name:var(--font-playfair)] text-xl text-[#C9A962]/70">{number}</span></div><h3 className="mt-6 font-[family-name:var(--font-playfair)] text-[24px] font-semibold leading-tight">{title}</h3><p className="mt-5 text-[14px] font-light leading-7 text-[#4C5F54]">{text}</p></article>)}</div>
    </div></RevealOnScroll></section>

    <section className="px-6 py-24 sm:px-8 lg:px-12 lg:py-32"><RevealOnScroll><div className="mx-auto max-w-[1280px]">
      <p className="text-[10px] font-bold uppercase tracking-[0.4em] text-[#9F7F36]">Principales ubicaciones comerciales belgas</p><h2 className="mt-6 font-[family-name:var(--font-playfair)] text-[clamp(2.3rem,4.4vw,4.6rem)] font-semibold leading-[1.05]">Contexto de compradores y distribución<span className="block text-[#A97B22]">en toda Bélgica</span></h2><p className="mt-7 max-w-[900px] text-[15px] leading-8 text-[#4C5F54]">Estas ubicaciones identifican posibles contextos comerciales y de distribución; no representan instalaciones, existencias, empleados, agentes ni relaciones garantizadas en Bélgica.</p>
      <div className="mt-12 grid auto-rows-fr gap-5 md:grid-cols-2 lg:grid-cols-4">{locations.map((location) => <article key={location.title} className="h-full min-h-[245px] border border-[#173B2A]/12 bg-[#FBF8F1] p-7 sm:p-8"><span className="block h-px w-12 bg-[#C9A962]" /><h3 className="mt-6 font-[family-name:var(--font-playfair)] text-[26px] font-semibold">{location.title}</h3><p className="mt-5 text-[14px] font-light leading-7 text-[#4C5F54]">{location.text}</p></article>)}</div>
    </div></RevealOnScroll></section>

    <section className="px-6 py-24 sm:px-8 lg:px-12 lg:py-32"><RevealOnScroll><div className="mx-auto max-w-[1120px]"><div className="text-center"><p className="text-[10px] font-bold uppercase tracking-[0.38em] text-[#9F7F36]">Consultas sobre aprovisionamiento para Bélgica</p><h2 className="mt-6 font-[family-name:var(--font-playfair)] text-[clamp(2.05rem,4vw,4.2rem)] font-semibold">Preguntas frecuentes</h2></div><div className="mt-12 divide-y divide-[#173B2A]/15 border-y border-[#173B2A]/15">{faqs.map((faq) => <article key={faq.question} className="grid gap-4 py-7 md:grid-cols-[0.8fr_1.2fr] md:gap-10"><h3 className="font-[family-name:var(--font-playfair)] text-xl font-semibold">{faq.question}</h3><p className="text-[14px] leading-7 text-[#4C5F54]">{faq.answer}</p></article>)}</div></div></RevealOnScroll></section>

    <section className="relative overflow-hidden bg-[#071B14] px-6 py-24 text-center text-[#F5F0E6] sm:px-8 lg:px-12"><GoldenParticles /><RevealOnScroll><div className="relative mx-auto max-w-[980px]"><p className="text-[10px] font-bold uppercase tracking-[0.38em] text-[#E4C878]">Inicie una conversación de aprovisionamiento para Bélgica</p><h2 className="mt-6 font-[family-name:var(--font-playfair)] text-[clamp(2.1rem,4.25vw,4.5rem)] font-semibold leading-[1.06]">Planifique su suministro de productos naturales desde la India</h2><p className="mx-auto mt-7 max-w-[760px] leading-8 text-white/65">Indique el producto, la cantidad, las especificaciones, el envase, las necesidades de marca del comprador y el destino en Bélgica para una revisión comercial específica.</p><Link href="/contact" className="mt-9 inline-flex border border-[#C9A962] bg-[#C9A962] px-8 py-4 text-[10px] font-bold uppercase tracking-[0.22em] text-[#102F23]">Solicitar presupuesto para Bélgica →</Link></div></RevealOnScroll></section>
    <FooterSection locale="es" /><FloatingContactButtons /><MagneticButtons /><PremiumCursor />
  </main>;
}
