import type { Metadata } from "next";
import Image from "next/image";
import Link from "next/link";

import FloatingContactButtons from "@/app/components/FloatingContactButtons";
import GoldenParticles from "@/app/components/GoldenParticles";
import MagneticButtons from "@/app/components/MagneticButtons";
import Navbar from "@/app/components/Navbar";
import PremiumCursor from "@/app/components/PremiumCursor";
import RevealOnScroll from "@/app/components/RevealOnScroll";
import StaggerItem from "@/app/components/StaggerItem";
import { argentinaLanguageAlternates } from "@/app/lib/i18n";
import FooterSection from "@/sections/FooterSection";

const canonicalUrl = "https://shiveshinternational.com/es/export/argentina";
const heroImage = "/images/export/argentina/argentina-natural-products-export-hero.png";
export const metadata: Metadata = {
  title: { absolute: "Exportador de henna e índigo a Argentina | Shivesh International" },
  description: "Henna natural, índigo, coloración capilar botánica, plantas ayurvédicas y especias de la India para Argentina. Suministro a granel y marca privada. MOQ de 200 kg por artículo.",
  keywords: ["exportador de henna a Argentina", "proveedor de índigo natural Argentina", "henna al por mayor Argentina", "coloración capilar botánica Argentina", "plantas ayurvédicas Argentina", "especias indias al por mayor Argentina", "productos naturales marca privada Argentina", "proveedor indio para importadores argentinos", "envasado Private Label Argentina", "exportación India Argentina"],
  alternates: { canonical: canonicalUrl, languages: argentinaLanguageAlternates },
  openGraph: { title: "Exportador de henna e índigo a Argentina", description: "Henna, índigo, coloración capilar botánica, plantas ayurvédicas y especias de la India, con suministro a granel y marca privada para Argentina.", url: canonicalUrl, type: "website", locale: "es_AR", siteName: "Shivesh International", images: [{ url: heroImage, alt: "Henna, índigo y productos herbales suministrados desde la India a Argentina" }] },
  twitter: { card: "summary_large_image", title: "Exportador de henna e índigo a Argentina", description: "Suministro indio a granel y de marca privada para compradores profesionales de Argentina.", images: [heroImage] }, robots: { index: true, follow: true, googleBot: { index: true, follow: true } },
};
const products = [
  ["Henna natural en polvo", "Para formuladores cosméticos, proveedores de salones, marcas de cuidado capilar natural, mayoristas y compradores de marca privada en Argentina.", "/products/natural-henna-powder"],
  ["Índigo natural en polvo", "Para sistemas de coloración capilar botánica oscura y aplicaciones en dos pasos con henna e índigo en canales profesionales y minoristas.", "/products/natural-indigo-powder"],
  ["Coloraciones naturales con henna", "Opciones de coloración capilar botánica para marcas, distribuidores, salones y canales minoristas de toda Argentina.", "/products/natural-henna-hair-colors"],
  ["Coloraciones a base de henna", "Diversas tonalidades para necesidades mayoristas y de marca privada, sujetas a la confirmación de especificaciones.", "/products/henna-based-hair-colors"],
  ["Plantas ayurvédicas de la India", "Polvos herbales y plantas para aplicaciones de bienestar, cosmética, cuidado personal y venta mayorista, sin alegaciones médicas.", "/products/ayurvedic-indian-herbs"],
  ["Especias de la India", "Especias enteras, molidas y mezcladas para importadores, distribuidores alimentarios y compradores mayoristas argentinos.", "/products/indian-spices"],
];
const buyers = [
  ["Importadores y distribuidores", "Coordinamos la selección, las especificaciones, las cantidades comerciales y el envasado con canales nacionales o regionales."], ["Marcas privadas", "Coordinamos envases viables con la marca del comprador, diseños, formatos y selección de productos para programas aprobados."], ["Compradores de ingredientes cosméticos", "Revisamos henna, índigo y polvos herbales según la formulación prevista, las especificaciones y la clasificación."], ["Empresas de cuidado capilar natural", "Planificamos gamas de coloración botánica para canales minoristas, salones, profesionales y comercio electrónico."], ["Proveedores de salones y profesionales", "Evaluamos formatos profesionales, presentaciones minoristas y necesidades periódicas a granel para distribución en salones."], ["Mayoristas de productos herbales", "Evaluamos polvos herbales y plantas indias para usos adecuados en cosmética, cuidado personal y venta mayorista."], ["Importadores de especias", "Planificamos especias enteras, molidas o mezcladas según especificaciones alimentarias y volúmenes comerciales."], ["Marcas minoristas y de comercio electrónico", "Seleccionamos productos y envases adecuados para tiendas físicas, marketplaces y canales directos en línea."],
];
const documents = [
  ["Factura comercial", "Se prepara para el comprador, los productos, las cantidades, los valores y las condiciones comerciales confirmadas."], ["Lista de empaque", "Puede detallar unidades, pesos netos y brutos, cajas o pallets y referencias del envío."], ["Certificado de origen", "Puede coordinarse según el producto, los requisitos del envío y la disponibilidad."], ["Documento de transporte", "Puede proporcionarse un conocimiento de embarque o una guía aérea según el medio y el envío confirmados."], ["Registros de producto y calidad", "Pueden proporcionarse ficha técnica, certificado de análisis o MSDS/SDS cuando correspondan y estén disponibles."], ["Otros documentos acordados", "Puede evaluarse una declaración Non-GMO u otra documentación de exportación acordada cuando corresponda."],
];
const steps = [
  ["Confirmar producto y especificación", "Indique el artículo, el uso comercial previsto, la especificación y el destino en Argentina."], ["Revisar cotización y condiciones", "Acordamos la cantidad comercial, el MOQ de 200 kg por artículo y las condiciones aplicables."], ["Confirmar el envasado", "Se aprueban formatos viables a granel o de marca privada, diseños y detalles de etiqueta antes de producir."], ["Producción y controles de calidad", "Se procede conforme a las especificaciones, la viabilidad del envase y el pedido acordado."], ["Preparar embalaje y documentos", "Se coordinan el embalaje de exportación y la documentación disponible del producto y el envío."], ["Planificar el despacho", "Coordinamos con el agente de carga o socio logístico designado por el comprador, planificamos el envío desde la India y compartimos los documentos."],
];
const strengths = [
  ["Experiencia consolidada", "La experiencia en productos, abastecimiento y exportación respalda conversaciones prácticas con compradores profesionales."], ["Apoyo de fabricación", "El apoyo de fabricación certificada y una red de materias primas respaldan programas de productos seleccionados."], ["Especificaciones consistentes", "Los pedidos se planifican según especificaciones, envases y requisitos comerciales confirmados."], ["Granel y marca privada", "Pueden evaluarse formatos mayoristas, listos para la venta y con la marca del comprador según su viabilidad."], ["Opciones de envasado", "Diversos formatos minoristas y a granel sirven a canales de distribución, reenvasado y fabricación."], ["Apoyo documental", "Los registros de producto y exportación aplicables y disponibles pueden coordinarse para el envío confirmado."], ["Coordinación del envío", "El despacho puede alinearse con el agente de carga o socio logístico designado por el comprador."], ["Comunicación centrada en el comprador", "Cada consulta se revisa según el producto, la especificación, el envase, el destino y el volumen."],
];
const faqs = [
  { question: "¿Shivesh International exporta henna en polvo a Argentina?", answer: "Shivesh International recibe consultas de Argentina sobre henna natural en polvo y coordina desde la India pedidos confirmados a granel o de marca privada, sujetos a requisitos de producto, comerciales y de envío." },
  { question: "¿Qué productos pueden adquirir los compradores argentinos?", answer: "Pueden evaluarse henna natural en polvo, índigo natural en polvo, coloraciones naturales con henna, coloraciones a base de henna, plantas ayurvédicas de la India y especias indias." },
  { question: "¿Cuál es la cantidad mínima de pedido?", answer: "La cantidad mínima es de 200 kg por producto o artículo seleccionado. La planificación de varios productos puede analizarse por separado, pero no pueden combinarse automáticamente para alcanzar el MOQ de un artículo." },
  { question: "¿Está disponible el envasado de marca privada?", answer: "Puede coordinarse para productos y pedidos adecuados, incluidos diseños con la marca del comprador y formatos listos para la venta, sujeto a la viabilidad del material, la impresión, el producto y la cantidad." },
  { question: "¿Qué tamaños minoristas y a granel están disponibles?", answer: "Los formatos minoristas o de marca privada pueden incluir 100 g, 200 g, 500 g y 1 kg. Los formatos a granel pueden incluir 20 kg y 25 kg, con envasado al vacío de doble capa cuando corresponda." },
  { question: "¿Se pueden pedir henna e índigo para productos de coloración capilar botánica?", answer: "Sí. Los compradores argentinos pueden evaluar henna e índigo para sistemas de coloración capilar botánica, incluidas aplicaciones en dos pasos, sujeto a la revisión de especificaciones y uso previsto." },
  { question: "¿Qué documentos de exportación pueden proporcionarse?", answer: "Pueden incluir factura comercial, lista de empaque, certificado de origen, conocimiento de embarque o guía aérea, ficha técnica y, cuando correspondan y estén disponibles, COA, MSDS/SDS, declaración Non-GMO u otros registros acordados." },
  { question: "¿Cómo se coordinan los envíos desde la India a Argentina?", answer: "Tras confirmar el pedido y el embalaje, el despacho puede coordinarse con el agente de carga o socio logístico designado por el comprador hacia Buenos Aires u otro destino viable indicado. No se garantizan el flete, el despacho aduanero, el tiempo de tránsito ni la entrega." },
  { question: "¿Pueden personalizarse las especificaciones y el envasado?", answer: "Los requisitos de especificación y envasado pueden revisarse para determinar su viabilidad. La configuración final depende del producto, el tamaño del envase, el diseño, los materiales y la cantidad." },
  { question: "¿Qué debe confirmar el importador argentino antes de realizar un pedido?", answer: "El importador o su asesor calificado debe confirmar los requisitos locales de importación, registro, etiquetado, clasificación, aduana y regulación aplicables al producto exacto antes del pedido y el envío." },
];
const structuredData = { "@context": "https://schema.org", "@graph": [
  { "@type": "WebPage", "@id": `${canonicalUrl}#webpage`, url: canonicalUrl, name: "Exportador de henna e índigo a Argentina", description: "Suministro desde la India de henna natural, índigo, coloración capilar botánica, plantas ayurvédicas y especias para Argentina.", isPartOf: { "@id": "https://shiveshinternational.com/#website" }, about: { "@id": "https://shiveshinternational.com/#organization" }, breadcrumb: { "@id": `${canonicalUrl}#breadcrumb` }, primaryImageOfPage: { "@type": "ImageObject", url: `https://shiveshinternational.com${heroImage}` }, inLanguage: "es-AR" },
  { "@type": "BreadcrumbList", "@id": `${canonicalUrl}#breadcrumb`, itemListElement: [{ "@type": "ListItem", position: 1, name: "Inicio", item: "https://shiveshinternational.com/" }, { "@type": "ListItem", position: 2, name: "Exportación", item: "https://shiveshinternational.com/export" }, { "@type": "ListItem", position: 3, name: "Argentina", item: canonicalUrl }] },
] };
const faqStructuredData = { "@context": "https://schema.org", "@type": "FAQPage", "@id": `${canonicalUrl}#faq`, mainEntity: faqs.map((faq) => ({ "@type": "Question", name: faq.question, acceptedAnswer: { "@type": "Answer", text: faq.answer } })) };
const Cards = ({ items, columns = "lg:grid-cols-4" }: { items: string[][]; columns?: string }) => <div className={`mt-14 grid auto-rows-fr gap-5 sm:grid-cols-2 ${columns}`}>{items.map(([title, text]) => <article key={title} className="h-full border border-[#173B2A]/12 bg-[#FBF8F1] p-7 sm:p-8"><span className="block h-px w-12 bg-[#C9A962]" /><h3 className="mt-5 font-[family-name:var(--font-playfair)] text-2xl font-semibold">{title}</h3><p className="mt-4 text-[14px] font-light leading-7 text-[#4C5F54]">{text}</p></article>)}</div>;

export default function ArgentinaExportPageSpanish() { return <main className="min-h-screen overflow-x-hidden bg-[#F5F0E6] text-[#173B2A]">
  <script type="application/ld+json" dangerouslySetInnerHTML={{ __html: JSON.stringify(structuredData).replace(/</g, "\\u003c") }} /><script type="application/ld+json" dangerouslySetInnerHTML={{ __html: JSON.stringify(faqStructuredData).replace(/</g, "\\u003c") }} /><Navbar />
  <section className="relative isolate overflow-hidden bg-[#173B2A]"><Image src={heroImage} alt="Henna, índigo y productos herbales suministrados desde la India a Argentina" fill priority sizes="100vw" className="object-cover object-center" /><div className="absolute inset-0 bg-gradient-to-r from-[#061711]/76 via-[#102F23]/48 to-[#071B14]/15" /><GoldenParticles /><div className="relative z-10 flex items-center px-6 pb-20 pt-32 sm:px-8 sm:pb-24 sm:pt-36 lg:px-12 lg:pb-28 lg:pt-40"><div className="w-full max-w-[940px]"><StaggerItem delay={0}><p className="text-[10px] font-bold uppercase tracking-[0.38em] text-[#E4C878] sm:text-xs">Suministro B2B de la India a Argentina</p></StaggerItem><StaggerItem delay={100}><h1 className="mt-5 font-[family-name:var(--font-playfair)] text-4xl font-medium leading-[1.02] tracking-[-0.04em] text-[#F5F0E6] sm:text-5xl lg:text-6xl xl:text-[66px]">Henna natural, índigo, plantas y especias <span className="block text-[#E4C878]">para compradores de Argentina</span></h1></StaggerItem><StaggerItem delay={200}><p className="mt-5 max-w-[780px] text-[17px] font-light leading-8 text-[#F5F0E6]/82">Shivesh International suministra henna natural, índigo, coloraciones capilares botánicas, plantas ayurvédicas y especias indias a importadores, distribuidores, marcas privadas y compradores mayoristas de toda Argentina.</p></StaggerItem><StaggerItem delay={300}><div className="mt-7 flex flex-wrap gap-4"><Link href="/contact" className="inline-flex items-center gap-4 border border-[#C9A962] bg-[#C9A962] px-7 py-4 text-[10px] font-bold uppercase tracking-[0.2em] text-[#102F23]">Enviar consulta para Argentina <span>→</span></Link><a href="#productos" className="inline-flex items-center gap-4 border border-[#F5F0E6]/30 bg-[#102F23]/40 px-7 py-4 text-[10px] font-bold uppercase tracking-[0.2em] text-[#F5F0E6]">Ver productos <span>↓</span></a></div></StaggerItem><div className="mt-10 grid max-w-[780px] grid-cols-2 gap-3 lg:grid-cols-4">{[["200 kg","MOQ por artículo"],["A granel","Suministro mayorista"],["Private Label","Envases de marca"],["Exportación","Apoyo documental"]].map(([v,l])=><div key={l} className="border border-white/15 bg-black/20 px-4 py-4"><p className="text-xl font-semibold text-[#E4C878]">{v}</p><p className="mt-2 text-[9px] font-bold uppercase tracking-[0.22em] text-[#F5F0E6]/55">{l}</p></div>)}</div></div></div></section>
  <section className="px-6 py-24 sm:px-8 lg:px-12 lg:py-32"><RevealOnScroll><div className="mx-auto max-w-[1120px]"><p className="text-[10px] font-bold uppercase tracking-[0.4em] text-[#9F7F36]">Suministro para el mercado argentino</p><h2 className="mt-6 font-[family-name:var(--font-playfair)] text-[clamp(2.5rem,4.6vw,4.6rem)] font-semibold">Productos naturales <span className="block text-[#A97B22]">para compradores de toda Argentina</span></h2><p className="mt-7 text-[16px] leading-8 text-[#4C5F54]">Importadores, distribuidores, marcas de coloración natural, compradores de materias primas cosméticas, empresas ayurvédicas, proveedores de salones, mayoristas y distribuidores de especias pueden evaluar productos para sus canales comerciales.</p><p className="mt-5 text-[15px] leading-8 text-[#4C5F54]">Compradores de Buenos Aires, Córdoba, Rosario, Mendoza, La Plata y otras regiones pueden planificar el suministro según su canal, especificación, volumen y envase. Estas referencias no implican oficinas, depósitos, stock local, representantes ni distribuidores exclusivos de Shivesh International en Argentina.</p></div></RevealOnScroll></section>
  <section id="productos" className="scroll-mt-24 bg-[#EDE5D7] px-6 py-24 sm:px-8 lg:px-12 lg:py-32"><RevealOnScroll><div className="mx-auto max-w-[1500px]"><div className="text-center"><p className="text-[10px] font-bold uppercase tracking-[0.4em] text-[#9F7F36]">Seis categorías comerciales</p><h2 className="mt-6 font-[family-name:var(--font-playfair)] text-[clamp(2.5rem,4.8vw,4.8rem)] font-semibold">Productos adecuados <span className="block text-[#A97B22]">para Argentina</span></h2></div><div className="mt-14 grid auto-rows-fr gap-5 sm:grid-cols-2 lg:grid-cols-3">{products.map(([title,text,href],i)=><article key={title} className="flex h-full min-h-[290px] flex-col border border-[#173B2A]/12 bg-[#FBF8F1] p-7"><span className="text-4xl text-[#C9A962]">{String(i+1).padStart(2,"0")}</span><h3 className="mt-5 font-[family-name:var(--font-playfair)] text-2xl font-semibold">{title}</h3><p className="mt-4 flex-1 text-sm leading-7 text-[#4C5F54]">{text}</p><Link href={href} className="mt-6 text-[10px] font-bold uppercase tracking-[0.2em] text-[#A97B22]">Ver {title} →</Link></article>)}</div></div></RevealOnScroll></section>
  <section className="px-6 py-24 sm:px-8 lg:px-12 lg:py-32"><RevealOnScroll><div className="mx-auto max-w-[1500px]"><div className="text-center"><p className="text-[10px] font-bold uppercase tracking-[0.4em] text-[#9F7F36]">Perfiles de compradores argentinos</p><h2 className="mt-6 font-[family-name:var(--font-playfair)] text-[clamp(2.5rem,4.7vw,4.7rem)] font-semibold">A quiénes suministramos <span className="block text-[#A97B22]">en Argentina</span></h2></div><Cards items={buyers}/></div></RevealOnScroll></section>
  <section className="bg-[#EDE5D7] px-6 py-24 sm:px-8 lg:px-12 lg:py-32"><RevealOnScroll><div className="mx-auto grid max-w-[1500px] gap-14 lg:grid-cols-[1.08fr_0.92fr]"><div><p className="text-[10px] font-bold uppercase tracking-[0.4em] text-[#9F7F36]">Envasado y marca privada</p><h2 className="mt-6 font-[family-name:var(--font-playfair)] text-[clamp(2.5rem,4.3vw,4.3rem)] font-semibold">Envases a granel, minoristas <span className="block text-[#A97B22]">y de marca privada</span></h2><p className="mt-7 text-[15px] leading-8 text-[#4C5F54]">Los formatos minoristas o de marca privada pueden incluir 100 g, 200 g, 500 g y 1 kg. Los formatos a granel pueden incluir 20 kg y 25 kg, con doble capa y envasado al vacío cuando corresponda. Pueden evaluarse bolsas metalizadas plateadas o doradas, envases de marca y formatos para reenvasado o fabricación.</p><p className="mt-5 text-[15px] leading-8 text-[#4C5F54]">La coordinación de etiquetas y diseños está disponible para programas viables. Las especificaciones se confirman según producto, tamaño, material, impresión, diseño, volumen y requisitos técnicos; no todos los materiales o formatos están disponibles para cada producto.</p><div className="mt-8 border border-[#C9A962] bg-[#173B2A] p-7 text-[#F5F0E6]"><p className="text-[10px] uppercase tracking-[0.3em] text-[#E4C878]">Cantidad mínima de pedido</p><p className="mt-3 text-4xl font-semibold">200 kg por artículo</p><p className="mt-3 text-sm leading-7 text-white/65">El MOQ se aplica a cada producto seleccionado. La planificación de varios productos puede evaluarse por separado. El envase final depende del producto, el tamaño, el diseño y la cantidad.</p></div></div><figure className="relative aspect-[3/2] overflow-hidden border border-[#C9A962]/35"><Image src="/images/export/argentina/argentina-private-label-henna-indigo-buyers.png" alt="Compradores argentinos revisando envases de henna e índigo de marca privada" fill sizes="(min-width:1024px) 45vw, 100vw" className="object-cover object-center"/></figure></div></RevealOnScroll></section>
  <section className="px-6 py-24 sm:px-8 lg:px-12 lg:py-32"><RevealOnScroll><div className="mx-auto max-w-[1500px]"><div className="text-center"><p className="text-[10px] font-bold uppercase tracking-[0.4em] text-[#9F7F36]">Registros de producto y envío</p><h2 className="mt-6 font-[family-name:var(--font-playfair)] text-[clamp(2rem,4.7vw,4.7rem)] font-semibold">Apoyo con la documentación <span className="block text-[#A97B22]">de exportación</span></h2><p className="mx-auto mt-7 max-w-[950px] text-[15px] leading-8 text-[#4C5F54]">Los documentos se preparan según el producto y envío confirmados, las condiciones comerciales, los requisitos del comprador y la disponibilidad. No se presentan documentos gubernamentales, de laboratorio, orgánicos, fitosanitarios, sanitarios, de libre venta o legalizados como automáticamente disponibles.</p></div><Cards items={documents} columns="lg:grid-cols-3"/><aside className="mt-10 border border-[#C9A962]/40 bg-[#173B2A] p-7 text-sm leading-7 text-white/70">El importador o comprador argentino debe confirmar los requisitos locales aplicables de importación, registro, etiquetado, clasificación, aduana y regulación antes del pedido. Shivesh International no brinda asesoría legal o aduanera argentina ni garantiza la aprobación de importación o el despacho aduanero.</aside></div></RevealOnScroll></section>
  <section className="bg-[#09271D] px-6 py-24 text-[#F5F0E6] sm:px-8 lg:px-12 lg:py-32"><RevealOnScroll><div className="mx-auto grid max-w-[1500px] gap-14 lg:grid-cols-[1.08fr_0.92fr]"><div><p className="text-[10px] font-bold uppercase tracking-[0.4em] text-[#E4C878]">Logística de la India a Argentina</p><h2 className="mt-6 font-[family-name:var(--font-playfair)] text-[clamp(2.5rem,4.5vw,4.5rem)] font-semibold">Coordinación de exportación <span className="block text-[#E4C878]">de la India a Argentina</span></h2><p className="mt-7 text-[16px] leading-8 text-white/70">El proceso abarca la confirmación del producto y las especificaciones, la cotización, las condiciones comerciales, el envase, la producción, los controles de calidad, el embalaje, los documentos, la coordinación con el agente de carga designado y el despacho desde la India.</p><p className="mt-5 text-[15px] leading-8 text-white/65">Puede considerarse Buenos Aires u otro puerto o destino viable indicado por el comprador según el pedido y las opciones logísticas vigentes. No se prometen ni garantizan tarifas, itinerarios, rutas, tiempos de tránsito, despacho aduanero, aprobación de importación o fechas de entrega.</p></div><figure className="relative aspect-[3/2] overflow-hidden border border-[#C9A962]/35"><Image src="/images/export/argentina/india-to-argentina-export-coordination.png" alt="Coordinación de exportación de productos naturales enviados desde la India a Argentina" fill sizes="(min-width:1024px) 45vw, 100vw" className="object-cover object-center"/></figure></div></RevealOnScroll></section>
  <section className="bg-[#EDE5D7] px-6 py-24 sm:px-8 lg:px-12 lg:py-32"><RevealOnScroll><div className="mx-auto max-w-[1500px]"><div className="text-center"><p className="text-[10px] font-bold uppercase tracking-[0.4em] text-[#9F7F36]">Seis etapas comerciales</p><h2 className="mt-6 font-[family-name:var(--font-playfair)] text-[clamp(2.5rem,4.7vw,4.7rem)] font-semibold">De la consulta en Argentina <span className="block text-[#A97B22]">al despacho coordinado</span></h2></div><Cards items={steps} columns="lg:grid-cols-3"/></div></RevealOnScroll></section>
  <section className="px-6 py-24 sm:px-8 lg:px-12 lg:py-32"><RevealOnScroll><div className="mx-auto max-w-[1500px]"><div className="text-center"><p className="text-[10px] font-bold uppercase tracking-[0.4em] text-[#9F7F36]">Suministro profesional de exportación</p><h2 className="mt-6 font-[family-name:var(--font-playfair)] text-[clamp(2.5rem,4.7vw,4.7rem)] font-semibold">Por qué los compradores argentinos eligen <span className="block text-[#A97B22]">Shivesh International</span></h2></div><Cards items={strengths}/></div></RevealOnScroll></section>
  <section className="bg-[#EDE5D7] px-6 py-24 sm:px-8 lg:px-12 lg:py-32"><RevealOnScroll><div className="mx-auto max-w-[1120px]"><div className="text-center"><p className="text-[10px] font-bold uppercase tracking-[0.4em] text-[#9F7F36]">Preguntas de compradores argentinos</p><h2 className="mt-6 font-[family-name:var(--font-playfair)] text-[clamp(2.4rem,4.4vw,4.4rem)] font-semibold">Preguntas frecuentes sobre el suministro a Argentina</h2></div><div className="mt-12 divide-y divide-[#173B2A]/15 border-y border-[#173B2A]/15">{faqs.map(f=><article key={f.question} className="grid gap-4 py-7 md:grid-cols-[0.8fr_1.2fr]"><h3 className="text-xl font-semibold">{f.question}</h3><p className="text-sm leading-7 text-[#4C5F54]">{f.answer}</p></article>)}</div></div></RevealOnScroll></section>
  <section className="relative overflow-hidden bg-[#071B14] px-6 py-24 text-center text-[#F5F0E6] sm:px-8 lg:px-12"><GoldenParticles/><RevealOnScroll><div className="relative mx-auto max-w-[1000px]"><p className="text-[10px] font-bold uppercase tracking-[0.4em] text-[#E4C878]">Inicie una conversación de suministro para Argentina</p><h2 className="mt-6 font-[family-name:var(--font-playfair)] text-[clamp(2.5rem,4.8vw,4.8rem)] font-semibold">Planifique su suministro de productos naturales</h2><p className="mx-auto mt-7 max-w-[760px] text-[16px] leading-8 text-[#F5F0E6]/65">Indique el producto, la cantidad, el tamaño del envase, las necesidades de marca, el destino y la información requerida. Nuestro equipo revisará la consulta y responderá con los próximos pasos comercialmente viables.</p><Link href="/contact" className="mt-9 inline-flex items-center gap-4 border border-[#C9A962] bg-[#C9A962] px-8 py-4 text-[10px] font-bold uppercase tracking-[0.22em] text-[#102F23]">Solicitar cotización para Argentina <span>→</span></Link></div></RevealOnScroll></section>
  <nav aria-label="Accesos directos a productos para Argentina" className="flex flex-wrap justify-center gap-6 bg-[#071B14] px-6 pb-10 text-[10px] font-bold uppercase tracking-[0.18em] text-[#E4C878]">{products.map(([label,,href])=><Link key={href} href={href}>{label}</Link>)}</nav>
  <FooterSection locale="es"/><FloatingContactButtons/><MagneticButtons/><PremiumCursor/>
</main>; }
