/* eslint-disable react/no-unescaped-entities */
import type { Metadata } from "next";
import { existsSync } from "node:fs";
import Image from "next/image";
import Link from "next/link";
import FloatingContactButtons from "@/app/components/FloatingContactButtons";
import GoldenParticles from "@/app/components/GoldenParticles";
import MagneticButtons from "@/app/components/MagneticButtons";
import Navbar from "@/app/components/Navbar";
import PremiumCursor from "@/app/components/PremiumCursor";
import RevealOnScroll from "@/app/components/RevealOnScroll";
import StaggerItem from "@/app/components/StaggerItem";
import FooterSection from "@/sections/FooterSection";

const canonicalUrl = "https://shiveshinternational.com/export/china";
const heroImage = "/images/export/china/china-natural-products-export-hero.png";
const keywordSubjects = ["natural henna powder", "henna powder", "bulk henna", "natural indigo powder", "indigo powder", "botanical hair colour", "private label henna", "natural hair colour", "cosmetic ingredients", "Ayurvedic herbs", "Indian herbs", "herbal powder", "Indian spices", "private label botanical products"];
const keywordIntents = ["exporter to China", "supplier China", "manufacturer India for China", "bulk supplier China", "private label China", "supplier for China importers"];
const metadataKeywords = keywordSubjects.flatMap((subject) => keywordIntents.map((intent) => `${subject} ${intent}`)).concat([
  "OEM natural products China", "OEM botanical hair colors China", "buyer-brand packaging China", "natural products retailer supplier China",
]);

export const metadata: Metadata = {
  title: { absolute: "Henna & Indigo Exporter to China | Shivesh International" },
  description: "Source natural henna, indigo, botanical hair colours, Ayurvedic herbs and Indian spices for China. Bulk and private-label supply from India. MOQ 200 kg per item.",
  keywords: metadataKeywords,
  alternates: { canonical: canonicalUrl },
  openGraph: { title: "Henna & Indigo Exporter to China | Shivesh International", description: "Bulk and private-label natural henna, indigo, herbs and spices supplied from India for professional buyers in China.", url: canonicalUrl, type: "website", locale: "en_CN", siteName: "Shivesh International", images: [{ url: heroImage, alt: "Natural henna, indigo, herbs and spices supplied from India to China" }] },
  twitter: { card: "summary_large_image", title: "Henna & Indigo Exporter to China", description: "Indian natural-product supply for China importers, distributors and private-label brands.", images: [heroImage] },
  robots: { index: true, follow: true, googleBot: { index: true, follow: true } },
};

const products = [
  ["Natural Henna Powder", "For cosmetic ingredient buyers, natural hair-care brands, salon suppliers, wholesalers and private-label businesses in China.", "/products/natural-henna-powder"],
  ["Natural Indigo Powder", "For botanical dark hair-colour systems and professional henna-and-indigo product programmes.", "/products/natural-indigo-powder"],
  ["Natural Henna Hair Colors", "Botanical powder hair-colour options for importers, distributors, professional suppliers and retail brands.", "/products/natural-henna-hair-colors"],
  ["Henna-Based Hair Colors", "Multiple powder hair-colour shade options for wholesale and feasible private-label requirements.", "/products/henna-based-hair-colors"],
  ["Ayurvedic Indian Herbs", "Raw herbs and herbal powders for professional natural-product, cosmetic, wellness and wholesale channels without medical claims.", "/products/ayurvedic-indian-herbs"],
  ["Indian Spices", "Whole, ground and blended spices for suitable food importers, distributors and wholesale buyers.", "/products/indian-spices"],
];
const buyers = [
  ["Importers and Distributors", "Coordinate product selection, commercial quantities, specifications and destination-market documentation needs."],
  ["Cosmetic Ingredient Buyers", "Review henna, indigo and herbal powders according to intended use, ingredient requirements and classification."],
  ["Natural Hair-Care Brands", "Plan botanical colour and hair-care products for professional, retail or e-commerce channels."],
  ["Private-Label Companies", "Discuss feasible buyer-brand packaging, artwork, labels and selected natural-product programmes."],
  ["Salon and Professional Suppliers", "Review professional formats and repeat supply for salon and beauty-product distribution."],
  ["Herbal Product Wholesalers", "Evaluate Indian herbs and herbal powders for appropriate natural-product and wholesale applications."],
  ["Spice and Food Ingredient Buyers", "Plan whole, ground or blended spice requirements for suitable commercial food channels."],
  ["Retail and E-commerce Brands", "Select products and pack formats for stores, marketplaces and direct retail channels."],
];
const documents = [
  ["Commercial Invoice", "Prepared around confirmed products, quantities, values and commercial terms."],
  ["Packing List", "May detail pack counts, net and gross weights, cartons or pallets and shipment references."],
  ["Certificate of Origin", "May be coordinated according to product and shipment requirements, subject to issuing availability."],
  ["Transport Documents", "A Bill of Lading or Air Waybill may be provided according to the confirmed shipment mode."],
  ["Product and Quality Records", "A specification sheet, Certificate of Analysis or MSDS/SDS may be provided where applicable and available."],
  ["Other Agreed Documents", "A Non-GMO declaration or other mutually agreed export documents may be discussed where applicable."],
];
const steps = [
  ["Product Selection", "Identify the product, intended use, China destination and approximate commercial quantity."],
  ["Specification Confirmation", "Align the requested specification and available product information."],
  ["Quotation & Terms", "Review the 200 kg per-item MOQ, quantity and applicable commercial terms."],
  ["Packaging Confirmation", "Approve feasible bulk or private-label formats, artwork and label details."],
  ["Production & Quality Checks", "Proceed according to the confirmed specification, packaging and agreed order."],
  ["Documentation & Dispatch", "Prepare available records, coordinate with the nominated forwarder and share dispatch documents."],
];
const strengths = [
  ["Established Experience", "Product and sourcing experience supports practical discussions with professional buyers."],
  ["Manufacturing Support", "Certified manufacturing support and a raw-material sourcing network underpin selected programmes."],
  ["Consistent Specifications", "Orders are planned around agreed product specifications and commercial requirements."],
  ["Bulk & Private Label", "Wholesale and buyer-brand supply can be reviewed according to feasibility."],
  ["Packaging Formats", "Retail-ready and bulk options support different commercial channels."],
  ["Documentation Support", "Applicable and available commercial, product and shipment records can be coordinated."],
  ["Shipment Coordination", "Dispatch planning can be aligned with the buyer's nominated freight forwarder."],
  ["Buyer-Focused Communication", "Each enquiry is reviewed around its product, use, specification, packaging and volume."],
];
const faqs = [
  { question: "Does Shivesh International supply henna powder to China?", answer: "Shivesh International accepts China enquiries for natural henna powder and coordinates confirmed bulk or private-label orders from India subject to product, commercial and destination requirements." },
  { question: "Which natural products can China buyers source?", answer: "China buyers can discuss natural henna powder, indigo powder, natural henna hair colors, henna-based hair colors, Ayurvedic Indian herbs and Indian spices." },
  { question: "What is the minimum order quantity?", answer: "The minimum order quantity is 200 kg per selected product or item. Mixed-product planning may be discussed separately." },
  { question: "Is private-label packaging available for China buyers?", answer: "Private-label packaging may be coordinated for suitable products and orders, subject to material, print, artwork, quantity and technical feasibility." },
  { question: "Which retail and bulk packaging formats are available?", answer: "Retail formats may include 100 g, 200 g, 500 g and 1 kg. Bulk formats may include 20 kg and 25 kg, with double-layer vacuum packaging where applicable." },
  { question: "Can China buyers source both henna and indigo powder?", answer: "Yes. Buyers can discuss natural henna and indigo for botanical hair-colour programmes, subject to separate specifications and the MOQ per item." },
  { question: "What export documents may be provided?", answer: "Documents may include a commercial invoice, packing list, certificate of origin, transport document, specification sheet, and COA, MSDS/SDS, Non-GMO declaration or other agreed records where applicable and available." },
  { question: "How are shipments from India to China coordinated?", answer: "After order confirmation, shipment planning and dispatch documents may be coordinated with the buyer's nominated freight forwarder for a feasible buyer-nominated cargo destination. Routes, schedules, clearance and delivery are not guaranteed." },
  { question: "Can product specifications and packaging be customized?", answer: "Specifications and packaging requirements can be reviewed for feasibility. Final configuration depends on the product, pack size, materials, artwork and order quantity." },
  { question: "What must the China importer confirm before ordering?", answer: "The importer or its qualified adviser must confirm product classification, intended-use requirements, ingredient restrictions, import eligibility, registrations, filings, labelling, language, testing, inspection, customs and other local requirements." },
];
const structuredData = { "@context": "https://schema.org", "@graph": [
  { "@type": "WebPage", "@id": `${canonicalUrl}#webpage`, url: canonicalUrl, name: "Henna & Indigo Exporter to China", description: "China-focused export supply of natural henna, indigo, botanical hair colours, Ayurvedic herbs and Indian spices from India.", isPartOf: { "@id": "https://shiveshinternational.com/#website" }, about: { "@id": "https://shiveshinternational.com/#organization" }, breadcrumb: { "@id": `${canonicalUrl}#breadcrumb` }, primaryImageOfPage: { "@type": "ImageObject", url: heroImage }, inLanguage: "en" },
  { "@type": "BreadcrumbList", "@id": `${canonicalUrl}#breadcrumb`, itemListElement: [{ "@type": "ListItem", position: 1, name: "Home", item: "https://shiveshinternational.com/" }, { "@type": "ListItem", position: 2, name: "Export", item: "https://shiveshinternational.com/export" }, { "@type": "ListItem", position: 3, name: "Asia-Pacific", item: "https://shiveshinternational.com/export/asia-pacific" }, { "@type": "ListItem", position: 4, name: "China", item: canonicalUrl }] },
] };
const faqStructuredData = { "@context": "https://schema.org", "@type": "FAQPage", "@id": `${canonicalUrl}#faq`, mainEntity: faqs.map((faq) => ({ "@type": "Question", name: faq.question, acceptedAnswer: { "@type": "Answer", text: faq.answer } })) };

function OptionalImage({ src, alt, priority = false, sizes = "(min-width: 1024px) 55vw, 100vw", className = "object-contain object-center" }: { src: string; alt: string; priority?: boolean; sizes?: string; className?: string }) { if (!existsSync(`${process.cwd()}/public${src}`)) return null; return <Image src={src} alt={alt} fill priority={priority} sizes={sizes} className={className}/>; }
const Cards = ({ items, columns = "lg:grid-cols-4" }: { items: string[][]; columns?: string }) => <div className={`mt-14 grid auto-rows-fr gap-5 sm:grid-cols-2 ${columns}`}>{items.map(([title,text])=><article key={title} className="h-full border border-[#173B2A]/12 bg-[#FBF8F1] p-7 sm:p-8"><span className="block h-px w-12 bg-[#C9A962]"/><h3 className="mt-5 font-[family-name:var(--font-playfair)] text-2xl font-semibold">{title}</h3><p className="mt-4 text-sm font-light leading-7 text-[#4C5F54]">{text}</p></article>)}</div>;

export default function ChinaExportPage(){return <main className="min-h-screen overflow-x-hidden bg-[#F5F0E6] text-[#173B2A]">
  <script type="application/ld+json" dangerouslySetInnerHTML={{__html:JSON.stringify(structuredData).replace(/</g,"\\u003c")}}/><script type="application/ld+json" dangerouslySetInnerHTML={{__html:JSON.stringify(faqStructuredData).replace(/</g,"\\u003c")}}/><Navbar/>
  <section className="relative isolate overflow-hidden bg-[#071B14]"><OptionalImage src={heroImage} alt="Natural henna, indigo, herbs and spices supplied from India to China" priority sizes="100vw" className="object-contain object-top xl:object-cover xl:object-center"/><div className="absolute inset-0 bg-gradient-to-r from-[#061711]/76 via-[#102F23]/48 to-[#071B14]/15"/><GoldenParticles/><div className="relative z-10 flex items-center px-6 pb-20 pt-32 sm:px-8 sm:pb-24 sm:pt-36 lg:px-12 lg:pb-28 lg:pt-40"><div className="w-full max-w-[950px]"><StaggerItem delay={0}><p className="text-[10px] font-bold uppercase tracking-[0.38em] text-[#E4C878] sm:text-xs">India to China B2B Supply</p></StaggerItem><StaggerItem delay={100}><h1 className="mt-5 font-[family-name:var(--font-playfair)] text-4xl font-medium leading-[1.02] tracking-[-0.04em] text-[#F5F0E6] sm:text-5xl lg:text-6xl xl:text-[66px]">Natural Henna, Indigo, Herbs &amp; Spices <span className="block bg-gradient-to-r from-[#F5F0E6] via-[#E4C878] to-[#C9A962] bg-clip-text text-transparent">Exporter to China</span></h1></StaggerItem><StaggerItem delay={200}><p className="mt-5 max-w-[790px] text-[16px] font-light leading-8 text-white/82">Shivesh International supplies natural henna powder, indigo powder, botanical hair colours, Ayurvedic herbs and Indian spices to importers, distributors, private-label brands and wholesale buyers across China.</p></StaggerItem><StaggerItem delay={300}><div className="mt-7 flex flex-wrap gap-4"><Link href="/contact" className="border border-[#C9A962] bg-[#C9A962] px-7 py-4 text-[10px] font-bold uppercase tracking-[0.2em] text-[#102F23]">Send China Inquiry →</Link><a href="#products" className="border border-white/30 bg-[#102F23]/40 px-7 py-4 text-[10px] font-bold uppercase tracking-[0.2em] text-white">Explore Export Products ↓</a></div></StaggerItem><StaggerItem delay={400}><div className="mt-10 grid max-w-[760px] grid-cols-2 gap-3 lg:grid-cols-4">{[["200 kg","MOQ per item"],["Bulk","B2B supply"],["Private Label","Buyer-brand packs"],["Export","Coordination"]].map(([v,l])=><div key={l} className="border border-white/15 bg-black/20 p-4"><p className="font-[family-name:var(--font-playfair)] text-xl font-semibold text-[#E4C878]">{v}</p><p className="mt-2 text-[9px] uppercase tracking-[0.22em] text-white/55">{l}</p></div>)}</div></StaggerItem></div></div></section>
  <section className="px-6 py-24 sm:px-8 lg:px-12 lg:py-32"><RevealOnScroll><div className="mx-auto max-w-[1200px]"><p className="text-[10px] font-bold uppercase tracking-[0.4em] text-[#9F7F36]">China Market Supply</p><h2 className="mt-6 font-[family-name:var(--font-playfair)] text-[clamp(2.3rem,4.6vw,4.6rem)] font-semibold">Natural Product Supply <span className="block text-[#A97B22]">for Professional Buyers in China</span></h2><p className="mt-7 text-[16px] font-light leading-8 text-[#4C5F54]">Professional buyers can discuss natural hair-colour powders, botanical cosmetic ingredients, herbal powders, private-label natural products, bulk raw materials, Indian herbs and whole or ground Indian spices according to their intended use and sales channel.</p><p className="mt-5 text-[15px] font-light leading-8 text-[#4C5F54]">Importers and distributors in Shanghai, Shenzhen, Guangzhou, Beijing, Ningbo, Qingdao and other buyer-nominated commercial destinations can plan product, packaging and documentation requirements. These references do not imply local offices, warehouses, employees, stock points, distributors, guaranteed demand, acceptance, registration or approval.</p></div></RevealOnScroll></section>
  <section id="products" className="bg-[#EDE5D7] px-6 py-24 sm:px-8 lg:px-12 lg:py-32"><RevealOnScroll><div className="mx-auto max-w-[1500px]"><div className="text-center"><p className="text-[10px] uppercase tracking-[0.4em] text-[#9F7F36]">Six Commercial Categories</p><h2 className="mt-6 font-[family-name:var(--font-playfair)] text-[clamp(2.3rem,4.8vw,4.8rem)] font-semibold">Products Available <span className="block text-[#A97B22]">for China Buyers</span></h2></div><div className="mt-14 grid auto-rows-fr gap-5 sm:grid-cols-2 lg:grid-cols-3">{products.map(([title,text,href],i)=><article key={title} className="flex h-full min-h-[290px] flex-col border border-[#173B2A]/12 bg-[#FBF8F1] p-7"><span className="text-4xl text-[#C9A962]">{String(i+1).padStart(2,"0")}</span><h3 className="mt-5 font-[family-name:var(--font-playfair)] text-2xl font-semibold">{title}</h3><p className="mt-4 flex-1 text-sm leading-7 text-[#4C5F54]">{text}</p><Link href={href} className="mt-6 text-[10px] font-bold uppercase tracking-[0.2em] text-[#A97B22]">Explore {title} →</Link></article>)}</div></div></RevealOnScroll></section>
  <section className="px-6 py-24 sm:px-8 lg:px-12 lg:py-32"><RevealOnScroll><div className="mx-auto max-w-[1500px]"><div className="text-center"><p className="text-[10px] uppercase tracking-[0.4em] text-[#9F7F36]">China Buyer Profiles</p><h2 className="mt-6 font-[family-name:var(--font-playfair)] text-[clamp(2.3rem,4.7vw,4.7rem)] font-semibold">Who We Supply in China</h2><p className="mx-auto mt-7 max-w-[900px] text-[15px] leading-8 text-[#4C5F54]">Final product, specification, packaging and documentation requirements depend on the buyer's intended use, sales channel and applicable destination requirements.</p></div><Cards items={buyers}/></div></RevealOnScroll></section>
<section className="bg-[#EDE5D7] px-6 py-24 sm:px-8 lg:px-12 lg:py-32"><RevealOnScroll><div className="mx-auto max-w-[1500px]"><div className="grid gap-14 lg:grid-cols-[1.05fr_0.95fr] lg:gap-20"><div><p className="text-[10px] uppercase tracking-[0.4em] text-[#9F7F36]">Packaging & Private Label</p><h2 className="mt-6 font-[family-name:var(--font-playfair)] text-[clamp(2.3rem,4.6vw,4.6rem)] font-semibold">Bulk, Retail and <span className="block text-[#A97B22]">Private-Label Packaging</span></h2><p className="mt-7 text-[15px] leading-8 text-[#4C5F54]">Silver and gold metallized pouches, buyer-brand packaging, artwork and label coordination, retail-ready formats and bulk packs for repacking or manufacturing can be reviewed.</p><p className="mt-5 text-[14px] leading-7 text-[#4C5F54]">Packaging is confirmed according to the product, material, artwork, quantity and technical feasibility. The MOQ applies per selected item; mixed-product planning may be discussed separately, and final packing depends on product, pack size, artwork and order quantity.</p></div><div><figure className="relative aspect-[3/2] overflow-hidden border border-[#C9A962]/35 bg-[#FBF8F1] shadow-[0_28px_70px_rgba(20,50,38,0.18)]"><OptionalImage src="/images/export/china/china-private-label-henna-indigo-buyers.png" alt="Chinese researchers evaluating henna, indigo and private-label packaging options"/></figure><div className="mt-5 grid gap-5 sm:grid-cols-2"><article className="border border-[#C9A962]/35 bg-[#FBF8F1] p-7"><h3 className="text-2xl font-semibold">Retail Packaging</h3><p className="mt-5 text-sm leading-7 text-[#4C5F54]">100 g · 200 g · 500 g · 1 kg formats</p></article><article className="border border-[#C9A962]/35 bg-[#FBF8F1] p-7"><h3 className="text-2xl font-semibold">Bulk Packaging</h3><p className="mt-5 text-sm leading-7 text-[#4C5F54]">20 kg and 25 kg, with double-layer vacuum packaging where applicable</p></article><article className="border border-[#C9A962] bg-[#173B2A] p-7 text-white sm:col-span-2"><p className="text-[10px] uppercase tracking-[0.3em] text-[#E4C878]">Minimum Order Quantity</p><p className="mt-4 text-4xl font-semibold">200 kg per item</p></article></div></div></div></div></RevealOnScroll></section>
  <section className="relative bg-[#09271D] px-6 py-24 text-white sm:px-8 lg:px-12 lg:py-32"><RevealOnScroll><div className="mx-auto max-w-[1500px]"><div className="grid items-center gap-14 lg:grid-cols-[0.9fr_1.1fr] lg:gap-20"><div><p className="text-[10px] uppercase tracking-[0.4em] text-[#E4C878]">Shipment and Document Support</p><h2 className="mt-6 font-[family-name:var(--font-playfair)] text-[clamp(2.3rem,4.7vw,4.7rem)] font-semibold">India to China Export Coordination</h2><p className="mt-7 text-[16px] leading-8 text-white/68">Coordination covers product selection, specification confirmation, quotation and terms, packaging or private-label confirmation, production and quality checks, documentation preparation, shipment planning, dispatch and document sharing with the buyer's nominated freight forwarder.</p><p className="mt-5 text-[15px] leading-8 text-white/62">Shanghai, Ningbo, Shenzhen, Guangzhou, Qingdao or another feasible buyer-nominated cargo destination may be considered. Freight rates, schedules, transit times, import approval, registration, clearance, inspection, delivery or regulatory acceptance are not guaranteed.</p></div><figure className="relative aspect-[3/2] overflow-hidden border border-[#C9A962]/35 bg-[#071B14]"><OptionalImage src="/images/export/china/india-to-china-export-coordination.png" alt="India-to-China natural product shipment and documentation coordination"/><div className="absolute inset-0 bg-gradient-to-t from-[#061711]/65 via-transparent to-transparent"/><figcaption className="absolute bottom-5 left-5 border border-white/15 bg-[#071B14]/80 px-4 py-3 text-[9px] uppercase tracking-[0.22em] text-[#E4C878]">India-to-China Export Coordination</figcaption></figure></div><aside className="mt-12 border border-[#C9A962]/35 bg-[#071B14]/60 p-7 text-sm leading-7 text-white/65">The China importer or buyer is responsible for confirming the applicable product classification, intended-use requirements, ingredient restrictions, import eligibility, registrations, filings, labelling, language, testing, inspection, customs and other local regulatory requirements before ordering. Requirements may differ between cosmetics, cosmetic ingredients, herbal products, food ingredients and spices. Shivesh International does not provide legal advice or guarantee China import approval or customs clearance. Production or dispatch should proceed only after the buyer confirms applicable destination requirements.</aside></div></RevealOnScroll></section>
  <section className="px-6 py-24 sm:px-8 lg:px-12 lg:py-32"><RevealOnScroll><div className="mx-auto max-w-[1500px]"><div className="text-center"><p className="text-[10px] uppercase tracking-[0.4em] text-[#9F7F36]">Available Product and Shipment Records</p><h2 className="mt-6 font-[family-name:var(--font-playfair)] text-[clamp(2.1rem,4.7vw,4.7rem)] font-semibold">Export Documentation Support</h2><p className="mx-auto mt-7 max-w-[950px] text-[15px] leading-8 text-[#4C5F54]">Available documents depend on the product, order, shipment terms, buyer requirements and issuing availability. Organic, phytosanitary, health, free-sale, government-laboratory, legalization, attestation, registration or inspection documents are not automatically promised.</p></div><Cards items={documents} columns="lg:grid-cols-3"/></div></RevealOnScroll></section>
  <section className="bg-[#EDE5D7] px-6 py-24 sm:px-8 lg:px-12 lg:py-32"><RevealOnScroll><div className="mx-auto max-w-[1500px]"><div className="text-center"><p className="text-[10px] uppercase tracking-[0.4em] text-[#9F7F36]">Six Commercial Steps</p><h2 className="mt-6 font-[family-name:var(--font-playfair)] text-[clamp(2.3rem,4.7vw,4.7rem)] font-semibold">China Commercial Workflow</h2></div><Cards items={steps} columns="lg:grid-cols-3"/></div></RevealOnScroll></section>
  <section className="px-6 py-24 sm:px-8 lg:px-12 lg:py-32"><RevealOnScroll><div className="mx-auto max-w-[1500px]"><div className="text-center"><p className="text-[10px] uppercase tracking-[0.4em] text-[#9F7F36]">Professional Export Supply</p><h2 className="mt-6 font-[family-name:var(--font-playfair)] text-[clamp(2.3rem,4.7vw,4.7rem)] font-semibold">Why China Buyers Choose <span className="block text-[#A97B22]">Shivesh International</span></h2></div><Cards items={strengths}/></div></RevealOnScroll></section>
  <section className="bg-[#EDE5D7] px-6 py-24 sm:px-8 lg:px-12 lg:py-32"><RevealOnScroll><div className="mx-auto max-w-[1120px]"><div className="text-center"><p className="text-[10px] uppercase tracking-[0.4em] text-[#9F7F36]">China Buyer Questions</p><h2 className="mt-6 font-[family-name:var(--font-playfair)] text-[clamp(2.3rem,4.4vw,4.4rem)] font-semibold">China Export Supply FAQ</h2></div><div className="mt-12 divide-y divide-[#173B2A]/15 border-y border-[#173B2A]/15">{faqs.map(f=><article key={f.question} className="grid gap-4 py-7 md:grid-cols-[0.8fr_1.2fr]"><h3 className="text-xl font-semibold">{f.question}</h3><p className="text-sm leading-7 text-[#4C5F54]">{f.answer}</p></article>)}</div></div></RevealOnScroll></section>
  <section className="relative overflow-hidden bg-[#071B14] px-6 py-24 text-center text-white sm:px-8 lg:px-12 lg:py-28"><GoldenParticles/><RevealOnScroll><div className="relative mx-auto max-w-[1000px]"><p className="text-[10px] uppercase tracking-[0.4em] text-[#E4C878]">China Export Enquiry</p><h2 className="mt-6 font-[family-name:var(--font-playfair)] text-[clamp(2.3rem,4.8vw,4.8rem)] font-semibold">Source Natural Indian Products for China</h2><p className="mx-auto mt-7 max-w-[820px] text-[16px] leading-8 text-white/65">Tell us your required product, specification, intended use, packaging format and order quantity. Our team will review your China inquiry and provide the relevant commercial and export information.</p><Link href="/contact" className="mt-9 inline-flex border border-[#C9A962] bg-[#C9A962] px-8 py-4 text-[10px] font-bold uppercase tracking-[0.2em] text-[#102F23]">Request China Export Quotation →</Link></div></RevealOnScroll></section>
  <FooterSection/><FloatingContactButtons/><MagneticButtons/><PremiumCursor/>
</main>}
