import type { Metadata } from "next";
import { existsSync } from "node:fs";
import Image from "next/image";
import Link from "next/link";
import FloatingContactButtons from "@/app/components/FloatingContactButtons";
import GoldenParticles from "@/app/components/GoldenParticles";
import MagneticButtons from "@/app/components/MagneticButtons";
import Navbar from "@/app/components/Navbar";
import PremiumCursor from "@/app/components/PremiumCursor";
import RevealOnScroll from "@/app/components/RevealOnScroll";
import StaggerItem from "@/app/components/StaggerItem";
import FooterSection from "@/sections/FooterSection";

const canonicalUrl = "https://shiveshinternational.com/export/new-zealand";
const heroImage = "/images/export/new-zealand/new-zealand-natural-products-export-hero.png";
const packagingImage = "/images/export/new-zealand/new-zealand-private-label-henna-indigo-buyers.png";
const coordinationImage = "/images/export/new-zealand/india-to-new-zealand-export-coordination.png";
const metadataKeywords = [
  "natural products exporter New Zealand", "natural products supplier New Zealand", "natural products manufacturer India for New Zealand", "Indian natural products exporter New Zealand", "bulk natural products New Zealand", "wholesale natural products New Zealand", "B2B natural products supplier New Zealand", "private label natural products New Zealand", "OEM natural products New Zealand",
  "henna exporter New Zealand", "henna powder exporter New Zealand", "natural henna powder supplier New Zealand", "henna manufacturer India for New Zealand", "bulk henna powder New Zealand", "wholesale henna powder New Zealand", "private label henna New Zealand", "henna importer New Zealand", "henna distributor New Zealand",
  "indigo powder exporter New Zealand", "natural indigo supplier New Zealand", "indigo powder manufacturer India for New Zealand", "bulk indigo powder New Zealand", "wholesale indigo powder New Zealand", "private label indigo New Zealand", "indigo importer New Zealand", "indigo distributor New Zealand",
  "natural henna hair colors New Zealand", "henna-based hair colors New Zealand", "botanical hair color supplier New Zealand", "natural hair color exporter New Zealand", "herbal hair color supplier New Zealand", "private label hair colors New Zealand", "OEM botanical hair colors New Zealand", "salon hair color supplier New Zealand",
  "Ayurvedic herbs exporter New Zealand", "Indian herbs supplier New Zealand", "herbal powder exporter New Zealand", "botanical ingredients supplier New Zealand", "bulk herbal powders New Zealand", "private label Ayurvedic herbs New Zealand", "wellness ingredient supplier New Zealand",
  "Indian spices exporter New Zealand", "Indian spices supplier New Zealand", "bulk Indian spices New Zealand", "wholesale spices New Zealand", "private label Indian spices New Zealand", "spice importer New Zealand", "spice distributor New Zealand", "Indian food ingredients New Zealand",
  "New Zealand natural product importer", "New Zealand natural product distributor", "New Zealand cosmetic ingredient buyer", "New Zealand natural cosmetic supplier", "New Zealand salon supplier", "New Zealand wellness product supplier", "New Zealand herbal wholesaler", "New Zealand private label supplier India", "New Zealand retail natural products supplier", "New Zealand e-commerce natural products supplier", "New Zealand food ingredient buyer", "New Zealand spice importer",
  "India to New Zealand natural products export", "India to New Zealand henna export", "India to New Zealand indigo export", "India to New Zealand herbs export", "India to New Zealand spices export", "natural products shipping India New Zealand", "export documentation support New Zealand", "bulk botanical products New Zealand", "Shivesh International New Zealand exporter",
];
export const metadata: Metadata = {
  title: { absolute: "Natural Products Exporter to New Zealand | Henna, Indigo, Herbs & Spices" },
  description: "Natural henna, indigo, botanical hair colors, Ayurvedic herbs and Indian spices for New Zealand importers, distributors, wholesalers and private-label buyers. MOQ 200 kg per item.",
  keywords: metadataKeywords,
  alternates: { canonical: canonicalUrl },
  openGraph: { title: "Henna & Indigo Exporter to New Zealand | Shivesh International", description: "India-origin henna, indigo, herbs and spices for professional New Zealand importers, distributors and buyer-brand programmes.", url: canonicalUrl, type: "website", locale: "en_NZ", siteName: "Shivesh International", images: [{ url: heroImage, alt: "Indian natural-product export supply for professional buyers in New Zealand" }] },
  twitter: { card: "summary_large_image", title: "Natural Products Exporter to New Zealand", description: "Bulk and private-label botanical product supply from India for professional buyers in New Zealand.", images: [heroImage] },
  robots: { index: true, follow: true, googleBot: { index: true, follow: true } },
};
const products = [
  ["Natural Henna Powder", "Fine botanical powder for New Zealand hair-care brands, ingredient buyers, specialist retailers and bulk repackers.", "/products/natural-henna-powder"],
  ["Natural Indigo Powder", "Natural indigo for professional two-step hair-color ranges, beauty distribution and suitable buyer-brand programmes.", "/products/natural-indigo-powder"],
  ["Natural Henna Hair Colors", "Retail-oriented botanical powder shades for hair-care brands, online sellers and natural-lifestyle channels.", "/products/natural-henna-hair-colors"],
  ["Henna-Based Hair Colors", "Commercial shade programmes for salon suppliers, private-label companies and selected cosmetic portfolios.", "/products/henna-based-hair-colors"],
  ["Ayurvedic Indian Herbs", "Selected Indian botanical powders for appropriate wellness, personal-care and specialist wholesale applications.", "/products/ayurvedic-indian-herbs"],
  ["Indian Spices", "Whole, ground and blended spice formats for food importers, regional wholesalers and specialty retail buyers.", "/products/indian-spices"],
];
const buyers = [
  ["Importers & Distributors", "Plan import programmes and onward distribution across professional New Zealand channels."],
  ["Natural Cosmetic Companies", "Evaluate henna, indigo and herbal powders for suitable formulation and product concepts."],
  ["Hair-Care Brands", "Develop botanical color assortments for retail, salon, specialist and online customers."],
  ["Salon & Beauty Suppliers", "Review professional formats and repeat-volume needs for beauty-trade distribution."],
  ["Private-Label Companies", "Discuss buyer-brand artwork, labels, feasible pouch formats and suitable volumes."],
  ["Herbal & Wellness Wholesalers", "Source selected Indian herbs for appropriate wholesale and natural-lifestyle ranges."],
  ["Spa & Natural-Lifestyle Buyers", "Consider botanical products for suitable spa, wellbeing and premium retail concepts."],
  ["Food & Spice Buyers", "Define grades, formats and quantities for food-service, manufacturing or retail channels."],
];
const locations = [
  ["Auckland", "New Zealand's largest commercial centre can support importer, beauty, wellness, retail and national distribution enquiries."],
  ["Wellington", "Capital-region businesses can assess specialist retail, natural-product, hospitality and professional supply opportunities."],
  ["Christchurch", "South Island distribution, food-sector and beauty businesses can review regional wholesale and retail programmes."],
  ["Hamilton", "Waikato-based wholesalers, wellness businesses and regional distributors can evaluate multi-category supply."],
  ["Tauranga", "Port-linked import activity and Bay of Plenty distribution can support buyer-nominated cargo planning."],
  ["Dunedin", "Otago's specialist retailers, wellness operators and regional businesses can consider botanical and spice ranges."],
  ["Palmerston North", "Its central position can be relevant to regional warehousing, food businesses and wholesale networks."],
  ["Napier / Hawke's Bay", "Food, hospitality, natural-lifestyle and regional wholesale businesses can assess appropriate products."],
];
const documents = [
  ["Commercial Invoice", "Prepared around confirmed products, quantities, values and agreed commercial terms."],
  ["Packing List", "May record package counts, weights, cartons, pallets and shipment references."],
  ["Certificate of Origin", "May be coordinated where applicable and subject to issuing availability."],
  ["Transport Documents", "A Bill of Lading or Air Waybill follows the confirmed shipment arrangement."],
  ["Product & Quality Records", "Specifications, COA or MSDS/SDS may be shared where applicable and available."],
  ["Agreed Export Records", "Other export-side documents may be assessed transaction by transaction."],
];
const steps = [
  ["Product Selection", "Define the product, intended use, New Zealand destination and expected volume."],
  ["Specification Review", "Align requested parameters with available specifications and product information."],
  ["Commercial Confirmation", "Confirm quantity, the 200 kg per-item MOQ, quotation and transaction terms."],
  ["Packaging & Production", "Approve feasible bulk or buyer-brand packing before scheduled production."],
  ["Documentation", "Prepare applicable and available commercial, quality and shipment records."],
  ["Shipment Coordination", "Coordinate dispatch and document sharing with the buyer or nominated forwarder."],
];
const faqs = [
  { question: "What products do you export to New Zealand?", answer: "New Zealand buyers can enquire about natural henna powder, natural indigo powder, natural henna hair colors, henna-based hair colors, Ayurvedic Indian herbs and Indian spices for suitable professional uses." },
  { question: "What is your MOQ for New Zealand orders?", answer: "The minimum order quantity is 200 kg per selected product or item. Multi-product requirements are reviewed separately for feasibility." },
  { question: "Do you offer private-label products for New Zealand buyers?", answer: "Buyer-brand packaging may be discussed for suitable products and quantities, subject to artwork, label, materials, printing, pack-size and technical feasibility." },
  { question: "What retail packaging sizes are available?", answer: "Depending on the selected product and confirmed feasibility, retail formats may include 100 g, 200 g, 500 g and 1 kg." },
  { question: "Do you offer bulk packaging?", answer: "Bulk formats may include 20 kg and 25 kg packs, including double-layer vacuum packaging where appropriate." },
  { question: "Can you support New Zealand importers and distributors?", answer: "Professional buyers can submit their product, intended-use, specification, quantity, packaging and destination requirements for review." },
  { question: "What export documents can you coordinate?", answer: "Subject to applicability and availability, records may include an invoice, packing list, certificate of origin, transport document, specification, COA or MSDS/SDS." },
  { question: "Can shipments be coordinated to Auckland or Tauranga?", answer: "Auckland, Tauranga, Lyttelton / Christchurch, Wellington or another feasible buyer-nominated cargo destination may be assessed. Freight, schedules, clearance, transit and delivery are not guaranteed." },
  { question: "Who is responsible for New Zealand import approvals and compliance?", answer: "The New Zealand importer or buyer must confirm classification, intended use, restrictions, eligibility, registrations, permits, filings, labeling, language, claims, testing, inspection, customs and local requirements." },
  { question: "How can a New Zealand buyer request a quotation?", answer: "Send company details, product, specification, intended use, quantity, pack preference and destination through the contact page." },
];
const structuredData = { "@context": "https://schema.org", "@graph": [
  { "@type": "WebPage", "@id": `${canonicalUrl}#webpage`, url: canonicalUrl, name: "Natural Products Exporter to New Zealand", description: "New Zealand-focused B2B export supply of natural henna, indigo, botanical hair colors, Ayurvedic herbs and Indian spices from India.", isPartOf: { "@id": "https://shiveshinternational.com/#website" }, about: { "@id": "https://shiveshinternational.com/#organization" }, breadcrumb: { "@id": `${canonicalUrl}#breadcrumb` }, primaryImageOfPage: { "@type": "ImageObject", url: heroImage }, inLanguage: "en-NZ" },
  { "@type": "BreadcrumbList", "@id": `${canonicalUrl}#breadcrumb`, itemListElement: [{ "@type": "ListItem", position: 1, name: "Home", item: "https://shiveshinternational.com/" }, { "@type": "ListItem", position: 2, name: "Export", item: "https://shiveshinternational.com/export" }, { "@type": "ListItem", position: 3, name: "Asia-Pacific", item: "https://shiveshinternational.com/export/asia-pacific" }, { "@type": "ListItem", position: 4, name: "New Zealand", item: canonicalUrl }] },
] };
const faqStructuredData = { "@context": "https://schema.org", "@type": "FAQPage", "@id": `${canonicalUrl}#faq`, mainEntity: faqs.map((faq) => ({ "@type": "Question", name: faq.question, acceptedAnswer: { "@type": "Answer", text: faq.answer } })) };
function OptionalImage({ src, alt, priority = false, className = "object-contain object-center" }: { src: string; alt: string; priority?: boolean; className?: string }) { if (!existsSync(`${process.cwd()}/public${src}`)) return null; return <Image src={src} alt={alt} fill priority={priority} sizes="(min-width: 1024px) 50vw, 100vw" className={className} />; }
function Cards({ items, columns = "lg:grid-cols-4" }: { items: string[][]; columns?: string }) { return <div className={`mt-14 grid auto-rows-fr gap-5 sm:grid-cols-2 ${columns}`}>{items.map(([title, text]) => <article key={title} className="h-full border border-[#173B2A]/12 bg-[#FBF8F1] p-7 sm:p-8"><span className="block h-px w-12 bg-[#C9A962]" /><h3 className="mt-5 font-[family-name:var(--font-playfair)] text-2xl font-semibold">{title}</h3><p className="mt-4 text-sm font-light leading-7 text-[#4C5F54]">{text}</p></article>)}</div>; }

export default function NewZealandExportPage() { return <main className="min-h-screen overflow-x-hidden bg-[#F5F0E6] text-[#173B2A]">
  <script type="application/ld+json" dangerouslySetInnerHTML={{ __html: JSON.stringify(structuredData).replace(/</g, "\\u003c") }} /><script type="application/ld+json" dangerouslySetInnerHTML={{ __html: JSON.stringify(faqStructuredData).replace(/</g, "\\u003c") }} /><Navbar />
  <section className="relative isolate overflow-hidden bg-[#071B14]"><OptionalImage src={heroImage} alt="Indian henna, indigo, herbs and spices prepared for professional supply to New Zealand" priority className="object-cover object-center" /><div className="absolute inset-0 bg-gradient-to-r from-[#061711]/85 via-[#102F23]/58 to-[#071B14]/35" /><GoldenParticles /><div className="relative z-10 flex items-center px-6 pb-20 pt-32 sm:px-8 sm:pb-24 sm:pt-36 lg:px-12 lg:pb-28 lg:pt-40"><div className="w-full max-w-[950px]"><StaggerItem delay={0}><p className="text-[10px] font-bold uppercase tracking-[0.38em] text-[#E4C878] sm:text-xs">India to New Zealand B2B Supply</p></StaggerItem><StaggerItem delay={100}><h1 className="mt-5 font-[family-name:var(--font-playfair)] text-4xl font-medium leading-[1.02] tracking-[-0.04em] text-[#F5F0E6] sm:text-5xl lg:text-6xl xl:text-[66px]">Natural Henna, Indigo, Herbs &amp; Spices <span className="block bg-gradient-to-r from-[#F5F0E6] via-[#E4C878] to-[#C9A962] bg-clip-text text-transparent">Exporter to New Zealand</span></h1></StaggerItem><StaggerItem delay={200}><p className="mt-5 max-w-[800px] text-[16px] font-light leading-8 text-white/82">Shivesh International coordinates natural henna powder, natural indigo powder, botanical hair colors, Ayurvedic herbs and Indian spices for New Zealand importers, distributors, private-label brands and wholesale buyers.</p></StaggerItem><StaggerItem delay={300}><div className="mt-7 flex flex-wrap gap-4"><Link href="/contact" className="border border-[#C9A962] bg-[#C9A962] px-7 py-4 text-[10px] font-bold uppercase tracking-[0.2em] text-[#102F23]">Send New Zealand Inquiry →</Link><a href="#products" className="border border-white/30 bg-[#102F23]/40 px-7 py-4 text-[10px] font-bold uppercase tracking-[0.2em] text-white">Explore Export Products ↓</a></div></StaggerItem><StaggerItem delay={400}><div className="mt-10 grid max-w-[760px] grid-cols-2 gap-3 lg:grid-cols-4">{[["200 kg", "MOQ per item"], ["Bulk", "B2B supply"], ["Private Label", "Buyer-brand packs"], ["Export", "Coordination"]].map(([value, label]) => <div key={label} className="border border-white/15 bg-black/20 p-4"><p className="font-[family-name:var(--font-playfair)] text-xl font-semibold text-[#E4C878]">{value}</p><p className="mt-2 text-[9px] uppercase tracking-[0.22em] text-white/55">{label}</p></div>)}</div></StaggerItem></div></div></section>
  <section className="px-6 py-24 sm:px-8 lg:px-12 lg:py-32"><RevealOnScroll><div className="mx-auto max-w-[1200px]"><p className="text-[10px] font-bold uppercase tracking-[0.4em] text-[#9F7F36]">New Zealand Market Supply</p><h2 className="mt-6 font-[family-name:var(--font-playfair)] text-[clamp(2.3rem,4.6vw,4.6rem)] font-semibold">Indian Botanical Supply <span className="block text-[#A97B22]">for Professional New Zealand Buyers</span></h2><p className="mt-7 text-[16px] font-light leading-8 text-[#4C5F54]">Build programmes around botanical hair color, natural cosmetic ingredients, wellness ranges, buyer-brand packs, bulk inputs and Indian food ingredients. Each enquiry is reviewed around intended use, specification, quantity, packaging and destination.</p></div></RevealOnScroll></section>
  <section id="products" className="bg-[#EDE5D7] px-6 py-24 sm:px-8 lg:px-12 lg:py-32"><RevealOnScroll><div className="mx-auto max-w-[1500px]"><div className="text-center"><p className="text-[10px] uppercase tracking-[0.4em] text-[#9F7F36]">Six Export Product Categories</p><h2 className="mt-6 font-[family-name:var(--font-playfair)] text-[clamp(2.3rem,4.8vw,4.8rem)] font-semibold">Products for New Zealand <span className="block text-[#A97B22]">Commercial Enquiries</span></h2></div><div className="mt-14 grid auto-rows-fr gap-5 sm:grid-cols-2 lg:grid-cols-3">{products.map(([title, text, href]) => <article key={title} className="flex h-full flex-col border border-[#173B2A]/12 bg-[#FBF8F1] p-8"><span className="block h-px w-12 bg-[#C9A962]" /><h3 className="mt-5 font-[family-name:var(--font-playfair)] text-2xl font-semibold">{title}</h3><p className="mt-4 flex-1 text-sm font-light leading-7 text-[#4C5F54]">{text}</p><Link href={href} className="mt-7 text-[10px] font-bold uppercase tracking-[0.2em] text-[#A97B22]">View Product →</Link></article>)}</div></div></RevealOnScroll></section>
  <section className="px-6 py-24 sm:px-8 lg:px-12 lg:py-32"><RevealOnScroll><div className="mx-auto max-w-[1500px]"><p className="text-center text-[10px] uppercase tracking-[0.4em] text-[#9F7F36]">Professional Buyer Profiles</p><h2 className="mt-6 text-center font-[family-name:var(--font-playfair)] text-[clamp(2.3rem,4.6vw,4.6rem)] font-semibold">Who We Support <span className="block text-[#A97B22]">in the New Zealand Market</span></h2><Cards items={buyers} /></div></RevealOnScroll></section>
  <section className="bg-[#0B3325] px-6 py-24 text-[#F5F0E6] sm:px-8 lg:px-12 lg:py-32"><RevealOnScroll><div className="mx-auto max-w-[1500px]"><p className="text-center text-[10px] uppercase tracking-[0.4em] text-[#E4C878]">Major New Zealand Commercial Locations</p><h2 className="mt-6 text-center font-[family-name:var(--font-playfair)] text-[clamp(2.3rem,4.6vw,4.6rem)] font-semibold">Buyer and Distribution Context <span className="block text-[#E4C878]">Across New Zealand</span></h2><div className="[&_article]:border-white/12 [&_article]:bg-white/[0.04] [&_article_h3]:text-[#F5F0E6] [&_article_p]:text-white/65"><Cards items={locations} /></div><p className="mx-auto mt-10 max-w-[1050px] border border-[#C9A962]/25 bg-black/15 p-6 text-center text-sm font-light leading-7 text-white/65">These locations identify potential commercial and distribution contexts only. They do not represent a Shivesh International office, branch, warehouse, agent, stock, inventory, current buyer, guaranteed relationship or exclusive territory.</p></div></RevealOnScroll></section>
  <section className="px-6 py-24 sm:px-8 lg:px-12 lg:py-32"><RevealOnScroll><div className="mx-auto grid max-w-[1400px] items-center gap-14 lg:grid-cols-2"><div><p className="text-[10px] font-bold uppercase tracking-[0.4em] text-[#9F7F36]">Packaging &amp; Private Label</p><h2 className="mt-6 font-[family-name:var(--font-playfair)] text-[clamp(2.3rem,4.5vw,4.5rem)] font-semibold">Formats Built Around <span className="block text-[#A97B22]">the Confirmed Order</span></h2><p className="mt-7 text-[16px] font-light leading-8 text-[#4C5F54]">Retail formats may include 100 g, 200 g, 500 g and 1 kg packs. Silver or gold metallized pouches, buyer-brand artwork, label coordination and retail-ready formats can be reviewed for suitable products and quantities.</p><p className="mt-5 text-[16px] font-light leading-8 text-[#4C5F54]">Bulk packaging may include 20 kg and 25 kg packs, with double-layer vacuum packaging where applicable. MOQ is 200 kg per item. Availability depends on product, technical feasibility, pack-size feasibility and order quantity; no format or New Zealand regulatory approval is promised universally.</p></div><div className="relative aspect-[4/3] overflow-hidden border border-[#C9A962]/30 bg-[#102F23]"><OptionalImage src={packagingImage} alt="Private-label henna and indigo packaging planning for New Zealand buyers" /></div></div></RevealOnScroll></section>
  <section className="bg-[#EDE5D7] px-6 py-24 sm:px-8 lg:px-12 lg:py-32"><RevealOnScroll><div className="mx-auto grid max-w-[1400px] items-center gap-14 lg:grid-cols-2"><div className="relative aspect-[4/3] overflow-hidden border border-[#C9A962]/30 bg-[#102F23]"><OptionalImage src={coordinationImage} alt="India to New Zealand export documentation and shipment coordination" /></div><div><p className="text-[10px] font-bold uppercase tracking-[0.4em] text-[#9F7F36]">India to New Zealand</p><h2 className="mt-6 font-[family-name:var(--font-playfair)] text-[clamp(2.3rem,4.5vw,4.5rem)] font-semibold">Structured Export Coordination <span className="block text-[#A97B22]">for New Zealand</span></h2><p className="mt-7 text-[16px] font-light leading-8 text-[#4C5F54]">Coordination can cover product selection, specification confirmation, quotation, commercial terms, packaging or private-label confirmation, production, quality checks, export documentation, shipment planning, dispatch and document sharing.</p><p className="mt-5 text-[16px] font-light leading-8 text-[#4C5F54]">We can align with the buyer or nominated freight forwarder for a feasible Auckland, Tauranga, Lyttelton / Christchurch, Wellington or other nominated cargo destination. Freight rates, vessel schedules, transit times, customs clearance, import approval, registration, inspection, delivery and regulatory acceptance are not guaranteed.</p></div></div></RevealOnScroll></section>
  <section className="px-6 py-24 sm:px-8 lg:px-12 lg:py-32"><RevealOnScroll><div className="mx-auto max-w-[1500px]"><div className="text-center"><p className="text-[10px] uppercase tracking-[0.4em] text-[#9F7F36]">Transaction-Wise Records</p><h2 className="mt-6 font-[family-name:var(--font-playfair)] text-[clamp(2.3rem,4.6vw,4.6rem)] font-semibold">Export-Side Document <span className="block text-[#A97B22]">Coordination</span></h2></div><Cards items={documents} columns="lg:grid-cols-3" /></div></RevealOnScroll></section>
  <section className="bg-[#0B3325] px-6 py-24 text-[#F5F0E6] sm:px-8 lg:px-12 lg:py-28"><RevealOnScroll><div className="mx-auto max-w-[1200px]"><p className="text-[10px] font-bold uppercase tracking-[0.4em] text-[#E4C878]">Importer Responsibility Notice</p><h2 className="mt-6 font-[family-name:var(--font-playfair)] text-[clamp(2.2rem,4.2vw,4.2rem)] font-semibold">Destination-Market Compliance <span className="block text-[#E4C878]">Remains with the Buyer</span></h2><p className="mt-7 text-[16px] font-light leading-8 text-white/70">The New Zealand importer or buyer is responsible for confirming applicable product classification, intended use, ingredient restrictions, import eligibility, registrations, permits, filings, labeling, language requirements, claims, testing, inspection, customs requirements and all other local regulatory requirements.</p><p className="mt-5 text-[16px] font-light leading-8 text-white/70">Shivesh International may coordinate export-side documentation according to the agreed transaction. This page makes no MPI, customs, cosmetic, food, registration, inspection or other New Zealand approval claim.</p></div></RevealOnScroll></section>
  <section className="px-6 py-24 sm:px-8 lg:px-12 lg:py-32"><RevealOnScroll><div className="mx-auto max-w-[1500px]"><div className="text-center"><p className="text-[10px] uppercase tracking-[0.4em] text-[#9F7F36]">Six-Step Workflow</p><h2 className="mt-6 font-[family-name:var(--font-playfair)] text-[clamp(2.3rem,4.6vw,4.6rem)] font-semibold">From Enquiry to <span className="block text-[#A97B22]">Shipment Coordination</span></h2></div><div className="mt-14 grid auto-rows-fr gap-5 sm:grid-cols-2 lg:grid-cols-3">{steps.map(([title, text], index) => <article key={title} className="border border-[#173B2A]/12 bg-[#FBF8F1] p-8"><p className="text-[10px] font-bold uppercase tracking-[0.25em] text-[#A97B22]">Step {String(index + 1).padStart(2, "0")}</p><h3 className="mt-5 font-[family-name:var(--font-playfair)] text-2xl font-semibold">{title}</h3><p className="mt-4 text-sm font-light leading-7 text-[#4C5F54]">{text}</p></article>)}</div></div></RevealOnScroll></section>
  <section className="bg-[#EDE5D7] px-6 py-24 sm:px-8 lg:px-12 lg:py-32"><RevealOnScroll><div className="mx-auto max-w-[1200px]"><div className="text-center"><p className="text-[10px] uppercase tracking-[0.4em] text-[#9F7F36]">Buyer Questions</p><h2 className="mt-6 font-[family-name:var(--font-playfair)] text-[clamp(2.3rem,4.6vw,4.6rem)] font-semibold">New Zealand Export <span className="block text-[#A97B22]">Frequently Asked Questions</span></h2></div><div className="mt-14 grid gap-5 lg:grid-cols-2">{faqs.map((faq) => <article key={faq.question} className="border border-[#173B2A]/12 bg-[#FBF8F1] p-7 sm:p-8"><h3 className="font-[family-name:var(--font-playfair)] text-xl font-semibold">{faq.question}</h3><p className="mt-4 text-sm font-light leading-7 text-[#4C5F54]">{faq.answer}</p></article>)}</div></div></RevealOnScroll></section>
  <section className="bg-[#071B14] px-6 py-24 text-center text-[#F5F0E6] sm:px-8 lg:px-12"><RevealOnScroll><div className="mx-auto max-w-[950px]"><p className="text-[10px] font-bold uppercase tracking-[0.4em] text-[#E4C878]">Start a Commercial Discussion</p><h2 className="mt-6 font-[family-name:var(--font-playfair)] text-[clamp(2.4rem,5vw,5rem)] font-semibold">Planning Natural-Product Supply <span className="block text-[#E4C878]">for New Zealand?</span></h2><p className="mx-auto mt-7 max-w-[760px] text-[16px] font-light leading-8 text-white/65">Share your company, product, intended use, specification, quantity, packaging and destination requirements for review.</p><Link href="/contact" className="mt-9 inline-flex border border-[#C9A962] bg-[#C9A962] px-8 py-4 text-[10px] font-bold uppercase tracking-[0.2em] text-[#102F23]">Send New Zealand Inquiry →</Link></div></RevealOnScroll></section>
  <FooterSection /><FloatingContactButtons /><MagneticButtons /><PremiumCursor />
</main>; }
