import type { Metadata } from "next";
import Image from "next/image";
import Link from "next/link";
import FloatingContactButtons from "@/app/components/FloatingContactButtons";
import GoldenParticles from "@/app/components/GoldenParticles";
import MagneticButtons from "@/app/components/MagneticButtons";
import Navbar from "@/app/components/Navbar";
import PremiumCursor from "@/app/components/PremiumCursor";
import RevealOnScroll from "@/app/components/RevealOnScroll";
import StaggerItem from "@/app/components/StaggerItem";
import { polandLanguageAlternates } from "@/app/lib/i18n";
import FooterSection from "@/sections/FooterSection";

const canonicalUrl = "https://shiveshinternational.com/it/export/polonia";
const heroImage = "/images/export/poland/poland-export-hero.png";
const metadataKeywords = [
  "esportatore di prodotti naturali in Polonia", "produttore di henné per la Polonia", "fornitore di henné naturale in Polonia", "henné all’ingrosso Polonia", "esportatore di henné naturale", "fornitore di indigo naturale", "esportatore di indigo naturale", "indigo all’ingrosso Polonia", "fornitore di colorazioni vegetali", "colorazione botanica per capelli", "fornitore per saloni professionali", "fornitore di cosmetici naturali", "importatori in Polonia", "distributori in Polonia", "grossisti in Polonia", "rivenditori specializzati Polonia", "fornitore di erbe ayurvediche", "esportatore di erbe ayurvediche", "fornitore di spezie indiane", "esportatore di spezie indiane", "Private Label Polonia", "OEM Polonia", "marchio proprio Polonia", "fornitura all’ingrosso Polonia", "approvvigionamento B2B Polonia", "prodotti naturali India Polonia", "henné Private Label Polonia", "indigo Private Label Polonia", "colorazioni botaniche Polonia", "erbe indiane all’ingrosso Polonia", "spezie indiane all’ingrosso Polonia", "confezionamento per marchi polacchi", "etichette in polacco", "documentazione export Polonia", "spedizione India Polonia", "trasporto marittimo Gdańsk", "trasporto aereo Polonia", "MOQ 200 kg per prodotto", "fornitore Varsavia", "fornitore Cracovia",
];

export const metadata: Metadata = {
  title: "Esportatore di henné, indigo, erbe e spezie in Polonia",
  description: "Fornitore indiano di henné, indigo, colorazioni botaniche, erbe ayurvediche e spezie per importatori, grossisti e marchi Private Label in Polonia.",
  keywords: metadataKeywords,
  alternates: { canonical: canonicalUrl, languages: polandLanguageAlternates },
  openGraph: { title: "Esportatore di henné, indigo, erbe e spezie in Polonia", description: "Fornitura indiana sfusa, all’ingrosso, OEM e Private Label per acquirenti professionali in Polonia.", url: canonicalUrl, type: "website", locale: "it_IT", siteName: "Shivesh International", images: [{ url: heroImage, alt: "Acquirenti polacchi coordinano la fornitura di prodotti naturali dall’India" }] },
  twitter: { card: "summary_large_image", title: "Esportatore di prodotti naturali in Polonia", description: "Fornitura indiana di henné, indigo, erbe, spezie e Private Label per acquirenti professionali polacchi.", images: [heroImage] },
  robots: { index: true, follow: true, googleBot: { index: true, follow: true } },
};

const marketLinks = [
  ["Henné naturale in polvere", "/products/natural-henna-powder"],
  ["Indigo naturale in polvere", "/products/natural-indigo-powder"],
  ["Spezie indiane", "/products/indian-spices"],
];

const products = [
  ["Henné naturale in polvere", "Henné di qualità per marchi cosmetici, rivenditori naturali, fornitori per saloni, grossisti e gamme Private Label in Polonia.", "/products/natural-henna-powder"],
  ["Indigo naturale in polvere", "Indigo naturale per colorazioni botaniche, distribuzione professionale, approvvigionamento sfuso e confezionamento a marchio dell’acquirente.", "/products/natural-indigo-powder"],
  ["Colorazioni naturali per capelli all’henné", "Un’ampia collezione botanica per importatori, marchi e-commerce, saloni e canali di cura naturale dei capelli in Polonia.", "/products/natural-henna-hair-colors"],
  ["Colorazioni per capelli a base di henné", "Colorazioni in polvere pronte per l’esportazione per programmi all’ingrosso, OEM, professionali e Private Label personalizzati.", "/products/henna-based-hair-colors"],
  ["Erbe ayurvediche indiane", "Polveri erboristiche indiane per cosmetica, cura personale, benessere e vendita specializzata all’ingrosso, senza dichiarazioni terapeutiche.", "/products/ayurvedic-indian-herbs"],
  ["Spezie indiane", "Spezie intere e macinate per acquirenti alimentari, importatori, confezionatori conto terzi, distributori e marchi Private Label polacchi.", "/products/indian-spices"],
];
const buyers = [
  ["Importatori e distributori", "Coordiniamo specifiche, quantità commerciali e documentazione disponibile per reti distributive polacche e dell’Europa centrale."],
  ["Aziende di cosmetica naturale", "Valutiamo henné, indigo e polveri erboristiche per progetti cosmetici previa verifica di uso, specifiche e classificazione."],
  ["Marchi di cura botanica dei capelli", "Pianifichiamo gamme botaniche per retail, saloni, canali professionali e online."],
  ["Fornitori di prodotti per saloni", "Esaminiamo confezioni professionali, formati retail e forniture sfuse ripetute per la distribuzione polacca."],
  ["Aziende erboristiche e ayurvediche", "Valutiamo prodotti botanici indiani per programmi di benessere, retail specializzato e marchio proprio senza dichiarazioni mediche."],
  ["Importatori di alimenti e spezie", "Pianifichiamo spezie intere e macinate e ingredienti alimentari per importatori, aziende e confezionatori conto terzi."],
  ["Marchi Private Label e OEM", "Coordiniamo buste, scatole, vasetti, grafiche, codici a barre e presentazioni in polacco, inglese o multilingue."],
  ["Canali farmacia, benessere ed e-commerce", "Valutiamo gamme non medicinali adatte a canali specializzati, parafarmaceutici, del benessere e digitali."],
];
const documents = [
  ["Fattura commerciale", "Predisposta in base ad acquirente, prodotti, quantità, valori e condizioni di spedizione confermati."],
  ["Packing List", "Può dettagliare colli, pesi netti e lordi, cartoni o pallet e riferimenti di spedizione confermati."],
  ["Origine e specifiche", "Certificato di origine, specifiche e riferimenti di lotto dipendono dal prodotto e dall’ordine."],
  ["Documentazione tecnica o di qualità", "COA, dati di lotto, sicurezza o informazioni tecniche possono essere coordinati ove applicabili e disponibili."],
  ["Informazioni su confezioni ed etichette", "Grafiche approvate, informazioni, codici a barre e dati di lotto possono essere allineati al programma confermato."],
  ["Documenti di spedizione", "I documenti disponibili possono essere coordinati con lo spedizioniere incaricato e il piano concordato."],
];
const steps = [
  ["Condividete i requisiti", "Indicate prodotto, uso commerciale previsto, destinazione in Polonia, quantità e confezionamento."],
  ["Confermate prodotto e MOQ", "Verificate specifiche e quantità minima di 200 kg per ogni singolo prodotto."],
  ["Allineate confezionamento e grafiche", "Valutate formati retail o sfusi, grafiche polacche o multilingue, sigilli, etichette, codici a barre e lotti."],
  ["Verificate i documenti disponibili", "Confermate la documentazione specifica del prodotto disponibile per l’ordine."],
  ["Pianificate il trasporto", "Valutate condizioni, spedizioniere dell’acquirente e modalità marittime, aeree, stradali, ferroviarie o multimodali."],
  ["Coordinate produzione e spedizione", "Procedete secondo condizioni confermate, fattibilità, confezionamento approvato e piano concordato."],
];
const locations = [
  ["Varsavia", "Importatori, aziende cosmetiche, marchi e-commerce e distributori nazionali possono valutare approvvigionamento multicategoria e Private Label."],
  ["Cracovia", "Rivenditori naturali, aziende del benessere e fornitori per saloni possono valutare gamme botaniche, erboristiche e per capelli."],
  ["Łódź", "Aziende produttive, di confezionamento e distribuzione possono coordinare ingredienti sfusi e formati Private Label."],
  ["Breslavia", "Importatori della Polonia occidentale e distributori dell’Europa centrale possono valutare forniture retail, professionali e all’ingrosso."],
  ["Poznań", "Acquirenti commerciali, grossisti e aziende alimentari possono pianificare spezie, prodotti botanici e forniture ripetute."],
  ["Danzica", "Aziende logistiche, importatori e distributori possono valutare trasporto marittimo, prodotti sfusi e distribuzione in Polonia."],
  ["Katowice", "Aziende industriali e distributive del sud possono valutare ingredienti botanici, prodotti per saloni e formati all’ingrosso."],
  ["Stettino", "Acquirenti collegati al porto e distributori regionali possono valutare importazione, magazzinaggio e trasporto stradale o ferroviario."],
];
const faqs = [
  { question: "Quali prodotti naturali sono disponibili per gli acquirenti polacchi?", answer: "È possibile valutare henné, indigo, colorazioni all’henné, erbe ayurvediche e spezie indiane, previa conferma delle specifiche e delle condizioni commerciali." },
  { question: "Qual è la quantità minima d’ordine per la Polonia?", answer: "Il MOQ è di 200 kg per prodotto. Prodotti distinti non possono essere combinati automaticamente e le quantità finali dipendono dal programma confermato." },
  { question: "Quali formati retail e sfusi possono essere valutati?", answer: "I formati retail o professionali possono comprendere 100 g, 200 g, 500 g e 1 kg; quelli sfusi confezioni sottovuoto a doppio strato da 20 kg e 25 kg, previa fattibilità." },
  { question: "Potete coordinare confezioni Private Label per la Polonia?", answer: "Alcuni programmi possono includere grafiche dell’acquirente, layout polacchi, inglesi o multilingue, buste, scatole o vasetti, etichette, sigilli, codici a barre e dati di lotto." },
  { question: "Quali documenti possono essere disponibili per gli ordini destinati alla Polonia?", answer: "In base al prodotto, all’ordine e alla disponibilità: fattura commerciale, Packing List, certificato di origine, specifiche, documenti di qualità o tecnici e documenti di spedizione." },
  { question: "Come possono essere coordinate le spedizioni dall’India alla Polonia?", answer: "Il trasporto marittimo o aereo può essere valutato con lo spedizioniere dell’acquirente. Danzica, Gdynia o altri porti europei possono essere considerati, senza garanzie su rotte, tempi o risultati." },
  { question: "Gli acquirenti polacchi possono richiedere campioni?", answer: "I campioni possono essere valutati prima di un ordine sfuso in base a disponibilità, quantità, corriere, costo e processo di valutazione. Non garantiscono accettazione normativa o forniture future." },
  { question: "Chi è responsabile dei requisiti polacchi e dell’UE?", answer: "L’importatore o l’operatore responsabile deve confermare denominazioni, ingredienti, dichiarazioni, istruzioni, avvertenze, etichette, classificazione, registrazioni, dogana e requisiti applicabili." },
];
const structuredData = { "@context": "https://schema.org", "@graph": [
  { "@type": "WebPage", "@id": `${canonicalUrl}#webpage`, url: canonicalUrl, name: "Esportatore di henné, indigo, erbe e spezie in Polonia", description: "Fornitura export dall’India di henné, indigo, colorazioni botaniche, erbe ayurvediche e spezie indiane per la Polonia.", isPartOf: { "@id": "https://shiveshinternational.com/#website" }, about: { "@id": "https://shiveshinternational.com/#organization" }, breadcrumb: { "@id": `${canonicalUrl}#breadcrumb` }, inLanguage: "it" },
  { "@type": "BreadcrumbList", "@id": `${canonicalUrl}#breadcrumb`, itemListElement: [{ "@type": "ListItem", position: 1, name: "Home", item: "https://shiveshinternational.com/" }, { "@type": "ListItem", position: 2, name: "Export", item: "https://shiveshinternational.com/export" }, { "@type": "ListItem", position: 3, name: "Europa", item: "https://shiveshinternational.com/export/europe" }, { "@type": "ListItem", position: 4, name: "Polonia", item: canonicalUrl }] },
] };
const faqStructuredData = { "@context": "https://schema.org", "@type": "FAQPage", "@id": `${canonicalUrl}#faq`, mainEntity: faqs.map((faq) => ({ "@type": "Question", name: faq.question, acceptedAnswer: { "@type": "Answer", text: faq.answer } })) };

const Cards = ({ items, columns = "lg:grid-cols-4" }: { items: string[][]; columns?: string }) => <div className={`mt-14 grid auto-rows-fr gap-5 sm:grid-cols-2 ${columns}`}>{items.map(([title, text]) => <article key={title} className="h-full border border-[#173B2A]/12 bg-[#FBF8F1] p-7 sm:p-8"><span className="block h-px w-12 bg-[#C9A962]" /><h3 className="mt-5 font-[family-name:var(--font-playfair)] text-2xl font-semibold">{title}</h3><p className="mt-4 text-[14px] font-light leading-7 text-[#4C5F54]">{text}</p></article>)}</div>;

export default function PolandExportPage() { return <main className="min-h-screen overflow-x-hidden bg-[#F5F0E6] text-[#173B2A]">
  <script type="application/ld+json" dangerouslySetInnerHTML={{ __html: JSON.stringify(structuredData).replace(/</g, "\\u003c") }} /><script type="application/ld+json" dangerouslySetInnerHTML={{ __html: JSON.stringify(faqStructuredData).replace(/</g, "\\u003c") }} /><Navbar />
  <section className="relative isolate overflow-hidden"><Image src={heroImage} alt="Acquirenti polacchi valutano henné, indigo, erbe e spezie indiane" fill priority sizes="100vw" className="object-cover object-center" /><div className="absolute inset-0 bg-gradient-to-r from-[#061711]/72 via-[#102F23]/40 to-[#071B14]/10" /><div className="absolute inset-0 bg-gradient-to-t from-black/10 via-transparent to-black/[0.04]" /><GoldenParticles /><div className="relative z-10 flex items-center px-6 pb-20 pt-32 sm:px-8 sm:pb-24 sm:pt-36 lg:px-12 lg:pb-28 lg:pt-40"><div className="w-full max-w-[820px] lg:max-w-[860px] xl:max-w-[900px]"><StaggerItem delay={0}><p className="text-[10px] font-bold uppercase tracking-[0.38em] text-[#E4C878] sm:text-xs">Esportazione dall’India alla Polonia</p></StaggerItem><StaggerItem delay={100}><h1 className="mt-5 font-[family-name:var(--font-playfair)] text-4xl font-medium leading-[1] tracking-[-0.04em] text-[#F5F0E6] sm:text-5xl lg:text-6xl xl:text-[66px]">Esportatore di prodotti naturali in Polonia<span className="mt-2 block bg-gradient-to-r from-[#F5F0E6] via-[#E4C878] to-[#C9A962] bg-clip-text text-transparent">Henné, indigo, erbe e spezie</span></h1></StaggerItem><StaggerItem delay={200}><p className="mt-5 max-w-[730px] text-[16px] font-light leading-7 text-[#F5F0E6]/82 sm:text-[17px] sm:leading-8">Shivesh International è un produttore, fornitore ed esportatore indiano che supporta importatori, distributori, grossisti, aziende cosmetiche, fornitori per saloni, aziende erboristiche, acquirenti alimentari e marchi Private Label polacchi.</p></StaggerItem><StaggerItem delay={300}><div className="mt-7 flex flex-wrap gap-4"><Link href="/contact" className="inline-flex items-center gap-4 border border-[#C9A962] bg-[#C9A962] px-7 py-4 text-[10px] font-bold uppercase tracking-[0.2em] text-[#102F23]">Invia una richiesta per la Polonia <span>→</span></Link><a href="#prodotti" className="inline-flex items-center gap-4 border border-[#F5F0E6]/30 bg-[#102F23]/40 px-7 py-4 text-[10px] font-bold uppercase tracking-[0.2em] text-[#F5F0E6] backdrop-blur-lg">Scopri i prodotti <span>↓</span></a></div></StaggerItem><StaggerItem delay={400}><div className="mt-10 grid max-w-[740px] grid-cols-2 gap-3 lg:grid-cols-4">{[["200 kg","MOQ per prodotto"],["Sfuso","Fornitura all’ingrosso"],["OEM","Private Label"],["Polonia","Richieste degli acquirenti"]].map(([v,l])=><div key={l} className="border border-white/15 bg-black/20 px-4 py-4 backdrop-blur-md"><p className="font-[family-name:var(--font-playfair)] text-xl font-semibold text-[#E4C878]">{v}</p><p className="mt-2 text-[9px] font-bold uppercase tracking-[0.22em] text-[#F5F0E6]/55">{l}</p></div>)}</div></StaggerItem></div></div></section>
  <section className="px-6 py-24 sm:px-8 lg:px-12 lg:py-32"><RevealOnScroll><div className="mx-auto max-w-[1120px]"><p className="text-[10px] font-bold uppercase tracking-[0.4em] text-[#9F7F36]">Approvvigionamento di prodotti naturali India–Polonia</p><h2 className="mt-6 font-[family-name:var(--font-playfair)] text-[clamp(2.5rem,4.6vw,4.6rem)] font-semibold leading-[1.04]">Fornitura indiana strutturata <span className="block text-[#A97B22]">per acquirenti professionali polacchi</span></h2><p className="mt-7 text-[16px] font-light leading-8 text-[#4C5F54]">La Polonia offre canali retail, cosmetici, professionali, erboristici, del benessere, alimentari e online, oltre a collegamenti con l’Europa centrale e orientale. Gli acquirenti necessitano di informazioni, quantità realistiche, confezioni adatte al canale e responsabilità chiare. Ogni richiesta viene coordinata in base a prodotto, uso, specifiche, destinazione, volume e formato.</p><p className="mt-5 text-[15px] font-light leading-8 text-[#4C5F54]">Un importatore di marchi cosmetici può richiedere informazioni diverse da un grossista di spezie, un confezionatore conto terzi o un distributore per saloni. Aziende a Varsavia, Cracovia, Łódź, Breslavia, Poznań, Danzica, Katowice e Stettino possono valutare approvvigionamenti mirati o multicategoria. Questi riferimenti non implicano uffici, magazzini, scorte, partnership o distributori esclusivi.</p><p className="mt-5 text-[15px] font-light leading-8 text-[#4C5F54]">La pianificazione può considerare previsioni di riordino, materiali di confezionamento, tempi produttivi ragionevoli e distribuzione in Polonia o nell’Europa centrale. Disponibilità, specifiche, produzione, documenti e spedizione restano soggetti a conferma scritta.</p></div></RevealOnScroll></section>
  <section id="prodotti" className="scroll-mt-24 bg-[#EDE5D7] px-6 py-24 sm:px-8 lg:px-12 lg:py-32"><RevealOnScroll><div className="mx-auto max-w-[1500px]"><div className="text-center"><p className="text-[10px] font-bold uppercase tracking-[0.4em] text-[#9F7F36]">Sei categorie commerciali</p><h2 className="mt-6 font-[family-name:var(--font-playfair)] text-[clamp(2.5rem,4.8vw,4.8rem)] font-semibold">Prodotti naturali <span className="block text-[#A97B22]">per acquirenti e marchi polacchi</span></h2></div><div className="mt-14 grid auto-rows-fr gap-5 sm:grid-cols-2 lg:grid-cols-3">{products.map(([title,text,href],i)=><article key={title} className="flex h-full min-h-[290px] flex-col border border-[#173B2A]/12 bg-[#FBF8F1] p-7"><span className="text-4xl text-[#C9A962]">{String(i+1).padStart(2,"0")}</span><h3 className="mt-5 font-[family-name:var(--font-playfair)] text-2xl font-semibold">{title}</h3><p className="mt-4 flex-1 text-sm leading-7 text-[#4C5F54]">{text}</p><Link href={href} className="mt-6 text-[10px] font-bold uppercase tracking-[0.2em] text-[#A97B22]">Scopri {title} →</Link></article>)}</div></div></RevealOnScroll></section>
  <section className="px-6 py-24 sm:px-8 lg:px-12 lg:py-32"><RevealOnScroll><div className="mx-auto max-w-[1500px]"><div className="text-center"><p className="text-[10px] font-bold uppercase tracking-[0.4em] text-[#9F7F36]">Profili degli acquirenti polacchi</p><h2 className="mt-6 font-[family-name:var(--font-playfair)] text-[clamp(2.5rem,4.7vw,4.7rem)] font-semibold">Pianificazione della fornitura per <span className="block text-[#A97B22]">canali di importazione, retail e distribuzione</span></h2></div><Cards items={buyers} /></div></RevealOnScroll></section>
  <section className="bg-[#EDE5D7] px-6 py-24 sm:px-8 lg:px-12 lg:py-32"><RevealOnScroll><div className="mx-auto grid max-w-[1500px] gap-14 lg:grid-cols-[1.05fr_0.95fr]"><div><p className="text-[10px] font-bold uppercase tracking-[0.4em] text-[#9F7F36]">Confezionamento, Private Label e MOQ</p><h2 className="mt-6 font-[family-name:var(--font-playfair)] text-[clamp(2.5rem,4.6vw,4.6rem)] font-semibold">Retail, professionale, sfuso e OEM <span className="block text-[#A97B22]">per programmi in Polonia</span></h2><p className="mt-7 text-[15px] leading-8 text-[#4C5F54]">I formati retail o professionali possono comprendere 100 g, 200 g, 500 g e 1 kg. I formati sfusi possono comprendere confezioni sottovuoto a doppio strato da 20 kg e 25 kg. Le opzioni commerciali includono fornitura sfusa all’ingrosso, OEM e Private Label, in base a prodotto, volume, materiali e fattibilità tecnica.</p><p className="mt-5 text-[15px] leading-8 text-[#4C5F54]">Il coordinamento può comprendere grafiche dell’acquirente, verifica di confezioni, etichette, sigilli e barriere all’umidità, codici a barre, dati di lotto, informazioni di prodotto, scatole, vasetti o buste e materiali sostenibili ove adatti. Non tutti i formati sono disponibili per ogni prodotto.</p><div className="mt-8 border border-[#C9A962] bg-[#173B2A] p-7 text-[#F5F0E6]"><p className="text-[10px] uppercase tracking-[0.3em] text-[#E4C878]">Quantità minima d’ordine</p><p className="mt-3 text-4xl font-semibold">200 kg per prodotto</p><p className="mt-3 text-sm text-white/65">Prodotti distinti non possono essere combinati automaticamente per raggiungere il MOQ di un singolo prodotto.</p></div></div><figure className="relative aspect-[3/2] overflow-hidden border border-[#C9A962]/35 bg-[#173B2A]"><Image src="/images/export/poland/poland-buyer-partnership.png" alt="Team polacco valuta buste, scatole, vasetti e confezioni sfuse sottovuoto" fill sizes="(min-width:1024px) 45vw, 100vw" className="object-cover object-center" /></figure></div></RevealOnScroll></section>
  <section className="px-6 py-24 sm:px-8 lg:px-12 lg:py-32"><RevealOnScroll><div className="mx-auto max-w-[1500px]"><div className="text-center"><p className="text-[10px] font-bold uppercase tracking-[0.4em] text-[#9F7F36]">Etichette, documenti e verifica dell’importatore</p><h2 className="mt-6 font-[family-name:var(--font-playfair)] text-[clamp(2.5rem,4.7vw,4.7rem)] font-semibold">Documentazione polacca <span className="block text-[#A97B22]">e coordinamento delle etichette</span></h2><p className="mx-auto mt-7 max-w-[900px] text-[15px] leading-8 text-[#4C5F54]">Layout in polacco, inglese o più lingue possono essere coordinati secondo il canale e i requisiti confermati. L’acquirente deve verificare informazioni finali, denominazioni legali, ingredienti, dichiarazioni, istruzioni, avvertenze, operatore responsabile, codici a barre e conformità.</p></div><Cards items={documents} columns="lg:grid-cols-3" /><aside className="mt-10 border border-[#C9A962]/40 bg-[#173B2A] p-7 text-sm leading-7 text-white/70">La documentazione è coordinata secondo prodotto, ordine e documenti disponibili. L’importatore o operatore responsabile resta responsabile di classificazione, etichette, dichiarazioni, registrazioni, autorizzazioni, dogana e requisiti polacchi e UE. Non sono garantiti approvazione normativa o sdoganamento.</aside></div></RevealOnScroll></section>
  <section className="bg-[#09271D] px-6 py-24 text-[#F5F0E6] sm:px-8 lg:px-12 lg:py-32"><RevealOnScroll><div className="mx-auto grid max-w-[1500px] gap-14 lg:grid-cols-[1.05fr_0.95fr]"><div><p className="text-[10px] font-bold uppercase tracking-[0.4em] text-[#E4C878]">Contesto logistico baltico e continentale</p><h2 className="mt-6 font-[family-name:var(--font-playfair)] text-[clamp(2.5rem,4.8vw,4.8rem)] font-semibold">Esportazione dall’India alla Polonia <span className="block text-[#E4C878]">e coordinamento del trasporto</span></h2><p className="mt-7 text-[16px] leading-8 text-white/70">La pianificazione può comprendere quantità confermate, imballaggio export, cartoni o pallet, documenti disponibili e coordinamento con spedizionieri incaricati secondo Incoterm o accordi commerciali. Trasporto marittimo o aereo possono essere valutati in base a volume, urgenza e movimentazione.</p><p className="mt-5 text-[15px] leading-8 text-white/65">Danzica o Gdynia possono offrire un contesto portuale baltico; si possono valutare altri porti europei con successivo trasporto stradale o ferroviario. Porti, vettori, rotte, programmi e reti dipendono dalle decisioni dell’acquirente e dello spedizioniere; non sono garantiti porto, rotta, transito, consegna, sdoganamento o risultato logistico.</p></div><figure className="relative aspect-[3/2] overflow-hidden border border-[#C9A962]/35 bg-[#071B14]"><Image src="/images/export/poland/india-to-poland-export-coordination.png" alt="Coordinamento delle spedizioni India–Polonia con porto baltico e distribuzione stradale e ferroviaria" fill sizes="(min-width:1024px) 45vw, 100vw" className="object-cover object-center" /></figure></div></RevealOnScroll></section>
  <section className="bg-[#EDE5D7] px-6 py-24 sm:px-8 lg:px-12 lg:py-32"><RevealOnScroll><div className="mx-auto max-w-[1500px]"><div className="text-center"><p className="text-[10px] font-bold uppercase tracking-[0.4em] text-[#9F7F36]">Sei fasi commerciali</p><h2 className="mt-6 font-[family-name:var(--font-playfair)] text-[clamp(2.5rem,4.7vw,4.7rem)] font-semibold">Dai requisiti dell’acquirente polacco <span className="block text-[#A97B22]">al coordinamento export</span></h2></div><Cards items={steps} columns="lg:grid-cols-3" /></div></RevealOnScroll></section>
  <section className="px-6 py-24 sm:px-8 lg:px-12 lg:py-32"><RevealOnScroll><div className="mx-auto max-w-[1280px]"><p className="text-[10px] font-bold uppercase tracking-[0.4em] text-[#9F7F36]">Principali località commerciali polacche</p><h2 className="mt-6 font-[family-name:var(--font-playfair)] text-[clamp(2.5rem,4.6vw,4.6rem)] font-semibold">Contesto di acquisto e distribuzione <span className="block text-[#A97B22]">in tutta la Polonia</span></h2><p className="mt-7 max-w-[900px] text-[15px] leading-8 text-[#4C5F54]">Queste località indicano possibili contesti commerciali e distributivi; non rappresentano sedi locali, scorte o rapporti garantiti.</p><Cards items={locations} /></div></RevealOnScroll></section>
  <section className="bg-[#EDE5D7] px-6 py-24 sm:px-8 lg:px-12 lg:py-32"><RevealOnScroll><div className="mx-auto max-w-[1120px]"><div className="text-center"><p className="text-[10px] font-bold uppercase tracking-[0.4em] text-[#9F7F36]">Domande degli acquirenti polacchi</p><h2 className="mt-6 font-[family-name:var(--font-playfair)] text-[clamp(2.4rem,4.4vw,4.4rem)] font-semibold">Domande frequenti sulla fornitura export in Polonia</h2></div><div className="mt-12 divide-y divide-[#173B2A]/15 border-y border-[#173B2A]/15">{faqs.map(f=><article key={f.question} className="grid gap-4 py-7 md:grid-cols-[0.8fr_1.2fr]"><h3 className="text-xl font-semibold">{f.question}</h3><p className="text-sm leading-7 text-[#4C5F54]">{f.answer}</p></article>)}</div></div></RevealOnScroll></section>
  <section className="relative overflow-hidden bg-[#071B14] px-6 py-24 text-center text-[#F5F0E6] sm:px-8 lg:px-12 lg:py-28"><GoldenParticles /><RevealOnScroll><div className="relative mx-auto max-w-[1000px]"><p className="text-[10px] uppercase tracking-[0.4em] text-[#E4C878]">Richieste degli acquirenti polacchi</p><h2 className="mt-6 font-[family-name:var(--font-playfair)] text-[clamp(2.5rem,4.8vw,4.8rem)] font-semibold">Parlateci delle vostre esigenze di prodotto per la Polonia</h2><p className="mx-auto mt-7 max-w-[800px] text-[16px] leading-8 text-white/65">Importatori, distributori, grossisti, aziende cosmetiche, fornitori per saloni, aziende erboristiche, acquirenti alimentari, confezionatori conto terzi e marchi Private Label possono comunicare prodotto, quantità, confezionamento, destinazione, uso e trasporto preferito.</p><div className="mt-9 flex flex-wrap justify-center gap-4"><Link href="/contact" className="border border-[#C9A962] bg-[#C9A962] px-8 py-4 text-[10px] font-bold uppercase tracking-[0.2em] text-[#102F23]">Invia i requisiti per la Polonia →</Link><Link href="/export/europe" className="border border-white/30 px-8 py-4 text-[10px] font-bold uppercase tracking-[0.2em]">Scopri i mercati europei →</Link></div><div className="mt-9 flex flex-wrap justify-center gap-5 text-[10px] uppercase text-white/45"><Link href="/export">Portale export</Link><Link href="/resources">Risorse per gli acquirenti</Link><Link href="/certifications">Certificazioni</Link><Link href="/infrastructure">Infrastruttura</Link><Link href="/about">Chi siamo</Link><Link href="/export/poland">Pagina export Polonia</Link></div></div></RevealOnScroll></section>
  <section className="bg-[#F5F0E6] px-6 py-24 sm:px-8 lg:px-12 lg:py-28"><RevealOnScroll><div className="mx-auto max-w-[1120px]"><p className="text-[10px] font-bold uppercase tracking-[0.4em] text-[#9F7F36]">Considerazioni pratiche sull’approvvigionamento</p><h2 className="mt-6 font-[family-name:var(--font-playfair)] text-[clamp(2.4rem,4.4vw,4.4rem)] font-semibold">Costruire un programma di fornitura per la Polonia <span className="block text-[#A97B22]">in base al canale effettivo dell’acquirente</span></h2><div className="mt-9 grid gap-8 text-[15px] font-light leading-8 text-[#4C5F54] md:grid-cols-2"><div><p>Una prima richiesta utile va oltre il nome del prodotto. Gli acquirenti polacchi dovrebbero indicare l’uso previsto, la qualità o specifica, il volume annuale o di prova, il formato, la destinazione e l’eventuale marchio dell’importatore. Queste informazioni distinguono le questioni tecniche da quelle di confezionamento, documentazione e trasporto.</p><p className="mt-5">Per henné, indigo e colorazioni botaniche, tonalità, finezza, presentazione e protezione della confezione possono influire sulla valutazione. Per le erbe vanno confermati identità botanica, uso e formato; per le spezie, tipo, forma intera o macinata, uso alimentare e specifiche. L’idoneità finale non può essere dedotta dalla sola categoria.</p><p className="mt-5">Una prova può iniziare con una categoria, mentre un distributore consolidato può pianificare più prodotti in formati retail e sfusi. Ogni prodotto mantiene un MOQ di 200 kg. Le previsioni aiutano la pianificazione, ma non costituiscono impegni finché ordine, specifiche, grafiche e condizioni non sono confermati per iscritto.</p></div><div><p>La preparazione Private Label richiede un controllo rigoroso delle grafiche. L’acquirente deve fornire o approvare denominazione legale, ingredienti, lingua, quantità netta, operatore responsabile, istruzioni, avvertenze, codice a barre e dichiarazioni. Shivesh International può coordinare il posizionamento, ma l’importatore deve convalidare le informazioni secondo i requisiti polacchi e UE.</p><p className="mt-5">La pianificazione del trasporto dovrebbe iniziare quando quantità e confezionamento sono chiari, poiché volume, peso, cartoni e urgenza influenzano le opzioni. Le spedizioni minori possono essere valutate per via aerea e quelle maggiori per mare con prosecuzione stradale o ferroviaria. Acquirente e spedizioniere devono confermare ingresso, dogana, rotta, assicurazione e consegna.</p><p className="mt-5">Prima dei riordini, gli acquirenti possono verificare vendite, scorte, tempi e modifiche alle confezioni. Un preavviso aiuta per nuove grafiche, confezioni multilingue o materiali. Modifiche a formule, nomi, dichiarazioni, etichette o requisiti vanno comunicate prima della produzione, favorendo preventivi chiari e programmi realistici.</p></div></div></div></RevealOnScroll></section>
  <aside className="bg-[#F5F0E6] px-6 pb-20 sm:px-8 lg:px-12"><p className="mx-auto max-w-[1120px] border-l-2 border-[#C9A962] pl-6 text-[15px] font-light leading-8 text-[#4C5F54]">Grossisti e titolari di marchi polacchi possono valutare l’introduzione della gamma in negozi specializzati, saloni, marketplace, e-commerce o distribuzione B2B. Gerarchia delle confezioni, quantità per cartone, posizionamento e riordino vanno discussi senza presumere l’accettazione del mercato. Acquisti, qualità, normativa, grafica e logistica devono concordare un unico requisito. Il controllo delle versioni è essenziale per testi polacchi e inglesi, più formati o categorie. File e ordine devono essere confermati per iscritto prima della produzione; ogni modifica successiva può influire su fattibilità, costi e tempi.</p></aside>
  <nav aria-label="Collegamenti ai prodotti per la Polonia" className="flex flex-wrap justify-center gap-6 bg-[#071B14] px-6 pb-10 text-[10px] font-bold uppercase tracking-[0.18em] text-[#E4C878]">{marketLinks.map(([label, href]) => <Link key={href} href={href}>{label}</Link>)}</nav>
  <style>{`@media (min-width: 1024px) { main > section:nth-of-type(5) h2, main > section:nth-of-type(7) h2 { font-size: 3.5rem; line-height: 1.08; } }`}</style>
  <FooterSection locale="it" /><FloatingContactButtons /><MagneticButtons /><PremiumCursor />
</main>; }
