/* eslint-disable react/no-unescaped-entities */
import type { Metadata } from "next";
import Image from "next/image";
import Link from "next/link";
import FloatingContactButtons from "@/app/components/FloatingContactButtons";
import GoldenParticles from "@/app/components/GoldenParticles";
import MagneticButtons from "@/app/components/MagneticButtons";
import Navbar from "@/app/components/Navbar";
import PremiumCursor from "@/app/components/PremiumCursor";
import RevealOnScroll from "@/app/components/RevealOnScroll";
import StaggerItem from "@/app/components/StaggerItem";
import FooterSection from "@/sections/FooterSection";

const canonicalUrl = "https://shiveshinternational.com/export/argentina";
const heroImage = "/images/export/argentina/argentina-natural-products-export-hero.png";
const keywordSubjects = ["natural products", "natural henna powder", "henna powder", "natural indigo powder", "indigo powder", "botanical hair colours", "henna hair colours", "henna-based hair colours", "Ayurvedic herbs", "Indian herbs", "herbal powders", "Indian spices", "botanical ingredients", "natural cosmetic ingredients", "private-label botanicals", "botanical hair colour", "bulk henna", "natural hair colour"];
const keywordIntents = ["exporter to Argentina", "supplier Argentina", "manufacturer India for Argentina", "bulk supplier Argentina", "private label Argentina", "supplier for Argentine importers", "supplier for Argentina distributors", "supplier for Argentine brands"];
const metadataKeywords = keywordSubjects.flatMap((subject) => keywordIntents.map((intent) => `${subject} ${intent}`)).filter((_, index) => index % 2 === 0);

export const metadata: Metadata = {
  title: { absolute: "Henna & Indigo Exporter to Argentina | Shivesh International" },
  description: "Source natural henna, indigo, botanical hair colours, Ayurvedic herbs and Indian spices for Argentina. Bulk and private-label supply from India. MOQ 200 kg per item.",
  keywords: metadataKeywords,
  alternates: { canonical: canonicalUrl },
  openGraph: { title: "Henna & Indigo Exporter to Argentina | Shivesh International", description: "Natural henna, indigo, botanical hair colours, Ayurvedic herbs and Indian spices for Argentina, with bulk and private-label supply from India.", url: canonicalUrl, type: "website", locale: "en_AR", siteName: "Shivesh International", images: [{ url: heroImage, alt: "Natural henna, indigo and herbal products supplied from India to Argentina" }] },
  twitter: { card: "summary_large_image", title: "Henna & Indigo Exporter to Argentina", description: "Bulk and private-label Indian natural-product supply for professional buyers in Argentina.", images: [heroImage] },
  robots: { index: true, follow: true, googleBot: { index: true, follow: true } },
};

const products = [
  ["Natural Henna Powder", "For Argentine cosmetic formulators, salon suppliers, natural hair-care brands, wholesalers and private-label buyers.", "/products/natural-henna-powder"],
  ["Natural Indigo Powder", "For botanical dark hair-colour systems and two-step henna-and-indigo applications for professional and retail channels.", "/products/natural-indigo-powder"],
  ["Natural Henna Hair Colors", "Botanical powder hair-colour options for brands, distributors, salons and retail supply across Argentina.", "/products/natural-henna-hair-colors"],
  ["Henna-Based Hair Colors", "Multiple shade options suitable for wholesale and private-label business requirements, subject to specification confirmation.", "/products/henna-based-hair-colors"],
  ["Ayurvedic Indian Herbs", "Herbal powders and raw herbs for natural wellness, cosmetic, personal-care and wholesale applications without medical claims.", "/products/ayurvedic-indian-herbs"],
  ["Indian Spices", "Whole, ground and blended Indian spices for Argentine importers, food distributors and wholesale buyers.", "/products/indian-spices"],
];
const buyers = [
  ["Importers and Distributors", "Align product selection, specifications, commercial quantities and packaging with national or regional distribution channels."],
  ["Private-Label Brands", "Coordinate feasible buyer-brand packaging, artwork, pack formats and product selection for an approved programme."],
  ["Cosmetic Ingredient Buyers", "Review henna, indigo and herbal powders according to the intended formulation, specification and classification."],
  ["Natural Hair-Care Companies", "Plan botanical colour ranges for retail, salon, professional and e-commerce channels."],
  ["Salon and Professional Suppliers", "Discuss professional pack sizes, retail formats and repeat bulk requirements for salon distribution."],
  ["Herbal Product Wholesalers", "Evaluate Indian herbal powders and raw herbs for appropriate cosmetic, personal-care and wholesale uses."],
  ["Spice Importers", "Plan whole, ground or blended spice supply around food-sector specifications and commercial volumes."],
  ["Retail and E-commerce Brands", "Select suitable products and packaging for physical retail, marketplaces and direct online channels."],
];
const documents = [
  ["Commercial Invoice", "Prepared for the confirmed buyer, products, quantities, values and agreed commercial terms."],
  ["Packing List", "May detail pack counts, net and gross weights, cartons or pallets and shipment references."],
  ["Certificate of Origin", "May be coordinated according to the product, shipment requirements and availability."],
  ["Transport Document", "A Bill of Lading or Air Waybill may be provided according to the confirmed mode and shipment."],
  ["Product and Quality Records", "A specification sheet, Certificate of Analysis or MSDS/SDS may be provided where applicable and available."],
  ["Other Agreed Documents", "A Non-GMO declaration or other mutually agreed export documents may be discussed where applicable."],
];
const steps = [
  ["Confirm Product and Specification", "Share the selected item, intended business use, specification and Argentina destination."],
  ["Review Quotation and Terms", "Align the commercial quantity, 200 kg per-item MOQ and applicable commercial terms."],
  ["Confirm Packaging", "Approve feasible bulk or private-label formats, artwork and label details before production."],
  ["Production and Quality Checks", "Proceed according to confirmed specifications, packaging feasibility and the agreed order."],
  ["Prepare Export Packing and Documents", "Coordinate export packing and the available product and shipment documentation."],
  ["Plan Dispatch", "Coordinate with the buyer's nominated freight forwarder, plan shipment from India and share dispatch documents."],
];
const strengths = [
  ["Established Experience", "Product, sourcing and export experience supports practical discussions with professional buyers."],
  ["Manufacturing Support", "Certified manufacturing support and a raw-material sourcing network underpin selected product programmes."],
  ["Consistent Specifications", "Orders are planned around confirmed product specifications, packaging and commercial requirements."],
  ["Bulk and Private Label", "Wholesale, retail-ready and buyer-brand formats can be discussed according to feasibility."],
  ["Packaging Options", "Multiple retail and bulk formats support different distribution, repacking and manufacturing channels."],
  ["Documentation Support", "Applicable and available product and export records can be coordinated for the confirmed shipment."],
  ["Shipment Coordination", "Dispatch planning can be aligned with the buyer's nominated freight forwarder or logistics partner."],
  ["Buyer-Focused Communication", "Each enquiry is reviewed around the product, specification, pack format, destination and order volume."],
];
const faqs = [
  { question: "Does Shivesh International export henna powder to Argentina?", answer: "Shivesh International accepts Argentina enquiries for natural henna powder and coordinates confirmed bulk or private-label orders from India subject to product, commercial and shipment requirements." },
  { question: "What products can Argentina buyers source?", answer: "Buyers can discuss natural henna powder, natural indigo powder, natural henna hair colors, henna-based hair colors, Ayurvedic Indian herbs and Indian spices." },
  { question: "What is the minimum order quantity?", answer: "The minimum order quantity is 200 kg per selected product or item. Mixed product planning may be discussed separately, but products cannot automatically be combined to meet one item's MOQ." },
  { question: "Is private-label packaging available?", answer: "Private-label packaging may be coordinated for suitable products and orders, including buyer-brand artwork and retail-ready formats, subject to material, print, product and quantity feasibility." },
  { question: "Which retail and bulk packaging sizes are available?", answer: "Retail or private-label formats may include 100 g, 200 g, 500 g and 1 kg. Bulk formats may include 20 kg and 25 kg, with double-layer vacuum packaging where applicable." },
  { question: "Can buyers order henna and indigo for botanical hair-colour products?", answer: "Yes. Argentina buyers can discuss henna and indigo for botanical hair-colour systems, including two-step applications, subject to specification and intended-use review." },
  { question: "What export documents may be provided?", answer: "Documents may include a commercial invoice, packing list, certificate of origin, Bill of Lading or Air Waybill, specification sheet, and COA, MSDS/SDS, Non-GMO declaration or other agreed records where applicable and available." },
  { question: "How are shipments from India to Argentina coordinated?", answer: "After order and packing confirmation, dispatch may be coordinated with the buyer's nominated freight forwarder or logistics partner for Buenos Aires or another buyer-nominated feasible destination. Freight, customs clearance, transit time and delivery are not guaranteed." },
  { question: "Can product specifications and packaging be customized?", answer: "Specifications and packaging requirements can be reviewed for feasibility. Final configuration depends on the selected product, pack size, artwork, materials and order quantity." },
  { question: "What must the Argentina importer confirm before ordering?", answer: "The importer or its qualified adviser must confirm local import, registration, labelling, product classification, customs and regulatory requirements for the exact product before ordering and shipment." },
];
const structuredData = { "@context": "https://schema.org", "@graph": [
  { "@type": "WebPage", "@id": `${canonicalUrl}#webpage`, url: canonicalUrl, name: "Henna & Indigo Exporter to Argentina", description: "Argentina-focused supply of natural henna, indigo, botanical hair colours, Ayurvedic herbs and Indian spices from India.", isPartOf: { "@id": "https://shiveshinternational.com/#website" }, about: { "@id": "https://shiveshinternational.com/#organization" }, breadcrumb: { "@id": `${canonicalUrl}#breadcrumb` }, primaryImageOfPage: { "@type": "ImageObject", url: heroImage }, inLanguage: "en" },
  { "@type": "BreadcrumbList", "@id": `${canonicalUrl}#breadcrumb`, itemListElement: [{ "@type": "ListItem", position: 1, name: "Home", item: "https://shiveshinternational.com/" }, { "@type": "ListItem", position: 2, name: "Export", item: "https://shiveshinternational.com/export" }, { "@type": "ListItem", position: 3, name: "Argentina", item: canonicalUrl }] },
] };
const faqStructuredData = { "@context": "https://schema.org", "@type": "FAQPage", "@id": `${canonicalUrl}#faq`, mainEntity: faqs.map((faq) => ({ "@type": "Question", name: faq.question, acceptedAnswer: { "@type": "Answer", text: faq.answer } })) };

const Cards = ({ items, columns = "lg:grid-cols-4" }: { items: string[][]; columns?: string }) => <div className={`mt-14 grid auto-rows-fr gap-5 sm:grid-cols-2 ${columns}`}>{items.map(([title, text]) => <article key={title} className="h-full border border-[#173B2A]/12 bg-[#FBF8F1] p-7 sm:p-8"><span className="block h-px w-12 bg-[#C9A962]" /><h3 className="mt-5 font-[family-name:var(--font-playfair)] text-2xl font-semibold">{title}</h3><p className="mt-4 text-[14px] font-light leading-7 text-[#4C5F54]">{text}</p></article>)}</div>;

export default function ArgentinaExportPage() { return <main className="min-h-screen overflow-x-hidden bg-[#F5F0E6] text-[#173B2A]">
  <script type="application/ld+json" dangerouslySetInnerHTML={{ __html: JSON.stringify(structuredData).replace(/</g, "\\u003c") }} /><script type="application/ld+json" dangerouslySetInnerHTML={{ __html: JSON.stringify(faqStructuredData).replace(/</g, "\\u003c") }} /><Navbar />
  <section className="relative isolate overflow-hidden bg-[#173B2A]"><Image src={heroImage} alt="Natural henna, indigo and herbal products supplied from India to Argentina" fill priority sizes="100vw" className="object-cover object-center" /><div className="absolute inset-0 bg-gradient-to-r from-[#061711]/76 via-[#102F23]/48 to-[#071B14]/15" /><GoldenParticles /><div className="relative z-10 flex items-center px-6 pb-20 pt-32 sm:px-8 sm:pb-24 sm:pt-36 lg:px-12 lg:pb-28 lg:pt-40"><div className="w-full max-w-[940px]"><StaggerItem delay={0}><p className="text-[10px] font-bold uppercase tracking-[0.38em] text-[#E4C878] sm:text-xs">India to Argentina B2B Supply</p></StaggerItem><StaggerItem delay={100}><h1 className="mt-5 font-[family-name:var(--font-playfair)] text-4xl font-medium leading-[1.02] tracking-[-0.04em] text-[#F5F0E6] sm:text-5xl lg:text-6xl xl:text-[66px]">Natural Henna, Indigo, Herbs &amp; Spices <span className="block bg-gradient-to-r from-[#F5F0E6] via-[#E4C878] to-[#C9A962] bg-clip-text text-transparent">Exporter to Argentina</span></h1></StaggerItem><StaggerItem delay={200}><p className="mt-5 max-w-[780px] text-[16px] font-light leading-7 text-[#F5F0E6]/82 sm:text-[17px] sm:leading-8">Shivesh International supplies natural henna powder, indigo powder, botanical hair colours, Ayurvedic herbs and Indian spices to importers, distributors, private-label brands and wholesale buyers across Argentina.</p></StaggerItem><StaggerItem delay={300}><div className="mt-7 flex flex-wrap gap-4"><Link href="/contact" className="inline-flex items-center gap-4 border border-[#C9A962] bg-[#C9A962] px-7 py-4 text-[10px] font-bold uppercase tracking-[0.2em] text-[#102F23]">Send Argentina Inquiry <span>→</span></Link><a href="#products" className="inline-flex items-center gap-4 border border-[#F5F0E6]/30 bg-[#102F23]/40 px-7 py-4 text-[10px] font-bold uppercase tracking-[0.2em] text-[#F5F0E6] backdrop-blur-lg">Explore Export Products <span>↓</span></a></div></StaggerItem><StaggerItem delay={400}><div className="mt-10 grid max-w-[780px] grid-cols-2 gap-3 lg:grid-cols-4">{[["200 kg","MOQ per item"],["Bulk","Wholesale supply"],["Private Label","Buyer-brand packs"],["Export","Document support"]].map(([v,l])=><div key={l} className="border border-white/15 bg-black/20 px-4 py-4 backdrop-blur-md"><p className="font-[family-name:var(--font-playfair)] text-xl font-semibold text-[#E4C878]">{v}</p><p className="mt-2 text-[9px] font-bold uppercase tracking-[0.22em] text-[#F5F0E6]/55">{l}</p></div>)}</div></StaggerItem></div></div></section>
  <section className="px-6 py-24 sm:px-8 lg:px-12 lg:py-32"><RevealOnScroll><div className="mx-auto max-w-[1120px]"><p className="text-[10px] font-bold uppercase tracking-[0.4em] text-[#9F7F36]">Argentina Market Supply</p><h2 className="mt-6 font-[family-name:var(--font-playfair)] text-[clamp(2.5rem,4.6vw,4.6rem)] font-semibold leading-[1.04]">Natural Product Supply <span className="block text-[#A97B22]">for Buyers Across Argentina</span></h2><p className="mt-7 text-[16px] font-light leading-8 text-[#4C5F54]">Argentina-based importers, distributors, natural hair-colour brands, cosmetic raw-material buyers, Ayurvedic product businesses, salon suppliers, wholesalers and spice distributors can discuss plant-based hair colouring, natural cosmetic ingredients, herbal powders, private-label botanical products, Indian herbs and whole or ground Indian spices.</p><p className="mt-5 text-[15px] font-light leading-8 text-[#4C5F54]">Buyers in Buenos Aires, Córdoba, Rosario, Mendoza, La Plata and other commercial regions can plan supply around their channel, specification, order volume and preferred packaging. These market references do not imply that Shivesh International has offices, warehouses, local stock, representatives or exclusive distributors in Argentina.</p></div></RevealOnScroll></section>
  <section id="products" className="scroll-mt-24 bg-[#EDE5D7] px-6 py-24 sm:px-8 lg:px-12 lg:py-32"><RevealOnScroll><div className="mx-auto max-w-[1500px]"><div className="text-center"><p className="text-[10px] font-bold uppercase tracking-[0.4em] text-[#9F7F36]">Six Commercial Categories</p><h2 className="mt-6 font-[family-name:var(--font-playfair)] text-[clamp(2.5rem,4.8vw,4.8rem)] font-semibold">Suitable Products <span className="block text-[#A97B22]">for Argentina</span></h2></div><div className="mt-14 grid auto-rows-fr gap-5 sm:grid-cols-2 lg:grid-cols-3">{products.map(([title,text,href],i)=><article key={title} className="flex h-full min-h-[290px] flex-col border border-[#173B2A]/12 bg-[#FBF8F1] p-7"><span className="text-4xl text-[#C9A962]">{String(i+1).padStart(2,"0")}</span><h3 className="mt-5 font-[family-name:var(--font-playfair)] text-2xl font-semibold">{title}</h3><p className="mt-4 flex-1 text-sm leading-7 text-[#4C5F54]">{text}</p><Link href={href} className="mt-6 text-[10px] font-bold uppercase tracking-[0.2em] text-[#A97B22]">Explore {title} →</Link></article>)}</div></div></RevealOnScroll></section>
  <section className="px-6 py-24 sm:px-8 lg:px-12 lg:py-32"><RevealOnScroll><div className="mx-auto max-w-[1500px]"><div className="text-center"><p className="text-[10px] font-bold uppercase tracking-[0.4em] text-[#9F7F36]">Argentina Buyer Profiles</p><h2 className="mt-6 font-[family-name:var(--font-playfair)] text-[clamp(2.5rem,4.7vw,4.7rem)] font-semibold">Who We Supply <span className="block text-[#A97B22]">in Argentina</span></h2></div><Cards items={buyers} /></div></RevealOnScroll></section>
  <section className="bg-[#EDE5D7] px-6 py-24 sm:px-8 lg:px-12 lg:py-32"><RevealOnScroll><div className="mx-auto grid max-w-[1500px] gap-14 lg:grid-cols-[1.08fr_0.92fr]"><div><p className="text-[10px] font-bold uppercase tracking-[0.4em] text-[#9F7F36]">Packaging and Private Label</p><h2 className="mt-6 font-[family-name:var(--font-playfair)] text-[clamp(2.5rem,4.3vw,4.3rem)] font-semibold">Bulk, Retail and <span className="block text-[#A97B22]">Private-Label Packaging</span></h2><p className="mt-7 text-[15px] leading-8 text-[#4C5F54]">Retail or private-label formats may include 100 g, 200 g, 500 g and 1 kg. Bulk formats may include 20 kg and 25 kg, with double-layer vacuum bulk packaging where applicable. Silver and gold metallized pouches, buyer-brand packaging, retail-ready packs and bulk packs for repacking or manufacturing can be discussed.</p><p className="mt-5 text-[15px] leading-8 text-[#4C5F54]">Label and artwork coordination is available for feasible programmes. Packaging specifications are confirmed according to the product, pack size, material, print method, artwork, order volume and technical requirements; not every packaging material or format is available for every product.</p><div className="mt-8 border border-[#C9A962] bg-[#173B2A] p-7 text-[#F5F0E6]"><p className="text-[10px] uppercase tracking-[0.3em] text-[#E4C878]">Minimum Order Quantity</p><p className="mt-3 text-3xl font-semibold sm:text-4xl">200 kg per item</p><p className="mt-3 text-sm leading-7 text-white/65">The MOQ applies per selected product or item. Mixed product planning may be discussed separately. Final packing depends on the product, pack size, artwork and order quantity.</p></div></div><figure className="relative aspect-[3/2] overflow-hidden border border-[#C9A962]/35 bg-[#173B2A]"><Image src="/images/export/argentina/argentina-private-label-henna-indigo-buyers.png" alt="Argentina buyers reviewing private-label henna and botanical product packaging" fill sizes="(min-width:1024px) 45vw, 100vw" className="object-cover object-center" /></figure></div></RevealOnScroll></section>
  <section className="px-6 py-24 sm:px-8 lg:px-12 lg:py-32"><RevealOnScroll><div className="mx-auto max-w-[1500px]"><div className="text-center"><p className="text-[10px] font-bold uppercase tracking-[0.4em] text-[#9F7F36]">Product and Shipment Records</p><h2 className="mt-6 font-[family-name:var(--font-playfair)] text-[clamp(2rem,4.7vw,4.7rem)] font-semibold">Export Documentation <span className="block text-[#A97B22]">Support</span></h2><p className="mx-auto mt-7 max-w-[950px] text-[15px] leading-8 text-[#4C5F54]">Documents are prepared according to the confirmed product, shipment, commercial terms, buyer requirements and availability. Government, laboratory, organic, phytosanitary, health, free-sale or legalized documents are not presented as automatically available.</p></div><Cards items={documents} columns="lg:grid-cols-3" /><aside className="mt-10 border border-[#C9A962]/40 bg-[#173B2A] p-7 text-sm leading-7 text-white/70">The Argentina importer or buyer is responsible for confirming applicable local import, registration, labelling, product classification, customs and regulatory requirements before ordering. Shivesh International does not provide Argentine legal or customs advice and does not guarantee import approval or customs clearance.</aside></div></RevealOnScroll></section>
  <section className="bg-[#09271D] px-6 py-24 text-[#F5F0E6] sm:px-8 lg:px-12 lg:py-32"><RevealOnScroll><div className="mx-auto grid max-w-[1500px] gap-14 lg:grid-cols-[1.08fr_0.92fr]"><div><p className="text-[10px] font-bold uppercase tracking-[0.4em] text-[#E4C878]">India-to-Argentina Logistics</p><h2 className="mt-6 font-[family-name:var(--font-playfair)] text-[clamp(2.5rem,4.5vw,4.5rem)] font-semibold">India to Argentina <span className="block text-[#E4C878]">Export Coordination</span></h2><p className="mt-7 text-[16px] leading-8 text-white/70">The workflow covers product and specification confirmation, quotation and commercial terms, packaging or private-label confirmation, production and quality checks, export packing, documentation preparation, coordination with the buyer's nominated freight forwarder or logistics partner, shipment planning from India, dispatch and document sharing.</p><p className="mt-5 text-[15px] leading-8 text-white/65">Buenos Aires or another buyer-nominated feasible cargo destination or port may be considered according to the order and current logistics options. Freight rates, carrier schedules, routes, transit times, customs clearance, import approval and delivery dates are not promised or guaranteed.</p></div><figure className="relative aspect-[3/2] overflow-hidden border border-[#C9A962]/35 bg-[#071B14]"><Image src="/images/export/argentina/india-to-argentina-export-coordination.png" alt="Export coordination for natural products shipped from India to Argentina" fill sizes="(min-width:1024px) 45vw, 100vw" className="object-cover object-center" /></figure></div></RevealOnScroll></section>
  <section className="bg-[#EDE5D7] px-6 py-24 sm:px-8 lg:px-12 lg:py-32"><RevealOnScroll><div className="mx-auto max-w-[1500px]"><div className="text-center"><p className="text-[10px] font-bold uppercase tracking-[0.4em] text-[#9F7F36]">Six Commercial Steps</p><h2 className="mt-6 font-[family-name:var(--font-playfair)] text-[clamp(2.5rem,4.7vw,4.7rem)] font-semibold">From Argentina Inquiry <span className="block text-[#A97B22]">to Coordinated Dispatch</span></h2></div><Cards items={steps} columns="lg:grid-cols-3" /></div></RevealOnScroll></section>
  <section className="px-6 py-24 sm:px-8 lg:px-12 lg:py-32"><RevealOnScroll><div className="mx-auto max-w-[1500px]"><div className="text-center"><p className="text-[10px] font-bold uppercase tracking-[0.4em] text-[#9F7F36]">Professional Export Supply</p><h2 className="mt-6 font-[family-name:var(--font-playfair)] text-[clamp(2.5rem,4.7vw,4.7rem)] font-semibold">Why Argentina Buyers Choose <span className="block text-[#A97B22]">Shivesh International</span></h2></div><Cards items={strengths} /></div></RevealOnScroll></section>
  <section className="bg-[#EDE5D7] px-6 py-24 sm:px-8 lg:px-12 lg:py-32"><RevealOnScroll><div className="mx-auto max-w-[1120px]"><div className="text-center"><p className="text-[10px] font-bold uppercase tracking-[0.4em] text-[#9F7F36]">Argentina Buyer Questions</p><h2 className="mt-6 font-[family-name:var(--font-playfair)] text-[clamp(2.4rem,4.4vw,4.4rem)] font-semibold">Argentina Export Supply FAQ</h2></div><div className="mt-12 divide-y divide-[#173B2A]/15 border-y border-[#173B2A]/15">{faqs.map(f=><article key={f.question} className="grid gap-4 py-7 md:grid-cols-[0.8fr_1.2fr]"><h3 className="text-xl font-semibold">{f.question}</h3><p className="text-sm leading-7 text-[#4C5F54]">{f.answer}</p></article>)}</div></div></RevealOnScroll></section>
  <section className="relative overflow-hidden bg-[#071B14] px-6 py-24 text-center text-[#F5F0E6] sm:px-8 lg:px-12 lg:py-28"><GoldenParticles /><RevealOnScroll><div className="relative mx-auto max-w-[1000px]"><p className="text-[10px] uppercase tracking-[0.4em] text-[#E4C878]">Argentina Buyer Enquiries</p><h2 className="mt-6 font-[family-name:var(--font-playfair)] text-[clamp(2.5rem,4.8vw,4.8rem)] font-semibold">Source Natural Indian Products for Argentina</h2><p className="mx-auto mt-7 max-w-[820px] text-[16px] leading-8 text-white/65">Tell us your required product, specification, packaging format and order quantity. Our team will review your Argentina inquiry and provide the relevant commercial and export information.</p><div className="mt-9 flex flex-wrap justify-center gap-4"><Link href="/contact" className="border border-[#C9A962] bg-[#C9A962] px-8 py-4 text-[10px] font-bold uppercase tracking-[0.2em] text-[#102F23]">Request Export Quotation →</Link><Link href="/export" className="border border-white/30 px-8 py-4 text-[10px] font-bold uppercase tracking-[0.2em]">Explore Global Markets →</Link></div></div></RevealOnScroll></section>
  <nav aria-label="Argentina product shortcuts" className="flex flex-wrap justify-center gap-6 bg-[#071B14] px-6 pb-10 text-[10px] font-bold uppercase tracking-[0.18em] text-[#E4C878]">{products.map(([label,,href]) => <Link key={href} href={href}>{label}</Link>)}</nav>
  <FooterSection /><FloatingContactButtons /><MagneticButtons /><PremiumCursor />
</main>; }
