import type { Metadata } from "next";
import Image from "next/image";
import Link from "next/link";

import FloatingContactButtons from "@/app/components/FloatingContactButtons";
import GoldenParticles from "@/app/components/GoldenParticles";
import MagneticButtons from "@/app/components/MagneticButtons";
import Navbar from "@/app/components/Navbar";
import PremiumCursor from "@/app/components/PremiumCursor";
import RevealOnScroll from "@/app/components/RevealOnScroll";
import StaggerItem from "@/app/components/StaggerItem";
import { franceLanguageAlternates } from "@/app/lib/i18n";
import FooterSection from "@/sections/FooterSection";

const pageUrl = "https://shiveshinternational.com/es/export/francia";
const heroImage = `${pageUrl.split("/es/export/francia")[0]}/images/export/france/france-botanical-beauty-atelier-hero-premium-v1.png`;

export const metadata: Metadata = {
  title: "Exportador de productos naturales a Francia",
  description: "Henna, índigo, coloración vegetal, plantas ayurvédicas y especias para importadores, mayoristas, OEM y marcas privadas en Francia. MOQ de 200 kg por artículo.",
  keywords: [
    "exportador de productos naturales a Francia", "fabricante de henna para Francia", "proveedor de henna natural", "henna al por mayor Francia", "exportador de índigo natural", "proveedor de índigo natural", "proveedor de coloración vegetal", "proveedor de coloración capilar botánica", "proveedor para salones profesionales", "proveedor de cosmética natural", "importadores en Francia", "distribuidores en Francia", "mayoristas en Francia", "minoristas especializados", "marca propia", "Private Label", "OEM", "suministro a granel", "proveedor de plantas ayurvédicas", "exportador de plantas ayurvédicas", "proveedor de especias indias", "exportador de especias indias", "aprovisionamiento B2B Francia", "fabricante de productos naturales para Francia", "proveedor indio para marcas de cosmética francesas", "envasado de productos naturales Francia", "etiquetado para marca privada Francia", "exportación India Francia", "coloración natural con henna Francia", "Shivesh International Francia",
  ],
  alternates: { canonical: pageUrl, languages: franceLanguageAlternates },
  openGraph: {
    title: "Suministro de productos naturales para Francia",
    description: "Suministro a granel, mayorista, OEM y Private Label de henna, índigo, coloración capilar botánica, plantas ayurvédicas y especias de la India para compradores profesionales en Francia.",
    url: pageUrl,
    type: "website",
    locale: "es_ES",
    siteName: "Shivesh International",
    images: [{ url: "/images/export/france/france-botanical-beauty-atelier-hero-premium-v1.png", width: 1536, height: 1024, alt: "Compradores franceses de cosmética natural y un exportador indio desarrollando productos botánicos en un atelier de París" }],
  },
  twitter: {
    card: "summary_large_image",
    title: "Suministro de productos naturales para Francia",
    description: "Proveedor indio de henna, índigo, coloración vegetal, plantas y especias para importadores y marcas privadas en Francia.",
    images: ["/images/export/france/france-botanical-beauty-atelier-hero-premium-v1.png"],
  },
  robots: { index: true, follow: true, googleBot: { index: true, follow: true, "max-image-preview": "large", "max-snippet": -1, "max-video-preview": -1 } },
};

const products = [
  { number: "01", title: "Henna natural en polvo", description: "Henna finamente procesada para importadores franceses, marcas de cosmética natural y canales profesionales, con grado, especificaciones y envasado acordados para cada pedido.", href: "/products/natural-henna-powder" },
  { number: "02", title: "Índigo natural en polvo", description: "Índigo botánico para programas comerciales de coloración capilar, disponible en formatos a granel, profesionales y con marca del comprador tras su revisión.", href: "/products/natural-indigo-powder" },
  { number: "03", title: "Coloraciones capilares naturales con henna", description: "Una cuidada gama de coloración vegetal para distribuidores franceses, proveedores de salones y marcas de cuidado capilar natural que desarrollan líneas profesionales o minoristas.", href: "/products/natural-henna-hair-colors" },
  { number: "04", title: "Coloraciones capilares a base de henna", description: "Productos de coloración a base de henna para gamas de marca propia, sujetos a la fórmula, el uso previsto, el envase y la viabilidad comercial.", href: "/products/henna-based-hair-colors" },
  { number: "05", title: "Plantas ayurvédicas de la India", description: "Plantas ayurvédicas y polvos botánicos seleccionados para programas de aprovisionamiento de bienestar, cuidado personal y comercio especializado en Francia.", href: "/products/ayurvedic-indian-herbs" },
  { number: "06", title: "Especias de la India", description: "Especias indias enteras y molidas seleccionadas para importadores, mayoristas, cadenas minoristas y empresas alimentarias francesas pertinentes.", href: "/products/indian-spices" },
];

const buyerTypes = ["Importadores", "Distribuidores", "Mayoristas", "Marcas de cosmética natural", "Marcas de cuidado capilar botánico", "Proveedores de salones profesionales", "Empresas ayurvédicas", "Cadenas minoristas", "Empresas de bienestar", "Compradores OEM", "Compradores a granel", "Compradores de marca privada"];
const supplyServices = [
  { title: "Suministro a granel y al por mayor", text: "Las cantidades comerciales para importadores, distribuidores y mayoristas en Francia pueden planificarse en formatos a granel, profesionales o minoristas seleccionados. El MOQ es de 200 kg por artículo." },
  { title: "OEM y Private Label", text: "Las marcas de cosmética natural, cuidado capilar botánico y bienestar pueden estudiar programas OEM o de marca privada para productos seleccionados, sujetos a la viabilidad del producto y la producción." },
  { title: "Envasado personalizado", text: "Podemos coordinar bolsas, cajas, tarros y presentaciones con la marca del comprador para pedidos viables. Los diseños aportados por el comprador quedan sujetos a revisión material, técnica y de impresión." },
  { title: "Especificaciones y documentación", text: "Las especificaciones disponibles y la documentación comercial pertinente se revisan según el artículo seleccionado, el uso previsto y la operación confirmada." },
];
const process = [
  { step: "01", title: "Revisión del producto y la cantidad", text: "La consulta para Francia comienza con el producto, el canal previsto, el grado, la cantidad y el pedido mínimo de 200 kg por artículo." },
  { step: "02", title: "Especificaciones y muestras", text: "Se analizan con el comprador las especificaciones disponibles, el uso previsto, las opciones de envasado y las muestras comercialmente viables." },
  { step: "03", title: "Oferta y condiciones comerciales", text: "La oferta recoge el alcance confirmado, los precios, las condiciones de pago, el envasado y los términos comerciales de envío aplicables." },
  { step: "04", title: "Coordinación del envase y el diseño", text: "La presentación minorista, profesional, a granel o de marca privada se revisa junto con el diseño del comprador según la viabilidad técnica, material y de impresión." },
  { step: "05", title: "Producción y control de calidad", text: "Los productos confirmados se procesan, envasan y revisan conforme a las especificaciones y los requisitos acordados para el pedido." },
  { step: "06", title: "Documentación de exportación y expedición", text: "Los documentos comerciales, la información de embalaje y la planificación de la expedición desde la India se coordinan conforme a las condiciones comerciales confirmadas." },
];
const faqs = [
  { question: "¿Qué categorías de productos pueden adquirir los compradores franceses?", answer: "La gama incluye henna natural en polvo, índigo natural en polvo, coloraciones capilares naturales con henna, coloraciones a base de henna, plantas ayurvédicas de la India y especias indias seleccionadas. La disponibilidad y la idoneidad se revisan en cada consulta." },
  { question: "¿Cuál es el MOQ para los pedidos de exportación a Francia?", answer: "El pedido mínimo es de 200 kg por artículo. Las cantidades finales y las configuraciones de envasado dependen del producto, el formato y el alcance comercial confirmados." },
  { question: "¿Qué tipos de compradores franceses pueden realizar consultas?", answer: "Atendemos consultas pertinentes de importadores, distribuidores, mayoristas, marcas de cosmética natural y cuidado capilar botánico, proveedores de salones, empresas ayurvédicas y de bienestar, cadenas minoristas, compradores OEM y marcas privadas." },
  { question: "¿Ofrecen suministro a granel y al por mayor para Francia?", answer: "Sí. Los productos viables pueden prepararse para suministro a granel y al por mayor en envases industriales acordados, formatos profesionales o presentaciones minoristas seleccionadas." },
  { question: "¿Pueden las marcas francesas solicitar envasado OEM o Private Label?", answer: "Puede estudiarse el apoyo OEM y de marca privada para productos seleccionados. Los formatos de envase, la presentación de la marca del comprador y las cantidades solo se confirman tras una revisión técnica y comercial." },
  { question: "¿Se pueden utilizar diseños del comprador y bolsas metalizadas?", answer: "Los diseños del comprador pueden revisarse para bolsas metalizadas doradas o plateadas, formatos kraft, cajas, tarros y otros envases viables. Los requisitos de material, troquel, impresión, idioma y cantidad quedan sujetos a aprobación." },
  { question: "¿Disponen de especificaciones, documentos y muestras?", answer: "Las especificaciones disponibles y los documentos comerciales pertinentes se estudian para el producto y la operación elegidos. Pueden organizarse muestras cuando resulte comercialmente viable; su disponibilidad o idoneidad no es automática." },
  { question: "¿Quién confirma los requisitos de importación franceses y de la UE?", answer: "El importador o comprador francés es responsable de confirmar la clasificación, el uso previsto, los requisitos aplicables en Francia y la Unión Europea, la importación, el despacho de aduanas, el registro o la notificación cuando proceda, el etiquetado, el idioma, la declaración de ingredientes, las alegaciones y las obligaciones de comercialización." },
];

const structuredData = { "@context": "https://schema.org", "@graph": [
  { "@type": "WebPage", "@id": `${pageUrl}#webpage`, url: pageUrl, name: "Suministro de productos naturales para Francia", description: "Información en español para el mercado francés sobre suministro a granel, mayorista, OEM y de marca privada de henna, índigo, coloración vegetal, plantas ayurvédicas y especias de la India.", isPartOf: { "@id": "https://shiveshinternational.com/#website" }, about: { "@id": "https://shiveshinternational.com/#organization" }, breadcrumb: { "@id": `${pageUrl}#breadcrumb` }, primaryImageOfPage: { "@type": "ImageObject", url: heroImage, width: 1536, height: 1024 }, inLanguage: "es" },
  { "@type": "Service", "@id": `${pageUrl}#service`, name: "Suministro de productos naturales de la India a Francia", serviceType: "Suministro de exportación a granel, mayorista, OEM y de marca privada", description: "Suministro comercial desde la India para importadores, distribuidores, mayoristas, proveedores de salones y marcas que abastecen el mercado francés.", url: pageUrl, provider: { "@id": "https://shiveshinternational.com/#organization" }, areaServed: { "@type": "Country", name: "Francia", sameAs: "https://www.wikidata.org/wiki/Q142" }, audience: { "@type": "BusinessAudience", audienceType: buyerTypes.join(", ") }, category: products.map((product) => product.title), termsOfService: "El pedido mínimo es de 200 kg por artículo. El producto, el envase, la documentación y las condiciones comerciales se confirman para cada necesidad del comprador." },
  { "@type": "BreadcrumbList", "@id": `${pageUrl}#breadcrumb`, itemListElement: [{ "@type": "ListItem", position: 1, name: "Inicio", item: "https://shiveshinternational.com/" }, { "@type": "ListItem", position: 2, name: "Exportación", item: "https://shiveshinternational.com/export" }, { "@type": "ListItem", position: 3, name: "Exportación a Francia", item: pageUrl }] },
  { "@type": "ItemList", "@id": `${pageUrl}#products`, name: "Productos naturales para compradores en Francia", numberOfItems: products.length, itemListElement: products.map((product, index) => ({ "@type": "ListItem", position: index + 1, name: product.title, url: `https://shiveshinternational.com${product.href}` })) },
] };
const faqStructuredData = { "@context": "https://schema.org", "@type": "FAQPage", "@id": `${pageUrl}#faq`, mainEntity: faqs.map((faq) => ({ "@type": "Question", name: faq.question, acceptedAnswer: { "@type": "Answer", text: faq.answer } })) };

export default function FranceExportPageSpanish() {
  return <main className="min-h-screen overflow-x-hidden bg-[#F5F0E6] text-[#173B2A]">
    <script type="application/ld+json" dangerouslySetInnerHTML={{ __html: JSON.stringify(structuredData).replace(/</g, "\\u003c") }} />
    <script type="application/ld+json" dangerouslySetInnerHTML={{ __html: JSON.stringify(faqStructuredData).replace(/</g, "\\u003c") }} />
    <Navbar />

    <section className="relative isolate overflow-hidden bg-[#071B14]">
      <Image src="/images/export/france/france-botanical-beauty-atelier-hero-premium-v1.png" alt="Compradores franceses de cosmética natural y un exportador indio desarrollando productos botánicos en un atelier de París" fill priority sizes="100vw" className="object-cover object-[90%_center]" />
      <div className="absolute inset-0 bg-gradient-to-r from-[#061711]/38 via-[#102F23]/18 to-transparent" /><div className="absolute inset-0 bg-gradient-to-t from-black/18 via-transparent to-black/[0.06]" /><GoldenParticles />
      <div className="relative z-10 flex items-center px-6 pb-20 pt-32 sm:px-8 sm:pb-24 sm:pt-36 lg:px-12 lg:pb-28 lg:pt-40"><div className="w-full max-w-[790px]">
        <StaggerItem delay={0}><div className="flex items-center gap-4"><span className="h-px w-14 bg-[#C9A962]" /><span className="text-[10px] font-bold uppercase tracking-[0.38em] text-[#E4C878] sm:text-xs">De la India a Francia</span></div></StaggerItem>
        <StaggerItem delay={100}><h1 className="mt-6 font-[family-name:var(--font-playfair)] text-[clamp(2.65rem,5.2vw,5.4rem)] font-medium leading-[1.02] tracking-[-0.04em] text-[#F5F0E6]">Suministro botánico desde la India<span className="mt-2 block bg-gradient-to-r from-[#F5F0E6] via-[#E4C878] to-[#C9A962] bg-clip-text text-transparent">para compradores en Francia</span></h1></StaggerItem>
        <StaggerItem delay={200}><p className="mt-7 max-w-[700px] text-[16px] font-light leading-8 text-[#F5F0E6]/80 sm:text-[18px]">Shivesh International colabora con compradores profesionales de toda Francia —desde París y Lyon hasta Marsella, Burdeos y Lille— en el aprovisionamiento a granel, al por mayor, OEM y Private Label de henna, índigo, coloración capilar botánica, plantas ayurvédicas y especias seleccionadas de la India.</p></StaggerItem>
        <StaggerItem delay={300}><div className="mt-9 flex flex-wrap gap-4"><a href="#gama-productos-francia" className="inline-flex items-center gap-4 border border-[#C9A962] bg-[#C9A962] px-7 py-4 text-[10px] font-bold uppercase tracking-[0.2em] text-[#102F23] transition-all duration-500 hover:-translate-y-1 hover:bg-[#E4C878]">Ver la gama <span>↓</span></a><Link href="/contact" className="inline-flex items-center border border-[#F5F0E6]/30 bg-[#102F23]/40 px-7 py-4 text-[10px] font-bold uppercase tracking-[0.2em] text-[#F5F0E6] backdrop-blur-lg transition-all duration-500 hover:border-[#C9A962] hover:text-[#E4C878]">Solicitar presupuesto para Francia</Link></div></StaggerItem>
        <StaggerItem delay={400}><div className="mt-10 grid max-w-[740px] gap-3 sm:grid-cols-2 lg:grid-cols-4">{[["200 kg", "MOQ por artículo"], ["A granel", "Suministro mayorista"], ["OEM", "Private Label"], ["Francia", "Consultas B2B"]].map(([value, label]) => <div key={label} className="border border-white/15 bg-black/20 px-4 py-4 backdrop-blur-md"><p className="font-[family-name:var(--font-playfair)] text-xl font-semibold text-[#E4C878]">{value}</p><p className="mt-2 text-[9px] font-bold uppercase tracking-[0.22em] text-[#F5F0E6]/55">{label}</p></div>)}</div></StaggerItem>
      </div></div>
    </section>

    <section id="gama-productos-francia" className="relative overflow-hidden px-6 py-24 sm:px-8 lg:px-12 lg:py-32"><RevealOnScroll><div className="mx-auto max-w-[1500px]">
      <div className="mx-auto max-w-[920px] text-center"><p className="text-[10px] font-bold uppercase tracking-[0.4em] text-[#9F7F36]">Seis categorías comerciales</p><h2 className="mt-6 font-[family-name:var(--font-playfair)] text-[clamp(2.4rem,4.6vw,4.8rem)] font-semibold leading-[1.04] tracking-[-0.035em]">Productos naturales de la India<span className="mt-1 block text-[#A97B22]">para el mercado francés</span></h2><p className="mx-auto mt-7 max-w-[820px] text-[16px] font-light leading-8 text-[#4C5F54] sm:text-[17px]">Una cartera de seis categorías para compradores profesionales que desarrollan gamas de cosmética natural, cuidado capilar botánico, salones, bienestar, alimentación y marca propia para Francia.</p></div>
      <div className="mt-14 grid gap-5 sm:grid-cols-2 lg:grid-cols-3">{products.map((product, index) => <StaggerItem key={product.title} delay={(index % 3) * 90}><article className="group flex h-full min-h-[300px] flex-col border border-[#173B2A]/12 bg-[#FBF8F1] p-7 shadow-[0_18px_45px_rgba(20,50,38,0.07)] transition-all duration-500 hover:-translate-y-2 hover:border-[#C9A962]/70 sm:p-8"><span className="font-[family-name:var(--font-playfair)] text-4xl font-semibold text-[#C9A962]/60">{product.number}</span><h3 className="mt-6 font-[family-name:var(--font-playfair)] text-[27px] font-semibold leading-tight">{product.title}</h3><p className="mt-5 flex-1 text-[14px] font-light leading-7 text-[#4C5F54]">{product.description}</p><Link href={product.href} className="mt-7 inline-flex items-center gap-3 text-[10px] font-bold uppercase tracking-[0.2em] text-[#A97B22]">Ver producto <span className="transition-transform group-hover:translate-x-2">→</span></Link></article></StaggerItem>)}</div>
    </div></RevealOnScroll></section>

    <section className="relative overflow-hidden bg-[#0B3325] px-6 py-24 text-[#F5F0E6] sm:px-8 lg:px-12 lg:py-32"><RevealOnScroll><div className="mx-auto grid max-w-[1500px] items-center gap-14 lg:grid-cols-[0.9fr_1.1fr] lg:gap-20"><div><p className="text-[10px] font-bold uppercase tracking-[0.4em] text-[#E4C878]">Pensado para compras profesionales</p><h2 className="mt-6 font-[family-name:var(--font-playfair)] text-[clamp(2.35rem,4.4vw,4.6rem)] font-semibold leading-[1.04]">Suministro estructurado para<span className="block text-[#E4C878]">canales comerciales en Francia</span></h2><p className="mt-7 text-[16px] font-light leading-8 text-[#F5F0E6]/68">Apoyamos a importadores, distribuidores, mayoristas, proveedores de salones, cadenas minoristas y marcas mediante una revisión comercial del uso previsto, las especificaciones, la cantidad, el envasado y la viabilidad del suministro.</p><div className="mt-8 flex flex-wrap gap-2">{buyerTypes.map((buyer) => <span key={buyer} className="border border-[#C9A962]/30 bg-white/[0.04] px-4 py-3 text-[9px] font-bold uppercase tracking-[0.18em] text-[#F5F0E6]/75">{buyer}</span>)}</div></div><div className="grid gap-5 sm:grid-cols-2">{supplyServices.map((service) => <article key={service.title} className="border border-[#C9A962]/25 bg-[#071B14]/55 p-7 sm:p-8"><span className="block h-px w-12 bg-[#C9A962]" /><h3 className="mt-6 font-[family-name:var(--font-playfair)] text-2xl font-semibold text-[#E4C878]">{service.title}</h3><p className="mt-4 text-[14px] font-light leading-7 text-[#F5F0E6]/65">{service.text}</p></article>)}</div></div></RevealOnScroll></section>

    <section className="px-6 py-24 sm:px-8 lg:px-12 lg:py-32"><RevealOnScroll><div className="mx-auto max-w-[1120px]"><div className="text-center"><p className="text-[10px] font-bold uppercase tracking-[0.4em] text-[#9F7F36]">Preguntas de compradores franceses</p><h2 className="mt-6 font-[family-name:var(--font-playfair)] text-[clamp(2.3rem,4.2vw,4.4rem)] font-semibold">Preguntas frecuentes sobre exportación a Francia</h2></div><div className="mt-12 divide-y divide-[#173B2A]/15 border-y border-[#173B2A]/15">{faqs.map((faq) => <article key={faq.question} className="grid gap-4 py-7 md:grid-cols-[0.8fr_1.2fr] md:gap-10"><h3 className="font-[family-name:var(--font-playfair)] text-xl font-semibold">{faq.question}</h3><p className="text-[14px] font-light leading-7 text-[#4C5F54]">{faq.answer}</p></article>)}</div></div></RevealOnScroll></section>

    <section className="px-6 py-24 sm:px-8 lg:px-12 lg:py-32"><RevealOnScroll><div className="mx-auto grid max-w-[1500px] items-center gap-14 lg:grid-cols-2 lg:gap-20"><div className="relative aspect-[4/3] overflow-hidden border border-[#C9A962]/35 bg-[#102F23] shadow-[0_28px_70px_rgba(20,50,38,0.18)]"><Image src="/images/export/france/france-private-label-colour-pouch-gallery-premium-v1.png" alt="Compradores franceses y un exportador indio revisando colores de bolsas y acabados para envases de marca privada" fill sizes="(min-width: 1024px) 50vw, 100vw" className="object-cover object-center" /><div className="absolute inset-0 bg-gradient-to-t from-[#071B14]/60 to-transparent" /></div><div><p className="text-[10px] font-bold uppercase tracking-[0.4em] text-[#9F7F36]">Desarrollo de la marca del comprador</p><h2 className="mt-6 font-[family-name:var(--font-playfair)] text-[clamp(2.35rem,4.35vw,4.6rem)] font-semibold leading-[1.04]">Programas de envasado para<span className="block text-[#A97B22]">canales minoristas y profesionales en Francia</span></h2><p className="mt-7 text-[16px] font-light leading-8 text-[#4C5F54]">Los compradores franceses pueden estudiar envases minoristas, formatos profesionales, suministro a granel, bolsas metalizadas doradas o plateadas cuando proceda, formatos kraft u otras opciones comercialmente viables, cajas, tarros y una presentación coordinada con su marca.</p><p className="mt-5 text-[14px] leading-7 text-[#4C5F54]">Los diseños aportados por el comprador quedan sujetos a viabilidad técnica, material y de impresión. El importador es responsable del etiquetado, el idioma, la declaración de ingredientes, las alegaciones y los requisitos de comercialización aplicables en Francia y la UE.</p><Link href="/contact" className="mt-8 inline-flex items-center gap-4 border border-[#C9A962] bg-[#C9A962] px-7 py-4 text-[10px] font-bold uppercase tracking-[0.2em] text-[#102F23] transition-all hover:-translate-y-1 hover:bg-[#D8BB68]">Consultar sobre marca privada <span>→</span></Link></div></div></RevealOnScroll></section>

    <section className="relative overflow-hidden bg-[#09271D] px-6 py-24 text-[#F5F0E6] sm:px-8 lg:px-12 lg:py-32"><div aria-hidden="true" className="pointer-events-none absolute -left-40 top-12 h-[460px] w-[460px] rounded-full bg-[#C9A962]/10 blur-[150px]" /><div aria-hidden="true" className="pointer-events-none absolute -right-48 bottom-10 h-[520px] w-[520px] rounded-full bg-[#C9A962]/[0.07] blur-[170px]" /><RevealOnScroll><div className="relative mx-auto max-w-[1500px]"><div className="grid items-center gap-12 lg:grid-cols-[0.9fr_1.1fr] lg:gap-16 xl:gap-20"><div><div className="flex items-center gap-4"><span className="h-px w-12 bg-[#C9A962]" /><p className="text-[10px] font-bold uppercase tracking-[0.4em] text-[#E4C878]">De la India a Francia</p></div><h2 className="mt-6 font-[family-name:var(--font-playfair)] text-[clamp(2.3rem,4.4vw,4.8rem)] font-semibold leading-[1.04]">Coordinación estructurada de exportación para compradores en Francia</h2><p className="mt-7 max-w-[720px] text-[16px] font-light leading-8 text-[#F5F0E6]/68 sm:text-[17px]">Cada consulta se coordina según el producto, la cantidad, las especificaciones, el envase, la documentación disponible y la planificación del envío desde la India conforme a las condiciones comerciales confirmadas.</p></div><figure className="relative aspect-[4/3] overflow-hidden border border-[#C9A962]/35 bg-[#071B14] shadow-[0_28px_75px_rgba(0,0,0,0.28)]"><Image src="/images/export/france/france-maritime-route-coordination-atelier-premium-v1.png" alt="Coordinación de ruta marítima, documentación y expedición de la India a Francia en Marsella" fill sizes="(min-width: 1024px) 55vw, 100vw" className="object-cover object-center" /><div className="pointer-events-none absolute inset-0 bg-gradient-to-t from-[#061711]/70 via-transparent to-transparent" /><figcaption className="absolute bottom-5 left-5 border border-white/15 bg-[#071B14]/80 px-4 py-3 text-[9px] font-bold uppercase tracking-[0.24em] text-[#E4C878] backdrop-blur-md sm:bottom-6 sm:left-6">Coordinación de exportación India–Francia</figcaption></figure></div>
      <div className="mt-16 grid auto-rows-fr gap-6 md:grid-cols-2 md:gap-8 lg:gap-10">{process.map((item) => <article key={item.step} className="group relative h-full border border-[#C9A962]/22 bg-[#071B14]/65 p-7 shadow-[0_22px_55px_rgba(0,0,0,0.16)] backdrop-blur-sm transition-all duration-500 hover:border-[#C9A962]/55 sm:p-8"><div className="flex items-start gap-5"><span className="flex h-14 w-14 shrink-0 items-center justify-center rounded-full border border-[#C9A962]/45 bg-[#C9A962]/10 font-[family-name:var(--font-playfair)] text-xl font-semibold text-[#E4C878]">{item.step}</span><div><h3 className="font-[family-name:var(--font-playfair)] text-[23px] font-semibold leading-tight text-[#F5F0E6] sm:text-[26px]">{item.title}</h3><p className="mt-4 text-[14px] font-light leading-7 text-[#F5F0E6]/62">{item.text}</p></div></div><span className="mt-7 block h-px w-full origin-left scale-x-0 bg-gradient-to-r from-[#C9A962] to-transparent transition-transform duration-500 group-hover:scale-x-100" /></article>)}</div>
      <aside className="mx-auto mt-20 max-w-[1120px] border border-[#C9A962]/45 bg-[#F5F0E6] p-7 text-[#173B2A] shadow-[0_24px_70px_rgba(0,0,0,0.2)] sm:p-9 lg:p-10"><div className="flex flex-col gap-6 sm:flex-row sm:items-start"><span className="inline-flex h-12 w-12 shrink-0 items-center justify-center rounded-full bg-[#173B2A] text-lg text-[#E4C878]">i</span><div><h3 className="font-[family-name:var(--font-playfair)] text-2xl font-semibold text-[#A97B22]">Responsabilidad del importador en Francia y la UE</h3><p className="mt-4 text-[14px] font-light leading-7 text-[#4C5F54] sm:text-[15px]">Shivesh International coordina la documentación comercial y de exportación del pedido confirmado. El importador o comprador francés es responsable de la clasificación del producto, los requisitos de importación, el despacho de aduanas, el etiquetado, las alegaciones, el registro y los requisitos aplicables en Francia y la UE.</p></div></div></aside>
      <div className="mt-10 text-center"><Link href="/contact" className="inline-flex items-center gap-4 border border-[#C9A962] bg-[#C9A962] px-8 py-4 text-[10px] font-bold uppercase tracking-[0.22em] text-[#102F23] transition-all duration-500 hover:-translate-y-1 hover:bg-[#E4C878]">Solicitar presupuesto de exportación a Francia <span>→</span></Link><p className="mx-auto mt-5 max-w-[720px] text-[9px] font-semibold uppercase tracking-[0.24em] text-[#F5F0E6]/38">Producto · Cantidad · Especificaciones · Envasado · Documentación</p></div>
    </div></RevealOnScroll></section>

    <section className="relative overflow-hidden bg-[#071B14] px-6 py-24 text-center text-[#F5F0E6] sm:px-8 lg:px-12"><GoldenParticles /><RevealOnScroll><div className="relative mx-auto max-w-[1000px]"><p className="text-[10px] font-bold uppercase tracking-[0.4em] text-[#E4C878]">Inicie una conversación de suministro para Francia</p><h2 className="mt-6 font-[family-name:var(--font-playfair)] text-[clamp(2.3rem,4.4vw,4.8rem)] font-semibold leading-[1.04]">Planifique su suministro de productos naturales para Francia</h2><p className="mx-auto mt-7 max-w-[760px] text-[16px] font-light leading-8 text-[#F5F0E6]/65">Indique el producto, la cantidad, el tamaño del envase, las necesidades de marca, el destino y la información requerida. Nuestro equipo revisará la consulta y responderá con los siguientes pasos comercialmente viables.</p><Link href="/contact" className="mt-9 inline-flex items-center gap-4 border border-[#C9A962] bg-[#C9A962] px-8 py-4 text-[10px] font-bold uppercase tracking-[0.22em] text-[#102F23] transition-all hover:-translate-y-1 hover:bg-[#E4C878]">Solicitar presupuesto de exportación a Francia <span>→</span></Link></div></RevealOnScroll></section>
    <FooterSection locale="es" /><FloatingContactButtons /><MagneticButtons /><PremiumCursor />
  </main>;
}
