import type { Metadata } from "next";
import { existsSync } from "node:fs";
import Image from "next/image";
import Link from "next/link";

import FloatingContactButtons from "@/app/components/FloatingContactButtons";
import GoldenParticles from "@/app/components/GoldenParticles";
import MagneticButtons from "@/app/components/MagneticButtons";
import Navbar from "@/app/components/Navbar";
import PremiumCursor from "@/app/components/PremiumCursor";
import RevealOnScroll from "@/app/components/RevealOnScroll";
import StaggerItem from "@/app/components/StaggerItem";
import FooterSection from "@/sections/FooterSection";

const canonicalUrl = "https://shiveshinternational.com/export/italy";
const heroImage = "/images/export/italy/italy-export-hero.png";

export const metadata: Metadata = {
  title: "Henna, Indigo, Herbs & Spices Exporter to Italy",
  description:
    "Shivesh International exports natural henna powder, indigo powder, botanical hair colors, Ayurvedic herbs and Indian spices to Italian importers, distributors and private-label buyers. MOQ 200 kg per product.",
  keywords: [
    "Natural products exporter to Italy", "Indian natural products supplier Italy", "Exporter from India to Italy", "Indian supplier for Italian importers", "Natural product manufacturer India for Italy", "Bulk natural products supplier Italy", "Private label products manufacturer for Italy", "Wholesale botanical products Italy", "Indian exporter for Italian distributors", "Natural cosmetic ingredients supplier Italy", "Herbal products exporter to Italy", "Plant-based products supplier Italy", "Botanical ingredients exporter Italy", "Indian manufacturer for Italian wholesalers", "B2B natural products supplier Italy",
    "Henna powder exporter to Italy", "Natural henna powder supplier Italy", "Henna powder manufacturer India for Italy", "Bulk henna powder supplier Italy", "Organic henna powder exporter Italy", "Private label henna powder Italy", "Wholesale henna powder Italy", "Cosmetic-grade henna powder supplier Italy", "Pure henna powder exporter to Italy", "Lawsonia inermis powder supplier Italy", "Indian henna exporter for Italian importers", "Henna powder for cosmetic brands Italy", "Henna powder for salon suppliers Italy", "Henna powder wholesale supplier Italy", "Private label henna manufacturer India for Italy", "Natural henna supplier Milan", "Henna powder supplier Rome", "Henna exporter for Italian beauty brands",
    "Indigo powder exporter to Italy", "Natural indigo powder supplier Italy", "Indigo powder manufacturer India for Italy", "Bulk indigo powder supplier Italy", "Organic indigo powder exporter Italy", "Private label indigo powder Italy", "Wholesale indigo powder Italy", "Indigofera tinctoria powder supplier Italy", "Natural indigo for botanical hair color Italy", "Indigo powder for Italian cosmetic brands", "Indian indigo exporter Italy", "Indigo hair dye ingredient supplier Italy", "Indigo powder for salons Italy", "Bulk indigo supplier for Italian importers",
    "Natural henna hair color manufacturer for Italy", "Botanical hair color supplier Italy", "Plant-based hair color exporter Italy", "Natural hair dye manufacturer India for Italy", "Private label natural hair color Italy", "Henna hair color wholesale Italy", "Botanical hair dye supplier Italy", "Herbal hair color manufacturer for Italian brands", "Powder hair color exporter Italy", "Natural hair color supplier for Italian salons", "Henna-based hair color supplier Italy", "Private label botanical hair color manufacturer India", "Natural hair color for Italian distributors", "Botanical hair color bulk supplier Italy", "Natural hair dye products for Italian beauty brands", "Salon hair color supplier Italy",
    "Ayurvedic herbs exporter to Italy", "Indian herbs supplier Italy", "Herbal powder exporter Italy", "Ayurvedic powder supplier Italy", "Bulk Indian herbs supplier Italy", "Private label herbal products Italy", "Wholesale Ayurvedic herbs Italy", "Indian botanical ingredients exporter Italy", "Herbal ingredients for cosmetic brands Italy", "Natural herbal powder manufacturer India for Italy", "Ayurvedic herbs for Italian importers", "Indian herbs for wellness brands Italy", "Bulk herbal powders exporter Italy", "Cosmetic herbal ingredients supplier Italy", "Amla powder supplier Italy", "Shikakai powder exporter Italy", "Herbal hair-care ingredients Italy",
    "Indian spices exporter to Italy", "Indian spices supplier Italy", "Bulk spices supplier Italy", "Wholesale Indian spices Italy", "Whole spices exporter to Italy", "Ground spices exporter Italy", "Private label Indian spices Italy", "Indian spice manufacturer for Italian buyers", "Spice exporter from India to Italy", "Indian spices for Italian importers", "Bulk spice powder supplier Italy", "Indian food ingredient supplier Italy", "Private label spice packaging Italy", "Indian spice wholesale supplier Italy", "Indian spices for Italian food businesses", "Indian spices distributor supply Italy",
    "Private label manufacturer India for Italy", "Custom packaging supplier for Italian buyers", "Private label henna packaging Italy", "Private label indigo packaging Italy", "Private label herbal powder Italy", "Private label spice supplier Italy", "Custom branded pouches for Italian importers", "Retail packaging natural products Italy", "Bulk packaging exporter India to Italy", "Contract packaging for Italian brands", "Multilingual label coordination Italy", "Italian label packaging coordination", "White label natural products Italy", "OEM natural products supplier Italy", "Custom brand botanical products Italy", "Private label natural hair color Italy",
    "Henna supplier for Italian importers", "Natural product supplier for Italian distributors", "Botanical products for Italian wholesalers", "Private label supplier for Italian brands", "Henna supplier for salon distributors Italy", "Herbal ingredients for Italian cosmetic manufacturers", "Indian products for Italian retail businesses", "Bulk supplier for Italian natural product brands", "Natural ingredients for Italian beauty brands", "Indian exporter for Italian wholesale buyers", "Natural product supplier Milan", "Botanical product supplier Rome", "Indian herbal supplier Naples", "Natural hair-care ingredients Bologna", "Private label products for Italian e-commerce brands",
  ],
  alternates: { canonical: "/export/italy" },
  openGraph: {
    title: "Henna, Indigo, Herbs & Spices Exporter to Italy",
    description: "Bulk, wholesale and private-label supply of Indian henna, indigo, botanical hair colors, Ayurvedic herbs and spices for professional buyers in Italy.",
    url: canonicalUrl,
    type: "website",
    locale: "en_IT",
    siteName: "Shivesh International",
  },
  twitter: {
    card: "summary_large_image",
    title: "Henna, Indigo, Herbs & Spices Exporter to Italy",
    description: "Indian natural-product supply for Italian importers, distributors, salons and private-label brands.",
  },
  robots: { index: true, follow: true },
};

const products = [
  { title: "Natural Henna Powder", text: "Fine-quality natural henna powder for Italian cosmetic brands, salon suppliers, herbal-product businesses, wholesalers and private-label retail requirements.", href: "/products/natural-henna-powder" },
  { title: "Natural Indigo Powder", text: "Natural indigo powder for botanical hair-color systems, cosmetic formulations, professional hair-care supply and private-label packaging.", href: "/products/natural-indigo-powder" },
  { title: "Natural Henna Hair Colors", text: "A broad collection of botanical hair-color shades for Italian importers, beauty brands, natural hair-care businesses and salon distribution.", href: "/products/natural-henna-hair-colors" },
  { title: "Henna-Based Hair Colors", text: "Export-ready powdered hair colors available for bulk, wholesale, OEM and customized private-label requirements.", href: "/products/henna-based-hair-colors" },
  { title: "Ayurvedic Indian Herbs", text: "Indian herbal powders and botanicals for cosmetic, personal-care, wellness, hair-care and wholesale applications.", href: "/products/ayurvedic-indian-herbs" },
  { title: "Indian Spices", text: "Whole and powdered Indian spices for Italian importers, food ingredient companies, distributors, retailers and private-label buyers.", href: "/products/indian-spices" },
];

const buyerProfiles = [
  ["Importers", "Coordinate Italy-focused product specifications, quantities, packaging and available export documentation with one India-based supply contact."],
  ["Distributors", "Build natural-product assortments for regional distribution across Italian professional, beauty, herbal and food channels."],
  ["Cosmetic Brands", "Source henna, indigo and Indian botanical ingredients for buyer-developed cosmetic and personal-care ranges."],
  ["Natural Hair-Care Brands", "Review botanical hair-color powders and herbal hair-care ingredients for Italian brand programmes."],
  ["Salon Suppliers", "Discuss henna, indigo and powdered hair colors for salon and professional hair-care distribution in Italy."],
  ["Herbal & Wellness Businesses", "Source Ayurvedic powders, amla, shikakai and selected botanicals for wellness and own-brand ranges."],
  ["Food & Spice Buyers", "Plan whole-spice, ground-spice and Indian food-ingredient supply for wholesale or retail channels."],
  ["Private-Label & E-Commerce Brands", "Coordinate selected products, buyer branding and commercially feasible packs for Italian digital retail."],
];

const applications = [
  ["Cosmetic & Personal Care", "Natural henna and herbal ingredients can support buyer-developed cosmetic and personal-care formulations, subject to specification and intended-use review."],
  ["Botanical Hair-Color Systems", "Henna, indigo and shade blends support two-step and prepared botanical hair-color concepts for professional buyers."],
  ["Salon Distribution", "Bulk and selected retail formats can be discussed for professional hair-care distributors and salon suppliers."],
  ["Herbal Hair Care & Wellness", "Amla, shikakai and other Ayurvedic powders can support herbal hair-care, wellness and personal-care ranges."],
  ["Retail Natural Products", "Buyer-ready natural-product ranges can combine selected pack sizes with coordinated labels, boxes and pouches."],
  ["Private Label & OEM", "Italian brands can discuss custom presentation and OEM or private-label supply after technical and commercial review."],
  ["Bulk Ingredient Sourcing", "Manufacturers, importers and wholesalers can source botanical powders in commercial bulk packaging for further use or resale."],
  ["Spice & Food Distribution", "Whole and ground Indian spices can be coordinated for Italian food businesses, ingredient buyers and private-label programmes."],
];

const trustItems = [
  ["India-Based Export Supplier", "Direct commercial coordination with an India-based natural-products export team."],
  ["MOQ from 200 kg per Product", "The commercial minimum begins at 200 kg for each selected product."],
  ["Retail, Bulk & Private Label", "Selected retail, professional, wholesale and buyer-brand formats can be reviewed."],
  ["Multiple Natural Product Categories", "Source henna, indigo, hair colors, Ayurvedic herbs and Indian spices."],
  ["Packaging Customization Support", "Coordinate feasible pouches, boxes, labels, artwork and barcode requirements."],
  ["Export Documentation Coordination", "Align available commercial and quality information with the agreed order."],
];

const faqs = [
  { question: "What products does Shivesh International export to Italy?", answer: "We supply natural henna powder, indigo powder, botanical and henna-based hair colors, Ayurvedic Indian herbs, and selected whole or ground Indian spices for qualified Italian business buyers." },
  { question: "What is the minimum order quantity for Italian buyers?", answer: "The minimum order quantity is 200 kg per product. Final quantities depend on the selected product, packaging format and private-label requirements." },
  { question: "Is private-label packaging available for Italy?", answer: "Private-label support can include buyer branding, printed pouches, boxes, custom labels, barcode coordination and Italian-language artwork coordination, subject to feasibility and buyer review." },
  { question: "Can Italian importers order henna and indigo powder in bulk?", answer: "Yes. Italian importers and distributors can discuss commercial henna and indigo supply in available bulk formats, including 20 kg and 25 kg double-layer vacuum bags." },
  { question: "Which retail packaging sizes are available?", answer: "Selected products can be discussed in 100 g, 200 g, 500 g and 1 kg pouches. Material, print and artwork requirements are confirmed for each order." },
  { question: "Does Shivesh International support export documentation for Italy?", answer: "We coordinate applicable commercial invoices, packing lists, certificates of origin, shipping documentation, product specifications, COA and available quality documents for confirmed orders." },
  { question: "Can Italian buyers source multiple product categories?", answer: "Multi-category enquiries are welcome. Product combinations, minimum quantities, packaging, documentation and shipment feasibility are reviewed before commercial confirmation." },
  { question: "How can an Italian buyer request a quotation?", answer: "Use the contact page and share the product, quantity, pack format, destination in Italy and private-label needs. Our export team will review the enquiry and respond with practical next steps." },
];

const structuredData = {
  "@context": "https://schema.org",
  "@graph": [
    { "@type": "WebPage", "@id": `${canonicalUrl}#webpage`, url: canonicalUrl, name: "Henna, Indigo, Herbs & Spices Exporter to Italy", description: "Italy-focused export supply of natural henna, indigo, botanical hair colors, Ayurvedic herbs and Indian spices from India.", isPartOf: { "@id": "https://shiveshinternational.com/#website" }, about: { "@id": "https://shiveshinternational.com/#organization" }, breadcrumb: { "@id": `${canonicalUrl}#breadcrumb` }, inLanguage: "en" },
    { "@type": "BreadcrumbList", "@id": `${canonicalUrl}#breadcrumb`, itemListElement: [
      { "@type": "ListItem", position: 1, name: "Home", item: "https://shiveshinternational.com/" },
      { "@type": "ListItem", position: 2, name: "Export", item: "https://shiveshinternational.com/export" },
      { "@type": "ListItem", position: 3, name: "Europe", item: "https://shiveshinternational.com/export/europe" },
      { "@type": "ListItem", position: 4, name: "Italy", item: canonicalUrl },
    ] },
  ],
};

const faqStructuredData = { "@context": "https://schema.org", "@type": "FAQPage", "@id": `${canonicalUrl}#faq`, mainEntity: faqs.map((faq) => ({ "@type": "Question", name: faq.question, acceptedAnswer: { "@type": "Answer", text: faq.answer } })) };

function OptionalImage({ src, alt, priority = false, sizes = "(min-width: 1024px) 55vw, 100vw", className = "object-cover object-center" }: { src: string; alt: string; priority?: boolean; sizes?: string; className?: string }) {
  if (!existsSync(`${process.cwd()}/public${src}`)) return null;
  return <Image src={src} alt={alt} fill priority={priority} sizes={sizes} className={className} />;
}

export default function ItalyExportPage() {
  return (
    <main className="min-h-screen overflow-x-hidden bg-[#F5F0E6] text-[#173B2A]">
      <script type="application/ld+json" dangerouslySetInnerHTML={{ __html: JSON.stringify(structuredData).replace(/</g, "\\u003c") }} />
      <script type="application/ld+json" dangerouslySetInnerHTML={{ __html: JSON.stringify(faqStructuredData).replace(/</g, "\\u003c") }} />
      <Navbar />

      <section className="relative isolate overflow-hidden bg-[radial-gradient(circle_at_75%_42%,#496d58_0%,#173b2a_35%,#071b14_78%)]">
        <OptionalImage src={heroImage} alt="Italian buyers reviewing botanical hair colors, henna and natural product formulations at an Indian production and innovation facility" priority sizes="100vw" className="object-cover object-[50%_52%] sm:object-[50%_52%] lg:object-[50%_52%]" />
        <div className="absolute inset-0 bg-gradient-to-r from-[#061711]/72 via-[#102F23]/40 to-[#071B14]/10" />
        <div className="absolute inset-0 bg-gradient-to-t from-black/10 via-transparent to-black/[0.04]" />
        <GoldenParticles />
        <div className="relative z-10 flex items-center px-6 pb-20 pt-32 sm:px-8 sm:pb-24 sm:pt-36 lg:px-12 lg:pb-28 lg:pt-40">
          <div className="w-full max-w-[820px] lg:max-w-[860px] xl:max-w-[900px]">
            <StaggerItem delay={0}><div className="flex items-center gap-4"><span className="h-px w-14 bg-[#C9A962]" /><p className="text-[10px] font-bold uppercase tracking-[0.38em] text-[#E4C878] sm:text-xs">Exporting from India to Italy</p></div></StaggerItem>
            <StaggerItem delay={100}><h1 className="mt-5 font-[family-name:var(--font-playfair)] text-4xl font-medium leading-[1] tracking-[-0.04em] text-[#F5F0E6] sm:text-5xl lg:text-6xl xl:text-[66px]">Natural Products Exporter to Italy<span className="mt-2 block bg-gradient-to-r from-[#F5F0E6] via-[#E4C878] to-[#C9A962] bg-clip-text text-transparent">Henna, Indigo, Herbs &amp; Spices</span></h1></StaggerItem>
            <StaggerItem delay={200}><p className="mt-5 max-w-[730px] text-[16px] font-light leading-7 text-[#F5F0E6]/82 sm:text-[17px] sm:leading-8">Shivesh International supports Italian importers, distributors, wholesalers, cosmetic companies, salon suppliers, herbal-product businesses and private-label brands with export-ready natural henna, indigo, botanical hair colors, Ayurvedic herbs and Indian spices from India.</p></StaggerItem>
            <StaggerItem delay={300}><div className="mt-7 flex flex-wrap gap-4"><Link href="/contact" className="inline-flex items-center gap-4 border border-[#C9A962] bg-[#C9A962] px-7 py-4 text-[10px] font-bold uppercase tracking-[0.2em] text-[#102F23] transition-all hover:-translate-y-1 hover:bg-[#E4C878] focus-visible:outline focus-visible:outline-2 focus-visible:outline-offset-4 focus-visible:outline-[#E4C878]">Send Italy Inquiry <span>→</span></Link><a href="#italy-products" className="inline-flex items-center gap-4 border border-[#F5F0E6]/30 bg-[#102F23]/40 px-7 py-4 text-[10px] font-bold uppercase tracking-[0.2em] text-[#F5F0E6] backdrop-blur-lg transition-all hover:border-[#C9A962] hover:text-[#E4C878] focus-visible:outline focus-visible:outline-2 focus-visible:outline-offset-4 focus-visible:outline-[#E4C878]">Explore Products <span>↓</span></a></div></StaggerItem>
            <StaggerItem delay={400}><div className="mt-10 grid max-w-[740px] grid-cols-2 gap-3 lg:grid-cols-4">{[["200 kg", "MOQ Per Product"], ["Bulk", "Wholesale Supply"], ["OEM", "Private Label"], ["Italy", "Buyer Enquiries"]].map(([value, label]) => <div key={label} className="border border-white/15 bg-black/20 px-4 py-4 backdrop-blur-md"><p className="font-[family-name:var(--font-playfair)] text-xl font-semibold text-[#E4C878]">{value}</p><p className="mt-2 text-[9px] font-bold uppercase tracking-[0.22em] text-[#F5F0E6]/55">{label}</p></div>)}</div></StaggerItem>
          </div>
        </div>
      </section>

      <section className="px-6 py-24 sm:px-8 lg:px-12 lg:py-32"><RevealOnScroll><div className="mx-auto max-w-[1120px]"><p className="text-[10px] font-bold uppercase tracking-[0.4em] text-[#9F7F36]">India–Italy Natural Product Sourcing</p><h2 className="mt-6 font-[family-name:var(--font-playfair)] text-[clamp(2.5rem,4.6vw,4.6rem)] font-semibold leading-[1.04]">Your Indian Export Partner <span className="block text-[#A97B22]">for the Italian Market</span></h2><p className="mt-7 text-[16px] font-light leading-8 text-[#4C5F54]">Italian importers, distributors and wholesalers can coordinate multiple product categories with one Indian export team. Shivesh International supports cosmetic and personal-care companies, natural hair-care brands, salon suppliers, herbal and wellness businesses, food ingredient buyers, spice companies, private-label operators and e-commerce brands seeking structured sourcing from India.</p><p className="mt-5 text-[15px] font-light leading-8 text-[#4C5F54]">Commercial enquiries may be associated with buyer and distribution activity in Milan, Rome, Bologna, Turin and Naples. Product availability, specifications, packaging, documentation and shipment preparation are reviewed according to the buyer’s selected category and agreed order requirements. Market references identify potential buyer locations and do not imply that Shivesh International maintains a local office or warehouse in Italy.</p></div></RevealOnScroll></section>

      <section id="italy-products" className="scroll-mt-24 bg-[#EDE5D7] px-6 py-24 sm:px-8 lg:px-12 lg:py-32"><RevealOnScroll><div className="mx-auto max-w-[1500px]"><div className="mx-auto max-w-[920px] text-center"><p className="text-[10px] font-bold uppercase tracking-[0.4em] text-[#9F7F36]">Six Commercial Categories</p><h2 className="mt-6 font-[family-name:var(--font-playfair)] text-[clamp(2.5rem,4.8vw,4.8rem)] font-semibold leading-[1.04]">Products Suitable <span className="block text-[#A97B22]">for Italian Buyers</span></h2><p className="mx-auto mt-7 max-w-[820px] text-[16px] font-light leading-8 text-[#4C5F54]">A focused portfolio for Italian cosmetic brands, professional hair-care channels, herbal businesses, wholesalers, food companies and private-label buyers.</p></div><div className="mt-14 grid auto-rows-fr gap-5 sm:grid-cols-2 lg:grid-cols-3">{products.map((product, index) => <StaggerItem key={product.title} delay={(index % 3) * 90}><article className="group flex h-full min-h-[300px] flex-col border border-[#173B2A]/12 bg-[#FBF8F1] p-7 shadow-[0_18px_45px_rgba(20,50,38,0.07)] transition-all hover:-translate-y-2 hover:border-[#C9A962]/70 sm:p-8"><span className="font-[family-name:var(--font-playfair)] text-4xl font-semibold text-[#C9A962]/60">{String(index + 1).padStart(2, "0")}</span><h3 className="mt-6 font-[family-name:var(--font-playfair)] text-[27px] font-semibold leading-tight">{product.title}</h3><p className="mt-5 flex-1 text-[14px] font-light leading-7 text-[#4C5F54]">{product.text}</p><Link href={product.href} className="mt-7 inline-flex items-center gap-3 text-[10px] font-bold uppercase tracking-[0.2em] text-[#A97B22] focus-visible:outline focus-visible:outline-2 focus-visible:outline-offset-4 focus-visible:outline-[#A97B22]">Explore {product.title} <span className="transition-transform group-hover:translate-x-2">→</span></Link></article></StaggerItem>)}</div></div></RevealOnScroll></section>

      <section className="bg-[#0B3325] px-6 py-24 text-[#F5F0E6] sm:px-8 lg:px-12 lg:py-32"><RevealOnScroll><div className="mx-auto max-w-[1500px]"><div className="mx-auto max-w-[920px] text-center"><p className="text-[10px] font-bold uppercase tracking-[0.4em] text-[#E4C878]">Italian Commercial Channels</p><h2 className="mt-6 font-[family-name:var(--font-playfair)] text-[clamp(2.5rem,4.7vw,4.7rem)] font-semibold leading-[1.04]">Natural Product Supply for Italian B2B Buyers</h2></div><div className="mt-14 grid auto-rows-fr gap-5 sm:grid-cols-2 lg:grid-cols-4">{buyerProfiles.map(([title, text]) => <article key={title} className="h-full border border-[#C9A962]/25 bg-[#071B14]/55 p-7"><h3 className="font-[family-name:var(--font-playfair)] text-2xl font-semibold text-[#E4C878]">{title}</h3><p className="mt-4 text-[14px] font-light leading-7 text-[#F5F0E6]/65">{text}</p></article>)}</div></div></RevealOnScroll></section>

      <section className="px-6 py-24 sm:px-8 lg:px-12 lg:py-32"><RevealOnScroll><div className="mx-auto max-w-[1500px]"><div className="grid gap-14 lg:grid-cols-[0.7fr_1.3fr] lg:gap-20"><div><p className="text-[10px] font-bold uppercase tracking-[0.4em] text-[#9F7F36]">Commercial Use Cases</p><h2 className="mt-6 font-[family-name:var(--font-playfair)] text-[clamp(2.5rem,4.5vw,4.5rem)] font-semibold leading-[1.04]">Product Applications <span className="block text-[#A97B22]">for the Italian Market</span></h2><p className="mt-7 text-[15px] font-light leading-8 text-[#4C5F54]">Every enquiry is reviewed around intended use, buyer specification, commercial quantity, packaging format and destination requirements.</p></div><div className="grid auto-rows-fr gap-5 sm:grid-cols-2">{applications.map(([title, text]) => <article key={title} className="h-full border border-[#173B2A]/12 bg-[#FBF8F1] p-7"><span className="block h-px w-12 bg-[#C9A962]" /><h3 className="mt-5 font-[family-name:var(--font-playfair)] text-2xl font-semibold">{title}</h3><p className="mt-4 text-[14px] font-light leading-7 text-[#4C5F54]">{text}</p></article>)}</div></div></div></RevealOnScroll></section>

      <section className="bg-[#EDE5D7] px-6 py-24 sm:px-8 lg:px-12 lg:py-32"><RevealOnScroll><div className="mx-auto grid max-w-[1500px] gap-14 lg:grid-cols-[1.05fr_0.95fr] lg:gap-20"><div><p className="text-[10px] font-bold uppercase tracking-[0.4em] text-[#9F7F36]">Buyer-Brand Formats</p><h2 className="mt-6 font-[family-name:var(--font-playfair)] text-[clamp(2.5rem,4.6vw,4.6rem)] font-semibold leading-[1.04]">Packaging &amp; Private-Label Solutions <span className="block text-[#A97B22]">for Italian Buyers</span></h2><p className="mt-7 text-[15px] font-light leading-8 text-[#4C5F54]">Selected programmes can include custom brand names, printed pouches, printed boxes, buyer-supplied artwork coordination, barcodes, label-layout support, multilingual packaging and Italian-language label artwork coordination. Retail, salon, professional and bulk formats, including OEM or private-label supply, remain subject to agreed requirements and technical feasibility.</p><p className="mt-5 text-[14px] font-light leading-7 text-[#4C5F54]">Retail options may include 100 g, 200 g, 500 g and 1 kg pouches. Bulk formats may include 20 kg and 25 kg double-layer vacuum bags. Final product labels, language requirements, claims, product classification and destination-market compliance remain subject to buyer review and the applicable product category.</p></div><div><figure className="relative aspect-[3/2] overflow-hidden rounded-sm border border-[#C9A962]/35 bg-[linear-gradient(135deg,#0b3325,#496d58)] shadow-[0_28px_70px_rgba(20,50,38,0.18)]"><OptionalImage src="/images/export/italy/italy-buyer-partnership.png" alt="Italian buyers and Indian packaging specialists developing retail, bulk and private-label packaging solutions" className="object-contain object-center" /></figure><div className="mt-5 grid gap-5 sm:grid-cols-2"><article className="border border-[#C9A962]/35 bg-[#FBF8F1] p-7"><h3 className="font-[family-name:var(--font-playfair)] text-2xl font-semibold">Retail Packaging</h3><p className="mt-4 text-sm leading-7 text-[#4C5F54]">100 g · 200 g · 500 g · 1 kg pouches</p></article><article className="border border-[#C9A962]/35 bg-[#FBF8F1] p-7"><h3 className="font-[family-name:var(--font-playfair)] text-2xl font-semibold">Bulk Packaging</h3><p className="mt-4 text-sm leading-7 text-[#4C5F54]">20 kg and 25 kg double-layer vacuum bags</p></article><article className="border border-[#C9A962] bg-[#173B2A] p-7 text-[#F5F0E6] sm:col-span-2"><p className="text-[10px] font-bold uppercase tracking-[0.3em] text-[#E4C878]">Minimum Order Quantity</p><p className="mt-4 font-[family-name:var(--font-playfair)] text-4xl font-semibold">200 kg per product</p></article></div></div></div></RevealOnScroll></section>

      <section className="bg-[#09271D] px-6 py-24 text-[#F5F0E6] sm:px-8 lg:px-12 lg:py-32"><RevealOnScroll><div className="mx-auto max-w-[1500px]"><div className="grid items-center gap-14 lg:grid-cols-[0.9fr_1.1fr] lg:gap-20"><div><p className="text-[10px] font-bold uppercase tracking-[0.4em] text-[#E4C878]">Shipment and Document Support</p><h2 className="mt-6 font-[family-name:var(--font-playfair)] text-[clamp(2.5rem,4.8vw,4.8rem)] font-semibold leading-[1.04]">India-to-Italy Export Coordination</h2><p className="mt-7 text-[16px] font-light leading-8 text-[#F5F0E6]/68">Coordination can cover commercial invoices, packing lists, certificates of origin, product specifications, COA and available quality documents, shipping documentation, buyer-appointed freight forwarders, export cartons, pallets and shipment information sharing.</p><p className="mt-5 text-[15px] font-light leading-8 text-[#F5F0E6]/62">Sea- or air-freight planning may be discussed for buyer-selected logistics arrangements associated with Genoa, La Spezia, Trieste, Milan-area air cargo or Rome-area air cargo. This does not promise route availability, delivery timing or customs clearance. Documentation and product information can be coordinated according to the product category, destination, buyer instructions and agreed order requirements.</p></div><figure className="relative aspect-[3/2] overflow-hidden rounded-sm border border-[#C9A962]/35 bg-[linear-gradient(135deg,#071b14,#496d58)] shadow-[0_28px_70px_rgba(0,0,0,0.25)]"><OptionalImage src="/images/export/italy/india-to-italy-export-coordination.png" alt="Italian representatives and Indian logistics staff coordinating documents, sea freight, air freight and container dispatch" className="object-contain object-center" /></figure></div><aside className="mt-12 border border-[#C9A962]/35 bg-[#071B14]/60 p-7 text-[14px] font-light leading-7 text-[#F5F0E6]/65">The Italian importer or buyer remains responsible for confirming product classification, labelling, registration, customs procedures and applicable destination-market requirements.</aside></div></RevealOnScroll></section>

      <section className="bg-[#EDE5D7] px-6 py-24 sm:px-8 lg:px-12 lg:py-32"><RevealOnScroll><div className="mx-auto max-w-[1500px]"><div className="mx-auto max-w-[920px] text-center"><p className="text-[10px] font-bold uppercase tracking-[0.4em] text-[#9F7F36]">Commercial Supply Strengths</p><h2 className="mt-6 font-[family-name:var(--font-playfair)] text-[clamp(2.5rem,4.7vw,4.7rem)] font-semibold leading-[1.04]">Why Italian Buyers Work with Shivesh International</h2></div><div className="mt-14 grid auto-rows-fr gap-5 sm:grid-cols-2 lg:grid-cols-3">{trustItems.map(([title, text]) => <article key={title} className="h-full border border-[#173B2A]/12 bg-[#FBF8F1] p-7 sm:p-8"><span className="block h-px w-12 bg-[#C9A962]" /><h3 className="mt-6 font-[family-name:var(--font-playfair)] text-2xl font-semibold">{title}</h3><p className="mt-4 text-[14px] font-light leading-7 text-[#4C5F54]">{text}</p></article>)}</div></div></RevealOnScroll></section>

      <section className="px-6 py-24 sm:px-8 lg:px-12 lg:py-32"><RevealOnScroll><div className="mx-auto max-w-[1120px]"><p className="text-[10px] font-bold uppercase tracking-[0.4em] text-[#9F7F36]">Italian Market Locations</p><h2 className="mt-6 font-[family-name:var(--font-playfair)] text-[clamp(2.5rem,4.6vw,4.6rem)] font-semibold leading-[1.04]">Supporting Natural Product Enquiries Across Italy</h2><p className="mt-7 text-[16px] font-light leading-8 text-[#4C5F54]">We welcome professional enquiries associated with Milan’s beauty and commercial businesses, Rome-based import and retail buyers, Turin and Bologna distribution channels, Naples-area herbal businesses, Florence beauty brands, Genoa logistics planning and Venice-area trade enquiries. Buyers can discuss product category, intended use, quantity, branding, packaging and destination before commercial review.</p><p className="mt-5 text-[14px] leading-7 text-[#4C5F54]">Location references indicate potential enquiry and distribution markets; they do not represent local offices, warehouses or guaranteed active supply relationships.</p><div className="mt-8 flex flex-wrap gap-3">{["Milan", "Rome", "Turin", "Bologna", "Naples", "Florence", "Genoa", "Venice"].map((city) => <span key={city} className="border border-[#C9A962]/40 bg-[#FBF8F1] px-5 py-3 text-[10px] font-bold uppercase tracking-[0.2em] text-[#A97B22]">{city}</span>)}</div></div></RevealOnScroll></section>

      <section className="bg-[#EDE5D7] px-6 py-24 sm:px-8 lg:px-12 lg:py-32"><RevealOnScroll><div className="mx-auto max-w-[1120px]"><div className="text-center"><p className="text-[10px] font-bold uppercase tracking-[0.4em] text-[#9F7F36]">Italian Buyer Questions</p><h2 className="mt-6 font-[family-name:var(--font-playfair)] text-[clamp(2.4rem,4.4vw,4.4rem)] font-semibold">Italy Export Supply FAQ</h2></div><div className="mt-12 divide-y divide-[#173B2A]/15 border-y border-[#173B2A]/15">{faqs.map((faq) => <article key={faq.question} className="grid gap-4 py-7 md:grid-cols-[0.8fr_1.2fr] md:gap-10"><h3 className="font-[family-name:var(--font-playfair)] text-xl font-semibold">{faq.question}</h3><p className="text-[14px] font-light leading-7 text-[#4C5F54]">{faq.answer}</p></article>)}</div></div></RevealOnScroll></section>

      <section className="relative overflow-hidden bg-[#071B14] px-6 py-24 text-center text-[#F5F0E6] sm:px-8 lg:px-12 lg:py-28"><GoldenParticles /><RevealOnScroll><div className="relative mx-auto max-w-[1000px]"><p className="text-[10px] font-bold uppercase tracking-[0.4em] text-[#E4C878]">Italy Buyer Enquiries</p><h2 className="mt-6 font-[family-name:var(--font-playfair)] text-[clamp(2.5rem,4.8vw,4.8rem)] font-semibold leading-[1.04]">Looking for a Reliable Natural Product Supplier from India?</h2><p className="mx-auto mt-7 max-w-[760px] text-[16px] font-light leading-8 text-[#F5F0E6]/65">Share your required product, quantity, packaging format, destination in Italy and private-label requirements with the Shivesh International export team.</p><div className="mt-9 flex flex-wrap justify-center gap-4"><Link href="/contact" className="inline-flex items-center gap-4 border border-[#C9A962] bg-[#C9A962] px-8 py-4 text-[10px] font-bold uppercase tracking-[0.22em] text-[#102F23] transition-all hover:-translate-y-1 hover:bg-[#E4C878]">Send Your Italy Requirement <span>→</span></Link><Link href="/export/europe" className="inline-flex items-center gap-4 border border-[#F5F0E6]/30 px-8 py-4 text-[10px] font-bold uppercase tracking-[0.22em] text-[#F5F0E6] transition-all hover:border-[#C9A962] hover:text-[#E4C878]">Explore Europe Hub <span>→</span></Link></div><div className="mt-9 flex flex-wrap justify-center gap-x-6 gap-y-3 text-[10px] font-bold uppercase tracking-[0.16em] text-[#F5F0E6]/45"><Link href="/export">Global Export Information</Link><Link href="/export/france">France Export Market</Link><Link href="/export/germany">Germany Export Market</Link><Link href="/resources">Buyer Resources</Link><Link href="/certifications">Certifications</Link><Link href="/infrastructure">Infrastructure</Link><Link href="/about">About Shivesh International</Link><Link href="/export/italy">Italy Export Page</Link></div></div></RevealOnScroll></section>

      <FooterSection /><FloatingContactButtons /><MagneticButtons /><PremiumCursor />
    </main>
  );
}
