import { existsSync } from "node:fs";
import type { Metadata } from "next";
import Image from "next/image";
import Link from "next/link";
import Navbar from "@/app/components/Navbar";
import FloatingContactButtons from "@/app/components/FloatingContactButtons";
import GoldenParticles from "@/app/components/GoldenParticles";
import MagneticButtons from "@/app/components/MagneticButtons";
import PremiumCursor from "@/app/components/PremiumCursor";
import { spainLanguageAlternates } from "@/app/lib/i18n";
import FooterSection from "@/sections/FooterSection";

const url="https://shiveshinternational.com/it/export/spagna";
const hero="/images/export/spain/spain-export-hero.png";
export const metadata:Metadata={title:"Esportatore di prodotti naturali in Spagna | Henné e indigo",description:"Henné, indigo, colorazioni vegetali, erbe ayurvediche e spezie indiane per acquirenti B2B in Spagna. Fornitura sfusa, OEM e Private Label da 200 kg.",keywords:["esportatore di prodotti naturali in Spagna","produttore di henné per la Spagna","esportatore di henné naturale","fornitore di henné naturale","henné all’ingrosso Spagna","fornitore di indigo naturale","esportatore di indigo naturale","fornitore di colorazioni vegetali","colorazione botanica per capelli","fornitore di colorazioni naturali","fornitore per saloni professionali","fornitore professionale per parrucchieri","fornitore di cosmetici naturali","marchi di cosmetica naturale","marchi per la cura dei capelli","importatori","distributori","grossisti","rivenditori","fornitori","produttore","esportatore","Private Label","marchio proprio","OEM","produzione conto terzi","confezionamento sfuso","fornitura sfusa","fornitore di erbe ayurvediche","esportatore di erbe ayurvediche","fornitore di spezie indiane","esportatore di spezie indiane","approvvigionamento B2B Spagna","henné naturale sfuso","indigo naturale sfuso","colorazioni naturali per marchi","prodotti botanici per saloni","fornitore Madrid","fornitore Barcellona","approvvigionamento Valencia","acquirenti Siviglia","distributori Malaga","grossisti Bilbao","cosmetica naturale Private Label","etichettatura in spagnolo","confezionamento per marchi","prodotti naturali dall’India","ingredienti botanici","erbe ayurvediche all’ingrosso","spezie indiane all’ingrosso","esportazione India Spagna","fornitore B2B di henné","produttore Private Label India","fornitore OEM","colorazioni all’henné","erbe ayurvediche indiane","spezie indiane","commercio retail","e-commerce","documentazione export","COA prodotti botanici","INCI ingredienti botanici","imballaggio multilingue","marchio del distributore","importazione di henné","importazione di indigo","marchi per capelli Spagna","benessere naturale","trasporto marittimo","trasporto aereo","fornitore Valencia","fornitore Siviglia","fornitore Malaga","fornitore Bilbao"],alternates:{canonical:url,languages:spainLanguageAlternates},openGraph:{title:"Prodotti naturali dall’India per acquirenti in Spagna",description:"Fornitura B2B di henné, indigo, colorazioni vegetali, erbe ayurvediche e spezie.",url,type:"website",locale:"it_IT",siteName:"Shivesh International",images:[{url:hero,width:1944,height:809,alt:"Acquirenti spagnoli valutano prodotti naturali dall’India"}]},robots:{index:true,follow:true}};
const products=[["Henné naturale","Henné per importatori, marchi, rivenditori e parrucchieri professionali.","/products/natural-henna-powder"],["Indigo naturale","Indigo botanico per colorazioni dei capelli e formati sfusi.","/products/natural-indigo-powder"],["Colorazioni naturali per capelli all’henné","Collezione vegetale per distributori, marchi e saloni.","/products/natural-henna-hair-colors"],["Colorazioni per capelli a base di henné","Prodotti Private Label soggetti a fattibilità.","/products/henna-based-hair-colors"],["Erbe ayurvediche indiane","Erbe e polveri per il benessere e la cura personale.","/products/ayurvedic-indian-herbs"],["Spezie indiane","Spezie intere e macinate per acquirenti del settore alimentare.","/products/indian-spices"]] as const;
const buyers=[["Importatori e distributori","Specifiche, quantità e documenti per le reti spagnole."],["Grossisti e rivenditori","Assortimenti per il commercio specializzato e l’e-commerce."],["Marchi di cosmetica naturale","Ingredienti botanici per progetti cosmetici."],["Marchi per la cura dei capelli","Gamme botaniche per canali professionali."],["Fornitori per saloni","Formati per parrucchieri e distributori."],["Aziende erboristiche e del benessere","Ingredienti ayurvedici per programmi specializzati."],["Acquirenti Private Label e OEM","Confezioni, grafiche definitive e marchio dell’acquirente."],["Importatori di alimenti e spezie","Spezie per aziende e distributori."]] as const;
const applications=[["Colorazione botanica per capelli","Henné e indigo per gamme vegetali."],["Cura professionale dei capelli","Polveri per saloni e marchi."],["Cosmetica naturale","Ingredienti soggetti a valutazione."],["Benessere ayurvedico","Erbe per il commercio specializzato."],["Ingredienti alimentari","Spezie per importatori."],["Commercio retail","Formati per negozi."],["Private Label","Presentazioni per l’acquirente."],["Fornitura sfusa","Formati per grossisti."],["Produzione conto terzi","Programmi OEM concordati."],["Approvvigionamento multicategoria","Sei famiglie con un unico team."]] as const;
const trust=[["Esperienza nell’esportazione","Coordinamento commerciale dall’India."],["Sei famiglie","Portafoglio per acquirenti professionali."],["MOQ chiaro","200 kg per prodotto."],["Private Label","Confezionamento soggetto a fattibilità."],["Documentazione","Informazioni in base al prodotto e all’ordine."],["Responsabilità","Nessuna promessa di approvazione automatica."]] as const;
const faqs=[{question:"Quali prodotti esportate in Spagna?",answer:"Henné, indigo, colorazioni all’henné, erbe ayurvediche e spezie indiane."},{question:"Qual è l’ordine minimo?",answer:"Il MOQ standard è di 200 kg per prodotto, soggetto a conferma commerciale."},{question:"Offrite Private Label e OEM?",answer:"Sì, in base al prodotto, alla quantità, alla stampa e alla fattibilità tecnica."},{question:"Quali confezioni sono disponibili?",answer:"È possibile valutare formati da 100 g, 200 g, 500 g, 1 kg e imballaggi sfusi da 20 kg o 25 kg."},{question:"Preparate etichette in spagnolo?",answer:"Possiamo coordinarle; l’acquirente convalida i requisiti legali e le dichiarazioni."},{question:"Quali documenti sono disponibili?",answer:"In base al prodotto: fattura commerciale, Packing List, certificato di origine, specifiche e COA."},{question:"Coordinate il trasporto verso la Spagna?",answer:"Sì, con lo spedizioniere scelto, senza garantire rotte, tempi o sdoganamento."},{question:"Avete un ufficio in Spagna?",answer:"No. Le città citate sono mercati potenziali, non una presenza locale."}];
const schema={"@context":"https://schema.org","@graph":[{"@type":"WebPage","@id":`${url}#webpage`,url,name:"Esportatore di prodotti naturali in Spagna",description:metadata.description,inLanguage:"it",about:{"@id":"https://shiveshinternational.com/#organization"}},{"@type":"BreadcrumbList",itemListElement:[{"@type":"ListItem",position:1,name:"Home",item:"https://shiveshinternational.com/"},{"@type":"ListItem",position:2,name:"Export",item:"https://shiveshinternational.com/export"},{"@type":"ListItem",position:3,name:"Spagna",item:url}]}]};
const faqSchema={"@context":"https://schema.org","@type":"FAQPage",mainEntity:faqs.map(f=>({"@type":"Question",name:f.question,acceptedAnswer:{"@type":"Answer",text:f.answer}}))};
function Pic({src,alt,priority=false}:{src:string;alt:string;priority?:boolean}){if(!existsSync(`${process.cwd()}/public${src}`))return null;return <Image src={src} alt={alt} fill priority={priority} sizes="100vw" className="object-cover object-center"/>}
function Grid({items,cols="lg:grid-cols-4"}:{items:readonly(readonly[string,string])[];cols?:string}){return <div className={`mt-14 grid gap-5 sm:grid-cols-2 ${cols}`}>{items.map(([t,d])=><article key={t} className="h-full bg-[#FBF8F1] p-7 text-[#173B2A]"><span className="block h-px w-12 bg-[#C9A962]"/><h3 className="mt-5 text-2xl font-semibold">{t}</h3><p className="mt-4 leading-7 text-[#4C5F54]">{d}</p></article>)}</div>}
const H=({children}:{children:React.ReactNode})=><h2 className="mt-6 text-[clamp(2.2rem,4.7vw,4.7rem)] font-semibold leading-[1.05]">{children}</h2>;
export default function Page(){return <main className="min-h-screen overflow-x-hidden bg-[#F5F0E6] text-[#173B2A]"><script type="application/ld+json" dangerouslySetInnerHTML={{__html:JSON.stringify(schema)}}/><script type="application/ld+json" dangerouslySetInnerHTML={{__html:JSON.stringify(faqSchema)}}/><Navbar/>
<section className="relative isolate overflow-hidden bg-[#071b14]"><Pic src={hero} alt="Acquirenti spagnoli esaminano prodotti naturali dall’India" priority/><div className="absolute inset-0 bg-gradient-to-r from-[#061711]/75 via-[#102F23]/45 to-transparent"/><GoldenParticles/><div className="relative z-10 px-6 pb-20 pt-32 lg:px-12 lg:pb-28 lg:pt-40"><div className="max-w-[900px]"><p className="text-[10px] font-bold uppercase tracking-[.38em] text-[#E4C878]">Esportazione dall’India alla Spagna</p><h1 className="mt-5 text-[clamp(2.25rem,6vw,4.125rem)] font-medium leading-none text-white">Esportatore di prodotti naturali in Spagna<span className="mt-2 block text-[#E4C878]">Henné, indigo, erbe e spezie</span></h1><p className="mt-5 max-w-[730px] leading-8 text-white/80">Fornitura per importatori, distributori, grossisti, marchi, saloni e acquirenti Private Label in Spagna.</p><div className="mt-7 flex flex-wrap gap-4"><Link href="/contact" className="bg-[#C9A962] px-7 py-4 text-[10px] font-bold uppercase text-[#102F23]">Invia una richiesta →</Link><a href="#prodotti" className="border border-white/30 px-7 py-4 text-[10px] font-bold uppercase text-white">Scopri i prodotti ↓</a></div><div className="mt-10 grid max-w-[740px] grid-cols-2 gap-3 lg:grid-cols-4">{[["200 kg","MOQ per prodotto"],["Sfuso","All’ingrosso"],["OEM","Private Label"],["Spagna","Acquirenti B2B"]].map(([v,l])=><div key={l} className="border border-white/15 bg-black/20 p-4"><p className="text-xl text-[#E4C878]">{v}</p><p className="mt-2 text-[9px] uppercase text-white/60">{l}</p></div>)}</div></div></div></section>
<section className="px-6 py-24 lg:py-32"><div className="mx-auto max-w-[1120px]"><p className="text-[10px] uppercase tracking-[.4em] text-[#9F7F36]">Approvvigionamento India–Spagna</p><H>Il vostro partner per l’esportazione <span className="block text-[#A97B22]">nel mercato spagnolo</span></H><p className="mt-7 leading-8 text-[#4C5F54]">Gli acquirenti coordinano più categorie con un unico team export. Esaminiamo disponibilità, specifiche, confezioni, documenti e preparazione della spedizione. Madrid, Barcellona, Valencia, Siviglia, Malaga e Bilbao sono riferimenti commerciali, non uffici o magazzini.</p></div></section>
<section id="prodotti" className="bg-[#EDE5D7] px-6 py-24 lg:py-32"><div className="mx-auto max-w-[1500px] text-center"><H>Prodotti naturali <span className="block text-[#A97B22]">per importatori e marchi</span></H><div className="mt-14 grid gap-5 sm:grid-cols-2 lg:grid-cols-3">{products.map(([t,d,h],i)=><article key={t} className="flex min-h-[290px] flex-col bg-white p-7 text-left"><span className="text-4xl text-[#C9A962]">0{i+1}</span><h3 className="mt-5 text-2xl font-semibold">{t}</h3><p className="mt-4 flex-1 leading-7 text-[#4C5F54]">{d}</p><Link href={h} className="mt-6 text-[10px] font-bold uppercase text-[#A97B22]">Scopri →</Link></article>)}</div></div></section>
<section className="bg-[#0B3325] px-6 py-24 text-white"><div className="mx-auto max-w-[1500px]"><H>Soluzioni per gli acquirenti B2B spagnoli</H><Grid items={buyers}/></div></section><section className="px-6 py-24"><div className="mx-auto max-w-[1500px]"><H>Applicazioni per il mercato spagnolo</H><Grid items={applications} cols="lg:grid-cols-2"/></div></section>
<section className="bg-[#EDE5D7] px-6 py-24"><div className="mx-auto grid max-w-[1500px] gap-14 lg:grid-cols-2"><div><H>Confezionamento e Private Label <span className="block text-[#A97B22]">per gli acquirenti spagnoli</span></H><p className="mt-7 leading-8 text-[#4C5F54]">Buste e scatole stampate, grafiche definitive, codici a barre, etichette e confezioni multilingue sono soggetti a fattibilità. L’acquirente convalida etichettatura, dichiarazioni, classificazione e requisiti applicabili in Spagna e nell’UE.</p></div><div><figure className="relative aspect-[3/2]"><Pic src="/images/export/spain/spain-buyer-partnership.png" alt="Confezionamento Private Label per acquirenti spagnoli"/></figure><div className="mt-5 bg-[#173B2A] p-7 text-white"><p className="text-[#E4C878]">Quantità minima d’ordine</p><p className="mt-3 text-4xl">200 kg per prodotto</p></div></div></div></section>
<section className="bg-[#09271D] px-6 py-24 text-white"><div className="mx-auto grid max-w-[1500px] gap-14 lg:grid-cols-2"><div><H>Coordinamento dell’esportazione India–Spagna</H><p className="mt-7 leading-8 text-white/70">Fattura commerciale, Packing List, certificato di origine, specifiche, COA e documentazione disponibile. È possibile valutare il trasporto marittimo o aereo, senza garantire rotte, tempi, sdoganamento o approvazione.</p><p className="mt-5 leading-8 text-white/65">L’acquirente è responsabile di classificazione, etichettatura, registrazione, dogana e requisiti di mercato.</p></div><figure className="relative aspect-[3/2]"><Pic src="/images/export/spain/india-to-spain-export-coordination.png" alt="Coordinamento documentale e logistico verso la Spagna"/></figure></div></section>
<section className="bg-[#EDE5D7] px-6 py-24"><div className="mx-auto max-w-[1500px]"><H>Punti di forza della fornitura commerciale</H><Grid items={trust} cols="lg:grid-cols-3"/></div></section><section className="px-6 py-24"><div className="mx-auto max-w-[1120px]"><H>Mercati commerciali in Spagna</H><p className="mt-7 leading-8 text-[#4C5F54]">Richieste professionali da Madrid, Barcellona, Valencia, Siviglia, Malaga e Bilbao. I riferimenti non rappresentano una presenza locale.</p><div className="mt-8 flex flex-wrap gap-3">{["Madrid","Barcellona","Valencia","Siviglia","Malaga","Bilbao"].map(c=><span key={c} className="border border-[#C9A962] px-5 py-3">{c}</span>)}</div></div></section>
<section className="bg-[#EDE5D7] px-6 py-24"><div className="mx-auto max-w-[1120px]"><H>Domande frequenti sulla Spagna</H><div className="mt-12 divide-y">{faqs.map(f=><article key={f.question} className="grid gap-4 py-7 md:grid-cols-2"><h3 className="text-xl font-semibold">{f.question}</h3><p className="leading-7 text-[#4C5F54]">{f.answer}</p></article>)}</div></div></section>
<section className="relative bg-[#071B14] px-6 py-24 text-center text-white"><GoldenParticles/><div className="relative mx-auto max-w-[950px]"><H>Cercate un fornitore affidabile di prodotti naturali?</H><p className="mx-auto mt-7 max-w-[720px] text-white/70">Condividete con il nostro team export il prodotto, la quantità, il confezionamento, la destinazione e i requisiti Private Label.</p><Link href="/contact" className="mt-9 inline-flex bg-[#C9A962] px-8 py-4 text-[10px] font-bold uppercase text-[#102F23]">Invia i requisiti →</Link></div></section><FooterSection locale="it"/><FloatingContactButtons/><MagneticButtons/><PremiumCursor/></main>}
